- packages/chakra-ui-docs/pages/slider.mdx
- packages/chakra-ui/src/Slider/index.js
Fixes #8 
It's tested on chrome android and also on chrome desktop's touch emulator, the slider works fine in both. Note that this is a quick fix, it's not heavily tested but it should mostly work everywhere.
You can test slider with this PR ~[here](http://chakra-ui-pr-18.surge.sh/?path=/story/slider--default)~ [here](https://deploy-preview-18--chakra-ui.netlify.com/?path=/story/slider--default) (I was a little faster than netlify bot :P)
I've also updated the docs for slider props to be `onMouseDown: React.MouseEventHander | React.TouchEventHandler` instead of `onMouseDown: React.MouseEventHander`
> Fixes issue #8: Slider not working on touch devices

- packages/chakra-ui/src/Button/index.d.ts
- packages/chakra-ui/src/Button/styles.js
The `xs` size was missing from the type enum.
The `fontSize` for it was also set to `sm`, rather than `xs`.
> [Button] Fixes for `xs` size

- packages/chakra-ui-docs/components/components.js
- packages/chakra-ui-docs/pages/modal.mdx
The `Modal` component is missing from the docs sidebar. I only found it because it's linked to from the `CloseButton` docs page.
There's also a few incorrect references to `AlertDialog` in the props table.
> [Docs-Modal] Update modal docs

- packages/chakra-ui/src/index.d.ts
The `ITheme` interface was missing from exports. This PR adds `export *` to allow all named exports from the theme folder to be available externally.
> [Theme] Add missing exports from theme

- packages/chakra-ui/src/RadioButtonGroup/index.js
When navigating through the elements of a RadioButtonGroup with keyboard, the page could be scrolled accidentally. This fix disables key-based scrolling inside the keyboard navigation context.
> Prevent page scroll from RadioButtonGroup key nav

- CONTRIBUTING.md
There is no `build` script in `package.json`, so executing the commands in `CONTRIBUTING.md` ('*Before doing anything else, run these commands:*') will not work.
I changed `yarn build` to `yarn core:build` to prevent `Module not found: Can't resolve '@chakra-ui/core'` when working on the docs and such.
Thanks for the great project.
> yarn build -> yarn core:build

- packages/chakra-ui/src/Toast/index.d.ts
This expands on the `toast` TypeScript definitions fixes from my comment in https://github.com/chakra-ui/chakra-ui/pull/66#issuecomment-530232556.
It fixes a type error from the conflicting `styled-system` `position` prop, and adds the `duration` prop.
> [Toast] Fix toast typescript defs

- packages/chakra-ui/src/Input/examples.js
- packages/chakra-ui/src/Input/index.d.ts
- packages/chakra-ui/src/Input/index.js
- packages/chakra-ui/src/Input/styles.js
As per https://github.com/chakra-ui/chakra-ui/issues/91, this PR proposes a few adjustments to the `Input` component's API.
One discrepancy that I've noted throughout the codebase is the ambiguity of the `color` prop. In some cases, users are expected to pass a "partial" color string, e.g., `teal`. In other cases, users are expected to pass a fully-formed color string that corresponds with a key in the `colors` object that powers the UI, e.g., `teal.500`.
I'm partial to the latter approach, but ultimately I care more about consistency. To that end, I've tweaked the `Input` API accordingly.
1. Change the default value of `focusBorderColor` from `blue` to `blue.500`, so as to avoid unnecessary string interpolation in the input style generator.
2. Applied the value of the `focusBorderColor` …
> Tweak Input focusBorderColor API

- packages/chakra-ui-docs/pages/Box.mdx
- packages/chakra-ui-docs/pages/aspectratiobox.mdx
- packages/chakra-ui-docs/pages/avatar.mdx
- packages/chakra-ui-docs/pages/contributing.mdx
- packages/chakra-ui-docs/pages/drawer.mdx
- packages/chakra-ui-docs/pages/image.mdx
- packages/chakra-ui-docs/pages/index.js
- packages/chakra-ui-docs/pages/responsive-styles.mdx
- packages/chakra-ui-docs/pages/tag.mdx
- packages/chakra-ui/src/Avatar/examples.js
- packages/chakra-ui/src/IconButton/index.d.ts
Many of the images use unsecure http urls, which causes browser security warnings even though the website is served over https. This PR addresses that issue.
> Fix http links to avoid secure content warnings

- packages/chakra-ui/package.json
- yarn.lock
I was trying out the yarn v2 release candidate, and ran across issues using chakra-ui with a project of mine.
They are all dependency/peerDependency issues. Before my updates, I was getting the following warnings running yarn:
```
❯ yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @react-spring/core@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@^16.8.0 requested by use-memo-one@npm:1.1.1
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@>=16.8 requested by @react-spring/addons@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide konva@>=2.6 requested by @react-spring/konva@npm:9.0.0-canary.809.3.a66b280
➤ YN0002: │ react-spring@npm:9.0.0-canary.809.3.a66b280 doesn't provide react@>=16.8 requested by …
```
> fix: resolve yarn v2 pnp issues

- packages/chakra-ui-docs/pages/formcontrol.mdx
This is a very small fix for the Formik example in the FormControl docs. Currently the validation logic will only show the second error message, even if the field is blank.
> Fix validation logic in Formik example for FormControl

- packages/chakra-ui-docs/components/SideNav.js
- packages/chakra-ui-docs/pages/recipes.mdx
Adds a recipes page to the docs with an initial example of using Chakra UI with React Hook Form. Resolves #165
> docs(recipes): add recipes page to docs with initial example

- packages/chakra-ui/src/CheckboxGroup/index.js
The `onChange` event should append to the array of controlled values.
> [CheckboxGroup] Fix controlling with `value` prop

- packages/chakra-ui/src/Heading/index.js
- packages/chakra-ui/src/Text/index.js
This commit follows up on #217. It adds the `fontFamily`attribute to Heading and Text components. This way the font families specified in the theme are applied to the headings and texts automatically. 💅 The `<Code>` element already automatically choses the `mono` font from the theme.
This change is introduced to make the `fonts` property in the theme object behave more consistently with the other properties in the theme.
Currently it is still unclear how to apply the font specified in the `body` property of the fonts object to all elements automatically but this change can be a good start. But components like `<Button>` are still untouched and should probably also have the font inherited from the theme but right now I don't know if there is a good way to do that. It might be to modify the …
> feat(theme): apply fonts to Heading and Text

- packages/chakra-ui/src/Switch/index.d.ts
The Switch component is not meant to be used with a children (there's no example of that situation in the docs), so it shouldn't be required
> Update ISwitch to have an optional children

- packages/chakra-ui/src/useNumberInput/index.js
E.g. for specifying placeholders without providing a default value.
Currently, when a nullish value is specified for `NumberInput`, it thinks that the component is uncontrolled. By using `null`, a developer may denote the intentional absence of a value, leaving space for placeholders.
> Allow intentionally null NumberInput value

- packages/chakra-ui/src/useNumberInput/utils.js
I added char codes range for numeric keypads 96-105 and extra code 110 for decimal point character.
> fix(number-input): cannot use numeric keypad

- packages/chakra-ui/src/Modal/index.js
When more than one modal is opened at the same time, once one of them is closed, the other one will "close" as well, because the portal div will be removed:
https://github.com/chakra-ui/chakra-ui/blob/db84d090c5f94da8c5979219d139d46a770ef4f2/packages/chakra-ui/src/Modal/index.js#L53-L57
The other modal disapears, but the `isOpen` state remains `true`, thus not being possible to open it again.
https://codesandbox.io/s/keen-swirles-uj9yq
1. Open parent modal
2. Open nested modal
3. Close nested modal
4. Parent is gone, and can't be opened anymore :(
Alternative: always open a new portal div (instead of using the id). It's the same aproach react-modal uses
> fix: prevent bugs with multiple modals opened at the same time

- packages/chakra-ui/src/SimpleGrid/index.d.ts
Added default export in `SimpleGrid` definitions
Resolve [this](https://github.com/chakra-ui/chakra-ui/issues/205#issuecomment-562478070) and [this](https://github.com/chakra-ui/chakra-ui/issues/205#issuecomment-545941369)
> fix: export SimpleGrid component

- packages/chakra-ui-docs/pages/toast.mdx
Fixes a simple bug in the documentation for the props of the toast component.
Addresses issue: https://github.com/chakra-ui/chakra-ui/issues/288.
> [docs] fix toast component `title` prop type

- packages/chakra-ui/src/Icon/index.d.ts
I discovered that the `focusable` prop is not set in the types file and made this small change to fix the issue. Please let me know if there's anything else to be done here. Thanks for the awesome library!
> [Icon] Add missing `focusable` prop to types

- packages/chakra-ui-docs/pages/theme.mdx
`lineHeight` object should display the `none` key for the `1` value to reflect the typography theme object.
> chore(docs): fix lineHeight object keys

- packages/chakra-ui/src/Stack/index.js
Hello.
I'm opening this PR because whenever I'm using Stack with 'shouldWrapChildren' prop set to true I keep getting following console warning:
```
react.development.js:167 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Stack`. See https://fb.me/react-warning-keys for more information.
in Box (created by Stack)
in Stack (created by GenerateForm)
in form (created by GenerateForm)
in div (created by Context.Consumer)
in Box (created by Flex)
in Flex (created by GenerateForm)
in GenerateForm
in Route
in Switch
in div (created by Context.Consumer)
in Box (created by Flex)
in Flex
in Router (created by HashRouter)
in HashRouter
in Unknown
in ThemeProvider (created by ThemeProvider)
in ThemeProvider
in div
```
However, I was not able to test my …
> [WIP] Stack - add 'key' prop to wrapped children when 'shouldWrapChildren' is set to true

- packages/chakra-ui-docs/pages/recipes.mdx
Hey,
As discussed on #291  it would be nice to have some Header example on the "recipe" section.
This PR adds a simple example of a responsive header, inspired by Tailwind's Header.
This is how it looks:
_Mobile:_
_Desktop:_
Another thing I did on this PR was to create an index list of recipes, so users can see all the recipes options without having to scroll down the whole page.
Thanks.
> (Docs) Add Header component to Recipes

- packages/chakra-ui/src/Image/index.js
Fixes #316 by making sure to track whether the component is mounted, prior to any asynchronous state updates.
The issue is caused by the asynchronous nature of the `image.onload` and `image.onerror` and can be easily reproduced on slow connections (see issue description).
> fix(image): add `isMounted` check on `Image` component

- packages/chakra-ui-docs/pages/numberinput.mdx
This fixes the title for the documentation regarding setting the `min` and `max` props of the `NumberInput` component.
> Fix incorrect title in number input docs

- examples/nextjs/README.md
- examples/nextjs/package.json
- examples/nextjs/src/components/CTA.js
- examples/nextjs/src/components/Container.js
- examples/nextjs/src/components/DarkModeSwitch.js
- examples/nextjs/src/components/Footer.js
- examples/nextjs/src/components/Hero.js
- examples/nextjs/src/components/Main.js
- examples/nextjs/src/pages/_app.js
- examples/nextjs/src/pages/index.js
- examples/nextjs/src/theme.js
This PR adds an example Next.js project with `chakra-ui` as its component library.
This example features how to use [chakra-ui](https://github.com/chakra-ui/chakra-ui) as the component library within a Next.js app.
We are connecting the Next.js `_app.js` with `chakra-ui`'s Theme and ColorMode containers so the pages can have app-wide dark/light mode. We are also creating some components which shows the usage of `chakra-ui`'s style props.
Reference: https://github.com/zeit/next.js/pull/10033
> Add Next.js example

- packages/chakra-ui/src/Image/index.js
The `Avatar` component makes use of `useHasImageLoaded` which tries to load the image even if src is undefined.
> [Image] useHasImageLoaded tries to load image even if no src is provided

- packages/chakra-ui/src/CloseButton/index.d.ts
- packages/chakra-ui/src/CloseButton/index.js
- yarn.lock
The CloseButton doesn't have a default type, which will make it act as a submit button by default.  This can cause issues for example if one were to wrap a Drawer in a form element and utilize the DrawerCloseButton.  
For example, in the sandbox below you can see that the DrawerCloseButton causes the form to be submitted.
https://codesandbox.io/s/busy-merkle-3b7fr
This can be avoided by passing type="button" to the DrawerCloseButton.  However, since the CloseButton is unlikely to be used as a submit button I believe that defaulting it to type="button" is a reasonable default.
> fix(button): default CloseButton to type of button

- packages/chakra-ui/src/Toast/index.js
When using the toast method from `useToast` in a `useEffect` hook I noticed that whenever the component re-renders a new toast method gets returned which means that another toast component gets added. This PR wraps the `notify` function inside the `useToast` hook in `useCallback` to make sure that the function is the same between renders.
Example code to replicate issue:
```js
import React, { useState, useEffect } from "react";
import { useToast, Button } from "@chakra-ui/core";
function TestComponent() {
const toast = useToast();
const [count, setCount] = useState(0);
useEffect(() => {
toast({
position: "bottom",
title: "Hello world",
duration: null,
});
}, [toast]);
return (
<Button onClick={() => setCount(count => count + 1)}>{count}</Button>
);
}
```
> fix(Toast): wrap notify in useCallback

- packages/chakra-ui/src/Box/config.js
While using `PseudoBox`, the following code had no stylistic effect:
```jsx
<PseudoBox
_odd={{
flexDirection: ["column", "row"],
// `flexDirection: "column"` would work fine, though
}}
>
...
</PseudoBox>
```
It turns out that `{ transformAliasProps } from "chakra-ui/src/Box/config"` transforms responsive arrays into objects by mistake, which could not be [interpreted by `css from "@styled-system/css"`](https://github.com/chakra-ui/chakra-ui/blob/37a19d8da7a628152fd1b4e44a33a96fb7beb527/packages/chakra-ui/src/PseudoBox/index.js#L74). This PR solves the issue by leaving arrays passed to `transformAliasProps` intact.
> fix(pseudobox): responsive props

- packages/chakra-ui/src/Editable/index.d.ts
It's relevant to #173, `onSubmit` also needs to be omitted .
I don't know whether any other components need to have same fix or not, but for my project i need this fix.
> [TypeScript] Incorrect merging of Editable's event handler types

- packages/chakra-ui/src/Input/styles.js
iOS Safari adds a shadow unless you specify `appearance: none`.
See https://stackoverflow.com/questions/23211656/remove-ios-input-shadow
> Fix iOS Safari input style

- packages/chakra-ui/src/Modal/index.js
Hey all, just a small update to catch an issue that a user encountered when trying to use this package with Snowpack: https://www.pika.dev/npm/snowpack/discuss/76
Node has finalized their ESM support plan in v13, and it includes support for ESM->CJS  imports but only via the default export. As a result, this import breaks under that resolution scheme since `exenv` only has a default export and no named imports. Both Snowpack and Rollup follow Node's ESM import conventions, which causes this package to break without this small fix.
See the end of this section for relevant docs: https://nodejs.org/api/esm.html#esm_import_statements
```
import packageMain from 'commonjs-package'; // Works
import { method } from 'commonjs-package'; // Errors
```
> "exenv" import breaks in Node v13, Snowpack

- packages/chakra-ui-docs/pages/formcontrol.mdx
This PR updates the formik example for formcontrol to use a child-callback function instead of using a render prop. 
https://jaredpalmer.com/formik/docs/migrating-v2#deprecation-warnings
> docs: Update formcontrol.mdx for formik example

- packages/chakra-ui-docs/pages/tag.mdx
In the `tag` documentation page were declared the wrong default value of  the props `variant`, `size` and `variantColor`. 
I've also changed the text of some of the examples. It was strange to me see a `variantColor="cyan"` with the "Green" text.
> Fixed default value of variant, size and variantColor in the documentation

- packages/chakra-ui-docs/pages/recipes.mdx
React Hook Form has formState object that contains isSubmitting.
You can use this instead of using useState in order to detect whether form is already submitted or not.
[Working example](https://codesandbox.io/s/chakra-ui-react-hook-form-rvi3p)
> docs(recipes): use formState instead of useState for isSubmitting

- packages/gatsby-plugin-chakra-ui/gatsby-browser.js
- packages/gatsby-plugin-chakra-ui/theme.js
This branch fixes an error made in #362 where although I moved the `gatsby-*.js` files to the root of the package, I forgot to update the path to `src/theme.js`, and kept the old `theme.js` file hanging out in the root of the package directory.
This change makes the plugin's directory structure _truly_ match the structure of [the temporary package](https://github.com/trevorblades/gatsby-plugin-chakra-ui) that I had used to test the previous change.
> fix: Gatsby plugin path to theme file

- packages/chakra-ui/src/Popover/index.js
Cancels the popover open timeout if a leave event happens before it is completed.
This prevents the flickering that occurs when you move the mouse quickly past an element with a "hover" popover.
> fix(popover): fix popover flickering when trigger is "hover"

- packages/chakra-ui/src/Icon/index.d.ts
Hi, first, thank you for the project!
Related: https://github.com/chakra-ui/chakra-ui/issues/204
This means using custom icons will cause an error:
https://chakra-ui.com/icon#adding-custom-icons
For me:
```
ERROR in /hsk/_ux/js/Layout.tsx(109,30):
TS2322: Type '"faHome"' is not assignable to type 'Icons'.
```
This this case, make the check on `icons` more lenient, allow any string in `name` of `<Icon>`
> Typings: Support custom icons

- packages/chakra-ui-docs/pages/input.mdx
This includes a pointer in the docs that <Input>s can be wrapped
in <FormControl>s and combined with a <FormLabel>s.
It also removes the <Text> element from one example - it is not
relevant to the example, and fulfils the role of a <FormLabel>,
hence nudging developers to inaccessible code.
> docs(input): pointer to making <Input> accessible

- packages/chakra-ui-docs/pages/toast.mdx
I believe this should be 'error' instead of 'danger'
> fix: update toast status documentation

- packages/chakra-ui-docs/pages/input.mdx
- packages/chakra-ui-docs/pages/select.mdx
According to the code [here](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Input/styles.js#L170-L182), the actual heights of `size` of `Input` and `Select`, are different from those in document. 
This PR fixes the document to reflect the actual height.
> fix: document of Input and Select about sizes

- packages/chakra-ui/src/Image/index.js
Image component had incorrectly typed `onError` event in camelcase, leading to the native DOM element having a property on it that it didn't recognize. Renaming it to `onerror` did the trick.
> fix: erroneous event handler in Image component

- packages/chakra-ui/src/Skeleton/examples.js
- packages/chakra-ui/src/Skeleton/index.d.ts
- packages/chakra-ui/src/Skeleton/index.js
This pull request adds:
- skeleton renders Box instead of Fragment if `isLoaded` is true
- fadeIn animation of children after `isLoaded` is true
- styles are cached with  `useMemo`
Working on my project using the `Skeleton` component I notices that using `Fragment` when the prop `isLoaded` is true removes all the other styling properties applied to `Skeleton`, like margins and spacing and i cannot use `Stack` component
I also added a customizable fadeIn animation that makes everything nicer
This is a small change but improves the usage a lot.
> build: Skeleton component improvements

- packages/chakra-ui-docs/pages/style-props.mdx
If I understand correctly, I _think_ this was just a typo
> fix: By default, proportional spacing are factors of 4

- packages/radio/src/RadioGroup.hook.tsx
Calling `querySelector` by itself causes a `TypeError: Illegal Invocation` error because it uses `this` and must be bound to `rootNode`. Calling `rootNode.querySelector` fixes this binding issue.
> fix(radio-group): call querySelector from rootNode directly

- packages/select/src/Select.tsx
This PR fixes an issue where `placeholder` was being incorrectly passed to the root `chakra.div` by destructuring it from `props` and passing it to `SelectField`.
> fix(select): pass placeholder prop to SelectField

- packages/accordion/src/tests/Accordion.test.tsx
- packages/avatar/src/tests/Avatar.test.tsx
- packages/breadcrumb/src/tests/Breadcrumb.test.tsx
- packages/close-button/src/tests/CloseButton.test.tsx
- packages/collapse/src/tests/Collapse.test.tsx
- packages/counter/src/tests/Counter.test.tsx
- packages/dialog/src/tests/Dialog.test.tsx
- packages/drawer/src/tests/Drawer.test.tsx
- packages/editable/src/tests/Editable.test.tsx
- packages/form-control/src/tests/FormControl.test.tsx
- packages/icon/src/tests/Icon.test.tsx
- packages/live-region/src/tests/LiveRegion.test.tsx
- packages/number-input/src/tests/NumberInput.test.tsx
- packages/popover/src/tests/Popover.test.tsx
- packages/switch/src/tests/Switch.test.tsx
This PR converts existing tests to import directly from the module exports rather than individual files within the module. This ensures that we're testing the public exports of each module, and will allow tests to catch unintentionally-removed public exports.
> test: use module public exports

- packages/spinner/README.md
This fixes a small typo in the code suggestion I made to the `README` for `Spinner`. The backticks should only wrap `animation-duration`, not the entire link text.
> fix(spinner): typo in README

- .all-contributorsrc
As suggested by @segunadebayo, I've added myself as a contributor, respecting the chronological order of contributions.
> chore: add kripod to '.all-contributorsrc'

- packages/chakra-ui/package.json
Adding a "typings" field to the `@chakra-ui/core` package.json makes the component typings automatically discoverable by IDEs.
> fix: make component typings discoverable

- .storybook/main.js
- packages/toast/migration.md
- packages/toast/src/Toast.hook.tsx
- packages/toast/src/Toast.manager.tsx
- packages/toast/src/Toast.stories.tsx
- packages/toast/src/Toast.tsx
- packages/toast/src/Toast.types.ts
This PR includes updates made to the toast component package in preparation for release. The following activities were carried out:
- Add Support for `onCloseComplete` prop, a callback function to run side
effects after the toast component has closed.
> feat: add onCloseComplete prop for toast component

- packages/stat/package.json
`@chakra-ui/visually-hidden` was missing from `dependencies` in the `stat` package, causing build failure. This PR resolves that.
> fix(stat): add missing @chakra-ui/visually-hidden dependency

- packages/chakra-ui-docs/components/DocsHeader.js
**This link should point to the repo, not the package.** By linking to the package, the current link makes Chakra UI look like a much smaller project than it really is!
One of my biggest concerns when adopting any new framework is project health. I want to see evidence of an active community, many contributors. I'd never heard of Chakra (I'm new to React!) so I did the usual; visit the homepage (very compelling!), quickly skim the starter doc, then click through to the GitHub repo.
Imagine my surprise when Chakra only had two listed contributors! Immediate red flag. "I don't care how many stars it has, I can't adopt a framework that won't take community contributions!" I closed the window and moved on; decisions happen quickly.
While documenting my decision against Chakra, I went back to …
> Fix header link to GitHub repository

- packages/chakra-ui-docs/pages/getting-started.mdx
This is the first time the `CSSReset` component was mentioned in the docs. It is not always intuitive to beginners that they should import it.
I also removed the comment from `customTheme` import since it's actually being used in the code snippet
> docs: Import CSSReset to match reference on GS page

- .lintstagedrc
This PR merges the `.lintstagedrc` entries together, and removes the use of `git add`. `lint-staged` will automatically use `git add` on any files.
I opened this because I've been having occasional pre-commit issues, and I think this should fix them.
> chore(lint-staged): clean up and fix lintstagedrc

- docs/gatsby-config.js
I updated the `gatsby-plugin-manifest` options from the values that were included in the Gatsby starter.
Here is more information about [Web app manifests](https://developer.mozilla.org/en-US/docs/Web/Manifest) and the [gatsby-plugin-manifest](https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/).
> fix(docs): updated gatsby-plugin-manifest options from starter values

- packages/chakra-ui-docs/pages/editable.mdx
If the `isPreviewFocusable` and `submitOnBlur` are set to false, changes made to the component would not be shown
> fix(docs): change false to true in the props of the Editable component

- packages/chakra-ui-docs/pages/modal.mdx
Change `Close Modal on Overlay Click` to `Prevent Modal from closing on Overlay click`
> docs: correct unclear heading

- packages/chakra-ui/src/ThemeProvider/index.js
I got error `TypeError: Cannot use 'in' operator to search...` like those issues.
https://github.com/chakra-ui/chakra-ui/issues/632
https://github.com/chakra-ui/chakra-ui/issues/627
This error happen when forget `<ThemeProvider>`.
`ThemeProvider` throw error when `theme` is `undefined`.
But sadly, `@emotion/core`'s `ThemeContext` returns empty object by default and this check is not passed
https://github.com/emotion-js/emotion/blob/master/packages/core/src/context.js#L17
This pull request append empty object checking.
> fix: Throw error when theme is empty object

- packages/chakra-ui/src/ColorModeProvider/index.js
In case of value provided to ColorModeProvider, don't rely on use-dark-mode result
> fix: #739 ColorModeProvider correctly use manual mode

- .eslintrc
- docs/gatsby-config.js
- docs/gatsby-node.js
- docs/package.json
- docs/pages/components/menu.mdx
- docs/pages/components/modal.mdx
- docs/pages/components/progress.mdx
- docs/src/components/docs/ColorPalette.js
- docs/src/components/docs/MDXComponents.jsx
- docs/src/components/header.js
- docs/src/components/layout.js
- docs/src/components/pagination.js
- docs/src/components/search.js
- docs/src/components/toc.js
- docs/src/styles/algolia.css
- docs/src/templates/docs.js
- docs/utils.js
- docs/utils.spec.js
- yarn.lock
Most of this comes from a pairing session with @segunadebayo. It adds a basic algolia search bar, floating table of contents, and pagination
It includes a few additional things I had from playing around with the floating nav layout:
- plugin for autolinking mdx headers
- memoized `Body` and `SidebarLayout` so they don't re-render anytime an anchor link is clicked
> chore(website): add search, toc, and pagination

- docs/gatsby-config.js
- docs/gatsby-node.js
- docs/src/components/github-edit-link.js
- docs/src/templates/docs.js
- docs/utils.js
This PR adds an "Edit this page on GitHub" link to the bottom of each docs page.
The link is generated using the relative path to the file. 
Links don't currently work because they point to `master` (example: https://github.com/chakra-ui/chakra-ui/blob/master/docs/pages/components/menu.mdx), but once `dev-ts` is merged in, they will work correctly. You can test them by replacing `/master` with `/dev-ts` in the link.
> docs: add github edit link to docs pages

- packages/chakra-ui-docs/components/DocsHeader.js
- packages/chakra-ui-docs/components/Header.js
Previously in docs page there is no button to storybook page, but in homepage has it. This PR add button storybook in docs pages.
_Before_
_After_
> fix: button storybook in docs header

- packages/css-reset/src/CSSReset.tsx
fixes #733 
This PR adds an ie-specific rule to `CSSReset` to prevent duplicate dropdown arrows showing on `Select`.
> fix(select): remove duplicate Select arrow in ie11

- docs/src/components/docs/side-nav.js
This PR cleans fixes nav link ordering by sorting all links first by `frontmatter.order` and then by `frontmatter.title`. It also cleans up the link query.
> docs: fix nav link ordering

- docs/pages/contributing.mdx
- package.json
Replaces `docs:now` with `docs:start` and updates `contributing.mdx`.
> docs: fix start command

- docs/gatsby-node.js
- docs/src/pages/guides.js
- docs/src/templates/guides.js
- docs/utils.js
This PR adds `fields.contributors` to `Mdx`. This is a field intended for use with `guides` pages, so we can list users that contributed to each guide.
> docs(guides): add file contributors functionality

- docs/gatsby-node.js
- docs/pages/guides/with-framer.mdx
- docs/pages/guides/with-rhf.mdx
- docs/src/pages/guides.js
- docs/src/templates/guides.js
- docs/utils.js
This PR uses `@octokit/rest.js` to fetch the contributors for guides. It also moves rendering for guide title/description/link to `templates/guides.js`.
> docs(guides): fix guide contributors functionality

- docs/gatsby-config.js
- docs/gatsby-node.js
- docs/package.json
- docs/src/components/header.js
- docs/src/pages/team.js
- docs/utils.js
- yarn.lock
This PR adds a team page to the site, fetching the team's data using `gatsby-source-graphql` and the GitHub API.
In order for this to work, we need to make sure we have a `GITHUB_API_TOKEN` in env with `repo` and `read:org` permissions available in the build step.
> chore(site): add team page

- docs/gatsby-config.js
This PR makes two changes:
1. Removed "Design System built with React" from `title` because it made tab titles so long they were essentially useless. You can now see most page-specific titles on a normal sized tab now.
2. Removes "Built with Styled System" from `description`.
> chore(site): adjust metadata

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
We lost our issue templates in the move (possibly intentional?). This PR re-adds them.
> chore(github): re-add issue templates

- .github/stale.yml
Explains why so many things are suddenly marked as `stale`.
> chore(stale): re-add configuration

- docs/pages/theming/theme.mdx
Link to default theme in docs is broken. If I'm not wrong the updated link on the pull request should be correct.
> fix: Broken default theme link

- README.md
Spectrum is no longer the tool used for discussions so this commit removes the badge from the Readme to avoid confusion among users.
> chore: remove spectrum badge from the readme

- docs/gatsby-config.js
- docs/gatsby-node.js
- docs/package.json
- docs/src/pages/team.js
- docs/utils.js
- yarn.lock
This PR removes `gatsby-source-graphql` and all the stuff related to Github API v4 and replaces it with Octokit usage. We're making this change because v4 doesn't allow anonymous api access and we don't want to require that users manage a local token just to do dev work on the site.
> chore(site): move from github api v4 to v3 for team page

- packages/css-reset/src/css-reset.tsx
`CSSReset` sets the default `border-style` for images to `solid` but it's already set to `none` above.
> Remove duplicate border-style for img

- website/gatsby-config.js
- website/utils.js
This PR adds optional auth support via `.env.development` and the `GITHUB_TOKEN` variable. The v3 API is rate limited for anonymous users to 60 requests/hour, which works for minor development work but anything involved multiple restarts will need a token.
I'll follow up with a note explaining how to use this functionality.
> chore(site): add optional octokit auth via .env

- website/gatsby-node.js
- website/utils.js
- website/utils.spec.js
This PR updates docs nodes to be finally ordered by their collection, so that previous/next links lead to the correct pages.
> fix(site): update pagination node order

- website/guides/how-to-create-a-guide.mdx
This PR adds a "How to Create a Guide" guide.
Things covered by this guide:
- where to create guide files
- what to name a guide file
- adding guide frontmatter
- how to write guide content (with links to markdown cheatsheet + mdx website)
- opening a PR with links to a tutorial for forking+opening a PR along with related GitHub Docs
> docs(guides): add "how to create a guide" guide

- website/utils.js
This adds `form` to the collection sorting/ordering util, so that docs pagination works correctly again.
> docs: fix form pagination ordering

- packages/toast/src/toast-manager.tsx
When testing, I found that this wasn't required - the docs, as an example, work fine with no `z-index` value.
> feat(toast): remove manager z-index

- packages/css-reset/src/css-reset.tsx
Changed the selector for the focus-visible polyfill to use an attribute instead of a class.
Per this update to the polyfill documentation: https://github.com/WICG/focus-visible/commit/fda80f8401807c1cbb702fb1a15b9635828bfc6d
> fix: Updated the selector for the focus-visible polyfill

- packages/system/src/create-styled.tsx
- packages/system/src/system.tsx
- packages/system/src/system.utils.ts
Move the style calculation for component props to utils to be calculated as an interpolation.
> chore: refactor component props style computation as an interpolation

- packages/utils/src/responsive.ts
This all the uses of `mapResponsive` that don't handle the null value
> feat(utils): Handle null values in mapResponsive

- .codesandbox/ci.json
I think this PR should fix our broken pipelines. It filters out the `test-utils` package which is supposed to be private.
> fix(codesandbox): filter private test-utils pkg

- website/src/components/bottom-nav.js
This resolves #945. It was an issue in mobile and desktop.
> fix: bottom nav works with dark mode

- website/docs/color-mode.mdx
- website/docs/contributing.mdx
- website/docs/getting-started.mdx
- website/docs/migration.mdx
- website/docs/principles.mdx
- website/docs/theming/advanced.mdx
- website/docs/theming/overview.mdx
- website/docs/z-index.mdx
Added a variety of changes to typos, grammar mistakes, clarifying confusing sentences, and (in one place) fixing a mistake related to a package name.
> docs: fixing a few spelling and grammar mistakes

- packages/accordion/package.json
this broke my parcel bundling
```
> parcel build frontend/src/index.html
🚨 Build failed.
@parcel/core: Failed to resolve '@chakra-ui/accordion' from './node_modules/@chakra-ui/core/dist/esm/index.js'
/home/capaj/work-repos/4house/4house-be-admin/node_modules/@chakra-ui/core/dist/esm/index.js:34:15
33 | export * from "@chakra-ui/tooltip";
> 34 | export * from "@chakra-ui/accordion";
>    |               ^^^^^^^^^^^^^^^^^^^^^^
35 | export * from "@chakra-ui/alert";
36 | export * from "@chakra-ui/button";
@parcel/resolver-default: Could not load './dist/esm/index/js' from module '@chakra-ui/accordion' found in package.json#module
/home/capaj/work-repos/4house/4house-be-admin/node_modules/@chakra-ui/accordion/package.json:69:13
68 |   "main": "dist/cjs/index.js",
> 69 |   "module": …
```
> fix bad path in accordion/package.json

- website/docs/components/code.mdx
- website/docs/components/tag.mdx
- website/docs/form/checkbox.mdx
- website/docs/form/numberinput.mdx
- website/docs/form/switch.mdx
- website/docs/layout/stack.mdx
Removed references to isInline prop. Replaced with `direction="row"`
Only remaining instances are in 'before' code examples and migration guide calling out the removal of the prop.
This resolved #999
> docs: removed references to isInline. remaining are in before examples

- website/docs/components/modal.mdx
- website/docs/migration.mdx
Updated the Modal docs and Modal section in the migration guide to call out the changes in transition components.
Fixes #944
> fix: updated the transition components in modal docs and migration guide

- .github/stale.yml
I've been doing a lot of work the last few days to groom our issues backlog so that we can become better organized. While doing so, I've been thinking a lot about how to make that process easier. One of the ways I think we can improve that is to better utilize `probot/stale`.
This PR makes a few changes to the `stale` config:
- Reduces the number of days until an issue is closed to 20. We're currently waiting 74 days until an issue is closed as stale and that's quite a bit longer than it should be imo. I think 20 is plenty, especially since I plan to continuously groom and tag issues to help manage them and prevent issues that matter from being marked stale.
- Updates the `stale` mark comment to be more friendly and provide more explanation for what's happening.
- Adds `not stale` to …
> chore(stale): adjust settings

- packages/media-query/src/media-query.hook.tsx
- packages/media-query/stories/media-query.stories.tsx
This PR is nearly identical to #797 except I've left out the `useViewportSize` hook. It adds the `useBreakpointValue`, `useAnimationPreference` and `useColorModePreference` hooks to `@chakra-ui/media-query`.
> feat(media-query): add breakpoint value, animation, and color mode utils

- packages/layout/src/list.tsx
I noticed that UnorderedList was rendering numbers, like an OrderedList. This appears to be corrected with this single change.
> fix: UnorderedList was not rendering bullets

- packages/theme/src/components/index.ts
I'm not sure if this was intentional, but there's no mention of Icon in the theme, despite being a theme file to customize icons. If it's not exported with the theme, I'm not sure how this file was ever doing anything. :)
> fix: Adding Icon to theme export

- packages/button/src/button.tsx
The `type` prop has a default of `button` which is passed down even if the `as` prop is used. Not sure if there are any edge cases I need to account for, like is there ever a time we would expect `as` and `type` to both be used at the same time?
Fixes #770
> fix: button ignores `type` prop when `as` prop is used

- packages/layout/src/stack.tsx
`HStack` and `VStack` should forward ref like `Stack` #526
> feat: added forwardRef to HStack and VStack

- packages/css/src/css.ts
- packages/css/src/css.types.ts
- packages/css/tests/css.test.ts
- packages/layout/src/aspect-ratio.tsx
- packages/layout/stories/aspect-ratio.stories.tsx
- packages/utils/src/responsive.ts
- packages/utils/tests/responsive.test.ts
I might have completely missed the point here. Please guide me if this can be fixed in some other way.
This would also fix #876
The isssue was that while this worked:
```
<Box _before={{paddingBottom: [1, 2, 3, 4]}}/>
```
the equivalent object notation didn't
```
<Box _before={{paddingBottom: { base: 1, sm: 2, md: 3, lg: 4 }}}/>
```
> feat: allow responsive pseudo props with object notation

- packages/layout/src/stack.tsx
Found and issue with the margin while testing out the responsive direction prop. Sorry about that.
> fix: fixed margin bug for Stack column-reverse and row-reverse

- website/docs/components/tag.mdx
Fixes #1117 
Replaced `TagIcon` with `TagLeftIcon` and `TagRightIcon` in the Tag docs examples
> docs: replaced TagIcon with TagLeftIcon and TagRightIcon in the examples

- website/docs/components/icon.mdx
- website/docs/components/tag.mdx
- website/docs/form/button.mdx
All tags stretch to full height since the removal of default `align` prop in `Stack` component,
So, today I took some time to update the examples of `Tag` component showing all variants,
> docs(tag): fix and update examples for tag component

- website/docs/theming/basic.mdx
- website/docs/theming/overview.mdx
This PR moves the `BadgeSpec` import to `theming/basic.mdx`.
> docs(theming): fix BadgeSpec import

- website/docs/components/tabs.mdx
This PR fixes docs build failures due to a `useTabsThemingContext` reference.
> docs(tabs): replace useTabsThemingContext

- website/docs/components/breadcrumb.mdx
This PR fixes broken links on the `Breadcrumb` docs page. Closes #1169
> docs(breadcrumb): fix broken example links

- .github/workflows/deploy-website.yml
- vercel.json
This PR makes two changes:
1. It updates `vercel.json` to point to `next.chakra-ui.com` for production deploys.
2. It adds a workflow for deploying the website to Vercel. The workflow only runs on commits to `master`, and only if the commit contains changes to files in `website/**`.
> chore: deploy website on master push

- website/docs/components/avatar.mdx
Closes #660 
This PR adds `wrap` to both `Stack` containers.
> docs(avatar): add wrap to stack containers

- website/docs/form/switch.mdx
This PR fixes a docs build failure due to `FormLabel` requiring a surrounding `StylesProvider`.
> docs(switch): wrap usage code with FormControl

- packages/tabs/src/tabs.tsx
- packages/theme/src/components/tabs.ts
Señor Bruno was asking in Discord if it was possible to right align Tabs. The `align` prop didnt seem to work, and the example in the docs was broken.
This fixes the align issue in the Tabs component.
> fix: tabs align prop didnt do anything

- vercel.json
This PR adds a Vercel redirect from `/discord` to https://discord.com/invite/BEZ8VDy which is a permanent invite to the Chakra Discord. This means can can invite people easily by linking them to https://chakra-ui.com/discord.
> chore(vercel): add /discord invite redirect

- .changeset/friendly-rivers-breathe.md
- packages/menu/src/use-menu.ts
This PR fixes the `MenuOption.isChecked` prop type.
> fix(menu): update MenuOption isChecked prop to boolean type

- tooling/cra-template-typescript/template/src/App.tsx
- tooling/cra-template/template/src/App.js
This PR fixes the docs linked in the cra templates to use https://next.chakra-ui.com/
> fix: use next docs link in cra templates

- CONTRIBUTING.md
Closes #1228 
This PR adds basic notes about `changesets` to `CONTRIBUTING.md`.
> docs(contributing): add changesets overview to CONTRIBUTING.md

- website/gatsby-node.js
- website/package.json
- website/src/components/github-edit-link.js
- website/src/pages/guides.js
- website/src/templates/docs.js
- website/src/templates/guides.js
- website/utils.js
- website/utils.spec.js
- yarn.lock
Closes #1204 
This PR uses `git` to look up the dates of the first and latest commits of `.mdx` files and uses the dates from those commits as the `createdAt` and `updatedAt` fields on `Mdx` nodes. Those fields are then available in GQL queries.
- uses [`simple-git`](https://github.com/steveukx/git-js) to access `git log` for commit lookup
- creates `createdAt`/`updatedAt` fields in `onCreateNode`
- reads `createdAt`/`updatedAt` fields using GQL queries in docs+guides pages/templates
- modifies `getRelativePagePath` to return the path without the `/` prefix
> docs: use git for accurate file history dates

- website/docs/theming/theme.mdx
This branch updates a typo in the docs. The key `base` was accidentally used twice in place of the `none` key in the `lineHeights` part of the theme docs.
> Fix `lineHeights.none` in the theme docs

- packages/breadcrumb/README.md
Ran into the term obviously when viewing the Popover docs today. That was removed earlier but found another instance. Suggest removing the term to make the documentation a little friendlier.
> docs(breadcrumb): removes obviously from documentation

- website/docs/getting-started.mdx
- website/docs/migration.mdx
Resolves #913
This PR adds a note about the minimum TypeScript version requirement for TypeScript projects to `getting-started.mdx` and `migration.mdx`.
> docs: add minimum typescript version notes

- README.md
- website/docs/getting-started.mdx
This PR adds link to v1 docs in README.md 
Additionally, it updates installation instructions to use `@chakra-ui/core@next`
> docs: update installation instructions and add link to next docs in readme

- packages/icon/tests/__snapshots__/icon.test.tsx.snap
This PR allows current icon tests to pass by removing `role="presentation"` from the rendered icon snapshots.
This attribute appears to have been removed in `develop`, possibly related to #1197. It seems like this is part of an ongoing conversation, but in the meantime this PR updates the tests to match the current code state.
<details>
<summary><strong>Before</strong></summary>
```bash
$ yarn icon test
yarn run v1.22.4
$ yarn workspace @chakra-ui/icon test
$ jest --env=jsdom --passWithNoTests
FAIL  tests/icon.test.tsx
✕ Icon renders correctly (101 ms)
✕ Icon renders a third-party icon correctly (70 ms)
● Icon renders correctly
expect(received).toMatchSnapshot()
Snapshot name: `Icon renders correctly 1`
- Snapshot  - 1
+ Received  + 0
@@ -12,11 +12,10 @@
}
<svg
class="chakra-icon …
```
> test(icon): remove presentation role from rendered icon snapshots

- website/docs/migration.mdx
This PR removes the remaining mention of `chakra-cli` from the docs.
> docs(getting-started): remove mention of chakra-cli

- website/docs/form/pin-input.mdx
This PR updates the docs for `PinInput` to the latest changes of the component (`PinInputField`s must be direct children of `PinInput`).
> fix(docs): adapt to changes

- website/src/components/header.js
Fix overlapping navbar on the menu page.
Closes #1452
> fix: fix overlapping navbar

- packages/menu/README.md
- packages/menu/migration.md
- packages/menu/src/menu.tsx
- website/docs/components/menu.mdx
- website/docs/migration.mdx
Resolves #1506 
This PR removes the `submenuIcon` prop and removes all references to the nested menus/submenus concept from the docs.
> docs(menu): remove submenu from menu docs

- packages/spinner/src/spinner.tsx
I have a product that take a long time to render and notice something regarding to spinner that spinner is a square a while before changing back to circle spinner. ([demo here](https://youtu.be/T-MKy_Vw24s))
It is because that when on server-side it recognize as `border-radius: full` instead of `border-radius: 99999...px`. So, this is minor style fix for that
> fix(spinner): sharp spinner on server-side rendering caused by misconfigured borderRadius property

- packages/input/src/input-element.tsx
Resolves #1497
This `z-index` has been in place for quite a long time, but I'm not sure what purpose it's serving.
> style(input-element): remove z-index

- packages/media-query/package.json
- packages/media-query/src/create-media-query.ts
- packages/media-query/tests/create-media-query.test.ts
- packages/media-query/tests/test-data.ts
- packages/media-query/tests/use-breakpoint-value.test.tsx
- yarn.lock
Fixes #1444 
This PR resolves an issue where `createMediaQueries` was returning a broken breakpoints array, causing `useBreakpointValue` objects to only match when using array numbers as keys rather than the breakpoint names.
Also added tests for both `createMediaQueries` and `useBreakpointValue` to help us avoid this situation in the future.
Thanks to @nassimbenkirane for investigating and sharing what he found!
> fix(media-query): create media queries using breakpoint name keys only

- packages/system/src/should-forward-prop.ts
- packages/system/tests/should-forward-prop.test.ts
Resolves #1347
The `isValid` check was added recently, but I don't think that logic works quite the way we were expecting it to. The only way I could set the correct "should forward" status and get the tests to pass was by removing `isValid`.
> chore(system): remove shouldForwardProp isValid check

- packages/styled-system/package.json
- packages/styled-system/src/config/background.ts
- packages/styled-system/src/config/border.ts
- packages/styled-system/src/config/color.ts
- packages/styled-system/src/config/flexbox.ts
- packages/styled-system/src/config/grid.ts
- packages/styled-system/src/config/layout.ts
- packages/styled-system/src/config/list.ts
- packages/styled-system/src/config/others.ts
- packages/styled-system/src/config/outline.ts
- packages/styled-system/src/config/position.ts
- packages/styled-system/src/config/shadow.ts
- packages/styled-system/src/config/space.ts
- packages/styled-system/src/config/transform.ts
- packages/styled-system/src/config/transition.ts
- packages/styled-system/src/config/typography.ts
- packages/styled-system/src/css.types.ts
- packages/styled-system/src/parser.types.ts
- yarn.lock
The purpose of this PR is to bring TypeScript hack for autocompletion for literal string/number unions with csstype v3 [https://github.com/frenic/csstype](https://github.com/frenic/csstype)
===
> chore(styled-system): migrate to csstype v3

- .github/ISSUE_TEMPLATE/bug_report.md
This PR adds a link to codesandbox js+ts templates to the bug report issue template. Hopefully this will make it easier for users to provide reproductions when creating issues.
This templates mirror our https://github.com/chakra-ui/codesandbox-react-js-template and https://github.com/chakra-ui/codesandbox-react-ts-template repos.
> chore(issue-templates): add js+ts codesandbox template links

- website/pages/docs/typography/heading.mdx
- website/pages/docs/typography/text.mdx
Hi! This is my first contribution to Chakra UI!
This PR adds little hints on the side of the `<Text />` and `<Heading />` documentation that correspond to the appropriate size. It makes it easier to know which size corresponds to which line of the example, instead of having to count!
Before:
After:
> feat(docs): add size hints in Text's and Heading's documentation

- packages/theme/src/components/input.ts
This brings the v1 input element in line with the v0 input element's behaviour of raising it's zIndex when it's focused. This is useful for when you have multiple inputs stacked on top of each other.
For reference, this is the `_focus` style for the v0 input: https://github.com/chakra-ui/chakra-ui/blob/v0/packages/chakra-ui/src/Input/styles.js#L45
Here's a comparison of the behaviour of v0 and v1 inputs:
**v0**
**v1**
> feat(input): Add zIndex: 1 to focused input (v0 behaviour)

- website/next.config.js
This PR fixes the `git log` error when running the website, and adds the `--follow` flag which makes `git` follow file renames when sourcing log information.
> chore(website): fix 'git log' error and add --follow flag

- website/pages/docs/getting-started.mdx
This PR adds a note to the Installation page pointing CRA users to the official CRA templates guide.
> docs(installation): add CRA templates guide note

- website/pages/_app.tsx
This change allows us to use any `@chakra-ui/core` export in any mdx
file without needing to first import it.
> feat(docs): add Chakra exports as mdx shortcodes

- packages/core/src/chakra-provider.tsx
This PR offers a possible fix for #1608, flipping the load order of `CSSReset` and `GlobalStyles` in `ChakraProvider`. This issue surfaced as a side-effect of a recent improvement. More context is available on the [issue](https://github.com/chakra-ui/chakra-ui/issues/1608).
One observation from debugging this, is that it seems like the correct way to apply the CSS reset going forward is to use the `resetCSS` prop on `ChakraProvider`, rather than including the `<CSSReset />` component directly – is that correct?
> fix(core): flip load order of CSSReset and GlobalStyles

- packages/icon/src/icon.tsx
When I passing `viewBox` prop to change icon library default viewBox, still is got default `0 0 24 24`, so I hoisting `_viewBox` argument.
> fix(Icon): custom icon library viewBox

- packages/system/src/forward-ref.tsx
Resolves #1582
@segunadebayo and I worked on this over the weekend. I need to run a few perf tests on it but it seemed to give a solid speed boost because we're no longer relying on `JSX.IntrinsicElement`.
> perf: widen As prop typing

- website/pages/docs/migration.mdx
Just a trivial typo. It should be `emotion-theming` instead of `@emotion/theming`.
By default the packages are ordered alphabetically, so I also updated the ordering here.
> docs: fix package name in the migration guide

- packages/number-input/src/use-number-input.ts
Fixes #1649:
> When number input is not empty, `onChange` callback is fired on each input blur, regardless of whether there was an actual change/input.
> 
> Happens both in controlled and uncontrolled mode.
> 
> Reproduction: https://codesandbox.io/s/numberinput-onchange-is-called-on-every-blur-1s72h?file=/src/index.js
> Version: 1.0.0-rc.2 (does not happen in v0.8.0)
It was tested with the [mentioned sample code (Reproduction)](https://codesandbox.io/s/numberinput-onchange-is-called-on-every-blur-1s72h?file=/src/index.js)
> fix onChange callback activation on NumberInput

- packages/color-mode/src/storage-manager.ts
- packages/color-mode/tests/use-color-mode-state.test.ts
This PR catches error when localStorage is disabled by browser setting. Currently, when localStorageManager tries to access disabled localStorage, it throws an error.
On Google Chrome,
```
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```
On FireFox,
```
window.localStorage is null
```
Instead, it will output warning to console.
Reference: This is how [theme-ui](https://github.com/system-ui/theme-ui) handle this type of error. https://github.com/system-ui/theme-ui/blob/a96e723bad9c0d8b03c858698045acf01587cf9d/packages/color-modes/src/index.js#L9-L32
> fix(color-mode): catch when localStorage is disabled

- website/pages/docs/migration.mdx
Added note in the migration guide about `RadioButtonGroup` being deprecated. Also added a link to the documentation around the hooks that replace it.
Fixes #1650
> docs: added not about RadioButtonGroup being deprecated

- packages/avatar/src/avatar-group.tsx
- packages/avatar/tests/avatar-group.test.tsx
There was a bug with the Avatar Group showing excess even when excess hasn't been reached. 
This fixes https://github.com/chakra-ui/chakra-ui/issues/1666
No breaking changes.
> fix(avatar): avatar group shows excess even when excess isn't hit

- packages/tabs/src/use-tabs.ts
- packages/tabs/tests/tabs.test.tsx
- website/pages/docs/components/tabs.mdx
Add `isLazy` property to `Tabs` to only mount the contents of a TabPanel to the DOM when the tab is activated/clicked/selected.
Fixes #1384
A new test has been added in `packages/tabs/tests/tabs.test.tsx`
#
Related:  #1118
> Performance: Add isLazy property to Tabs

- website/pages/docs/components/icon.mdx
Noted that the default chakra icons need to be imported from `@chakra-ui/icons`
Closes #1670
> docs: called out that default chakra icons need to be imported from @chakra-ui/icons

- website/pages/docs/overlay/alert-dialog.mdx
- website/pages/docs/overlay/modal.mdx
Expanded the `Modal` docs to provide more information and an example on adding transitions. Updated the `AlertDialog` docs with the correct transition components.
Fixes #1551
> docs: updated transition section for modal and alert dialog

- website/pages/docs/migration.mdx
This should occur in `_document.js`, not `_app.js`.
See https://nextjs.org/docs/advanced-features/custom-document for further guidelines on customising the `_document`.
> Amend InitializeColorMode steps for Next.js

- packages/modal/src/modal.tsx
I wasn't able to do the following because of the typings (which I could do with the `ModalHeader`).
```
<ModalFooter as={Stack} direction="row">...</ModalFooter>
```
Looking into the code I found that the footer was defined diferently than the header and the body. This PR fixes this incosistency by using the same method as the other components.
> fix(modal): fix ModalFooter to use the forwardRef utility

- website/pages/docs/migration.mdx
IconButton wasn't mentioned in the migration doc, so I've added a section for it.
> docs: add `IconButton` to migration doc

- packages/number-input/src/number-input.tsx
The number input component renders its `Stepper` children with a `zIndex` of 1: https://github.com/chakra-ui/chakra-ui/blob/develop/packages/number-input/src/number-input.tsx#L125
This causes issues with the steppers appearing above other absolutely-positioned elements with a lower `zIndex` or that appear before the number input in the HTML stack.
Here's a GIF of the bug in action:
By setting `zIndex: 0` on the wrapper component, its children won't render above other elements like this:
> fix: Zero-out number input wrapper z-index

- packages/utils/src/dom.ts
I am just adding a reference to prove that the memory leak happened in IE11.
So other can get to know about it too.
> docs: add ref to IE11 window memory leak issue

- website/pages/docs/components/icon.mdx
- website/src/components/codeblock/react-live-scope.tsx
- website/src/components/docs/icon.tsx
Resolves #998 
Currently, the `Icon` documentation feels fragmented and without a clear direction or purpose. The page begins with importing the `Icon` component, moves into an example that then doesn't use the `Icon` component, lists all of the Chakra icons, then starts the section about using a third-party icon library by explaining all of the reasons to not use the third-party icon library directly. Just kind of all over the place, which is hard for users to follow.
This PR fixes that by breaking the page down into three main parts:
- using the official Chakra UI icon library
- using a third-party icon library
- creating your own icons
Each part is treated like its own "concept", explaining what it does, how to install and/or import it, and how to use it. The "creating your own icons" …
> docs: restructure `Icon` page

- website/configs/docs-sidebar.ts
This PR adds the docs in `pages/docs/components` to the sidebar. Poor things were missing!
> fix(website): add missing docs/components to the sidebar

- website/pages/team.tsx
This changes an issue where team GitHub links didn't link to anything. Thanks @ljosberinn for catching that.
> fix(website): enable team github links

- package.json
This PR fixes an issue where the `public/` directory wasn't correctly copied to deployments by `vercel.` The `public/` directory needs to be in the root directory in order for it to find it, so I added a command to `cp` to that directory to the root. 
As part of this change I updated the build command in the Vercel project settings to `yarn docs:deploy`.
Thanks to @jmiazga for the assist on this one!
> chore(website): add docs:deploy script

- packages/input/src/input-element.tsx
- packages/input/tests/__snapshots__/input.test.tsx.snap
Fixes #1900 
See #1900
- `InputElement` has a `z-index` of `2`.
This is a naive solution. Without a `_groupFocusWithin` pseudoselector, we don't have a good way to apply `z-index` only when the `input` is focused.
I'd be happy to create that if we'd rather go with that.
> fix(input-element): increase z-index

- package.json
- tooling/cra-template-typescript/package.json
- tooling/cra-template-typescript/tsconfig.json
- tooling/cra-template-typescript/typings.ts
- tooling/cra-template/package.json
`cra-template` and `cra-template-typescript` don't have a `lint` script defined, so they are not type-checked or linted during the pipelines.
- Added `lint` script to `cra-template` that runs `eslint` on `js, jsx` files in `template/src`
- Added `lint` script to `cra-template-typescript` that runs `eslint` and `tsc --noEmit` on files in `template/src`
I had to introduce `tsconfig.json` and a `typings.ts` file to `cra-template-typescript` to get linting and type-checking to work. These files won't be added to projects generated from the template, so they have no end-user effect.
> chore(cra-templates): add lint scripts

- website/pages/index.tsx
On safari there's a rather amusing bug that makes "Chakra Heroes" look very
L
O
N
G
Image sizes are fixed to specific width and height
> Set width and height for heroes

- packages/number-input/src/use-number-input.ts
N/A
Since the `useCounter` uses the `onChange` directly in the `updateFn`.
I think it's safe to remove the `onChangeProp` destructure here.
> refactor(number-input): no onChange destrct needed

- packages/theme-tools/src/component.ts
Typing isn't exported, leading to issues when declaring global style
```typescript
import { default as defaultTheme } from "@chakra-ui/theme";
import { SystemStyleObject } from "@chakra-ui/styled-system";
import { merge } from "@chakra-ui/utils";
import { runIfFn } from "@chakra-ui/utils";
import type { Theme } from "@chakra-ui/theme";
export const theme: Theme = {
...defaultTheme,
styles: {
...defaultTheme.styles,
global: (props): SystemStyleObject =>
merge(runIfFn(defaultTheme.styles.global, props), {
"@media screen and (max-width: 60em)": {
"html, body, #___gatsby, #gatsby-focus-wrapper": {
height: "100%",
},
"#gatsby-focus-wrapper > div.css-0": {
height: …
```
> chore(theme-tools): Make GlobalStyleProps exportable

- packages/number-input/src/use-number-input.ts
onMouseUp is called when onMouseLeave is executed
onMouseUp is called when onMouseUp is executed
> fix(number-input): handler for onMouseLeave

- packages/number-input/src/use-number-input.ts
`ariaValueTest = undefined`
`ariaValueTest = ${currentValueAsString}`
When getAriaValueText is not provided, araiValueText default to `undefined` but we can show the value(string) by default.
> fix(number-input): provide ariaValueText fallback

- packages/icon/src/icon.tsx
> The icons from @chakra-ui/icons@1.0.0-rc.3 are throwing the following error:
> Type '{}' is missing the following properties from type ...
Fix #1903 
Make all properties in `IconProps` optional with type `Partial<T>`.
> fix(icon-props-type): make icons props optional

- packages/input/tests/__snapshots__/input.test.tsx.snap
- packages/number-input/tests/__snapshots__/number-input.test.tsx.snap
- packages/select/tests/__snapshots__/select.test.tsx.snap
- packages/textarea/tests/__snapshots__/text-area.test.tsx.snap
Just update a test snapshot for the `NumberInput`, `Input`, `Select` and `TextArea`. 
The background color changed from `#FFF` to `inherit`.
Failing test due invalid snapshot
Green test
> test(number-input): update number-input, input, select and textarea snapshot due background

- tooling/gatsby-plugin-chakra-ui/gatsby-browser.js
Flips the order of GlobalStyles and CSSReset to fix CSSReset taking precedence, same as in PR #1609
GlobalStyle is loaded before CSSReset, making CSSReset take precedence
Swaps the order to reset first and then load the new GlobalStyles
> fix(tooling): flip load order of CSSReset and GlobalStyles

- website/pages/docs/feedback/toast.mdx
Docs do not explain the usage of the `close` and `closeAll` instance methods on the `toast` object.
@ljosberinn I might be missing something here, but I don't think the `closeAll` method is working as I thought it should be in the example story. Any ideas?
#63
> docs: document usage of close/closeAll instance methods

- packages/toast/src/use-toast.tsx
This PR fixes the alignment issue in #1183, preventing the right edge of right-aligned toasts from getting cut off.
---
> fix(toast): improve type and layout style with relative units from theme

- packages/alert/src/alert.tsx
- packages/alert/tests/__snapshots__/alert.test.tsx.snap
- packages/theme/src/components/alert.ts
- website/pages/docs/feedback/alert.mdx
This PR improves the `Alert` component's layout consistency, addressing #1619 and previously included with #1611.
Presently, `AlertTitle` and `AlertDescription` have slightly different line heights, and behave inconsistently depending on the content provided. A few of the [stories](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/alert/stories/alert.stories.tsx) for this component use additional markup with varying results. This PR attempts to reconcile some of these issues.
`AlertTitle` and `AlertDescription` present as inline as a side-effect of the alert container's flex styling, but then present with a line break when placed inside another div …
> fix(alert): improve layout and text/icon alignment

- website/pages/docs/components/accordion.mdx
`AccordionItem` no longer has the `isOpen` and `onChange` props as part of its api, but these are still documented.
- Removed references to `isOpen` and `onChange` in the props table
> docs(accordion): remove references to some AccordionItem props

- packages/system/src/use-style-config.ts
- fixes #2012
please see https://github.com/chakra-ui/chakra-ui/issues/2012#issuecomment-691458782 for more info
Its a perf improvement for non-Preact projects too, for some reason it simply doesn't occur in React though.
> fix: useStyleConfig omit children when merging

- website/pages/docs/features/style-props.mdx
- website/pages/docs/migration.mdx
* Lack of explicit guidance to replace PsuedoBox on migration guide (although noted in features list, it should probably be included as part of the migration steps)
* Minor formatting/consistency issues with semicolons on the style-props
* Adding a step 6 in the migration guide to be explicit about deprecating `PsuedoBox` 
* Clean up semicolons on `style-props.mdx` for consistency with the rest of the documentation (note Prettier seems to be automatically adding a semicolon if a single HTML element is displayed in conjunction with an `import` statement so adding another example prevents that behavior) 
* Added an example on how to use …
> docs: add depreciation of psuedobox in migration guide, update formatting/consistency of style-props doc

- packages/menu/src/use-menu.ts
- packages/menu/tests/menu.test.tsx
Issue Number: Fixes #2011 
- The anonymous func passed to `onInteractOutside` of `useInteractOutside ` in `useMenu` hook was updated
Made a small investigation of the issue: #2011.  Both menus have their outside click listeners. While they share the same state for `isOpen` prop, a click on the first menu item is handled by `onClose` of the second menu which closes the first. 
See below screenshots:
Click 1 on button;
Click 2 on Menu item.
FF (doesn't fire onClick listener on a MenuItem, just forces closing): https://prnt.sc/uh0e3n 
Chrome: https://prnt.sc/uh0flo
> fix: don't call onClose in onInteractOutside if menu isn't opened

- packages/menu/src/menu.tsx
IE 11 has problems with `flex: 1`. Flex basis is set to 0 and flex-grow is ignores, which results in a width of 0. The `span` element inside the `MenuButton` uses `flex: 1`, which results in a broken layout:
(Screenshots from the docs page)
`flex-basis` will be set to auto, which allows IE to calculate the correct element width and fixes the layout issue:
(Screenshots from the docs page)
> fix: MenuButton flex-basis in IE11

- website/pages/docs/components/tabs.mdx
Issue Number: #2050 
Now there's dark variants of each color being used on the dark mode for the example.
> docs(tabs): fix tabs onchange example colors for dark mode

- packages/layout/src/list.tsx
- [ x] Bugfix
In Firefox, `UnorderedList` currently renders with numbers (due to incompatibility of `"bullet"`)
To resolve this, the `styleType` is instead set to the default (or `initial`) browser for `ul`
> Change default UnorderedList styleType to initial

- packages/slider/src/use-slider.ts
- website/pages/docs/form/slider.mdx
See below
Adds a boolean `thumbFocusCapture` to `use-slider` so users can opt-out of the default behavior where the slider thumb captures focus on every value change - expected use-case is with a controlled slider that shares a page with other elements require focus for user input.  Without it the slider will continually "steal" focus by default.
> Add `thumbFocusCapture` prop to `use-slider`

- website/pages/docs/migration.mdx
In my previous PR #2061 I by mistaken wrote `isOpen` instead of `defaultIsOpen` for `useDisclosure` hook which prevents updates caused by `onClose`, `onOpen` and `onToggle`
This may cause problems since v0.x had behaviour similar to `defaultIsOpen` which will allow user to modify on using hook functions
Sorry for confusion :sweat_smile:
NA
NA
> :memo: migration guide use defaultIsOpen instead of isOpen

- packages/skeleton/src/skeleton.tsx
- packages/skeleton/stories/skeleton.stories.tsx
- [ x ] Bugfix
If the `isLoaded` prop is passed to the `SkeletonText` component, the console produces the following error:
```
Warning: React does not recognize the `isLoaded` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isloaded` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
Additionally, the `isLoaded` prop will not toggle the skeleton's status.
`isLoaded` on `SkeletonText` now reveals its children if `true`, and the console error is no longer reduced.
- [x ] No
I also updated the storybook to show the fix in …
> fix(skeletontext): added isLoaded to skeletontext

- website/pages/docs/overlay/alert-dialog.mdx
By doing the following in line 57, 
`const [isOpen, setIsOpen] = React.useState(false)`
`setIsOpen` will have the type `React.Dispatch<(prevState: undefined) => undefined>`.
This would give us a type error at line 58 as `useIsOpen` expects an undefined rather than a boolean. To fix this, we simply just pass `false` into `useState`. Now `setIsOpen` will have `React.Dispatch<React.SetStateAction<boolean>>`, which is what we expect.
Tests not needed as its just changing documentation.
`setIsOpen` has type `React.Dispatch<(prevState: undefined) => undefined>` we want the type to be `React.Dispatch<React.SetStateAction<boolean>>`. 
`setIsOpen`now …
> docs: Initialze isOpen hook to false to prevent undefined problems.

- packages/input/src/input-group.tsx
When rendering `InputLeftElement` using https://github.com/hashicorp/next-mdx-remote I'm getting this error:
```
TypeError: Cannot read property 'height' of undefined
at /Users/adelnizamutdinov/Projects/sumptus/node_modules/@chakra-ui/input/dist/cjs/input-group.js:39:62
at Array.forEach (<anonymous>)
at Object.InputGroup [as render] (/Users/adelnizamutdinov/Projects/sumptus/node_modules/@chakra-ui/input/dist/cjs/input-group.js:33:17)
```
I want to point out to maintainers that there's an issue, but I'm not comfortable enough with codesandbox to create a repro 😞
> fix Cannot read property 'height' of undefined

- website/pages/docs/components/accordion.mdx
Fixes #2103 
Removed the `defaultIsOpen` prop from the `AccordionItem` props table.
> docs(accordion): remove reference to AccordionItem defaultIsOpen prop

- packages/media-query/src/use-breakpoint.ts
Fixes: #2111
- useBreakpointValue should now work in Safari
> Fix: useBreakpoint - mediaQuery undefined in safari (issue: #2117)

- packages/media-query/src/use-breakpoint.ts
useBreakpoint breaks in any old version of Safari, the issue was reported and fixed here:
https://github.com/chakra-ui/chakra-ui/issues/2117
But the submitted fix was only partial, the second cleanup also needed to use the old removeListener function.
Fixes: 2117
- useBreakpoint works as expected in Safari, using the old style addListener / removeListener functions.
> Fixes useBreakpoint on Safari < 14.0

- website/pages/docs/overlay/menu.mdx
- website/pages/docs/overlay/popover.mdx
- add isLazy prop for `Menu` component
related issue #2146
> docs(menu,popover): add isLazy prop for menu and popover

- tooling/gatsby-plugin-chakra-ui/gatsby-browser.js
This change is required since https://github.com/chakra-ui/chakra-ui/commit/097c783a00736a119b253fb26316c7538de929c5 moved `ColorModeProvider`'s `useSystemColorMode` option from a non-required prop to a property of a new `option` prop. If `gatsby-plugin-chakra-ui` is used without setting `isUsingColorMode` to false, we get the following error:
> TypeError: Cannot read property 'useSystemColorMode' of undefined
This happens because `gatsby-plugin-chakra-ui` doesn't pass any `options` prop to the `ColorModeProvider`, and [there isn't a default value for that prop](https://github.com/chakra-ui/chakra-ui/commit/097c783a00736a119b253fb26316c7538de929c5#diff-d296f0384fcd423d710d49ec1d834d32R57). So I decided to just pass `theme.config` [as it's currently done in …
> fix: forward theme.config in Gatsby plugin

- packages/theme/src/components/input.ts
The input's `borderBottom` property contained "inherit" as part of it's value. Only individual properties such as `borderColor` can "inherit". This caused an issue when trying to update borderColor with theme object.
Fixes: #2113 
Small change, added borderColor property with "inherit" value for input and select.
> fix(input): input & select in flushed variant has no borderColor

- website/pages/guides/how-to-create-a-guide.mdx
On the [How to create a guide](https://next.chakra-ui.com/guides/how-to-create-a-guide) documentation page, the final two links on the page link to the same URL.
I've provided the correct URL for the [_Creating a pull request from a fork_](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) link.
Additionally, GitHub has introduced a new documentation website, https://docs.github.com (details [here](https://github.blog/2020-07-02-how-we-launched-docs-github-com/)).  I've updated both links with new URLs for the same content.
> docs: fix GitHub links

- packages/color-mode/src/color-mode-provider.tsx
- packages/color-mode/src/color-mode.utils.ts
A CRA project with react-scripts ^3.4.3 and chakra-ui 1.0.0-rc.5 fails in a jest test due non existing `window.matchMedia` with:
```
Error: Uncaught [TypeError: Cannot read property 'media' of undefined]
```
[see Discord Discussion](https://discordapp.com/channels/660863154703695893/758645914868514827/763026733553025036)
Added check for falsy return value of `const mediaQueryList = window.matchMedia?.(query)` in `getMediaQuery` with fallback to `initialColorMode`.
> fix(color-mode): getColorScheme fails in test env

- website/pages/docs/components/tabs.mdx
- [] Docs have been reviewed and added / updated if needed (for bug fixes
The available props section for the Tabs component is entirely missing on the v1 docs page.
Fixes: #2175 
- Added `props` section to tabs.
> docs(tabs): add props section

- packages/toast/package.json
- packages/toast/src/index.ts
- packages/toast/src/use-toast.tsx
- packages/toast/test/standalone-toast.test.tsx
- website/pages/docs/feedback/toast.mdx
As mentioned in #1693 application code outside of the react context should be able to create a new toast.
E.g. in API abstractions or Vanilla JS files it can simplify the code.
Fix #1693
```
import { createStandaloneToast } from "@chakra/core"
const toast = createStandaloneToast()
// const customToast = createStandaloneToast({ theme: customTheme })
const fetchUsers = async () => {
await fetch() // ...
toast({
title: "Yay",
status: "success"
})
}
```
> feature(standalone-toasts): create toasts outside of react components

- packages/toast/src/toast-manager.tsx
- packages/toast/src/toast.class.tsx
- packages/toast/src/toast.types.ts
- packages/toast/stories/toast.stories.tsx
- website/pages/docs/feedback/toast.mdx
Using `toast.closeAll()` always closes all toasts. 
You may now pass `...cloaseAll({ positions: ['bottom'] })` to only close selected positions, keeping other toasts intact.
> feat(toast): allow toast.closeAll position selection

- packages/button/src/button.tsx
- packages/select/src/select.tsx
- packages/skip-nav/src/index.tsx
- packages/styled-system/src/css.ts
- packages/system/src/hooks.ts
- packages/system/src/providers.tsx
- packages/system/src/use-style-config.ts
- packages/utils/package.json
- packages/utils/src/object.ts
- website/pages/docs/theming/advanced.mdx
- in favor of lodash.mergeWith, they work identical if the last argument is not a function
we're carrying both `lodash.merge` and `lodash.mergeWith` around, `.mergeWith` is only there for `extendTheme`. they do the same, however, unless the last argument passed is a function: https://codesandbox.io/s/condescending-mountain-m2p5v?file=/src/index.js
This is a bundle analyzer of my site using Chakra. Except for the `src` and `i18next`, folder, almost in there should be Chakra related. As you can see, `lodash.mergeWith` and `lodash.merge` are entirely separate and not exactly small (gzip representation in bundle analyzer is active)
- all usage of `lodash.merge` …
> refactor: remove lodash.merge dependency

- packages/skeleton/package.json
- packages/skeleton/src/skeleton.tsx
- packages/skeleton/stories/skeleton.stories.tsx
- packages/skeleton/tests/skeleton.test.tsx
- packages/skeleton/tests/test-data.ts
- packages/system/src/system.types.tsx
Fixes: #2170 
Currently the Skeleton Component implements its own noOfLines prop instead of using the system-wide one. Therefore it's also a static value and no chakra responsive value.
- noOfLine for Skeleton.Text Component can now be passed as responsive values (different noOfLine value for different breakpoints)
> fix(skeleton): implemented noOfLines as responsive value

- packages/accordion/src/use-accordion.ts
`AccordionContext` provides access to the data required by Chakra's `Accordion`-related components, but doesn't provide access to the actual `index` value, or the `setValue` function for modifying that value.
- `index` and `setIndex` are attached to `AccordionContext`
This is the result of a conversion on Discord surrounding the ability to create a "toggle all" button for toggling all accordion items open or closed. That's possible with the existing API but would require directly passing `index` and `setIndex` to the button. This change allows the button to directly access and set the `index` value just by using context.
> refactor: add index, setIndex to AccordionContext

- packages/layout/src/list.tsx
- packages/layout/stories/list.stories.tsx
`List` handles the spacing prop by injecting `mb` directly into children. This causes `List` spacing to fail when children are wrapped in `React.Fragment`.
Fixes: #2233 
`List` now handles the spacing prop by using the lobotomized owl selector. This causes `List` spacing to work correctly even when children are wrapped in `React.Fragment`.
> fix: use the lobotomized owl selector for spacing list children

- packages/utils/src/object.ts
- packages/utils/tests/object.test.ts
The `filteredUndefined` method in `@chakra-ui/utils` does not properly filter undefined. The unit test for this was a false positive due to the use of `.toMatchObject()`, which will pass on partial matches.
- Fixed `filterUndefined()` to also remove `undefined`, along with `null`.
- Fixed the associated unit test to use `.toStrictEqual()`.
> fix(utils): properly filter undefined object values

- website/pages/docs/features/style-props.mdx
Group Hover docs in 1.0RC is missing some information details still not brought from 0.8.0 docs.
I just added the role="group, as this is required for _groupHover to work
> docs: Update _groupHover parent role="group" attribute info - 1.0RC

- packages/tooltip/src/use-tooltip.ts
- packages/tooltip/stories/tooltip.stories.tsx
- packages/tooltip/tests/tooltip.test.tsx
Fixes: https://github.com/chakra-ui/chakra-ui/issues/500
Events are not dispatched by default on disabled buttons. However, for tooltips, when `shouldWrapChildren` is set to true, we can still expect to see the tooltip, since it's placed on the `span` parent. There seemed to be an issue with the tooltip never being closed in such cases. My guess is that it's related to the following React issue: https://github.com/facebook/react/issues/11972.
- The tooltip is closed when an `onMouseLeave` event is launched from a "wrapped trigger" that has a disabled element as a child
This is my first contribution! Please let me know if I'm missing something. 🙂
> fix: close tooltip when leaving wrapped disabled trigger

- packages/styled-system/src/config/typography.ts
lineSpacing prop had jsdoc referring to 'line-height' css property before.
Now, it correctly refers to 'line-spacing' css property.
-
-
-
> docs(doc-mistake): Corrected jsdoc for lineSpacing typography prop

- packages/image/src/use-image.ts
Fixes: https://github.com/chakra-ui/chakra-ui/issues/1827
The problem is the default value on useImage `status` state. Now I changed it to `pending` as default value and let useEffect update it.
> fix(avatar): fix unmounting & mounting avatar doesn't display the src

- packages/system/src/forward-ref.tsx
> Uses `keyof JSX.IntrinsicElements` for 'As' type used in PropsOf

- website/pages/docs/features/color-mode.mdx
I've found out that when there are no other cookies, checking just for a truthy value of `cookie` doesn't seem to work, but checking it is an actual string as in the example for older Next versions seems to work fine. I was wondering if this change was intentional, or just a mistake. 
Please, feel free to close this PR if the change was intentional and this is not the problem. 
Thanks!
When there are no other cookies (such as session, etc,etc) and you're not calling `toggleColorMode` or `setColorMode` and just relying on system preferences, the cookie is never set.
When there are no other cookies (such as session, etc,etc) and you're not …
> fix: Update cookies checks in example

- packages/layout/src/wrap.tsx
- packages/layout/stories/wrap.stories.tsx
- website/pages/docs/layout/wrap.mdx
Currently, `Wrap` clones all children and "wraps" each child with item styles. Although I may have something to do with influencing this in the initial version of [`raam`](raam.joebell.co.uk/), I no longer believe this is the right way forward.
I recently hit a snag in a custom component which involved adding/removing items to `Wrap`, with the last element being an `Input` (enhanced by Downshift). Unfortunately, every time an item was added/removed, the re-render of children caused Downshift to behave unexpectedly (https://github.com/downshift-js/downshift/issues/1187#issuecomment-713641908).
With the current implementation it's also difficult to customise the …
> RFC: Use WrapItem in favour of cloning children in Wrap

- packages/tooltip/src/tooltip.tsx
Fixes a className type on the arrow element.
The current arrow component of `Tooltip` has a the className of `chakra-toolip_arrow`.
- Set the className to `chakra-tooltip_arrow`.
> fix(tooltip): className typo on arrow

- packages/layout/src/flex.tsx
- packages/layout/tests/__snapshots__/layout.test.tsx.snap
- packages/layout/tests/layout.test.tsx
- website/pages/docs/layout/flex.mdx
Fixes: #2373 
The Flex component accepts the `shrink` prop but does not map to `flexShrink`.
The Flex component now correctly maps `shrink` prop to `flexShrink` style prop.
> fix(flex-shrink-shorthand): adds missing shrink style prop shorthand for Flex

- packages/popover/src/popover.tsx
The PopoverContent component accepts the className prop but doesn't apply it to the underlying component.
The PopoverContent component now apply the className prop to the underlying component.
Thank you for your work on chakra-ui! 🙏
> fix(popover-content): add missing className merge

- packages/toast/src/toast.tsx
- packages/toast/src/use-toast.tsx
- packages/toast/test/use-toast.test.tsx
The `useToast` hook cannot accept default options for subsequent `toast(...)` calls.
Fixes: #2316 
The `useToast` hook cannot accept default options for subsequent `toast(...)` calls.
-
-
-
> feat(toast): useToast can accept default options

- packages/button/stories/button.stories.tsx
- packages/theme/src/components/button.ts
Buttons receive hover styles when disabled.
Buttons hover styles are overriden with default styles when disabled.
A better approach may be to set the hover styles via `:hover:enabled` but would require a change to the [pseudoselectors](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/styled-system/src/pseudo/pseudo.selector.ts) to support this.
> feat: unset button hover styles when disabled

- packages/hooks/src/use-controllable.ts
- packages/hooks/tests/use-controllable.test.tsx
The `updateValue` callback inside `useControllableState` has an empty dependencies array, so it's impossible to update the `onChange` callback.
Fixes #2384
- Added `onChange` callback to `updateValue` dependencies array, so that when `onChange` changes, the correct callback is called.
I think this change makes sense, but I'd like to get some feedback to make sure.
> fix(use-callback): allow onChange prop to update updateValue callback

- .eslintrc
`eslint` complains about `parserOptions.project` configuration in files
that aren't specified in `tsconfig.json` (like `babel.config.js`). This
change moves the parser configuration to an `overrides` section
specifically for `ts` and `tsx` files.
> chore(eslint): add tsconfig parserOptions only for ts,tsx

- website/pages/docs/layout/aspect-ratio.mdx
- ~[ ] Tests for the changes have been added (for bug fixes / features)~
The docs conflict on whether a child of `AspectRatio` should be specified as `iframe` vs `<Box as="iframe>`
The docs are consistent and reflect the proper usage.
c91fdf397f5b75a315d9dff6918684b9f1e5e988 removed the need to supply a styleable child.
8990a903716f9d78b784ee5e91a3360331b2d8b5 updated the examples to reflect that change, but missed this note.
> docs(aspect-ratio): remove obsolete note

- packages/layout/src/text.tsx
- packages/layout/stories/text.stories.tsx
A theme variant for the `Text` component should be able to override the aliased props `align`, `decoration` and
`casing`.
Fixes: #2464 
Props are overridden by the theme variant values. 
See storybook story Text -> Issue 2464.
> fix(aliased-text-props): allow override of aliased props

- tooling/gatsby-plugin/README.md
Gatsby plugin docs say to override theme in `src/@chakra-ui/gatsby-plugin/index.js`
Theme needs to be placed at `src/@chakra-ui/gatsby-plugin/theme.js`
-
-
-
> fix: gatsby-plugin had wrong filename to override theme

- .changeset/fluffy-buttons-appear.md
- packages/layout/src/stack.tsx
- `StackDivider` will cause `each child in a list should have a unique "key" prop.` error.
Fixes: #2509 
- When using `<StackDivider>` at Stack `divider` props, There will be no errors anymore. 
None.
> fix: stack divider keys issue

- .changeset/sharp-trains-fly.md
- packages/utils/src/object.ts
- packages/utils/tests/object.test.ts
The cache for memoized get function in the object util is using newly created arrays for it's keys, this causes cache misses on every call and leads to a memory leak. 
The cache now uses the provided path as it's keys, this fixes the cache misses and by extension the memory leak.
We are now exporting 'memoize' from object.ts to make testing it easier/possible.
> Fix/utils: stop memory leak in object.ts

- .changeset/spotty-trees-attack.md
- tooling/cra-template-typescript/template.json
(not required for this fix)
When starting a new CRA project using the @chakra-ui/typescript template, runtime errors are raised due to the following missing dependencies:
@emotion/react
@emotion/styled
This is very similar to issue : #2493  which is for the regular, non typescript template.
This PR mirrors PR #2494 to make the same fix in the typescript template
The missing dependencies have been added to the manifest file of the CRA template for typescript.
N/A
> fix(cra-template-typescript): added missing dependencies

- CONTRIBUTING.md
Updated `CONTRIBUTING.md` example that was referencing checkbox for an example that was actually using a button.
> docs: fix example referencing wrong component

- .changeset/unlucky-peas-yawn.md
- packages/media-query/src/use-breakpoint.ts
`useBreakpoint` uses `undefined` for its current breakpoint if no default value is passed, causing its effect to trigger a re-render when the current breakpoint gets updated to its correct value
`useBreakpoint` matches media on first render
> fix: match media on useBreakpoint when no default value

- .changeset/nasty-bottles-run.md
- packages/form-control/src/form-control.tsx
Nonfunctional props `helperText` and `errorText` are present
removed the props
The removal of the prop definition is imo a breaking change. It do not think it will have an impact on the userland usage, because they do nothing. 
Should we major bump form-control for this or go with a patch?
> fix(form-control): remove obsolete props

- .changeset/beige-snails-burn.md
- packages/number-input/package.json
- packages/number-input/src/use-number-input.ts
- packages/number-input/stories/number-input.stories.tsx
- packages/number-input/tests/__snapshots__/number-input.test.tsx.snap
- packages/number-input/tests/number-input.test.tsx
- website/pages/docs/form/form-control.mdx
Fixes: #804 
`FormControl` propagates props down to `NumberInput` children.
I couldn't find any tests between FormControl and Select. So do i have to test the composition between FormControl and NumberInput?
> feat(number-input): uses props of wrapping form-control

- website/pages/docs/migration.mdx
The last version of framer-motion is still 2.9.4
Following the migration steps by manually update the package.json file give the following message with yarn :
```
Couldn't find any versions for "framer-motion" that matches "^2.9.5"
? Please choose a version of "framer-motion" from this list: (Use arrow keys)
❯ 3.0.0-rc.16 
3.0.0-rc.14 
3.0.0-rc.13 
3.0.0-rc.12 
3.0.0-rc.11 
3.0.0-rc.10 
3.0.0-rc.9 
3.0.0-rc.8 
3.0.0-rc.7 
3.0.0-rc.6 
3.0.0-rc.5 
3.0.0-rc.4 
3.0.0-rc.3 
3.0.0-rc.2
```
The documented version of framer-motion is wrong.
> docs(migration): fix the framer-motion version

- website/vercel.json
This PR adds `/discord` as a redirect to the URL for our Discord server invite so we can direct users to https://chakra-ui.com/discord.
> chore(website): add /discord invite redirect

- .eslintrc
- packages/clickable/src/use-clickable.ts
- packages/clickable/src/use-event-listeners.ts
- packages/counter/src/use-counter.ts
- packages/hooks/src/use-focus-on-show.ts
- packages/hooks/src/use-outside-click.ts
- packages/hooks/src/use-unmount-effect.ts
- packages/menu/src/use-menu.ts
- packages/modal/src/modal.tsx
- packages/number-input/src/use-number-input.ts
- packages/pin-input/src/use-pin-input.ts
- packages/popover/src/use-popover.ts
- packages/popper/src/use-popper.ts
- packages/toast/src/toast.tsx
- packages/tooltip/src/use-tooltip.ts
This PR enables `plugin:react-hooks/recommended` rules, which gives us the `react-hooks/exhaustive-deps` rule. I've bumped that rule to `error` level and resolved this error throughout the project. This should have been enabled awhile ago but didn't notice it was missing until now.
> chore(eslint): enable plugin:react-hooks/recommended

- .changeset/sixty-lizards-provide.md
- packages/transition/src/collapse.tsx
- packages/transition/stories/collapse.stories.tsx
- packages/transition/tests/collapse.test.tsx
Collapse with in prop set to true on first render did not show its children
Fixes: #2534 
- Now it renders its children
> fix(collapse): show children if initial in prop is true

- website/pages/docs/migration.mdx
- [-] Tests for the changes have been added (for bug fixes / features)
The bullet points contain all changes depicted in the diff, except for one: `"@emotion/styled": "^11.0.0"`
I recently migrated to chakra-ui v1 using the migration guide. Unfortunately I overlooked that it is mandatory to update the `@emotion/styled` package since I followed only the steps in the bullet points, assuming that the diff below reflects the exact steps from the bullet points.
As a result, I was still using v10.0.27 which resulted in theme tokens not being resolved at all without any runtime error or warning.
Add a bullet point explicitly mentioning that `@emotion/styled` needs to …
> docs: Mention mandatory version update explicitly

- .changeset/rotten-doors-smash.md
- packages/react/src/extend-theme.ts
Throws TypeScript error with some overrides.
- moved type escape hatch to an higher level to allow every override
Tested with this _not so pretty_ theme override:
```ts
const customTheme = extendTheme({
shadows: {
outline: "0 0 0 3px rgb(0, 255, 0)",
},
colors: {
gray: {
"300": "red",
},
myCustomColor: {
"50": "papayawhip",
},
},
textStyles: {
dl: {
lineHeight: "tall",
"dd + dt": {
marginTop: "4",
},
},
dt: {
color: "gray.600",
fontSize: "sm",
fontWeight: "bold",
},
dd: {
color: "gray.800",
},
},
config: {
useSystemColorMode: false,
initialColorMode: "dark",
},
styles: {
global: {
body: {
color: "green.500",
},
},
},
components: {
Button: {
variants: {
ghost: {
fontFamily: "mono",
_active: {
bg: "red",
},
},
},
},
Input: {
baseStyle: { …
```
> fix(extend-theme): move escape hatch typings

- package.json
This PR updates the `lint:types` command to use `lerna run lint:types`, causing the command to only be run in packages where it exists. The previous script would run `tsc --noEmit` in packages where it shouldn't be run (like `examples` packages) causing local failures. This script is now useful for checking types locally.
> chore(scripts): use lerna run for lint:types

- .changeset/nice-tools-jump.md
- packages/system/src/use-style-config.ts
Fixes #2705
`useStyleConfig` is typed for the `props` argument to be optional, but
we then destructure `props` within the function. This change resolves
the issue by setting a default empty object value for the `props` and
`opts` arguments.
> fix(system): set default useStyleConfig arguments

- website/src/components/sidebar/sidebar.tsx
- The MainNavLink color in sidebar.tsx is hard to see in dark mode.
Fixes: #2714
I added `useColorModeValue` to change the color to display them better in active/hover link mode.
```js
useColorModeValue("gray.900", "whiteAlpha.900")
```
- The above was the default for the other links in the sidebar so I used the same.
- This changes is for `active` (if it's the current path) and `:hover`
-
> docs: add colorModeValue to MainNavLink

- .changeset/plenty-experts-explain.md
- packages/alert/src/alert.tsx
Bugfix
Fixes: #2696
`Alert` now respects the `colorScheme` property.
You can set it to override the color scheme that is by default determined by the `status` property.
No
> fix(alert): respect the colorScheme prop

- .changeset/curly-squids-chew.md
- packages/pin-input/src/pin-input.tsx
- packages/pin-input/src/use-pin-input.ts
- packages/pin-input/stories/pin-input.stories.tsx
- packages/table/src/table.tsx
Closes #2679
- Move input props logic to parent hook and expose prop-getter `getInputProps`.
This helps to co-locate the state logic for easier debugging
- Added support for alpha-numeric and secret values.
- Added `type` prop which can be either `alphanumeric` or `number`
- Added `mask` prop to hide input value similar to `<input type='password' />`
```jsx
<PinInput type="alphanumeric" mask>
<PinInputField />
<PinInputField />
<PinInputField />
</PinInput>
```
> feat: update and refactor pin input

- README.md
Readme recommends using the `CSSReset` component, although it is not needed as it is included by default in the `ChakraProvider`.
No
> docs: remove CSSReset from README

- .changeset/sour-cherries-unite.md
- packages/input/tests/__snapshots__/input.test.tsx.snap
- packages/number-input/tests/__snapshots__/number-input.test.tsx.snap
- packages/select/tests/__snapshots__/select.test.tsx.snap
- packages/textarea/tests/__snapshots__/text-area.test.tsx.snap
- packages/theme/src/components/input.ts
Closes #2703 
The Select component uses border for both focus state and invalid state, and the invalid state takes precedence. This means that, when a Select component has the isInvalid prop applied, it becomes impossible to visually determine whether the element has focus.
(Input has a similar style conflict, but it at least has the blinking cursor—but that might not be enough feedback for disabled users who expect a stronger visual signal.)
Focus outline now takes precedence over "isInvalid" outline.
No
This change just moves lines around to change their css priority.
Should we leave a comment in the code to make the intent explicit?
> fix(input): make focus outline take precedence over isInvalid outline

- .changeset/clever-eggs-kick.md
- packages/radio/src/radio.tsx
- packages/theme/src/components/radio.ts
Now we cannot customize the radio container like the checkbox. I want to add a part named container like the checkbox, so we can customize it.
We cannot customize the radio container
Now we can customize the radio container
> fix: cannot customize the radio container theme

- .changeset/stale-masks-stare.md
- packages/theme/src/components/checkbox.ts
Currently we able to add `container` in the parts, but this is not provided in the checkbox parts type.
Error type when adding container at the checkbox theme parts:
No error type
> fix(checkbox): fix themable parts list

- .changeset/rude-ravens-smell.md
- packages/skeleton/src/skeleton.tsx
- packages/skeleton/stories/skeleton.stories.tsx
Closes #2644
As described in #2644 there are cases where during the render of a skeleton component we might want to statically set isLoaded to true OR cases where the loading is already completed and therefore we want to avoid using the skeleton for a better UX (less page flickering).
#2644 did mention that a solution could be to add a flag to control this behavior. But I think that we should be opinionated about this and always prevent the use of the skeleton if the isLoaded property is already true on the first load. This will make the skeleton component simpler (by avoiding excessive flags) and nudge the developer towards better UX (less noise).
If **isLoaded** is true on the first render the fade-in animation is included
If **isLoaded** is true on the first render that fade-in …
> fix: #2644 skeleton fading on mounting

- .changeset/new-terms-explode.md
- packages/utils/src/array.ts
- packages/utils/tests/array.test.ts
Currently, `isCustomBreakpoint` filters the breakpoint key like `2xl` as it using `parseInt` which parses string starting with number into Integer.  I think replace it with `Number()` can solve this problem.
> fix: use Number instead of parseInt in isCustomBreakpoint #2789

- packages/radio/src/radio-group.tsx
The type for `RadioGroupProps` was a little too wide and allow `defaultChecked` to be passed to `RadioGroup` even though that has no effect. Could be potentially confusing.
Added `defaultChecked` to the `Omitted` type for `RadioGroupProps`.
No
> chore(radio): omit invalid "defaultChecked" prop from RadioGroupProps

- packages/css-reset/src/css-reset.tsx
> vertical-align only applies to inline, inline-block and table-cell elements: you can't use it to vertically align block-level elements. from [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align)
No.
> fix: vertical align property not used with display: block in css-reset

- packages/accordion/README.md
docs
Closes # 
> There is no spacing between 'accordion' and 'items'. And, it is not good for readability.
> I added spacing between 'accordion' and 'items'.
> This improves readability.
> docs(accordion): fix typo in README

- .changeset/early-poems-fly.md
Closes # 
The `@chakra-ui/gatsby-plugin` readme was updated but never published. I generated a changeset just so we can get this published.
The docs are outdated and dont match whats in the repo: https://www.npmjs.com/package/@chakra-ui/gatsby-plugin
Docs are current
No
> chore: readme was updated but never published

- .changeset/clean-balloons-pull.md
- packages/react/src/extend-theme.ts
Closes #2769
```diff
- extendTheme(overrides)
+ extendTheme(overrides, baseTheme = defaultTheme)
```
Allows extending an already extended theme. This is helps maintaining inherited design system.
Not possible without a copy of the extendTheme function.
```ts
const theme1 = extendTheme(overrides)
const theme2 = extendTheme(overrides, theme1)
```
No
> feat(extend-theme): allow passing a base theme to customize

- website/pages/docs/theming/customize-theme.mdx
I think it would be nice to also show how you can use a custom theme color for the `colorScheme` prop 😄
> docs: add example of how to use custom colorScheme

- .changeset/late-schools-wash.md
- packages/skeleton/src/skeleton.tsx
- packages/skeleton/stories/skeleton.stories.tsx
Closes #2800 
SkeletonText does not
* fade in when isLoaded toggles (so fadeDuration property does nothing on top of that)
* obey speed property
* Appling the component children to the first Skeleton in the noOfLines map function allows the animation to kick in.
* Passed the missing props through
SkeletonText accepts fadeDuration and speed prop and animates children
No
> fix(skeleton-text): accept animation props

- website/pages/docs/features/chakra-factory.mdx
Fix a typo in the code example of how to filter non-HTML attributes.
Little typo in the documentation.
Typo fixed.
No.
> docs(chakra-factory): Fix typo in filter example

- .changeset/light-geckos-divide.md
- packages/radio/src/radio.tsx
- packages/radio/tests/behavior.test.tsx
Closes #2842 
This PR resolves an issue where `Radio` components used outside of `RadioGroup` were not working correctly when uncontrolled. I also added a suite of tests around controlled/uncontrolled behavior for both `Radio` and `RadioGroup` to help prevent these issues in the future.
When used outside of `RadioGroup`, `Radio` components don't work when uncontrolled.
`Radio` can be used independently of `RadioGroup` without issues.
No
> fix(radio): allow useRadio to detect uncontrolled Radio

- .github/stale.yml
Closes #2634 
This PR makes `stalebot` useful again by removing almost all of the label exemptions while increasing the number of days of inactivity on an issue before it's marked as "stale" to 30.
`stalebot` does nothing because almost every label we use was added to `exemptLabels`.
- Removed all labels except for "not stale" and "Priority: High 🚨" from `exemptLabels`, which means everything except high priority issues and those we specifically mark as "not stale" will now be handled by the `stalebot` workflow.
- Since we're a small team and it can take us awhile to address things, I increased the number of days of inactivity on an issue before an issue is marked as "stale" to 30. This gives us a whole month on inactivity to decide whether to label an issue as "not stale" or not.
No
cc …
> chore(stalebot): make only "not stale" and high priority issues exempt

- .changeset/sharp-comics-tease.md
- packages/pin-input/src/use-pin-input.ts
Closes #2879 
This PR resolves an issue where `PinInputField` renders an `input` with invalid attribute `autocomplete="not-allowed".
`input` rendered by `PinInputField` contains `autocomplete="not-allowed"` attribute.
`input` rendered by `PinInputField` contains `autocomplete="off"` attribute.
No
> fix(pin-input): use valid autocomplete value

- .changeset/young-trainers-invite.md
- packages/react/src/extend-theme.ts
- packages/react/tests/extend-theme.test.tsx
Closes #2757
`extendTheme`  override type could not handle nested property names other than from the `ColorHues` type at `colors`.
Extended the override type to allow `Record<string, string>` values in the `colors` section.
Extended the ThemeExtensionTypeHints type and added two TypeScript tests.
No
> fix(extend-theme): allow string properties besides ColorHue

- website/pages/docs/overlay/tooltip.mdx
This PR adds a note to the `Tooltip` docs explaining that `react-icons` must be wrapped in `span` since [`react-icons` icons don't use `forwardRef`](https://github.com/react-icons/react-icons/issues/336).
> docs(tooltip): add note to wrap react-icons with span

- .changeset/late-colts-change.md
- packages/checkbox/src/use-checkbox.ts
- packages/radio/src/use-radio.ts
This PR deprecates the `defaultIsChecked` prop in favor of a new `defaultChecked` prop. I think `defaultChecked` makes more sense as it mirrors the default prop name that React uses for `radio` and `checkbox` elements, which will make this easier to pick up. It's also confusing because `Radio` and `Checkbox` have both `defaultChecked` and `defaultIsChecked` as part of their types due to reliance on the underlying `HTMLInputElement` type, so removing this extra prop will make that even more clear.
Uncontrolled `Radio` and `Checkbox` components use `defaultIsChecked` for setting the default checked element.
`Radio` and `Checkbox` now use the `defaultChecked` prop to set the default checked element. 
No. This is not a breaking change because `defaultChecked` defaults to the value of …
> refactor: deprecate defaultIsChecked props

- website/configs/docs-sidebar.json
This PR changes the ordering of items in the `docs-sidebar.json` to match the ordering of the sidebar. The ordering in the JSON is used to determine next/prev links in docs.
Some items such as `Link` and `CloseButton` have invalid next/previous links due to them being at the wrong position in the JSON file.
This PR fixes the ordering so that all items in the docs have the correct siblings.
No
N/A
> docs: fix next/prev links not corresponding to sidebar ordering

- website/next-redirect.js
- website/src/components/header.tsx
- website/vercel.json
Fixes issue from #2636
`/discord` redirect now works.
The `/discord` redirect specified in `vercel.json` doesn't work.
The `/discord` redirect was moved to `next-redirect.js` which works correctly. Also replaced the Discord nav item link with `/discord` so it uses the same redirect.
No
> fix(website): move /discord redirect to next-redirect

- .changeset/warm-shrimps-tease.md
- website/pages/docs/components/icon.mdx
A few cosmetic changes / typo fixes.
> docs(icon): fix typos and inconsistent word capitalization

- .changeset/spotty-ties-mix.md
- website/src/components/header.tsx
The Github and Discord buttons in the header are vertically misaligned and I cannot sleep because of that.
Buttons are vertically slightly misaligned.
Buttons are perfectly aligned.
No
> fix(docs): align social buttons vertically

- website/pages/docs/overlay/menu.mdx
This just cost me half an hour!
Could be explained more succinctly, and maybe in a better place in the document.
Closes # 
Document requirement to have a `ref`-accepting component for the `as` prop of `MenuButton`
Not described.
Describe requirement in docs.
No
> docs: explain `ref` needed for MenuButton `as` Component

- .changeset/eighty-teachers-brush.md
- packages/modal/src/modal.tsx
Closes #2519
`motionPreset="none"` introduced in #2888 disables the `ModalContent` animation, but the `ModalOverlay` is still animated. This PR fixes it.
`ModalOverlay` component fades in/out even if `motionPreset="none"`.
https://user-images.githubusercontent.com/6268183/103666173-9e659900-4fb7-11eb-8ee7-9e58df94fe98.mp4
No animations for `ModalOverlay` component with `motionPreset="none"`.
https://user-images.githubusercontent.com/6268183/103665970-62323880-4fb7-11eb-9e44-d9474383d905.mp4
No.
> fix(modal): disable the ModalOverlay animation if motionPreset="none"

- website/pages/docs/form/radio.mdx
The invalid radio example title reads "Invalid Checkbox", it should read "Invalid Radio".
The title for the invalid radio example reads "Invalid Checkbox"
The title is changed to "Invalid Radio"
No.
> docs(radio): change invalid example title copy from checkbox to radio

- .changeset/brown-cherries-collect.md
- packages/modal/src/modal-transition.tsx
- packages/modal/src/modal.tsx
- packages/system/src/forward-ref.tsx
- packages/system/src/system.ts
- packages/system/src/system.types.tsx
- packages/system/tests/as-prop.test.tsx
- packages/transition/src/fade.tsx
Closes #2265
Autocomplete was broken in Jetbrains IDEs with the complex `as` prop type.
Multiple intersection types including many usages of `Omit` took too long to resolve for Jetbrains IDEs.
This PR uses less intersection types and resolves fast in PhpStorm 2020.2.
**It should not,** but this is a pretty big change in our type codebase, so I would like to be sure that it is an improvement for every editor.
One explicit type annotation for a `callAllHandlers` call was needed and the `ModalTransitionProps` needed a minor change.
> fix: typescript autocomplete

- .changeset/sweet-cherries-breathe.md
- website/pages/docs/hooks/use-token.mdx
Since we now have gradients supported "natively" in Chakra, it might be better to not show how to use `useToken` to make one. 
`useToken` docs show how to use it to make a background gradient.
Docs show how to use it to make a `boxShadow` with colors from theme.
No.
> docs(use-token): replace gradient example with boxShadow example

- website/pages/docs/hooks/use-token.mdx
People looking for more flexible ways of using themes token can land on the useToken page in the documentation.
No
> docs: notify about the `sx` prop in the useToken doc page

- .changeset/dry-wolves-kick.md
- website/pages/docs/form/select.mdx
The `Changing the icon in the Select` example is not live / editable.
In the source code there was `jsx live=true`, which apparently does the same as `jsx live=false`. 
To enable editable example, the `live` directive has to be omitted altogether.
> fix(docs): make select custom icon example live

- website/pages/guides/integrations/with-framer.mdx
- Used the imported `Box` instead of `chakra.div`
- added `forwardRef` import
The framer example is not using the imported `Box`
Easier to understand the framer example.
No.
> fix(guides): unsued box import

- .changeset/spicy-eels-fold.md
- packages/styled-system/src/utils/parse-gradient.ts
- packages/styled-system/tests/parse-gradient.test.ts
- packages/system/stories/system.stories.tsx
Closes #2981
`bgGradient="linear(to-l, rgb(0,0,0) 15%, rgb(255,255,255) 15%)"`  did create an invalid css value.
Modified the regex to extract values between the first `(` to the last `)` in the gradient string by removing the lookahead operator.
Creates correct CSS gradient values for rgb values. A test ensures this.
No
> fix(gradient-rgb): handle rgb values in gradients

- website/pages/docs/features/style-props.mdx
Closes # 
As described in [#2986](https://github.com/chakra-ui/chakra-ui/issues/2986) the boxes are out of their wrapper in the mobile version for [#shadow](https://chakra-ui.com/docs/features/style-props#shadow) example
`columns="4"`  for `SimpleGrid` component, which make it not responsive
The boxes are now inside their wrapper in the mobile version (responsive design), by changing `columns="4"` to `columns={{sm: 2, md: 4}}`
No, it's not a breaking change
> docs: handle the display of boxes in responsive design

- .changeset/little-rocks-battle.md
- packages/skeleton/src/skeleton.tsx
Closes #2956
`SkeletonText` kept its fixed height and width when `isLoaded === true`.
size props where not dependent on `isLoaded`
`mb`, `width` and `height` are set according to `isLoaded`.
No
> fix(skeleton-text): fix SkeletonText dimensions when isLoaded

- packages/slider/src/use-slider.ts
- website/src/components/omni-search.tsx
- website/src/components/props-table.tsx
- yarn.lock
Closes #2984 
Updated the `PropsTable` component to display valid values for the `size` and `variant` props for each component on the docs.
All valid values for the `size` and `variant` props are not being displayed in the props table for each component.
Display all valid values for the `size` and `variant` props in the props table for each component.
No
> docs: Update props table to display valid size and variant props values

- .changeset/tasty-singers-design.md
- website/src/components/props-table.tsx
Currently some props are formatted as TS types and some as loose human-readable strings. 
I updated the `size` and `variant` values formatting to be a valid TS string literal union type (same as `orientation` for example). 
For example, before:
`ghost, outline, solid, link, unstyled`
After:
`"ghost" | "outline" | "solid" | "link" | "unstyled"`
No.
> fix(docs): format size and variant values as TS types

- website/pages/docs/getting-started.mdx
When I wanted to copy the commands, I might try to use the copy button but if I do it won't work :/
This PR slightly reworks that section to enable this flow
No
> chore(docs): split installation codeblocks to allow easier copying

- .changeset/brave-ties-flow.md
- packages/progress/src/progress.tsx
- packages/progress/stories/progress.stories.tsx
Closes #2921
`borderRadius` for the linear progress component can't be set in the theme.
You can set `borderRadius` in the `baseStyle` of the `track` part and it will take effect on both `track` and `filledTrack`.
Prop `borderRadius` can still be used to override it.
No
> fix(progress): allow overriding borderRadius in theme

- .changeset/hip-ears-float.md
- website/pages/docs/form/input.mdx
Removed redudant `borderRadius` related props from `InputGroup` example.
No
> chore(docs): remove redudant props in InputGroup example

- package.json
- packages/transition/src/slide.tsx
Closes #2468
The Drawer currently uses a height of `100vh` (introduced in e7cbdeb762c38767268cf5fd3fafb649e0f6691e) which is the whole viewport. Unfortunately, depending on the scrolling direction, Safari overlays the page content with a bottom bar (to share the URL or switch tabs). So, if a user scrolls up and opens a Drawer, parts of it might be hidden by the bottom bar.
The drawer is already `position: fixed`. It is therefore easy to replace the explicit hight by an implicit one by setting `top: 0; bottom: 0` as this relates to the currently available space (i.e. takes the bottom bar into account). (There' no need to re-calculate in case the bar appears / disappears, as there's a scroll-lock in place when the Drawer opens and the bar can't change.)
| without Safaris UI | with Safaris …
> fix(slide): iOS Safari overlays DrawerFooter

- website/pages/docs/features/color-mode.mdx
I just changed the name "Next.js" to "Create React App" in the instructions for setting color mode in CRA
It says "Next.js" in the instructions for CRA
The name "Next.js" was changed to "Create React App"
No
> docs: fix typo in color mode instructions for Create React App

- .changeset/pretty-actors-float.md
- website/src/components/props-table.tsx
Currently, default value for `size` and `variant` is always displayed as `-` in the props table.
I added a check that sets it to `defaultProps.size` and  `defaultProps.variant` from the theme where possible.
No
Example before:
After:
> feat(docs): show default value for variant and size in props table

- website/pages/docs/layout/wrap.mdx
There is a typo between the justify & align should be swapped
Closes # 
> docs: typo on justify & align axis

- .changeset/twenty-trees-stare.md
- packages/menu/src/use-menu.ts
- packages/popper/src/react-popper.ts
- packages/popper/src/use-popper.ts
Closes #2531
I added a `enabled` option to `usePopper`. While this option is `false`, the attrs and styles won't be updated.
`Menu` uses this option, so its position won't update while it is not open.
> fix(menu): update popper position only while open

- .changeset/orange-boats-pretend.md
- packages/hooks/src/use-event-listener.ts
Closes #3040 
A recent change to `useEventListener` removed the separate `listener` function that was attached to `env` as a listener and directly attached the passed `handler`. This change resulted in listeners being removed entirely, so that something like `Slider` would no longer have a listener after the first event.
Re-added the separate `listener` function that results in the `handler` remaining attached after events.
No
See https://github.com/chakra-ui/chakra-ui/commit/27c8a6ce627aa18e52998b68ede6661e4c117be7#diff-28915326605476712d3e02282e5a571ea49369d7bd59eb52f2ee104cf9077bfcL24-L31 for the previous change that resulted in this issue.
> fix(use-event-listener): restore listener fn

- .changeset/slow-comics-sing.md
- packages/popover/src/use-popover.ts
The same fix as #3022, but for `Popover`.
No
> fix(popover): update popper position only while open

- .changeset/loud-teachers-shop.md
- packages/styled-system/src/config/others.ts
- packages/styled-system/tests/sr-only.test.tsx
Move `srOnly` prop to styled system props. This will deprecate the need for the `visually-hidden` package. Less is more!
```jsx
// If `true`, hide an element visually without hiding it from screen readers.
<Box srOnly>Visually hidden</Box>
// If `focusable`, the sr-only styles will be undone, making the element visible to sighted users as well as screen readers.
<Box srOnly _active={{ srOnly: "focusable" }}>Visually hidden but shown on focus</Box>
```
> feat: sr-only prop

- packages/progress/src/circular-progress.tsx
- website/pages/docs/feedback/circular-progress.mdx
Closes # 
I noticed that the description for the `thickness` prop on CircularProgress is erroneous and may cause confusion. It says that it sets things by ratio, expecting a value between 0 and 1, but in reality all it's doing is setting stroke width by pixel.
n/a
n/a
No
> docs(progress): correct description about thickness prop

- .changeset/chilly-emus-mate.md
- website/pages/docs/form/button.mdx
Added missing props table for the `ButtonGroup` component.
No
> docs(button): add ButtonGroup props table

- website/pages/docs/features/color-mode.mdx
* Export `Document` instead of `App`
* Add `Head` tag as required by Next.js
* Remove unused imports and `getInitialProps` method
> docs(color-mode): Fix Next _document.js example

- .changeset/witty-pets-visit.md
- website/src/components/seo.tsx
Closes #3047
Added the same description and title to OpenGraph tags that is used for meta `title` and `description`.
Before:
After:
No
> docs: descriptive title and description in OG tags

- website/src/components/header.tsx
Closes #3068 
Fix issue with the Input icon overlap on navbar by updating the `zIndex` value for the navbar.
The icons for Inputs with `InputLeftElement` or `InputRightElement` overlap the navbar on scroll.
The icons for Inputs with `InputLeftElement` or `InputRightElement` do not 
overlap the navbar on scroll.
No
> docs: update the zIndex value for the navbar

- .changeset/small-trainers-deliver.md
- packages/portal/src/portal.tsx
- packages/portal/stories/portal.stories.tsx
Closes #3026
Fix issue where adding portalZIndex makes portaled content unusable.
This happened because we added `inset:0` styles to the portal z-index container and that makes the container occupy the full screen, making it hard to interact with content inside the portal.
> fix: portal manager z-index issue

- .changeset/khaki-rivers-rescue.md
- packages/checkbox/src/checkbox.tsx
- packages/menu/src/menu.tsx
- packages/radio/src/radio.tsx
Make checkbox, radio and menu components work in RTL languages by default.
These components use physical css properties (margin-left) for spacing.
I changed it to use `margin-start` instead. Now works for RTL by default
No
> fix: update styles to use logical css style props

- .changeset/friendly-parents-guess.md
- website/src/components/props-table.tsx
Currently, the `size` and `variant` props are listed for all components, although it does not do anything with chakra's default theme in many of them.
I added the description that will warn you where component does not implement these.
Example before:
After:
The description can/should be improved upon time. Ideally with a link to example on how to do that for that specific component.
No
> feat(docs): display "not implemented" note for size and variant where appropriate

- website/pages/docs/overlay/menu.mdx
Closes #3090
Added example on how to use the `icon` property on `MenuItem`.
Also enabled `live` for few other examples
No
> docs(menu): improve examples

- .changeset/four-ways-visit.md
- packages/pin-input/src/use-pin-input.ts
- packages/pin-input/tests/pin-input.test.tsx
- website/pages/docs/form/pin-input.mdx
This PR adds an `otp` prop to `PinInput` which causes `PinInputField` children to render with `autocomplete="one-time-code"`.
```jsx
<PinInput otp>
<PinInputField />
<PinInputField />
<PinInputField />
<PinInputField />
</PinInput>
```
`PinInputField` always renders with `autocomplete="off"`.
When `PinInput` has the `otp` prop enabled, each `PinInputField` renders with `autocomplete="one-time-code"`.
No
> feat(pin-input): add otp flag to PinInput

- website/pages/docs/theming/theme.mdx
This PR adds `fontWeights` values that were missing from the "Default Theme" docs.
> docs(theme): add missing fontWeights

- website/pages/docs/migration.mdx
Update Migration documentation for dropping support of IE11
Chakra v0 was supporting IE11 and it will give developers unnecessary problems to figure this out to late.
See [pull request](https://github.com/chakra-ui/chakra-ui/pull/2762)
> Update migration documentation regarding IE11

- .changeset/lazy-poets-cheat.md
- packages/accordion/src/use-accordion.ts
- packages/hooks/src/use-controllable.ts
- packages/radio/src/use-radio-group.ts
- packages/tabs/src/use-tabs.ts
Closes #3112
Fixed issue where using an uncontrolled RadioGroup without a defaultValue causes multiple radio options can be selected.
Multiple Radios are Selected when there's no defaultValue
Works as expected. only one radio can be active at a time.
No
> fix(radio-group): fix issue with uncontrolled radio group

- .changeset/smooth-tomatoes-hope.md
- packages/portal/src/portal.tsx
- packages/portal/stories/portal.stories.tsx
Closes #3088
Fixed issue where using portalZIndex causes Tooltips and Popovers to not render correctly.
> fix(portal-manager): portal z-index wrapper squashing portaled elements 

- packages/popover/src/use-popover.ts
> add filp prop to Popover
> I cannot control whether the popover is filp through props
> I can
> feat(popover): add filp prop to Popover

- .changeset/odd-cobras-fix.md
- packages/select/src/select.tsx
Closes #2951 
Allow theme-derived `color` style from `Select.icon` to be applied.
`SelectIcon` never receives the `color` style from the `Select.icon` theme because `Select` always passed a `color` prop to it, even if the value was `undefined`.
`Select` only passes the `color` prop if `iconColor` or `color` have a value.
No
> fix(select): allow Select.icon component theme color to be applied

- .changeset/shaggy-seahorses-poke.md
- packages/color-mode/src/color-mode-provider.tsx
Closes #3132
Fixes issue with color flashing for when using system.
When using `useColorModeValue` there is a flash that is occurring. 
This is because useColorModeValue was checking if `useColorMode` was equal to 'light' else it defaults to whatever value is passed into 'dark'. 
This is a problem when using `initialColorMode= 'system'`, because it's passing the colorMode as 'system' and the dark value is being used.
So for example when using `bg={useColorModeValue('blue.500', 'red.500')}` and then disable javascript, and then set the `config.initialColorMode = system` the rendered output is showing up red, not blue. The defaults should always be set to use light, because everything else is using light.
Colors and values show up properly. And the flashing is consistent with the rest of …
> fix: useColorModeValue to default to light mode first, dark only if set

- .changeset/hungry-donkeys-unite.md
- packages/menu/src/menu.tsx
- website/pages/docs/overlay/menu.mdx
I noticed the MenuItem's command currently does not have a margin.
I added the `commandSpacing` prop similar to `iconSpacing` that can be used to customize the default margin of `0.75rem`.
No.
Before:
After:
> feat(menu): add commandSpacing prop to MenuItem

- .changeset/wild-pandas-suffer.md
- website/pages/docs/form/button.mdx
Closes #3153 
I corrected the capitalization of `rightIcon`.
The docs use `rightIcon` instead of `RightIcon`.
Absolutely not.
> fix(docs): correct capitalization of rightIcon

- website/pages/guides/integrations/with-gatsby.mdx
The current Gatsby doc had a couple of typos and wrong heading order, so I updated those and other things.
- Moved Migration Notes to bottom and made it a `h2`
- Fixed typos
- Updated links to our docs
- Added link to what "shadowing" is
> docs: Update `with-gatsby`

- .changeset/weak-wombats-shake.md
- packages/react/src/extend-theme.ts
- packages/react/tests/extend-theme.test.tsx
Closes #3085
Add recursive TS type to allow deeply nested color objects in `extendTheme`
Did not allow nested color objects.
Now you can nest them as deep as it gets.
No
> fix(extend-theme): allow nested theme colors

- packages/form-control/src/form-error.tsx
Closes # 
I changed the spelling of "instrctions" to "instructions". Added a "u"
Documentation for FormErrorMessage says "instrctions"
Documentation now has the correct spelling, "instructions"
No
> fix: typo in FormErrorMessage documentation

- packages/number-input/src/use-number-input.ts
- packages/number-input/tests/number-input.test.tsx
Closes #3178 
This PR resolves an issue where clamping to a `precision` prop value doesn't occur on blur.
Blurring the `input` when `precision` prop is present doesn't clamp the value to the `precision` value.
Blurring the `input` clamps the value using the `precision` prop.
No
> fix(number-input): always cast counter.value

- .changeset/slimy-birds-melt.md
- packages/checkbox/src/checkbox.tsx
- packages/checkbox/tests/checkbox.test.tsx
Closes #3177 
This PR resolves an issue where `Checkbox` used inside `CheckboxGroup` was calling `group.onChange` twice per event.
Within `Checkbox`, `ownProps` is now derived only from `props` rather than `mergedProps` which already contains `group.onChange` if `props.onChange` does not exist.
No
> fix(checkbox): call group.onChange only once

- .changeset/flat-files-provide.md
- packages/react/src/extend-theme.ts
- packages/react/tests/extend-theme.test.tsx
Closes https://github.com/chakra-ui/chakra-ui/issues/2615
> When we have polyfill for `Array` or `Object`, calling useBreakpoint will throw error `Object doesn't support property or method 'endsWith'`. This is because extendTheme are also extending the polyfill functions of Array and Object
> When we have polyfill like `Array.prototype.each = () => {}` in our code, `extendTheme` will treat `each` as a props in theme 
> When we have polyfill like `Array.prototype.each = () => {}` in our code, `extendTheme` should not include `each` as a props in theme
No
Sometimes we don't have control over which polyfill to load. For my case, I am building an embeddable widget to be included in another website, but the website are loading `prototype.js` which includes bunch of polyfills
Here's what …
> fix(extend-theme): extend theme should not include polyfill function

- packages/checkbox/src/use-checkbox.ts
- packages/radio/src/use-radio.ts
Closes #2350
Fixes checkbox and radio components in React concurrent mode by applying workaround from https://github.com/facebook/react/issues/18591#issuecomment-697999763. This can be removed after the mentioned issue is resolved in React.
Currently in React concurrent mode checkbox and radio inputs require two clicks to update a checked state.
This fix only applies the workaround for projects that use experimental React. It should not affect other projects.
No.
> fix: workaround for react concurrent mode focus and change events issue

- website/pages/docs/form/number-input.mdx
Closes https://discord.com/channels/660863154703695893/660865137137156146/804092804561240084
Added note about disabling `focusThumbOnChange` on the `Slider`, so the `NumberInput` won't lose focus after input.
> docs(number-input): add `focusThumbOnChange` in the Slider example

- website/pages/docs/features/responsive-styles.mdx
- website/pages/docs/theming/theme.mdx
- updated the breakpoints
- use the `createBreakpoints` function
- remove some redudant sentences in `Default Theme` and instead link to `Responsive Styles` section.
> docs: update docs regarding breakpoints

- .changeset/tidy-berries-promise.md
- packages/theme/src/components/button.ts
Closes #3147
`<Button variant="link">chakra</Button>` should have `vertical-align="baseline"` instead of `"middle"`
Before:
After:
Hopefully no
> fix(theme): align link button to baseline

- website/pages/_app.tsx
- website/src/utils/seo.ts
Omit `og:image` tags on all Docs pages (pages where path starts with `/docs/`).
The image currently provides no additional value, as it is just Chakra UI logo, and it clutters up discussions on Discord, for example.
Not the most straightforward solution, but [`next-seo` doesn't allow to unset `og:image`](https://github.com/garmeeh/next-seo/blob/master/src/meta/buildTags.tsx#L469) once it's set in `DefaultSeo`, so we could it override on page-level.
Observation: For some reason Discord makes the preview wider when there is no image, so it takes even less space vertically.
No
> docs: omit og:image in docs pages

- .changeset/slow-chicken-shave.md
- packages/system/src/system.types.tsx
Theme Typings introduced a too narrow type for `ThemeTypings['colorScheme']`
TS error: 
```
Type 'string' is not assignable to type '"whiteAlpha" | "blackAlpha" | "gray" | "red" | "orange" | "yellow" | "green" | "teal" | "blue" | "cyan" | "purple" | "pink" | "linkedin" | "facebook" | "messenger" | "whatsapp" | "twitter" | "telegram" | undefined'.
249             colorScheme={buttonColorScheme}
```
No TS error in userland project
No
Let's get this fix published asap 🚀 😅
> fix: loosen colorScheme type

- .changeset/unlucky-onions-sin.md
- tooling/cli/package.json
- website/pages/docs/theming/advanced.mdx
- Package `@chakra-ui/cli@1.0.0` [did already exist](https://www.npmjs.com/package/@chakra-ui/cli)
- Add minor bump for adding subcommand `tokens` to generate Theme Typings
> chore: bump cli package to publish previous package

- website/pages/docs/theming/advanced.mdx
`npx @chakra-cli tokens` is missing the project dependencies we cannot know of, like the version of @types/react etc.
```bash
$  npx @chakra-ui/cli tokens path/to/theme.ts
Chakra UI CLI  v1.1.0 by chakra UI
Generate theme typings for autocomplete
✖ An error occurred
...
Error: Cannot find module 'react'
...
```
Usage of npx is documented
Installation in project is recommended
> docs: update cli install instructions

- .changeset/little-tomatoes-clean.md
- packages/toast/package.json
- yarn.lock
Closes #2988
Installation of chakra-ui fails with npm v7 due upstream dependency conflict.
Updated the peer deps version.
@chakra-ui/react should be installable without errors with npm v7
No
> chore: update peer dep version of @reach/alert

- website/pages/docs/overlay/tooltip.mdx
Discovered in #3223 
This PR removes the `shouldWrapChildren` prop from `Tooltip` examples. The presence of that prop causes `children` to be wrapped in a `span` with `tabIndex={0}`. Since `children` are already buttons, this causes them to have two focusable wrappers, requiring a double-tab to move to the next element.
> docs(tooltip): remove shouldWrapChildren prop from examples

- .changeset/old-sheep-melt.md
- packages/react/src/extend-theme.ts
- packages/react/tests/extend-theme.test.tsx
- packages/styled-system/src/types.ts
- packages/theme/src/foundations/colors.ts
- packages/theme/src/foundations/index.ts
- packages/theme/src/foundations/radius.ts
- packages/theme/src/foundations/shadows.ts
- packages/theme/src/foundations/sizes.ts
- packages/theme/src/foundations/spacing.ts
- packages/theme/src/foundations/typography.ts
- packages/theme/src/foundations/z-index.ts
- packages/theme/src/index.ts
- packages/theme/src/theme.types.ts
Closes #3101 
Adding an arbitrary baseTheme as second parameter to the `extendTheme` function lead to the return type any.
This PR adds a new type for a chakra ui theme `ChakraTheme`, which defined how the generic theme object looks like.
With this new type the `extendTheme` function can now provide better autocomplete and typesafety for theme overrides.
Introducing a generic TypeScript type `ChakraTheme` to improve the `extendTheme` function even further.
```ts
import { extendTheme } from "@chakra-ui/react"
export const customTheme = extendTheme({
// here you get autocomplete for
//   - existing definitions from the default theme
//   - new components (Single and MultiStyle)
//   - CSS definitions
//   - color hues
//   - etc.
})
export type MyCustomTheme = typeof customTheme
```
You can …
> feat(chakra-theme): introduce type ChakraTheme

- website/pages/docs/hooks/use-controllable.mdx
Hi! I just notice this little typo in the [hooks/use-controllable](https://github.com/chakra-ui/chakra-ui/blob/main/website/pages/docs/hooks/use-controllable.mdx) docs, is fixed now! 😉
> docs(use-controllable): fix typo

- website/pages/docs/form/slider.mdx
Closes #3183
As pointed out in #3183, add an example for discrete sliders in documentation.
As described,
As described.
No.
> docs(slider): add discrete slider example

- .changeset/eighty-ties-melt.md
- .changeset/fast-dragons-retire.md
- .changeset/moody-mice-knock.md
- .eslintrc
- packages/styled-system/src/config/others.ts
- packages/styled-system/src/core/types.ts
- packages/styled-system/src/css.ts
- packages/styled-system/src/types.ts
- packages/styled-system/tests/css.test.ts
- packages/system/src/system.ts
- packages/system/stories/system.stories.tsx
- packages/system/tests/style-resolver.test.ts
- packages/utils/package.json
- packages/utils/src/object.ts
- yarn.lock
This PR adds support for using `layerStyle` and `textStyle` in component theme.
- Extracted the layer and text style code to chakra's styled-system package
- Extracted the apply style to the styled-system package config
It's not possible to use layer and text styles
No
> feat: add support for text and layer style in component theme

- .changeset/cuddly-ladybugs-suffer.md
- packages/styled-system/src/config/border.ts
- packages/styled-system/src/config/typography.ts
Closes #3246
`borderTop` did not allow numbers
`fontWeight` did not use the autocomplete string value `string & {}`
Updated the types
`borderTop` allows numbers and there is autocomplete for the prop `fontWeight`
No
> fix: allow numbers in borderTop and autocomplete for fontWeight

- .changeset/metal-snails-shout.md
- packages/theme/src/components/input.ts
Closes #3243
Fixed an issue in Firefox where `Input` overflows it's flex container.
No
> fix(theme): input flex overflow

- .changeset/shy-swans-yawn.md
- packages/color-mode/src/storage-manager.ts
Closes #3202 #3252
Reading from localStorage directly can fail due to several reasons. When rendered in an iframe or incognition, it could throw a SecurityError, Uncaught DOMException, TypeError, etc. To handle this, I wrapped the calls to localStorage in a try-catch block.
Throws when rendered in an iframe or codesandbox incognito
> fix: localstorage error in iframe or incognito

- .changeset/fast-cars-raise.md
- packages/theme/src/components/tooltip.ts
- packages/tooltip/src/tooltip.tsx
Closes #3257
The element with `role="tooltip"` already has `pointer-events: none` applied in the CSS, which seems to be in the spirit of resolving this issue.
But this doesn't do a lot when its parent, which in code seems to be named the "positioner" element, doesn't have the same rule applied! The positioner still receives the pointer events, which breaks my use case, and seems to contradict the intent of `pointer-events: none` on its child.
No
> fix(tooltip): move `pointerEvents:none` to parent

- website/configs/docs-sidebar.json
- website/pages/docs/features/the-sx-prop.mdx
- website/src/components/page-container.tsx
- website/src/components/sidebar/sidebar.tsx
- website/src/utils/convert-backticks-to-inline-code.tsx
Added documentation for the `sx` prop.
Open to any suggestions!
Edit:
I also whipped out a quick and dirty function to format code blocks in titles. I am not sure if I can utilize `remark` in an easy way to achieve the same. Should I commit it?
```ts
function convertBackticksToCodeBlocks(input: string) {
return input
.split(/(`\w+`)/)
.map((chunk) =>
chunk.startsWith("`") && chunk.endsWith("`") ? (
<MDXComponents.inlineCode key={chunk}>
{chunk.slice(1, -1)}
</MDXComponents.inlineCode>
) : (
chunk
),
)
}
```
> docs: document the `sx` prop

- .changeset/funny-monkeys-build.md
- packages/react/src/extend-theme.ts
- packages/react/tests/extend-theme.test.tsx
Fixed issue in `extendTheme` where overrides defined as function replaced all base styles defined as plain object.
If styles (`baseStyles`, an variant, or an size) are defined in a plain object in the base theme and user provides a function as override, all base theme styles will be dropped.
Styles returned from user's override function will be merged to base theme styles.
Hopefully no?
> fix(extend-theme): merge fn overrides with objects

- .changeset/quiet-rules-share.md
- packages/input/src/input.tsx
- packages/theme/src/components/alert.ts
- website/pages/docs/media-and-icons/avatar.mdx
- website/src/components/props-table.tsx
Refactored the props table while improving few details.
- strip the `(string & {})` from type in `size`, `variant` and `colorScheme`
- handle components that use foreign theme key, so we can still show default props for them (e.g. `IconButton` uses `theme.components.Button`)
- show default `colorScheme` value where possible
- note where `colorScheme` is not implemented in the default theme
- show `required` tag in front of `type` for required props
- don't mutate objects imported from `@chakra-ui/props-docs`
example shown: `IconButton`
No
> docs: refactor props table

- CONTRIBUTING.md
> Fix command that needs to be run before running `yarn changeset`.
> The current command `git fetch origin master:master` is erroneous because we do not have a master branch in the repo and the `main` branch is the source of truth.
> Updated the docs with the proper command - `git fetch origin main:master` that needs to be run before running `yarn changeset`
> docs: update command to run before changeset

- .changeset/silly-bugs-dance.md
- packages/styled-system/src/utils/positive-or-negative.ts
- packages/styled-system/tests/css.test.ts
- packages/utils/src/assertion.ts
- packages/utils/tests/assertion.test.ts
Closes #3111 
This handles negative scale values for css variables used in custom themes
If css variables are used for theme values, negative scales will be ignored and be treated as positive.
This PR will use `calc()` to convert them to convert css variable to negative values.
no.
> fix: support negative values for css variable theme tokens

- .changeset/curly-cameras-doubt.md
- tooling/cli/src/command/tokens/config.ts
- tooling/cli/src/command/tokens/create-theme-typings-interface.ts
- tooling/cli/test/theme-typings.test.ts
The theme typings only provide autocomplete for positive values:
```tsx
<Box mt="2" />
```
Added a `flatMap` property to the theme tokens type generator to create for every value a type prefixed with `-`.
Now we get autocomplete for negative values as well:
```tsx
<Box mt="-2" />
```
No
> feat(theme-typings): add autocomplete for negative space values

- .changeset/tiny-apples-wait.md
- packages/pin-input/src/use-pin-input.ts
- packages/pin-input/tests/pin-input.test.tsx
Previously `isComplete` was being determined based off of old state values as it was determined before the setState took effect. This caused the last pin-input entry to not call `onComplete` when updated. Updating the `isComplete` check to reference the next values (the value of the state after rerender) allows the check to use the most up to date values in the pin-input fields fixing the last digit update issue.
Previously, when updating the last entry in a `PinInput`, the `onComplete` function would not be called.
This PR changes the `isComplete` flag to check the next values which is the most up to date value the user entered. With this change, the `onComplete` is now called when the last entry is updated as expected.
No.
> Fix: pin input last entry update fails to call onComplete

- packages/accordion/stories/accordion.stories.tsx
- packages/accordion/tests/accordion.test.tsx
- website/pages/docs/disclosure/accordion.mdx
The [WAI-ARIA Authoring Practices document](https://www.w3.org/TR/wai-aria-practices-1.2/) notes that accordion headers [must be rendered inside an element with role `heading`](https://www.w3.org/TR/wai-aria-practices-1.2/#wai-aria-roles-states-and-properties). This PR wraps instances of `AccordionButton` in `heading` elements in stories, tests, and docs. 
No
> docs(accordion): add button heading wrappers and note

- .changeset/violet-cats-march.md
- packages/accordion/src/accordion.tsx
- packages/avatar/src/avatar-group.tsx
- packages/button/src/button-group.tsx
- packages/checkbox/src/checkbox-group.tsx
- packages/input/src/input-group.tsx
- packages/radio/src/radio-group.tsx
Components like `ButtonGroup`, `AvatarGroup`, `CheckboxGroup` don't own their theming props, they only propagate the same theming props their child accepts.
For example:
If checkbox size can either sm, md, or lg, CheckboxGroup should also map to those values since it's purpose is to provide size, variant, etc to a group of checkboxes.
No type autocomplete for these components
There's now autocomplete
> fix: theme typings for *group components

- .changeset/tricky-beers-smell.md
- .github/workflows/release.yml
- packages/react/tests/extend-theme.test.tsx
- packages/theme/src/theme.types.ts
Fixes 
```
Type '{ defaultProps: { focusBorderColor: string; }; }' is not assignable to type 'ComponentStyleConfig'.
Property 'parts' is missing in type '{ defaultProps: { focusBorderColor: string; }; }' but required in type 'ComponentMultiStyleConfig'.
```
> fix: narrow theme types for defaultProps and ComponentMultiStyleConfig

- website/configs/resources.json
> Benjamin Carlson's resource URL was pointing to a wrong URL. I found the correct one and replaced the URL.
> Clicking on `Chakra UI Quickstart - With Next.js` in Resources opens up Kitze's live streaming link (previous resource)
> Clicking on `Chakra UI Quickstart - With Next.js` in Resources opens up the correct YouTube video
> No
> fix: fixed Benjamin Carlson's resource URL

- .changeset/big-cherries-wash.md
- packages/styled-system/src/utils/types.ts
- packages/styled-system/tests/css-type.test.ts
Closes #3305 
Custom breakpoint names are not allowed in ResponsiveObject. 
Current workaround is to use the [@chakra-ui/cli](https://chakra-ui.com/docs/theming/advanced) to generate new typings for the custom theme.
```jsx
<Box mt={{ base: "130px", tablet: "152px" }}  />
// => TS error `tablet` not allowed...
```
Add `string` as valid key for `ResponsiveObject`.
`string` is allowed as key in `ResponsiveObject`.
No
> fix: allow custom breakpoint names in ResponsiveObject

- .changeset/hungry-coins-hang.md
- packages/color-mode/src/color-mode-script.tsx
Closes #3294
You can now customize the `nonce` of the `<script>` that `ColorModeScript` creates by passing `nonce` prop.
No
> feat(color-mode): add support for nonce

- .changeset/red-mayflies-reflect.md
- tooling/cli/bin/tsconfig.json
Closes #3308 
Theme tokens typings are not generated if there are TS errors in the theme file.
Using the ts-node flag `transpileOnly` we can disable the type checking.
Chakra theme typings are generated even if there TS errors in the source theme file
No
> fix: cli tokens command ignores TS errors in theme file

- packages/color-mode/src/color-mode-script.tsx
- website/pages/docs/features/color-mode.mdx
Added a little documentation for the `nonce` prop of `<ColorModeScript>`.
No
> docs: add docs for ColorModeScript nonce

- website/pages/docs/navigation/link-overlay.mdx
> docs: Fix typo in link overlay docs

- README.md
The README.md has outdated installation instruction. It missed the dependencies (`@emotion/react` `@emotion/styled` ) required to run Chakra in my project. I copied the installation instruction from https://chakra-ui.com/docs/getting-started.
Install and run correctly in my React project.
No.
> docs: Update install instruction in README.md

- website/pages/docs/overlay/menu.mdx
> docs(menu): fix typo

- .changeset/afraid-eels-visit.md
- packages/styled-system/src/types.ts
- packages/theme/src/index.ts
- packages/theme/src/theme.types.ts
Closes # 
> Exporting Types from them and style-system
> some types were not exported and were throwing typescript error when extending the theme
>  the types are exported now and this should fix the issue
> fix: export types from theme, styled-system

- .changeset/blue-games-join.md
- packages/focus-lock/package.json
- packages/modal/package.json
- yarn.lock
Closes #2820 and Closes #3327
Upgrade to react-remove-scroll@2.4.1 and react-focus-lock@2.5.0 which adds support for React 17.
@chakra-ui/modal@1.5.1 and @chakra-ui/focus-lock@1.0.4 seem to have broken dependencies. Seems to expect react ^16.8.0 and brakes on react 17. react-remove-scroll@2.4.1 and react-focus-lock@2.5.0 add the compatibility with react 17.
--legacy-peer-deps seems to be the workaround at the moment. 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0" from react-remove-scroll@2.4.0
npm WARN node_modules/@chakra-ui/modal/node_modules/react-remove-scroll
npm WARN react-remove-scroll@"2.4.0" from @chakra-ui/modal@1.5.1
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0" from react-focus-lock@2.4.1
npm WARN …
> Fix: broken peer deps modal and focus-lock on React 17

- .changeset/soft-knives-hide.md
- .changeset/sweet-otters-arrive.md
- packages/react/src/extend-theme.ts
- packages/react/tests/extend-theme.test.tsx
- packages/theme/src/index.ts
- packages/theme/tests/theme.test.ts
Closes #3314
This PR removes the typecast of the default chakra theme to `ChakraTheme`.
Type `Theme` was replaced by `DefaultChakraTheme` in the last release. This PR brings it back again and deprecates `DefaultChakraTheme`.
`ChakaTheme` is the definition how **a** theme looks like. `Theme` and former `DefaultChakraTheme` are the exact types of the default chakra theme.
No, it brings back a removed type.
> fix: remove default theme type cast

- .changeset/twenty-bags-approve.md
- packages/popper/src/react-popper.ts
- website/pages/docs/overlay/menu.mdx
Closes #2531
The Popper.js instance is now created only once it is actually needed for positioning.
No
> fix(popper): lazy init popper instance

- .changeset/four-bees-tell.md
- packages/checkbox/src/checkbox.tsx
Closes #3363 
When validating the Chakra checkbox element in the w3 HTML validator an error for each rendered checkbox comes up: "Element div not allowed as child of element label in this context. (Suppressing further errors from this subtree.)" because each StyledContainer `<label>` contains a StyledControl `<div>` and a "chakra-checkbox__label" `<div>`. This is causing errors in my project which requires that I have 0 errors when my HTML is validated, so I would like to propose that these `<div>` elements are converted to `<span>` elements to resolve the issue.
StyledControl is a `<div>`, so is "chakra-checkbox__label"
Changing those 2 elements to `<span>`s instead.
No
> fix(checkbox): Chakra Checkbox HTML Validation fix

- website/pages/docs/contributing.mdx
Update 'push to to GitHub with ...'  =>  'push to GitHub with ...'
Closes # 
> Remove duplicate word ('to' preposition).
> The word 'to' is repeated twice (push to to GitHub with ...)
> Removed the repetition (push to GitHub with ...)
No
> docs: remove duplicate preposition

- packages/accordion/src/accordion.tsx
- packages/theme/src/components/accordion.ts
Closes #3375
Allow Accordion Icon to be themed
Accordion Icon is currently not exposed to be themable
Able to style Accordion Icon through the `extendTheme`
No
> feat(accordion): make accordion icon themable

- website/pages/docs/principles.mdx
I think mentioning `ColorModeProvider` in `Design Principles` is not really needed and might be confusing for users. `ColorModeProvider` is already included in `ChakraProvider` and if users use another one, it will cause bugs.
I have already seen a few users got bitten by it.
No
> docs: remove ColorModeProvider mention in Principles

- website/pages/docs/features/color-mode.mdx
I was trying to setup the Color Mode manager to prevent flash issues in a Next.js app and noticed that the approach currently described in the documentation doesn't work.
I faced two main issues:
- ChakraProvider should be set at the _app level, not in the index page;
- I couldn't force dark mode to be the default because I didn't know straight away the cookie name.
Therefore, I found the cookie name and setup the ChakraProvider at the _app level, providing the `cookies` value through the individual `pageProps`.
I also noticed that, when using the `cookieStorageManager`, `ColorModeScript` in `_document.js` has no effect. Am I missing something? Or should we maybe add a note to the docs saying that "If you use `cookieStorageManager`, you can remove `ColorModeScript` from `_document.js`"? …
> docs: improved ssr info about color mode

- website/pages/docs/layout/wrap.mdx
I just noticed on Discord that the `Wrap` has a very generic meta description.
No
> docs(wrap): add more descriptive meta

- .changeset/nervous-poems-grab.md
- packages/hooks/src/use-clipboard.ts
- packages/hooks/tests/use-clipboard.test.tsx
Users might want to copy text in `text/html` format for example from Rich-Text Editors
Format option is not supported.
We can pass option object, with `format` parameter.
No.
> feat: add format options to use-clipboard

- website/pages/docs/layout/container.mdx
Adding missing documentation on how to set Container size
Closes # 
Adding instructions on how to set the size of the Container
Missing doc (I had to ask on Discord how to do it)
Adding the `maxW` attribute and the desired size value `container.xl`, `container.lg`, `container.md` or `container.sm` 
No
> docs(container): add size example

- packages/progress/README.md
- packages/progress/migration.md
This PR adds missing commas between components in an import example of progress component.
The original commit created pretty old but I think this is a typo error.
https://github.com/chakra-ui/chakra-ui/commit/02f498f6618387a0cda7ec5b9db1cfe5944fb294#diff-f4d36845a1e15d4eae657b037a06059d27d92a5b7301fd8db0f89187e10cdb0dR11
https://github.com/chakra-ui/chakra-ui/commit/45002940dca8f2791f1e3b76f7cf4879f442e070#diff-eb06f216259fde293a3463566b5dcbed5125b86ce94fd5cfa190b218589ee8e3R21
None.
None.
No, there is no breaking changes.
> docs: add missing commas in chakra-ui/progress

- .changeset/wicked-taxis-greet.md
- packages/system/src/system.utils.ts
Adds support for the [`main`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) element to [chakra factory](https://chakra-ui.com/docs/features/chakra-factory).
I've been moving most of my arbitrary `Box` usage over to chakra factory when I noticed `main` (which I'm using for my page layout) isn't supported
Adds `main`
No
> Add support for `main` in chakra factory

- CONTRIBUTING.md
There's a typo in `CONTRIBUTING.md`.
Instead of being:
- "we treat each component as an independent package"
It is:
- "we treat each component has an independent package".
This PR fixes that.
> docs(contributing): fixed typo "has an" -> "as an"

- website/pages/docs/feedback/toast.mdx
> docs: fix typo

- .changeset/khaki-books-occur.md
- packages/modal/stories/modal.stories.tsx
- packages/theme/src/components/modal.ts
Closes #3453
This fixes a problem with using a `Modal` with `size="full"` which has a long content that causes scroll
https://user-images.githubusercontent.com/22922179/109181389-27b17480-778c-11eb-988c-d93872328ebe.mp4
https://user-images.githubusercontent.com/22922179/109183661-7829d180-778e-11eb-8861-cecc6f9bba42.mp4
No
> fix(modal): full size with long content (overflow)

- website/pages/docs/features/color-mode.mdx
Using custom theme is optional and I didn't use it until I started to implement dark mode.
This guide shows how to change the theme's configuration, but it misses one point that I initially didn't know about: you need to pass the custom theme to the ChakraProvider in order to make it work.
And that's why I think this guide needs at least this quick reminder.
No
> docs(color-mode): add a reminder about passing theme to ChakraProvider

- .changeset/chatty-deers-flash.md
- packages/modal/README.md
- website/pages/docs/overlay/alert-dialog.mdx
- website/pages/docs/overlay/drawer.mdx
Closes #3425 
The link in drawer documentation was broken because drawer component was moved to the modal package. I also found that alert dialog link was also broken.
Links in documentation lead to 404 pages.
I changed links to lead to modal source code and added basic example for drawer to modal readme.
No
> Update drawer docs

- website/pages/docs/feedback/skeleton.mdx
Fix two invalid prop names in the Skeleton docs
> `colorStart` and `colorEnd`
> `startColor` and `endColor`
> docs: fix skeleton animation color prop names

- .changeset/shiny-dots-buy.md
- packages/tabs/src/tabs.tsx
- packages/theme/src/components/tabs.ts
Allow styling `TabPanels` component from theme.
`TabPanels` does not accept styles from theme.
`TabPanels` can be styled from `Tabs` component theme, specifying the `tabpanels` part.
No
> feat(tabs): make TabPanels themable

- .changeset/silly-mice-repair.md
- packages/theme/src/components/select.ts
Closes #2853
For browsers that allow styling of `select` element contents, we set a default `bg` for `option` but not for `optgroup`. This change covers `optgroup`.
No
> fix(select): add baseStyle bg for optgroup element

- .changeset/orange-tools-smell.md
- packages/react/tests/extend-theme.test.tsx
- packages/theme/src/theme.types.ts
Closes #3418 
Provide proper typings for `ThemeOverride.components`.
Previously the typings for function in the components part of ThemeOverride have been typed as `(theme: Theme) => CSSObject` which is not correct.
No
> fix: provide proper typings for ThemeOverride.components

- .changeset/perfect-melons-serve.md
- packages/slider/src/use-slider.ts
Closes #2887 
`onChangeEnd` can't reliably be used to detect when dragging ends because it isn't called if the new `value` is the same as the old `value`.
`Slider` currently has a check that prevents calling `onChangeEnd` if `value` matches the previous `value`.
`onChangeEnd` is now called whether `value` matches the previous `value` or not.
Possibly? Need to discuss. If users don't expect `onChangeEnd` to be called, it will now be called. Created as a draft so we can discuss this before merging.
> fix(slider): call onChangeEnd even if value doesn't change

- .changeset/rotten-panthers-worry.md
- packages/react/src/extend-theme.ts
Closes #3372 
Fixed an issue where extending the theme with custom breakpoints with
`strictNullChecks: false` in `tsconfig.json` lead to an error.
No
> fix: extend theme type with breakpoints

- .changeset/odd-cooks-beam.md
- packages/popper/src/react-popper.ts
- packages/tooltip/stories/tooltip.stories.tsx
Closes #3160
This fix makes sure that we don't return stale popper state from the `usePopper` hook in `popper/react-popper.ts` which was causing wrong popper behaviour with using an auto-placed tooltip together with `AnimatedPresence` component.
When we use an auto-places `Tooltip` which has an `AnimatedPresense` component in it, the `usePopper` hook returns stale state causing incorrect arrow positioning.
I changed the `usePopper` behaviour to keep track of the PopperJS state property in a `useState` hook and update it in a modifier alongside updating `style` and `attrs` state.
No
I've got two additional ideas:
1) I think it would be a good idea to refactor the `react-popper` a bit so that we don't both the PopperJS `state` from it as well as `style`/`attributes` (as separate object …
> fix(popper): sync popper instance state

- website/pages/guides/integrations/with-gatsby.mdx
* Update the gatsby example to use `extendTheme` api as opposed to using the raw object.
When I use the example provided in the doc I run into the following error:
```
// gatsby-browser.js
import './src/css/index.css';
import React from 'react';
import { ChakraProvider, CSSReset } from '@chakra-ui/react';
const customTheme = {};
export const wrapRootElement = ({ element }) => {
return (
<ChakraProvider theme={customTheme}>
<CSSReset />
{element}
</ChakraProvider>
);
};
```
* Update example for the gatsby plugin. Use `extendTheme` to create the theme.
```
/**
* Implement Gatsby's Browser APIs in this file.
*
* See: https://www.gatsbyjs.org/docs/browser-apis/
*/
import './src/css/index.css';
import React from 'react';
import { ChakraProvider, CSSReset, extendTheme } from '@chakra-ui/react'; …
```
> docs: use extend-theme to create the theme

- .changeset/poor-numbers-burn.md
- tooling/props-docs/src/build.ts
Extract all props for our hooks with the `props-docs` package if the first and only parameter is an object.
Now it only omits TypeScript native types and leaves all other props in there.
This helps to render the props table for `useToast` where the prop `position` was omitted.
Followup to https://github.com/chakra-ui/chakra-ui/pull/3494#discussion_r585515751
> docs: extract hook props for docs

- website/pages/docs/feedback/toast.mdx
Closes https://github.com/chakra-ui/chakra-ui/issues/3482
Current docs for toasts do not mention that variants can be used.
No
- Added an example of using variants with toasts.
- Combined existing examples of statuses into one example.
- Added all positions to the example of positions.
- Use `PropsTable` component instead of manual props table.
> docs(toast): add variants example to toast docs

- website/pages/docs/getting-started.mdx
Adds missing closing quote in gatsby-plugin example
No
> docs: fix typo on getting-started page

- .changeset/few-wasps-judge.md
- packages/layout/src/aspect-ratio.tsx
On the SSR, `<style>` tag was displayed for a split second because of `display: "flex"` applied to all children.
A fix is to override the `display` property for style tags.
You can reproduce this here
https://codesandbox.io/s/chakra-ssr-aspect-ratio-issue-qghp1
Preview (JS is disabled so only the HTML form server side is rendered)
> fix: aspect ratio SSR style tag display

- website/pages/docs/features/chakra-factory.mdx
> Fixed typo on Chakra Factory Documentation
> Invalid usage `isValidHMTLProp` where the import is `isValidHTMLProp`
Fixes Typo isValidH**MT**LProp
Link to the current Docs: https://chakra-ui.com/docs/features/chakra-factory
> docs: fixed typo on example usage from emotion/is-prop-valid package

- .changeset/olive-walls-promise.md
- packages/styled-system/src/config/others.ts
- packages/styled-system/src/css-var.ts
- packages/styled-system/src/css.ts
- packages/styled-system/src/types.ts
- packages/styled-system/stories/css.stories.tsx
- packages/styled-system/tests/css-var.test.ts
- packages/styled-system/tests/text-styles.test.ts
- packages/system/tests/style-resolver.test.ts
Closes #3501
Closes #3514
- Fix issue where responsive styles defined in `textStyles` not overridden when passing props.
- Fix issue where `toCSSVars` omitted the transition tokens
- Styles defined in `layerStyles` and `textStyles` and apply can now be overridden with props.
- Tokens now include transition values in css custom properties.
No
> fix: styled system css and css vars

- .changeset/loud-rivers-listen.md
- tooling/cli/src/command/tokens/index.ts
- tooling/cli/src/scripts/read-theme-file.worker.ts
Mentioned in https://github.com/chakra-ui/chakra-ui/issues/3459#issuecomment-788210258
The CLI tokens command exited unexpectedly if a warning was logged in the theme file.
The CLI uses a worker script to parse the theme file.
The parent process checked if the worker logged something on stderr and exited accordingly.
Now the CLI uses [fork](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) for IPC.
Now it only exits on _real_ errors.
No
> fix: CLI exits unexpectedly on warnings

- website/pages/guides/as-prop.mdx
changing `ChakraComponent` --comes-- its props to `ChakraComponent` gets its props. I had to re-read the sentence several times to understand it, I hope my change doesn't change the intended meaning of it.
Closes # 
> Fixed a word, I had to re-read the sentence to understand what it was saying, I hope I make it easier for others without changing the meaning.
No
> Fixing a sentence

- .changeset/wicked-apes-wink.md
- packages/theme/src/theme.types.ts
Context: https://github.com/chakra-ui/chakra-ui/discussions/3568
Added typings for the `theme` prop in `ThemingPropsThunk` and export a standalone type `ThemeComponentProps`
```ts
import { ThemeComponentProps } from "@chakra-ui/react"
function baseStyle(props: ThemeComponentProps) {
return {
boxShadow: `0 1px 2px 0 rgba(0, 0, 0, 0.05) ${props.theme.colors.whiteAlpha[500]}`,
}
}
```
Type is hidden in `ThemingPropsThunk`
It is exported as standalone type.
No
> feat: export type ThemeComponentProps with theme property

- .changeset/giant-seahorses-laugh.md
- packages/system/src/providers.tsx
StylesProvider is not defined in CSB - this is a try to fix this. 
`export const [StylesProvider, useStyles]`
`export { StylesProvider, useStyles }`
No
CSB deployment does not work for me, but I think this approach is worth a try.
> fix: export of styles provider

- website/pages/docs/migration.mdx
Added migration docs for obsolete `onClose` prop on `<ModalCloseButton />`
If `onClose` is not specified on `<Modal />`, it throws an error. 
See comments here from inside the codebase: https://github.com/chakra-ui/chakra-ui/blob/main/packages/modal/src/modal.tsx#L495
> docs: Migration docs for obsolete `onClose` prop on <ModalCloseButton />

- .changeset/warm-insects-joke.md
- packages/toast/package.json
- yarn.lock
Closes #1443
Fixes a yarn PNP issue (`@reach/visually-hidden` missing `prop-types`)
```
ERROR in ./.yarn/$$virtual/@reach-visually-hidden-virtual-9044b33769/0/cache/@reach-visually-hidden-npm-0.13.0-0b8255612b-c535e1eb2a.zip/node_modules/@reach/visually-hidden/dist/visually-hidden.esm.js 2:0-35
ui_1                 | Module not found: Error: Can't resolve 'prop-types' in '/ui/.yarn/$$virtual/@reach-visually-hidden-virtual-9044b33769/0/cache/@reach-visually-hidden-npm-0.13.0-0b8255612b-c535e1eb2a.zip/node_modules/@reach/visually-hidden/dist'
```
Requires workaround:
```yaml
packageExtensions:
"@reach/visually-hidden@*":
peerDependencies:
prop-types: "*"
```
No workaround needed
No
> Bump @reach/alert to fix yarn pnp issue

- .changeset/dirty-radios-flash.md
- packages/hooks/src/use-controllable.ts
Closes #3406
Example:
```ts
const [selectedIndex, setSelectedIndex] = useControllableState({
defaultValue: 0,
onChange,
})
```
Currently, if user calls the `setSelectedIndex` function with the current value, the `onChange` callback will be still called.
This happens for example [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/tabs/src/use-tabs.ts#L315), because click on a `Tab` triggers both `onClick` and `onFocus`.
If the new value is strictly equal (`===`) to the current one, the `onChange` callback won't be called.
No?
> fix(use-controllable): call `onChange` only if value changed

- .changeset/tidy-suns-exercise.md
- packages/counter/src/use-counter.ts
- packages/hooks/src/use-controllable.ts
- packages/hooks/tests/use-controllable.test.tsx
Closes #3663
Fix issue where onChange gets called when value did not change.
> fix: onchange for number-input and counter

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
Adding a Next JS TypeScript starter in the README file and Bug Report issue template.
> docs: add Next JS TypeScript starter link

- .changeset/giant-rules-switch.md
- .changeset/gorgeous-flowers-impress.md
- .changeset/pink-timers-explode.md
- .changeset/witty-ears-boil.md
- packages/checkbox/src/checkbox.tsx
- packages/checkbox/src/use-checkbox.ts
- packages/styled-system/src/css.ts
- packages/switch/README.md
- packages/switch/src/switch.tsx
- packages/theme/src/components/stat.ts
- packages/theme/src/components/switch.ts
- packages/theme/src/components/table.ts
Closes #3480
Closes #3638
- Improves the accessibility for the Switch component. To prevent duplicate `labels` for the underlying `input` element, you can change the dom element for the switch container using the `as` prop.
```diff
<FormControl display="flex" alignItems="center">
<FormLabel htmlFor="email-alerts" mb="0">
Enable email alerts?
</FormLabel>
-  <Switch id="email-alerts" />
+ <Switch as="div" id="email-alerts" />
</FormControl>
```
- The switch component can now accept children as well, just like radio and checkbox.
```diff
-  <Switch />
+ <Switch>
+      Hello
+ <Switch />
```
- Update RTL styles for the switch component and use CSS variables for most things.
- Switch works in RTL
- Switch can be made more accessible by changing the dom node to `div`
No
> fix: improve switch accessibility

- .changeset/quick-cobras-invent.md
- packages/layout/src/stack.utils.tsx
Closes #3657 
> Fixed the bug where a margin bottom would get applied to direction=row of stack
> When we set the first breakpoint (the base) of the direction property to column-reverse, there is extra padding.
> Fixes the margins that get added
No
> fix(stack): stack column-reverse extra margin fixed

- .changeset/beige-insects-scream.md
- .changeset/sweet-zoos-invite.md
- .changeset/tidy-cameras-pay.md
- packages/counter/src/use-counter.ts
- packages/form-control/src/form-control.tsx
- packages/form-control/src/form-error.tsx
- packages/form-control/src/use-form-control.ts
- packages/number-input/src/number-input.tsx
- packages/number-input/src/use-number-input.ts
- packages/number-input/stories/number-input.stories.tsx
- packages/number-input/tests/number-input.test.tsx
Closes #3676
Closes #3654
- Improve the number input logic
- Forwards all `aria-*` props to the input element
- Refactor implicit form control handling from `useNumberInput` to `NumberInput` in favor of composition
- Fix issue where typing `e` in input and blurring sets the value to `0`
No
> fix: number-input and form control

- website/pages/docs/getting-started.mdx
Chakra website currently suggests a required version of TS 3.8 is required, however Chakra has a dependency on TS 4.1. 
This could potentially cause some confusion, e.g. https://github.com/chakra-ui/chakra-ui/discussions/3686
Docs suggest required TS version 3.8.
Docs suggest required TS version 4.1.
No
> docs: Update suggested required TS version to 4.1

- packages/env/README.md
- packages/env/index.ts
- packages/env/jest.config.js
- packages/env/package.json
- packages/env/src/env.tsx
- packages/env/src/index.ts
- packages/env/src/mock-document.ts
- packages/env/src/mock-window.ts
- packages/env/stories/env.stories.tsx
- packages/env/tests/env.test.tsx
- packages/env/tsconfig.json
- plop-templates/component-pkg/README.md.hbs
This PR introduces a new package `@chakra-ui/env` that provides the correct `window` and `document` object globally to all components and hooks.
It leverages the ref callback in react to determine the owner window and document using a temporarily rendered `span` element.
Let's say we need to design a portal component, we can leverage the `EnvironmentProvider` and `useEnvironment`
```jsx
// 1. create the portal that appends to the env's `document.body`
const Portal = ({ children }) => {
const env = useEnvironment()
return createPortal(children, env.document.body)
}
// 2. Render the portal in an iframe to see that the portal automatically appends to the iframe's
// `document.body`, not the root window
<IFrame style={{ background: "yellow" }}>
<EnvironmentProvider>
<Portal>Inside …
```
> feat: add env package

- website/pages/docs/overlay/modal.mdx
This change resolves two issues:
- `Lorem` uses the `count` prop to determine how much text to generate,
not the `size` prop
- 5 paragraphs of text was not enough to trigger scrolling on larger
screens, so I bumped it to 15
Example doesn't work.
Example works and for large screens too!
No
> docs(modal): fix scrolling example Lorem usage

- website/configs/site-config.ts
Fixing the `og:image` URL by prefixing it with `https://chakra-ui.com`.
> fix: added full URL in og images in site-config.ts

- .changeset/eleven-frogs-kneel.md
- .changeset/smart-turkeys-build.md
- .changeset/stale-falcons-divide.md
- .changeset/yellow-ducks-look.md
- examples/next-js/pages/popper.js
- packages/menu/src/use-menu.ts
- packages/popover/package.json
- packages/popover/src/popover-context.ts
- packages/popover/src/popover-transition.tsx
- packages/popover/src/popover.tsx
- packages/popover/src/use-popover.ts
- packages/popover/stories/hover.stories.tsx
- packages/popper/package.json
- packages/popper/src/index.tsx
- packages/popper/src/modifiers.ts
- packages/popper/src/use-popper.ts
- packages/popper/src/utils.ts
- packages/popper/stories/popper-v2.stories.tsx
- packages/react-utils/src/types.ts
- packages/theme/src/components/alert.ts
- packages/theme/src/components/form.ts
- packages/theme/src/components/popover.ts
- packages/theme/src/components/tooltip.ts
Closes #2481 
Closes #3713
- Updates popper code to expose prop getters in a way that improves SSR,
- Update popper to use `min-width: max-content` so it can be sized according to its child content
- Use `ref` callback to detect the presence of popover header and body instead of use-effect
No
> refactor: update popper for better ssr

- .changeset/shaggy-seahorses-call.md
- packages/toast/src/toast-manager.tsx
Closes #3581 
Take into account safe area insets for Toasts.
When setting `<meta name="viewport" content="viewport-fit=cover"/>` and running the webapp in fullscreen mode on an iPhone, toasts are placed behind the notch and the bottom bar.
Toasts are positioned by taking into account safe area inset [env variables](https://developer.mozilla.org/en-US/docs/Web/CSS/env())
No
> feat(toast-manager): take into account safe area

- .changeset/tasty-cooks-dress.md
- packages/progress/src/circular-progress.tsx
Fix an issue where `CircularProgress` with `isIndeterminate` doesn't show the indicator
The component `<CircularProgress isIndeterminate />` doesn't show the indicator because the opacity is set to 0.
The component `<CircularProgress isIndeterminate />` correctly shows the indicator.
No
> fix(progress): don't set opacity when `progress.value` is `0` and `isIndeterminate` is `true`

- .changeset/stale-rivers-wave.md
- packages/menu/README.md
- packages/menu/src/menu.tsx
- packages/menu/src/use-menu.ts
- packages/menu/stories/menu.stories.tsx
- packages/menu/tests/menu.test.tsx
Closes #2698
Allow `MenuItem` and `MenuItemOption` overriding their parent `Menu`'s `closeOnSelect` behavior.
Menus do not offer per-item granularity on `closeOnSelect`: either all items close the menu (default `closeOnSelect={true}`), or none of them do (`closeOnSelect={false}`).
This can be problematic for menus with mixed content, where `MenuItem`s are expected to close on select, and `MenuItemOption` are not.
This PR adds `closeOnSelect` overrides to `MenuItem` and `MenuItemOption`. Each item can declare if they want to close the menu (or keep it open) when selected.
No.
It works both ways:
- Menus with the default `closeOnSelect={true}` can include items with `closeOnSelect={false}` to keep the menu open
- Menus with `closeOnSelect={false}` can include items with …
> feat(menu): add `closeOnSelect` to `MenuItem` and `MenuItemOption`

- .changeset/hot-dodos-reflect.md
- packages/tabs/src/use-tabs.ts
- packages/tabs/tests/tabs.test.tsx
fix(tabs): do not unmount tab content when lazy
Closes #3683
Tabs' isLazy behavior is now to mount on first select and never unmount.
Current behavior is to unmount on navigating away from a tab.
Tabs' isLazy behavior is now to mount on first select and never unmount.
No
> fix(tabs): do not unmount tab content when lazy

- .changeset/strong-games-love.md
- packages/clickable/package.json
- packages/system/package.json
- packages/tooltip/package.json
Closes #3774
Add missing dependency issue of @chakra-ui/react-utils
ModuleNotFoundError: Module not found: Error: @chakra-ui/tooltip tried to access @chakra-ui/react-utils, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
*Should* be fine given the workaround from #3774
No
N/A
> Bugfix: issue 3774 add missing dependency issue of @chakra-ui/react-utils

- .changeset/chilly-apples-lick.md
- packages/react/src/extend-theme.ts
Closes #3662
Improve typings for `extendTheme`
Overriding existing variants lead to the TS error 
```
X has no properties in common with type 'DeepThemeExtension<Partial<{ ...Y
```
I could only reproduce this in a next app locally 🤔 
The `DeepPartial` solves this issue.
No
> fix(extend-theme): use DeepPartial to fix TS override error

- .changeset/small-kings-call.md
- packages/hooks/src/use-outside-click.ts
- website/pages/docs/hooks/use-disclosure.mdx
- website/pages/docs/hooks/use-outside-click.mdx
Improve wording for the `use-outside-click` page
Add jsodcs for the UseOutsideClickProps interface.
> docs(hooks): improve wording for the use-outside-click page

- .changeset/healthy-beds-drive.md
- packages/theme/src/components/progress.ts
Changes incorrect `panel` part name in `Progress` theme file to `label`
> fix incorrect part name in progress theme

- website/pages/docs/theming/component-style.mdx
Closes #3770
Updates the component style docs.
Docs promote the `sx` prop to pass theme styles to the component. This leads to some unexpected behaviour regarding overrides.
Now the docs use the `__css` prop like all chakra components do.
No
> docs(component-styles): use __css for useStyles return values

- .changeset/orange-pens-destroy.md
- packages/system/src/use-style-config.ts
Closes #3758
TS type is too narrow to pass arbitrary props.
It only allows `ThemingProps`.
Allow arbitrary props with `ThemingProps & Dict`.
No
> feat(system): allow passing custom props to useStyleConfig

- .changeset/violet-chicken-fry.md
- packages/modal/src/modal.tsx
- packages/theme/src/components/modal.ts
Closes #3801
Closes #3684
This PR fixes an invalid calculated height of the modal.
The dialog container exceeds the viewport on iOS.
Check if platform [@supports](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) `-webkit-fill-available` to use correct container height. Then calculate height based on percentage value instead of viewport values, which are incorrect on iOS devices.
No
Open https://chakra-ui-git-fix-modal-height-ios-chakra-ui.vercel.app/docs/overlay/modal on an iOS device and scroll down to "Modal overflow behavior" and click "Trigger modal":
<div style="display: flex; justify-content: space-between">
</div>
> fix(modal): calc height correctly on iOS

- .changeset/nice-cooks-switch.md
- packages/stat/src/stat.tsx
- packages/stat/tests/stat.test.tsx
Closes #3799 
The component `StatHelpText` wraps its content with an invalid `dd` tag child. What is throwing the below error related to a11y.
`<dl>s do not contain only properly ordered <dt> and <dd> groups, <script>, or <template> elements`
reference: https://web.dev/definition-list/?utm_source=lighthouse&utm_medium=devtools
`StatHelpText` wraps its content with the tag `p`, which is an invalid `dd` tag child.
`StatHelpText` wraps its content with the tag `dl`, which is a valid `dd` tag child.
No
--
> fix(stat): StatHelpText audit fails

- website/pages/docs/getting-started.mdx
Missing URL protocol is causing the link to be interpreted as a relative URL.
Links to: https://chakra-ui.com/docs/gatsbyjs.com/plugins/@chakra-ui/gatsby-plugin
Links to: https://www.gatsbyjs.com/plugins/@chakra-ui/gatsby-plugin/
No
> docs: fix broken external link

- packages/slider/src/use-slider.ts
- packages/slider/stories/slider.stories.tsx
Closes #2210
This fixes a regression of #2210.
While dragging `SliderThumb` a small amount such that the value does not change, `onChange` is fired rapidly
`onChange` will only fire when the value changes.
No, this is a bug fix
It looks like the previous fix was
reverted in fa8273bb41ad667a113b99ed97d1ab39e5790e63 due to the fix
introducing a new issue:
- Begin drag from value X
- Drag to value X + 1 without finishing drag
- Continue drag back to value X is not allowed
That issue was because `onMouseDown`/`onTouchStart` had stale closures
around `value`. Using an evergreen ref of `value` resolves this.
I looked into added tests for these two issues to avoid further regressions, but had trouble creating `mousemove` events because the track's box is always `{ bottom: 0, height: 0, left: 0, …
> fix(slider): avoid excess onChange calls

- website/pages/docs/features/global-styles.mdx
Closes nothing. I spotted the mistake and quickly fixed it without making an Issue first.
While defining global styles, I copied and pasted the example in the docs hoping to see them apply.
The Global Styles from the docs weren't having any effect. 
Typo in the docs. Global styles need to be nested under a selector e.g. `html, body`.
No
None
> docs (global styles) Correction of example config

- .changeset/perfect-beans-raise.md
- packages/tabs/src/use-tabs.ts
- packages/tabs/src/utils.ts
- packages/tabs/tests/tabs.test.tsx
- packages/tabs/tests/utils.test.ts
Closes #3683 
The behavior of the `isLazy` prop was broken in `@chakra-ui/tabs@1.3.2` due to a change in its default behavior. This change reverts the default behavior `isLazy` behavior to its old default, and allows toggling the newer behavior through the new `umountHiddenPanels` prop available on the `Tabs` component.
`isLazy` behavior was broken by `1.3.2`. `isLazy` leaves mounted the panels for any tabs that were previously selected.
- `isLazy` default behavior restored to original pre-`1.3.2` behavior. When a tab is deselected, its panel is unmounted
- Added `unmountHiddenPanels` prop (defaults to `true`) to `Tabs`. This prop only works with `isLazy`, and allows the user to control whether tabs remain mounted or are unmounted (default behavior, `true`) when another tab is selected. …
> feat(tabs): make new isLazy behavior toggleable via unmountHiddenPanels prop

- .changeset/bright-socks-hope.md
- packages/checkbox/src/checkbox-group.tsx
- packages/checkbox/src/checkbox.tsx
- packages/checkbox/src/use-checkbox-group.ts
- packages/checkbox/tests/checkbox.test.tsx
Closes #3718 
Used logic from `ButtonGroup` and adapt it to `CheckboxGroup`.
`CheckboxGroup` does not have an `isDisabled` prop.
`CheckboxGroup` now has the `isDisabled` prop implement, and it is used in all `Checkbox`es that don't have the `isDIsabled` prop defined.
No.
-
> feat(checkbox-group): add isDisabled prop to checkbox group

- .changeset/lemon-ravens-poke.md
- packages/styled-system/src/config/transition.ts
- packages/styled-system/src/utils/index.ts
- packages/styled-system/tests/css.test.ts
Closes #3840
Fix the resolution of transition tokens to css vars from the theme.
I extended the `t` helper object with `transitionProperty`, `transitionDuration` and `transitionEasing` and use them in the transition config. 
Transition tokens were not resolved correctly.
Transition tokens are resolved correctly
No
> fix(styled-system): transform transition theme tokens correctly

- website/src/components/omni-search.tsx
- website/theme.ts
Improvements for `OmniSearch`:
- made it look mostly the same as our `DocSearch`
- fixed issue where clicking result did not close modal if the result is on the same page user is currently on
- changed sorting of results to respect hierarchy
No.
> feat(docs): improve search

- .changeset/purple-rockets-jog.md
- packages/progress/src/circular-progress.tsx
Fix circular-progress link to docs from 
Displays wrong documentation link to Doc on  JSDoc `https://chakra-ui.com/docs/feedback/progress`
Fix JSDocs to display correctly link `https://chakra-ui.com/docs/feedback/circular-progress`
No
> docs(progress): fix circular progress Docs link

- website/src/components/omni-search.tsx
Closes: N/A
I find myself instinctively trying to toggle the search bar closed with the hotkey when I navigate the docs. This PR adds the ability to close the search bar using the hotkey cmd/ctrl+k
Hotkey opens the search bar, but doesn't close it
Hotkey toggles the search bar open/closed
No
> fix(docs): toggle omni search with hotkey (cmd/ctrl+k)

- .changeset/lovely-dancers-guess.md
- packages/button/src/button.tsx
- packages/button/tests/button.test.tsx
Closes #3859 , #3871 
Fixes issue where button wasn't receiving type prop on first mount
Button does not receive type="button", even when passed in as a prop.
If is a button, so doesn't have a as props should receive `type={type}` where default type is a button
No
> fix(button): #3859 fix button type as undefined

- .changeset/tiny-hornets-dress.md
- .changeset/young-fishes-tap.md
- packages/react/src/extend-theme.ts
- packages/react/src/index.tsx
- packages/react/src/theme-extensions/index.ts
- packages/react/src/theme-extensions/with-default-color-scheme.ts
- packages/react/src/theme-extensions/with-default-props.ts
- packages/react/src/theme-extensions/with-default-size.ts
- packages/react/src/theme-extensions/with-default-variant.ts
- packages/react/tests/theme-extension.test.tsx
- packages/react/tests/with-default-color-scheme.test.tsx
- packages/react/tests/with-default-props.test.tsx
- packages/react/tests/with-default-size.test.tsx
- packages/react/tests/with-default-variant.test.tsx
- packages/theme/src/index.ts
- packages/theme/src/utils.ts
- packages/theme/tests/theme.test.ts
- packages/utils/src/assertion.ts
- packages/utils/src/function.ts
- website/pages/docs/theming/customize-theme.mdx
Closes #2828
This PR introduces theme extentions. `extendTheme` now composes all overrides and extensions onto the baseTheme.
`extendTheme` accepts one override object.
You can apply a default color scheme to all components in your baseTheme.
```js
import {
extendTheme,
theme as baseTheme,
withDefaultColorScheme,
} from "@chakra-ui/react"
const customTheme = extendTheme(
withDefaultColorScheme({ colorScheme: "red" }),
baseTheme, // optional
)
```
Or pass the component names you want to apply a default `colorScheme` to. This
lets you apply different color schemes to a group of components.
```js
import {
extendTheme,
withDefaultColorScheme,
} from "@chakra-ui/react"
const customTheme = extendTheme(
withDefaultColorScheme({
colorScheme: "red",
components: ["Button", "Badge"],
}), …
```
> feat: add theme extension withDefaultColorScheme

- .changeset/friendly-parents-mate.md
- packages/menu/src/menu.tsx
Closes #3862 
Menu button text is not truncated correctly.
I've created a sandbox example of the issue here https://codesandbox.io/s/chakra-ui-menu-button-truncated-text-his57?file=/src/App.tsx:311-324
> Fix #3862 Menu button issue with truncated text

- .changeset/forty-kids-exercise.md
- packages/popover/src/popover.tsx
Closes #3899
The fix was a simple line and could be done just exporting the `usePopoverContext` hook that was already imported in the modified file.
After [this changes](https://github.com/chakra-ui/chakra-ui/pull/3733/files#diff-90c4d042a18f8ae178e87611b561c7b86ddd6029b77d35b98b30f153dbe2a1f6L48), the `usePopoverContext` hook could not be imported from `@chakra-ui/react` anymore.
Now should be possible to import the `usePopoverContext` hook from `@chakra-ui/react` normally.
No
--
> fix: export `usePopoverContext`

- .changeset/kind-rocks-kick.md
- packages/utils/src/function.ts
Closes #3920 
This PR adds types to the return value of `pipe`. This helps resolving the return value typings of `extendTheme` .
Return type of `pipe` is `any`
Return type of `pipe` is the combination of all function argument result types.
No
> feat(utils): add return value typings for `pipe`

- website/pages/docs/getting-started.mdx
The `App` component was returning itself in two sections of this page. This is incorrect, as it would create an infinite compilation loop
> Fix a mistake in the Getting Started documentation

- .changeset/slow-jokes-arrive.md
- tooling/cli/src/command/tokens/index.ts
- tooling/cli/src/scripts/read-theme-file.worker.ts
Closes #3940 
Passes error messages from forked worker up to parent allowing the cli command to fail
- `read-theme.worker` Will write errors to `stderr` but not send a message back to the parent process causing the parent to not handle worker errors, making script hang forever
- `runTemplateWorker` does not support handling errors a `ChildProcess` encounters (message needs to be passed)
- An error message will be passed to the `parent` in the shape of `{ err: errMessage }`
- `runTemplateWorker` will check if the message matches the error shape if it does the promise will reject, passing the error message along
No
> fix(cli): silent failure

- .github/workflows/pr.yml
- .github/workflows/release.yml
- jest.config.js
- package.json
- packages/styled-system/tests/interpolation.test.ts
This PR greatly improves `test` speed. 
- dropped `lerna run` in favor of a single `jest` process
- changed `test` script to `jest --maxWorkers=50%` which makes local runs even faster
- created `test:ci` script which runs `jest --runInBand`
Local tests take multiple minutes to run. CI tests takes 6-8 minutes to run.
Local tests take less than a minute to run. CI tests take 1-3 minutes to run.
No
> chore: speed up test runs

- website/src/components/table-of-content.tsx
Closes #3999.
Changed hover color to use a lighter color in dark mode, the color used is the same as in Header icons.
Hover links in dark mode are too darker to read:
Updated to use lighter color in dark mode:
> fix: 'on this page' links to use lighter hover color in dark mode

- .changeset/twelve-planes-brush.md
- tooling/gatsby-plugin/gatsby-browser.js
- tooling/gatsby-plugin/gatsby-ssr.js
Closes https://github.com/chakra-ui/chakra-ui/issues/4014
In the last major update I introduced a little error as I didn't pass the `pluginOptions` correctly. It's always the second arg and just spreading `props` won't pass that to the provider component.
`pluginOptions` isn't passed to the `ChakraProvider`
Accessing the second arg from the `wrapRootElement` API to pass `pluginOptions` to the provider component.
No
> fix(gatsby-plugin): Pass pluginOptions correctly

- .changeset/lovely-houses-repair.md
- packages/modal/src/modal.tsx
Closes #4045
Fix link to modal documentation
N/A
N/A
No
I found some redirect duplication happening in `next-redirect.js`. For example `/avatar` 
```js
// ...
{
source: "/avatar",
destination: "/docs/data-display/avatar",
permanent: true,
},
// ...
{
source: "/docs/data-display/avatar",
destination: "/docs/media-and-icons/avatar",
permanent: true,
},
```
We can (should?) remove all the duplications and make shortpaths direct to current latest location (i.e. `/avatar` to `/docs/media-and-icons/avatar`) then update all `@see Doc [link]` comments to use the short format `/[target]` like
```js
/*
* @see Docs https://chakra-ui.com/avatar
*/
```
> fix(modal): @see doc link

- .changeset/warm-llamas-trade.md
- packages/menu/src/use-menu.ts
- packages/popover/src/use-popover.ts
- packages/popper/src/use-popper.ts
- packages/tooltip/src/use-tooltip.ts
Fixes regression of https://github.com/chakra-ui/chakra-ui/pull/3343
Add `isOpen` option to `usePopper` hook. 
The `popper.js` instance will not be created until this option is true.
`Menu`, `Popover` and `Tooltip` components now use this option,
so the `popper.js` instance is created only once the popper is open.
This should significantly improve render and scroll performance.
`popper.js` instance is created for every `Menu`/`Popper`/`Tooltip` instance, regardless of whether it is open.
`popper.js` instance is only created once the popper is actually needed for positioning.
No
> fix(popper): perf regression for lazy init

- .changeset/new-seas-attack.md
- packages/media-query/package.json
- packages/media-query/src/use-breakpoint.ts
- packages/media-query/src/use-media-query.ts
- packages/media-query/stories/media-query.stories.tsx
If one had used useBreakpointValue within an IFrame,
the root window element was used to determine the breakpoint.
Now the window from the current context is used.
Closes #3693
> fix(media-query): fix an issue with useBreakpointValue

- website/pages/docs/overlay/drawer.mdx
Removes redundant closing tag for `DrawerContent` in the [drawer-placement example](https://chakra-ui.com/docs/overlay/drawer#drawer-placement).
No
> docs: drawer remove redundant closing tag

- packages/styled-system/src/index.ts
> This fixes the esm build for the styled-system package; currently the esm build is trying to export `WithCSSVar` from an empty `types.js` file.
> When including `@chakra-ui/styled-system` `rollup` is not able to build as the `WithCSSVar` `type` is trying to be re-exported in the esm build.
> When including `@chakra-ui/styled-system` `rollup` is able to build.
> fix: Fix type export in styled-system package
