chakra-ui/chakra-ui

website/pages/docs/disclosure/tabs.mdx

Fixed SEO `description` tag.
Mistyped `description` won't be rendered
Get's properly rendered.
No

docs(tabs): fixed meta tag

---

website/pages/docs/disclosure/visually-hidden.mdx

Fixed a type in `description` for SEO meta tags.
The field name is ignored, as it's mistyped. 
Renders now correct SEO description
No.

docs(visually-hidden): fixed description

---

website/next-redirect.js

This very minor PR adds a redirect rule to navigate `/docs` to `/docs/getting-started` since there is no index page for `/docs`.
`/docs` shows the 404 page.
`/docs` should redirect to `/docs/getting-started`.
No.
Merge is optional. ✌🏻

feat: add `/docs` redirect to getting started page

---

website/pages/guides/integrations/with-framer.mdx

The example for using framer-motion with Typescript seems unnecessarily complicated.
New code is much less intimidating.
No
I may be missing something that means it's necessary to have these types. It's also interesting we show the usage of chakra.div instead of Box.

docs(with-framer): Simplify Typescript example for framer-motion

---

packages/checkbox/src/use-checkbox.ts

The `onChange` prop's description in Checkbox has an extra dot

docs: removed extra dot in checkbox onChange desc

---

.changeset/loud-radios-travel.md
packages/media-query/src/use-breakpoint-value.ts
packages/media-query/tests/use-breakpoint-value.test.tsx

When using `useBreakpoint()`, it's possible to SSR by providing a `defaultBreakpoint` value. However, it's not possible to do the same with `useBreakpointValue()` because it is hard coded to call `useBreakpoint()` without a default.
Calling `useBreakpointValue()` on the server will always return `undefined` due to the hard coded call to `useBreakpoint()` without a default.
This addition allows calculating a useful value from `useBreakpointValue()` on the server by passing a `defaultBreakpoint` value.
No

Support defaultBreakpoint for useBreakpiontValue()

---

.changeset/red-dancers-know.md
packages/stat/src/stat.tsx

Closes #4123 
> Exported the `StatGroupProps` interface

fix(statgroup): export statgroupprops interface

---

.changeset/soft-hairs-happen.md
tooling/cli/README.md
tooling/cli/src/scripts/read-theme-file.worker.ts
website/pages/docs/theming/advanced.mdx

I'm distributing a Chakra theme within my organization as a package on NPM and there's currently no good way to distribute the associated token type definitions.
The Chakra CLI (**@chakra-ui/cli**) expects a theme to exist in a file within a project (e.g: `src/path/to/theme.ts`) with which to generate definitions from.
Add support to **chakra-ui/cli** to consume themes distributed as NPM packages, e.g: `chakra-cli tokens @my-org/chakra-theme`.
No.
I'm curious if this sort of use case has come up before. I did try to search around a bit in the issues and discussions on GitHub and didn't find anything. Ideally, it would be possible to define custom theme type definitions via declaration merging (similar to how [**styled-components** does …

✨ Support generating token type definitions from theme packages

---

.changeset/shy-geese-think.md
packages/system/src/system.ts
packages/system/tests/style-resolver.test.ts

This PR append  `chakra` factory function enable functional `baseStyle` and use props.
```js
const CustomButton = chakra(Button, {
baseStyle:  (props) => {
bg: `${props.colorScheme}.200`,
p: 10
}
})
```
```js
<CustomButton colorScheme="red" />
```
I'm not very confident about the implementation. If this PR have any problems(implementations, design, or etc), please close this PR.
`chakra` factory is not accept baseStyle as a function and we can't treat `props`.
`chakra` factory can resolve functional baseStyle.
No
We can create custom component as normally, but sometimes those need `forwardRef`...
```js
// this component occur error when use refs. …
```

feat: append functional baseStyle 

---

.changeset/nasty-hairs-invent.md
packages/theme/src/components/textarea.ts

Firefox and Chome set the display property of TextAreas to Inline-Block by default, that causes a gap at the bottom of the component, can be fixed by changing the display to block or if we want to keep it inline, we can also set the vertical align of the component to top, bottom, middle, just not base line, also fixes issue I think is a better solution.
check discussion on https://github.com/chakra-ui/chakra-ui/discussions/4087
no vertical alignment set by default on the textarea component, firefox and chrome set this to baseline
set the vertical align of the textarea component to `top` by default, fixes an issue of a 7px gap on the bottom of the component 
no

fix(textarea): bottom gap space 

---

.changeset/red-hotels-raise.md
examples/next-js/package.json
examples/next-js/pages/_app.js
examples/next-js/pages/accordion.js
examples/next-js/pages/auto-id.js
packages/hooks/src/use-id.ts
packages/react/src/chakra-provider.tsx
yarn.lock

Closes #4044
This PR introduces a consistent API to generate isomorphic Ids on the client and server.
Our current approach (with reach/auto-id) generates an `undefined` id on the server and resolves to an `id` on the client. The only way to get a consistent id is by telling the consumer to specify an `id`.
Consistent id on server and client. Big thanks to the work done by the React Aria team, I basically leveraged their SSRProvider model.
No
To get this working, I had to render an `IdProvider` to the set of providers in `ChakraProvider`

fix: consistent id generation

---

website/pages/docs/features/responsive-styles.mdx

> Fixes minor numeric typo 
> From the docs -
Here's how to interpret this syntax:
500px: From 48em upwards
but the `w={[300, 400, 560]}`

docs: fix minor numeric typo

---

.changeset/shy-clouds-smash.md
packages/toast/src/use-toast.tsx

I noticed that showing a toast with content that is bigger than the toast maximum width is cut-off. Instead, I expected the child elements to respect the width of the toast.
```tsx
toast({
title: `Error while evaluating template`,
description: (
<Code
overflowX="scroll"
display="block"
whiteSpace="pre"
children={result.chatMessageCreate.error.reason}
/>
),
status: "error",
duration: null,
isClosable: true,
position: "top"
});
```
Reproduction on CodeSandbox: https://codesandbox.io/s/beautiful-cache-1yc6d?file=/src/index.tsx:576-2422
No overflow-x scroll bar possible 😢 
overflow-x is possible, as child elements cannot be bigger than the max-width of the toast ✅
no

fix(toast): set maxWidth on container component

---

.changeset/rotten-timers-promise.md
packages/tabs/src/tabs.tsx

The `<Tabs>` component _does_ render a DOM element: a `div`. I've removed the comment that says otherwise.
no

Remove erroneous note about <Tabs> not rendering to DOM

---

.changeset/wet-spoons-play.md
packages/button/src/icon-button.tsx

Closes #4244
> Makes the IconButton component use the themed borderRadius, not set to md.
> IconButton always has borderRadius: 'md' unless directly set or using the isRound prop.
> IconButton uses the themed default for the Button borderRadius.
No

fix(icon-button): update IconButton to use theme borderRadius

---

.changeset/lucky-taxis-shave.md
.changeset/ten-turkeys-relax.md
packages/menu/src/use-menu.ts
packages/popover/src/use-popover.ts
packages/popper/src/use-popper.ts

Closes #4109
Closes #4186
This PR makes it possible for users to choose if they want to position the menu and popover components on mount or when it's open.
We only position these components when it's open and it can cause an overflow on the page
I'd consider the current behavior a breaking change from the previous release but now we're in a better place. It's up to the user to choose which strategy they want.

fix: initial position issue with popover or menu

---

packages/form-control/migration.md

Fixes a typo, `it is` → `its`.

docs: fix grammar in packages/form-control/migration.md

---

.changeset/twelve-fishes-reflect.md
packages/button/src/button.tsx

Closes #4255 
Fixed an issue where style props that are set to `undefined` won't use default theme styles. Now, undefined props are not passed to Chakra base button elements so that their `undefined` values won't override the styles.
There was a recent PR (#4245) that fixed the icon button's border radius not using the themed border radius when `isRound` is false, [as intended](https://chakra-ui.com/docs/form/icon-button#props). That change meant setting `borderRadius` to `undefined`, but the issue was that undefined props were being passed to the Chakra base button element, thus overriding any **default** theme styles if no theme was set.
https://github.com/chakra-ui/chakra-ui/blob/bb0356f10e14886a19072b68f9e4999c6a3bfc1d/packages/button/src/icon-button.tsx#L50
I'd noticed that this was …

fix(button): undefined style props not using default style 

---

.github/stale.yml

Closes #4155 
This PR updates the `stalebot` configuration to apply only to issues with the "Awaiting Response" or "Needs Reproduction" labels. This avoids closing issues that haven't been fully considered/addressed by the Chakra team.
I also updated the stale comment to reflected that this targets only these types of issues.

chore(stalebot): target only issues awaiting a response/reproduction

---

package.json
yarn.lock

Fixes #4299
The repo cannot run on m1 Macs because the present version of the `sharp` package depends on homebrew to build. But homebrew is not fully supported on m1 macs yet. So there is a new `sharp` version that fixes this. 
This PR updates sharp.

fix(dependency): sharp on m1

---

package.json
scripts/plopfile.ts
website/package.json
website/pages/resources.tsx
website/src/components/blog-post-card.tsx
website/src/components/sidebar/sidebar.tsx
yarn.lock

Change the `lodash` imports to import individual functions inside the package :)
This saves 15kB of not importing the whole `lodash` (since its index.js is CJS bundle.)
*793kB -> 778kB (-1.9%)*
```js
import _ from "lodash"
```
```js
import capitalize from "lodash/capitalize"
```
No.
Originally from https://github.com/chakra-ui/chakra-ui/pull/4292#discussion_r659318653

Docs/fix lodash import: saved 15kB of import size

---

packages/form-control/README.md

The source indicates the prop name is `requiredIndicator` but `chakra-ui/packages/form-control/README.md` says it's just `indicator`, which is incorrect
https://github.com/chakra-ui/chakra-ui/blob/main/packages/form-control/src/form-label.tsx#L20
`chakra-ui/packages/form-control/README.md` says `indicator`
`chakra-ui/packages/form-control/README.md` now says `requiredIndicator`
No
Just an update to `chakra-ui/packages/form-control/README.md`

Fixed prop name to match source

---

.changeset/polite-gifts-join.md
packages/utils/src/walk-object.ts

If you bundle Chakra-UI yourself with rollup you get a warning about a Circular dependency.
The Change fixed this warning, when bundling with rollup:
Circular dependency: ../../common/temp/node_modules/.pnpm/@chakra-ui+utils@1.8.0/node_modules/@chakra-ui/utils/dist/esm/index.js -> ../../common/temp/node_modules/.pnpm/@chakra-ui+utils@1.8.0/node_modules/@chakra-ui/utils/dist/esm/walk-object.js -> ../../common/temp/node_modules/.pnpm/@chakra-ui+utils@1.8.0/node_modules/@chakra-ui/utils/dist/esm/index.js
No more Rollup warning
No

fix(utils): Removed Circular dependency in @chakra-ui/utils

---

.changeset/rare-experts-beg.md
packages/styled-system/src/config/grid.ts

This PR makes grid props type definitions reflect the currently implemented behavior of the components.
Gap props incorrectly specify that sizes tokens are applicable to the css properties, which is not the case, only space tokens are taken into consideration (which is also the expected and documented behavior). Other changed properties don't support token values at the moment.
Type definitions are adjusted to the currently implemented behavior. Types for gap properties either specify the correct token (space) or no token at all if inapplicable.
No, the behavior was never supported in first place.

fix: make grid props type definitions reflect current implementation

---

.changeset/cold-guests-hug.md
packages/button/src/button.tsx

This is a fix so that the left and right icon of a button also stay in the DOM while the button isLoading to avoid jumping button elements.
Currently, the left and right icons of a button don't get rendered when the button is in the loading state, which leads to less width of the button, leading to unwanted layout shifts.
The left and right icons also get rendered when the button is in the loading state and will be hidden with opacity 0 like the rest of the children.
No

fix(button): take left and right icons into consideration for button loading state

---

packages/form-control/src/form-control.tsx
packages/form-control/tests/form-control.test.tsx
packages/theme/src/components/form.ts

Closes #4270
> Support variants on FormControl by using the the form styles from the theme. Changed the FormControl to look at the styles object rather than being embedded within the component
> Variants cannot be set
> Variants can be set to override FormControl styling
No

feat: enable root element to be themed

---

website/src/components/algolia-search.tsx

The action key in search button always shows Mac's action key,  "⌘".
The action key in search button shows  "⌘" when I use Ubuntu.
Using a OS other than Mac,  the action key shows "Ctrl" as follows.

fix(docs): default action key works

---

website/pages/docs/disclosure/tabs.mdx

Closes N/A
I saw a small typo in the keyboard section under the accessibility paragraph. This PR fixes it.
Docs display the wrong key (`ArrowUp`) for the 'Moves focus to the previous tab' action.
Docs display the correct key (`ArrowRight`) for the 'Moves focus to the previous tab' action.
No
N/A

docs: fix typo in tabs docs

---

.changeset/itchy-planes-confess.md
packages/slider/src/use-slider.ts

Closes #4367
Fix issue where slider's thumb active state doesn't work properly on Firefox
If you click the slider thumb without dragging, it doesn't show its active state
The slider thumb now shows its active state
No.

fix: issue with slider thumb and firefox

---

website/pages/docs/features/responsive-styles.mdx

> Fixes a minor word typo in responsive styles section of the documentation website
> From the docs of responsive styles under the section "The Array Syntax":
> _"All style props **that** arrays as values for mobile-first responsive styles."_
> Changed _"that"_ to _"accept"_
> _"All style props **accept** arrays as values for mobile-first responsive styles."_

docs: fixed a typo in responsive styles docs

---

website/pages/guides/integrations/with-hook-form.mdx

so people can see it without having to open codesandbox...
Closes # 
There was no example displayed on the react-hook-form page of Chakra-UI wiki, so I pulled the example out of CodeSandBox and put it on the page
No example displayed on react-hook-form page of Chakra-UI wiki 
PR displays example from provided CodeSandBox on the page
No
Credited author of CodeSandBox example

Put sandbox example on wiki page

---

website/pages/docs/theming/customize-theme.mdx

Fixes a small discrepancy in the docs. The directory structure recommends the main theme entrypoint be called index.js but the comment calls it theme.js.
No.

fix discrepancy in main theme entrypoint filename

---

website/src/components/codeblock/code-container.tsx
website/src/components/codeblock/codeblock.tsx
website/src/components/codeblock/copy-button.tsx
website/src/components/codeblock/highlight.tsx
website/src/components/codeblock/react-live-block.tsx
website/src/components/codeblock/styles.tsx

> Load live-editor dynamically after page mount
Per page size reduction: 785kB -> 532kB. Reduced **32.2%** of the initial bytes.
The current `<CodeBlock />` imports `react-live` everywhere. Even for those pages that are not even using the live-editor feature (`live=true` ). 
Refactor `<CodeBlock />` and make the live-editor parts loadable via `next/dynamic`.
No
The loadable information by `Nextjs`:

docs(react-live-dynamic): reduces 32.2% size of the docs website

---

.changeset/rotten-cobras-smash.md
packages/layout/src/stack.tsx
packages/layout/tests/layout.test.tsx

Closes #4447
Ensures that, when cloning children, their original `key` is used if provided.
Stack currently clones its children if `props.divider` is set or `props. shouldWrapChildren` is true. When cloning the children, the index of the children in the array is used as the key.
This results in children being unexpectedly/unnecessarily destroyed and re-created.
Using indexes as keys is described [in the React docs](https://reactjs.org/docs/lists-and-keys.html#keys) as a last resort.
Prefers the child's provided `key` if it exists, falling back to index.
NO
Regression test added to assert this fix.

fix(Stack): When cloning children, prefer each childs provided key 

---

.changeset/rude-geckos-build.md
packages/theme/src/components/modal.ts

Closes #4461 
Remove the vertical margin from the Modal with size `full` so the modal is displayed without scrollbars.
The `modal` with `size:full` has a vertical margin.
The vertical margin is set to `0` when `size===full`
No

fix(modal): remove vertical margin in full screen modal

---

.github/workflows/daily.yml

Fix issues mentioned in #4410.
1. Runs on every forked repo
2. Commit and push to `main` branch
1. Use [jobs.<job_id>.if](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif) with repository check
2. Use [create-pull-request](https://github.com/peter-evans/create-pull-request) for committing changes
No
@with-heart the workflow has been tested on my forked repo (with modified `daily.yml` pointed to my repo) and it created a PR:
* https://github.com/tomchentw/chakra-ui/runs/3148979339?check_suite_focus=true
* https://github.com/tomchentw/chakra-ui/pull/4

docs: daily workflow create pr

---

website/pages/docs/theming/theme.mdx

Some time ago the `0` spacing was removed from the theme ([see this commit](https://github.com/chakra-ui/chakra-ui/commit/8c10423fb34a03d8cb5d4402ac3e592b3195108a#diff-5cd6a66aae12147b476dcb95669bb5435159f86cf037293de113e4cc5eca48f6)).
The docs still include the removed spacing though.
Referencing this value via indexer would lead to `undefined` and could cause unwanted default behavior where `0` is intended.
No.

docs(theming): remove obsolete zero space

---

.changeset/strong-snakes-suffer.md
packages/menu/src/use-menu.ts
packages/utils/src/dom-query.ts
packages/utils/src/dom.ts
packages/utils/src/focus.ts
packages/utils/src/pointer-event.ts
packages/utils/src/tabbable.ts
packages/utils/tests/dom.test.ts

Closes #4457
Use constructors like `Element` for `instanceof` checks from the `window` object that the current node belongs to.
When rendered into a different window, some components currently misbehave (e.g. `<Menu>` doesn't close when clicking an item or clicking outside) because `instanceof Element` (and similar) checks fail, because the elements inherit the `Element` from a the other window object.
Also see #4457 .
All `instanceof SomeContrusctor` checks now use `instanceof win.SomeConstructor` instead, where `win` is the window object that the current node or event belongs to.
No
Didn't add a lot of tests, since JSDOM doesn't support `window.open`, and also since most of the code wasn't explicitly tested. Let me know if you need more tests or have any ideas how to better test this.

fix(utils): use correct window for instanceof checks

---

.changeset/ninety-suits-camp.md
packages/styled-system/src/config/others.ts
packages/system/src/system.types.tsx

Support for responsive values in the `apply` prop was added [here](https://github.com/chakra-ui/chakra-ui/pull/3245), however, overlapping type definitions prevent this from being accurately reflected in TypeScript.
```tsx
// Type error, expects `string` for `apply`;
<Text apply={{ sm: 'styles.h3', lg: 'styles.h4' }}>
```
```tsx
// No type error, expects `ResponsiveValue<string>`
<Text apply={{ sm: 'styles.h3', lg: 'styles.h4' }}>
```
No.

fix: type definition for apply style prop

---

.changeset/lucky-mirrors-sleep.md
packages/menu/src/use-menu.ts
packages/menu/stories/menu.stories.tsx

Closes #4510
Added `preventScroll:false` to `focus`-calls in `use-menu`
If `MenuList` has a `maxHeight` and overflowing items and the User navigates it via Keyboard the `MenuList` doesn't scroll to the focused `MenuItem`  which is inside the "overflow-area".
`preventScroll` is set to `false` in `use-menu` and now the focused item is scrolled into view when selected.
No

fix(menu): scroll menu list with maxHeight on keyboard navigation

---

.changeset/early-meals-impress.md
packages/stat/src/stat.tsx
packages/theme/src/components/stat.ts

Closes #4537 
Add `container` style to`Stat`-component.
Currently, it isn't possible to overwrite the container style in the theme (see #4537)
Added a `container` prop in the `Stat`-theme and used the `container`-style inside the Stat component so that the container style can be overwritten inside the theme.
No

feat(stat): add `container` style to `Stat`-component

---

website/configs/site-config.ts

fix #4532  
Changed so that clicking `Edit this page` takes you to the correct page instead of the 404 page of GitHub.
When I clicked the "Edit this Page" link on the documentation page, I was sent to a 404 page on GitHub.
For example, clicking the link on the Getting Started page took me to https://github.com/chakra-ui/chakra-ui/edit/main/website/docs/getting-started.mdx, That's it.
Clicking the "Edit this Page" link on the documentation page now takes you to the correct GitHub editing page.
For example, clicking the link on the Getting Started page took me to "https://github.com/chakra-ui/chakra-ui/edit/main/website/pages/docs/getting-started.mdx ".
No

Fix document Page"edit this page" link

---

.changeset/eight-socks-invent.md
packages/form-control/src/use-form-control.ts
packages/form-control/tests/form-control.test.tsx

Closes #4522 
If the user provides an `aria-describedby` property to any form element this value isn't taken into account and will be overwritten.
if the user provides a value for `aria-describedby` this value will be attached to the other labels like `feedbackText` and `helperText`.
No

fix(form-control): provided `aria-describedby` isnt ignored anymore

---

.changeset/great-parrots-guess.md
.changeset/silver-hounds-shout.md
packages/radio/src/radio-group.tsx
packages/radio/src/radio.tsx
packages/radio/src/use-radio-group.ts
packages/radio/stories/radio.stories.tsx
packages/radio/tests/radio-group.test.tsx

Closes #4551 
Add `isDisabled` to `RadioGroup` to match the behavior of `CheckboxGroup`
[feat(checkbox-group): add isDisabled prop to checkbox group](https://github.com/chakra-ui/chakra-ui/pull/3778/commits/8e24bfff938478311027f091d47d105489ccb8e3)
Also added `isFocusable` to `RadioGroup` so we can [trulyDisabled](https://github.com/chakra-ui/chakra-ui/blob/main/packages/radio/src/use-radio.ts#L205) all `Radio`'s inside a `RadioGroup`
It isn't possible to disable a whole `RadioGroup` on the `RadioGroup`-Level
It is possible to disable all `Radio` inside a `RadioGroup` by setting `isDisabled:false`
No

feat(radio-group): add isDisabled and isFocusable to RadioGroup

---

.changeset/angry-knives-sniff.md
packages/slider/src/use-slider.ts

Closes #4563
When supplying an onChangeEnd callback to the slider component it will receive focus on every rerender.
The onChangeEndProp is not stable between renders and hence the following [lines](https://github.com/chakra-ui/chakra-ui/blob/main/packages/slider/src/use-slider.ts#L327-L332) causes the slider thumb to be focused on every render:
```
useUpdateEffect(() => {
focusThumb()
if (eventSourceRef.current === "keyboard") {
onChangeEndProp?.(valueRef.current)
}
}, [value, onChangeEndProp])
```
Instead use the onChangeEnd callbackRef that is stable between renders and therefore not causing the slider to receive focus.
No (unless someone depends on this behavior)

fix(slider): don't use onChangeEndProp as dep

---

.changeset/curly-frogs-kick.md
packages/skeleton/src/skeleton.tsx
packages/skeleton/tests/skeleton.test.tsx

Closes #4394.
https://github.com/chakra-ui/chakra-ui/pull/2775 fixed one bug but introduced another. 
If a component has a child Skeleton that's loaded (`<Skeleton isLoaded/>`) and the parent component re-renders, the Skeleton would animate because it was no longer the first render.
It now needs to meet a stronger condition to animate when loaded. If `isLoaded=true` and it's the first render **or** the skeleton was already loaded in the previous render, no animation will happen.
No.
Test was added. Was failing before my fix.

fix(skeleton): don't animate when skeleton was previously loaded

---

.changeset/chatty-emus-relate.md
website/src/components/sidebar/sidebar-link.tsx

This PR fixes the docsite's `SidebarLink` active state checking.
Some of the pages don't highlight their corresponding `SidebarLink` when active
Now they all do
No

docs: fixed SidebarLink's active state check

---

.changeset/thin-pens-fetch.md
packages/slider/src/use-slider.ts

Closes #4572 
`onChangeStart`/`onChangeEnd` aren't triggered on click see #4572 
made it possible to trigger `onChangeStart`/`onChangeEnd` onClick
Moved the call to `onChangeEnd` from `onPanEnd` to `onPanSessionEnd` - because `onPanEnd` is only called if there is a panning involved. 
❗  Also removed some logic in `onPanSessionEnd` - because this shouldn't break anything - or was there a cause why this was added @segunadebayo ?
Moved the call of `onChangeStart` from. `onPanStart` to `onPanSessionStart` - because `onPanStart` is only called if there is a panning involved.

fix(slider): onChangeStart/onChangeEnd are triggered onClick

---

.changeset/twenty-candles-burn.md
packages/theme/src/components/tag.ts

Closes #4565 
Added `overflow:visible` to `baseStyle` of `TagLabel` to render the label without any clipped Text when using font-family`Segoe UI Semibold`
No

fix(tag): added overflow:visible to `TagLabel`

---

.changeset/modern-garlics-taste.md
packages/hooks/src/use-outside-click.ts
packages/menu/src/use-menu.ts
packages/menu/stories/menu.stories.tsx

This MR adds an `enabled` prop to the `useOutsideClick` hook so that we can conditionally apply the event listeners. We can use this prop in the `useMenu` hook to only apply the event listeners when the menu is open and `closeOnBlur`. 
This improves performance for pages with many menu items.
Currently useOutsideClick attaches a new event listener for `mousedown`, `mouseup`, `touchstart` and `touchend` every time the `useOutsideClick` hook is used. Since this is attached to the document, the callback is fired for every click in the document.
Outside click is currently used in the `useMenu` hook with no way to disable it. For each Menu component that appears on the page an event listener is created:
Adding an `enabled` prop to `useOutsideClick` enables us to control when to apply the event …

feat: use outside click enable

---

packages/system/src/use-style-config.ts

The useMemo in useStyleConfig can't return any memoized result because of a dependancy on the locally created object `mergedProps`, so I figured it's better to just remove it as it is misleading (and can actually _cost_ a tiny bit of perf).
No

perf: remove useless useMemo

---

website/pages/docs/disclosure/tabs.mdx

Closes # 
@segunadebayo  The explanation of the section says "Because TabList needs to know the order of the children, we use cloneElement to pass state internally.", but the ref is not passed to any component in the example <CustomTab>.

docs: update tabs doc by passing the ref to <StyledTab>.

---

.changeset/plenty-avocados-drop.md
packages/toast/src/use-toast.tsx

Corrected the TS type for the useToast hook options according to the [docs](https://chakra-ui.com/docs/feedback/toast#variants)
`UseToastOptions.variant?: string | undefined`
`UseToastOptions.variant?: "subtle" | "solid" | "left-accent" | "top-accent" | undefined`
No

fix: add correct variant type to UseToastOptions

---

website/src/components/omni-search.tsx

This commit aims to enhance the omni-search results so that you can open the results using gestures / shortcuts (right click => open new tab, middle click, ctrl + click, etc.)
Users are not able to open the result of searches in omni-search on a new tab.
This is due to the results rendered with a `<NextLink>` (NextJS' Link) component but without an actual `<a>` tag which will, as far as I know, do nothing.
Users are able to open the result of search in omni-search on a new tab using normal gestures / shortcuts. As an added bonus, when using modifier keys to click on a result, the modal does not close, increasing the ease of use.
No. This only changes the documentation website.

docs(omni-search): link implementation on results boxes 

---

.changeset/ten-goats-eat.md
website/pages/docs/overlay/tooltip.mdx

Closes #4555 
This PR adds the example for the use of `forwardRef` in the tooltip in the docs
No

docs: tooltip forward ref

---

website/pages/docs/theming/theme.mdx

> Fixes a minor word typo in default theme section of the documentation website.
> Chakra provides a minimal set of ***z-indeces*** out of the box to help control the stacking order of components.
> Changed "*z-indeces*" to "*z-indices*" .
> Chakra provides a minimal set of ***z-indices*** out of the box to help control the stacking order of components.

docs: fixed a typo in theme docs

---

.changeset/rare-chairs-whisper.md
packages/image/src/image.tsx
packages/image/tests/image.test.tsx

Closes #4648
Currently, the user has to optIn into `ignoreFallback` in the `Image`-component. If the user doesn't provide any possibility to fall back to, the image flashes until the image source is loaded.
If the user doesn't provide any sort of fallback (e.g. `fallbackSrc`/`fallback`) the component behaves equally as if the user would have set `ignoreFallback` on the Image
No

fix(image): ignore fallback behavior when no fallback is set

---

packages/pin-input/README.md

> fixed typo in `@chakra-ui/pin-input` package, where the example code orginally said `@chakra-ui/pin-input`
```javascript import {
PinInput,
PinInputField,
usePinInput,
usePinInputField,
} from "@chakra-ui/switch"
```
```javascript import {
PinInput,
PinInputField,
usePinInput,
usePinInputField,
} from "@chakra-ui/pin-input"
```
No, it's simply an update to the documentation.

fix: typo in readme for `@chakra-ui/pin-input` package

---

.changeset/spicy-chairs-build.md
packages/menu/src/use-menu.ts
packages/menu/stories/menu.stories.tsx

Closes #4688
The menu should be always focused when opened and arrow navigation should work without rendering the menu button. This is useful for context menus.
The first item is not auto-selected and pressing arrows doesn't select any items
The first item is auto-selected and arrow navigation works
No

fix: menu keyboard navigation consistency

---

.changeset/gentle-icons-smell.md
packages/anatomy/src/index.ts

Closes https://github.com/chakra-ui/chakra-ui/issues/4720
Breadcrumb anatomy was missing the "container" part.

fix: add missing breadcrumb part

---

.changeset/lemon-beers-relax.md
tooling/cli/package.json
tooling/cli/src/scripts/read-theme-file.worker.ts
yarn.lock

Closes #4652 
This PR allows the CLI to resolve custom TS config paths.
The CLI uses currently its own `tsconfig.json` to transpile the userland theme file.
The CLI reads the projects `tsconfig.json` and replaces the `compilerOptions.paths` during runtime of `ts-node`.
It uses the npm packages [tsconfig-paths](https://github.com/dividab/tsconfig-paths) to read the userland `tsconfig.json` and replaces the aliases with [module-alias](https://github.com/ilearnio/module-alias) while running.
No
🚨 Please note that only the first alias target from the string array will be resolved.
```json5
// tsconfig.json
{
//...
compilerOptions: {
baseUrl: "src",
paths: {
"@alias/*": ["target/*"],
//           ^-- only the first target will be resolved
},
},
}
```

fix(cli): resolve custom tsconfig paths

---

.changeset/khaki-feet-count.md
packages/transition/src/transition-utils.ts

Closes #4729 
> Preventing drawer modal from disappearing on changing the placement value
> Drawer gets hidden if placement prop changes
> Now drawer doesn't get hidden and placement is changed accordingly
No
Explicitly mentioning x and y values of enter and exit states for slide transition variants

fix(modal): preventing drawer from disappearing on placement change

---

packages/system/README.md

Updates some of the grammar inside the `@chakra-ui/system` package's README, as well as the reference to the `styled-components` library.
`@chakra-ui/system`'s README is slightly choppy to read.
Adds a bit more fluidity to the README.
No
N/A

docs: fix grammar in @chakra-ui/system README

---

.changeset/young-flowers-travel.md
packages/toast/src/use-toast.tsx
packages/toast/test/standalone-toast.test.tsx
packages/toast/test/use-toast.test.tsx

Closes #4699 
* Adds an additional `id` attribute on the AlertTitle rendered by toast, and a matching `aria-labelledby` on the Alert.
* Behaviour of screen readers should be unchanged since the reader should announce either the title and then the content, or only the content. See https://github.com/chakra-ui/chakra-ui/issues/4699#issuecomment-916902517
* The alert div rendered by toast now has an [accessible name](https://knowledge.evinced.com/concepts/accessible-names/) which is the title of the toast.
* The alert div rendered by toast is discoverable using react-testing-library [ByRole](https://testing-library.com/docs/queries/byrole) methods by using the `name` option and providing the title of the toast.
```js
const toast = …
```

fix(toast-accessible-name): allow toast to be discovered by name

---

.changeset/early-ears-flow.md
packages/button/package.json
yarn.lock

`@chakra-ui/button` package.json was missing `@chakra-ui/react-utils` dependency (although it's used in `button-group.tsx`)
Was usually harmless as all other chakra packages declare it as a dep, but could cause issues if package manager doesn't hoist the dep at root, or if one uses only button.
Missing dependency error.
No error.
No

fix(imports): added missing react-utils import

---

packages/descendant/README.md

Updates the import statement to reflect proper usage of the `@chrak-ui/descendant` package.
The import statement in the usage section of the README is incorrect.
The import statement in the usage section of the README is corrected.
No
N/A

docs: udpate descendant package README's usage

---

packages/slider/tests/range-slider.test.tsx

Adds tests for the range slider to help Draft #4740
Range slider does not have unit tests.
Adds initial unit tests for the range slider.
No
N/A

chore: add range slider tests

---

.changeset/loud-poets-care.md
tooling/cli/src/scripts/read-theme-file.worker.ts

Closes #4755
The chakra CLI fails unexpectedly with a SyntaxError.
The cli uses the theme file path to resolve a userland project `ts-config.json`.
It uses the npm package `tsconfig-paths` to resolve it, and its function `loadConfig()` requires a directory path to search for the `ts-config.json`. If it receives a file path it just uses this file. 
Provide the directory of the given theme file to `loadConfig()` to let `tsconfig-paths` search for the correct `ts-config.json`.
No

fix(cli): resolve ts-config from dirname

---

website/pages/guides/as-prop.mdx

corrected typo, removed repeated word 'need to'
you need to need to consume this component in a way that works with the as prop, like this:
Closes # 
> Fixed Typo removing repeated words

docs: update as-prop.mdx

---

packages/color-mode/test/color-mode-provider__browser.test.tsx
packages/color-mode/test/color-mode-provider__server.test.tsx
packages/color-mode/test/utils.tsx

Fixes a failing unit test inside the server tests for the `ColorModeProvider`.
The unit test asserting if the local storage object's `get` method is called is failing because the mocked jest module is inside of a separate utility function, which gives it a different scope than where the actual import for `@chakra-ui/utils` is being called in each test.
See:
> [Note: In order to mock properly, Jest needs jest.mock('moduleName') to be in the same scope as the require/import statement.](https://jestjs.io/docs/26.x/manual-mocks#examples)
Puts the mocked module inside of the `color-mode-provider__server.test.tsx` file so that all unit tests have the scope to this mocked module.
No
N/A

chore: update jest module mock scoping to mimic server environment in ColorModeProvider server tests

---

.changeset/few-jars-tan.md
packages/utils/src/dom.ts

Closes #4425 
This PR fixes the bug where the popover window will not close when clicking on an iframe on Firefox.
The `getRelatedTarget()` function [here](https://github.com/chakra-ui/chakra-ui/blob/7d54710a00472ac1658592fa2537175c742fb346/packages/popover/src/use-popover.ts#L223), uses `explicitOriginalTarget`, a Firefox/Mozilla-specific API, which causes inconsistent behavior between browsers. `explicitOriginalTarget` evaluates a valid element on Firefox, but `null` for other browsers (Safari, Chrome)
No
This is my attempt to address the issue mentioned, any inputs/feedbacks are welcome, and appreciated as I am not sure if this is the best approach.
For this PR, I removed `explicitOriginalTarget` from the `getRelatedTarget` function, which is being referenced by **Editable** and …

fix: iframe bug on firefox

---

.changeset/smart-dingos-worry.md
packages/popper/src/use-popper.ts

When not passing `modifiers` to the usePopper hook, the property gets initialized to a new empty array.
When this array is passed to the useCallback deps, it causes the useCallback to never return the memoized instance (it's always a different new empty array), which causes other useCallback in the same hook to never return their memoized instances.
This PR fixes it by not initializing modifiers to a new empty array.
No
Current workaround I'm using:
```ts
const { ... } = usePopper({
...
modifiers: useMemo(() => [], []),
...
});
```

fix(popper): allow useCallback to do its thing

---

.changeset/curvy-eels-wave.md
packages/checkbox/package.json
packages/menu/package.json
packages/modal/package.json
packages/popover/package.json
packages/react/package.json
packages/theme/src/components/table.ts
packages/toast/package.json
packages/tooltip/package.json
packages/transition/package.json

Closes #4942 
Allow to use chakra-ui with `framer-motion` v5. 
checked https://www.framer.com/docs/guide-upgrade/#50 if we're using anything is breaking but everything seems fine.
No

chore: upgrade peerDependency framer-motion v5

---

.changeset/chatty-kings-protect.md
packages/radio/src/use-radio-group.ts

Closes #4951 
Added type support for getRadioProps to add  `checked` & `isChecked` 
No

fix(radio): add type support for getRadioProps

---

.changeset/khaki-toes-repair.md
packages/color-mode/src/color-mode-provider.tsx
packages/color-mode/src/color-mode-script.tsx
packages/color-mode/src/color-mode.utils.ts
website/pages/docs/features/color-mode.mdx

Sort of similar to #4224, but with a somewhat different approach
I wanted to add the possibility to use the system preferred color scheme as a value for
`initialColorMode`, while still respecting a user's previous choice.
When the `system` value is used for the `<ColorModeScript />`s `initialColorMode` prop, the color mode will _always_ initially be set to the color mode that matches the system preference. 
However, this may not be what a user expects after manually selecting a color mode through the UI. A user is more likely to expect the color mode to remain in the configuration that he/she left it in.
Additionally, while I am not 100% sure if intended or not (or if I missed something), there seemed to be a mismatch of the types between the `ColorModeProvider` and `ColorModeScript` …

Better handling of `system` as initial color mode

---

.changeset/heavy-bears-reflect.md
packages/focus-lock/package.json
yarn.lock

`react-focus-lock@2.5.1` includes a dependency update of `focus-lock` from `0.8.1` -> `0.9.1`. The change in `focus-lock` includes a fix for performance in JSDOM: https://github.com/theKashey/focus-lock/pull/24
JSDOM is used when testing react components in jest and other unit testing frameworks. In particular, when used with `@testing-library/react` for simulating real user input.
Locally tested on an Apple M1 Air using a moderately complex `<Modal>` component (which contained inputs, `react-hook-form` usage, etc).
Before this change: 20,149ms
After this change: 2,347ms
Approx. 10x performance increase.
'tis slow 🐢
'tis _fast_ 🏎
No
Until this is released, you can workaround the slowness by adding this to your `package.json` if you're using `yarn`:
```
"resolutions": { …
```

Bump `react-focus-lock` for JSDOM performance boost

---

website/pages/docs/theming/customize-theme.mdx

I've added the final step to [customizing-global-styles](https://chakra-ui.com/docs/theming/customize-theme#customizing-global-styles) that we should provide the customized theme to `ChakraProvider` component. 
I've noticed that there's a demand for adding additional explanation to customizing 
Although there's a reminder that we should pass the custom theme to  `ChakraProvider` in the end of [updating-the-theme-config](https://chakra-ui.com/docs/features/color-mode#updating-the-theme-config), some people who miss this section and started to configure their theme according to [customizing-global-styles](https://chakra-ui.com/docs/theming/customize-theme#customizing-global-styles) might miss this step and have issues that their changes aren’t applied: [Example …

docs: added additional explanation to the customizing global styles section

---

.changeset/gold-files-guess.md
packages/slider/src/use-range-slider.ts

Closes https://github.com/chakra-ui/chakra-ui/issues/4981
fixed the bug in RangeSlider where an index out of bounds error would occur in
case of stacked thumbs
The logic to check if a thumb was stacked or not was incorrect. 
It would previously only check for duplicate values and if a duplicate value existed, it would consider that the current thumb was stacked
The check has been changed to find if duplicates of the current closest thumbs are present
No

fix: range slider out of bounds error

---

website/src/components/algolia-search.tsx

The button to open the search text field had a `role=search` on it, as well as an `aria-label`.
[`role=search` is a type of landmark](https://www.w3.org/TR/wai-aria-1.2/#search), and not a role that indicates it is actionable.    Removing this role allows the control to be correctly exposed as a button element.
The `aria-label="Search the docs"` on the button suppresses the announcement of its child content, making it so that the key commands to open the search modal will not be announced.  
As "Search the docs" is already child content of the button (line 67), removing the `aria-label` allows the name of this button to still be announced correctly, and the additional "press ... to search" content will now be announced.
If you would like the search landmark to still be used / exposed, it …

docs: accessibility fixes for Search button

---

.changeset/funny-steaks-heal.md
packages/select/src/select.tsx
packages/select/tests/select.test.tsx
packages/theme/src/components/select.ts

Closes #4938
Allow the spacing between the `field` and `icon` parts of the `Select` component to be applied from the theme.
The spacing is currently hard-coded as `2rem` in the `Select` component here: https://github.com/chakra-ui/chakra-ui/blob/445fc8b15bd1155a53ac95c5c1ba74d671062355/packages/select/src/select.tsx#L133-L136.
Allow said spacing to be applied in the `Select` component's theme, while preserving the current default behavior as best as possible.
No

fix(select): allow icon spacing to be customized via theme

---

.changeset/wild-bikes-sneeze.md
packages/color-mode/src/color-mode-provider.tsx
packages/color-mode/src/color-mode-script.tsx
packages/color-mode/src/color-mode.utils.ts
packages/color-mode/test/color-mode-provider__browser.test.tsx
packages/color-mode/test/color-mode-script.test.tsx
website/pages/docs/features/color-mode.mdx

Closes #4987
Fix the behavior of color-mode when in system mode 
Fixed color mode behavior priority in the following order:
- if `useSystemColorMode` is true system-color will be used as default - initial
colormode is the fallback if system color mode isn't resolved
- if `--chakra-ui-color-mode` is defined through e.g. `ColorModeScript` this
will be used
- if `colorModeManager` = `localStorage` and a value is defined for
`chakra-ui-color-mode` this will be used
- if `initialColorMode` = `system` system-color will be used as default -
initial colormode is the fallback if system color mode isn't resolved
- if `initialColorMode` = `'light'|'dark'` the corresponding value will be used
No

fix(color-mode): fix colormode in system-view

---

packages/radio/src/use-radio.ts

Closes #5086
Remove the unused `ref` variable in `Radio`.
-
No

chore(radio): remove unused ref

---

.changeset/happy-pants-tickle.md
packages/slider/src/range-slider.tsx
packages/slider/src/use-range-slider.ts
packages/slider/tests/range-slider.test.tsx

Closes https://github.com/chakra-ui/chakra-ui/issues/5041
fixed a bug where thumb would not move in case of stacked thumbs
The thumb does not move because the incorrect thumb is selected
Fixed the index of thumb being selected
No

fix: thumb does not move in case of stacked thumbs

---

.changeset/dull-weeks-drum.md
.github/workflows/release.yml
tooling/props-docs/package.json
tooling/props-docs/src/build.ts
website/src/components/props-table.tsx
website/src/utils/convert-backticks-to-inline-code.tsx

This PR fixes a build issue with the prop-docs package and adds types for the output files.
Based on the last release, there's currently no `dist` output for this package. This is an unintended side-effect from the migration to preconstruct.
Added `yarn build:prop-docs` to the CI after running the build command so we can get the correct build artifacts for that package
No
- Updated the website prop-table to be more typesafe
- The build script is quite slow and expect that we can improve this. It takes as long as `yarn preconstruct build` which is strange but understandable, perhaps it's related to the slowness of `ts-node`.

fix: prop-docs package

---

.changeset/mean-bikes-work.md
packages/color-mode/test/color-mode-script.test.tsx

Now and then it happened that the `color-mode` [test failed](https://github.com/chakra-ui/chakra-ui/runs/4217655474?check_suite_focus=true).  I assumed that this happened because of the `Object.define` in the `color-mode.script.test` . I replaced it with a `jest.spyOn` and now the mock should work without interfering with other tests.

chore(color-mode): fix flaky color-mode-script test

---

.changeset/brown-rivers-switch.md
packages/layout/src/flex.tsx
packages/layout/stories/flex.stories.tsx
packages/styled-system/src/config/flexbox.ts

Closes #2720
Follow up PR of #4671
Thank you @MichaelKilbane for your time creating the initial PR!
Add CSS properties gap, columnGap and rowGap to the StyleProps.
Some chakra users use `gridGap` as current workaround.
We can use `gap`, `columnGap` and `rowGap` which map to the token scale _space_.
No
https://developer.mozilla.org/en-US/docs/Web/CSS/gap

feat: add flex gap

---

.changeset/moody-bees-pay.md
packages/toast/src/toast-manager.tsx
packages/toast/src/toast.tsx
packages/toast/src/toast.types.ts
packages/toast/src/use-toast.tsx
packages/toast/stories/toast.stories.tsx

Closes #4387
This PR is a continuation of #4432 since that PR seems to have been abandoned. As such, the description is copied from that original PR and extended if necessary.
When users set a fixed-width on their custom toast, this causes their toast to not be centered. This is because we set a fixed `maxWidth` property on the wrapper component around the toast, which results in the invisible wrapper being centered correctly, but the visible custom component overflowing the parent (the wrapper), making it seem off-centered.
A more detailed explanation of why this arises can be found [here](https://github.com/chakra-ui/chakra-ui/issues/4387#issuecomment-884419618)
The div (with `class="chakra-toast__inner"`) wrapping the dispatched `Toast` component currently has a hardcoded style, …

feat(toast): expose Toast wrapper style prop for override

---

.changeset/long-dancers-vanish.md
packages/react/package.json

Hi Chakra UI team 😊 
This PR update the Storybook URL to the correct Storybook deployment URL so the automatic composition of Storybook works out of the box.
Using (automatic) composition, [we have the following result](https://start-ui.vercel.app/storybook) (check the bottom of the nav)
This is because the Storybook deployed on Netlify is old.
Using (automatic) composition with the new URL, we should have the following result 
I think this change could impact users with Storybook v5 
Users using Storybook v6 can do the following to their `main.js` file to enable composition
```js
refs: {
'chakra-ui': {
title: 'Chakra UI',
url: 'https://storybook.chakra-ui.com',
},
'@chakra-ui/react': { disable: true },
},
```
I guess users using older Storybook can do the following to their `main.js` …

docs: update storybook url to enable composition

---

.storybook/.babelrc

Closes # 
Silence this error white running storybook: 
>Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
No

chore(babel): silence babel loose warning

---

.changeset/quiet-worms-float.md
packages/tooltip/src/use-tooltip.ts

Closes # 
`onKeyDown` callback is de/registred on every call of `useTooltip`, which can cause performance issues
`onKeyDown` callback is de/registred on every call of `useTooltip`
`onKeyDown` callback is de/registred only on change of its dependencies via `React.useCallback`
No

fix: prevent `onKeyDown` callback from de/registering on every call of `useTooltip`

---

.changeset/young-guests-bow.md
packages/icon/src/create-icon.tsx
packages/icon/stories/icon.stories.tsx

> Assign key for each path if we pass array of paths for createIcon
> We will need to pass key for each path manually
```ts
import { createIcon } from '@chakra-ui/icons';
export const HeartIcon = createIcon({
displayName: 'HeartIcon',
path: [
<path key={0} stroke='none' d='M0 0h24v24H0z' fill='none' />,
<path
key={1}
d='M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572'
/>,
],
});
```
> createIcon will assign key automatically for each path, we don't need to assign when passing to the prop
```ts
import { createIcon } from '@chakra-ui/icons';
import { defaultProps } from './common';
export const HeartIcon = createIcon({
displayName: 'HeartIcon',
defaultProps,
path: [
<path stroke='none' d='M0 0h24v24H0z' fill='none' />,
<path
d='M19.5 13.572l-7.5 7.428l-7.5 …
```

fix(icon): auto assign key for each path element if createIcon prop path is array

---

.changeset/funny-laws-relate.md
packages/styled-system/src/utils/parse-gradient.ts
packages/styled-system/tests/parse-gradient.test.ts

Fixed the gradient parsing logic when a position is specified
Actually parsing result:
-  `radial(circle at center, #000, #FFF)` produces `radial-gradient(circle at, center, #000, #FFF)` <-- See extra comma
-  `radial(circle at 50% 50%, #000, #FFF)` produces `radial-gradient(circle at, 50%, 50%, #000, #FFF)` <-- See extra comma
Fixed the parsing logic.
Added a couple of test to secure the implementation.
No
I just flatten the array before joining it. I could use `.flat` method but is not supported on older browser/node versions.

fix: gradient parser when a position is specified

---

.changeset/yellow-donuts-eat.md
packages/switch/stories/switch.stories.tsx

The `<Switch />` example using `react-hook-form` isn't working as expected.
It's happening when I access the URL: https://storybook.chakra-ui.com/?path=/story/components-forms-switch--with-react-hook-form
No
I fixed the `props` using `register` to config `name`, `ref`, `onBlur` and `onChange`.

fix(@chakra-ui/switch): react-hook-form story example

---

.changeset/wet-drinks-wonder.md
packages/styled-system/src/config/position.ts

Closes #5191 
I've also fixed inset types
setting `inset="4px 8px"`
produced
```css
top: 4px 8px;
right: 4px 8px;
bottom: 4px 8px;
left: 4px 8px;
```
now it produces 
```css
top: 4px;
right: 8px;
bottom: 4px;
left: 8px;
```
Nope, the old behavior was producing invalid css
This is my first PR here, so please be patient

fix: multi-value css inset property behavior

---

.changeset/tasty-hounds-buy.md
packages/transition/src/slide.tsx

The ref prop of the <DrawerContent /> component returns null. The issue is with this component though, because that is where the ref is passed. I guess the issue is with the order of props passed, as they are overwritten with the spread {...rest}
Closes # 
The `<DrawerContent />` component `ref` props returns null
No

fix: drawer content ref returns null

---

.changeset/smooth-comics-sing.md
packages/tooltip/src/tooltip.tsx

Update JSDoc link in Tooltip component to go the correct link. The current link is broken.
Clicking on JSDoc link directs to broken link
Clicking on JSDoc link directs to correct link
No

fix: broken link in tooltip js-doc

---

.changeset/grumpy-trains-change.md
tooling/cli/package.json

Closes #5219
Fixed an error where the cli fails when prettier is not installed.
If the package prettier is not found the std.err will be polluted and the cli fails.
~~Added token scales `blur`, `borderStyles` and `borderWidths`.~~
Removed the optional prettier run and prettified the output itself.
No

fix(cli): add missing prettier dependency

---

.changeset/silly-bees-build.md
tooling/cli/src/command/tokens/config.ts

Added token scales blur, borderStyles and borderWidths to cli tokens command
No TypeScript types are generated for those scales.
Types are generated
No

feat(cli): add token scales `blur`, `borderStyles` and `borderWidths`

---

.changeset/olive-lemons-lay.md
packages/radio/src/use-radio.ts

> "The `aria-describedby` attribute is used to indicate the IDs of the elements that describe the object. It is used to establish a relationship between widgets or groups and text that described them." ([reference](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-describedby_attribute))
- In order to improve accessibility, the radio element needs to follow the convention described by **MDN Web Docs** and to have the attribute "_aria-describedby_".
```js
<Radio aria-describedby="label_id">Hello</Radio>
```
`aria-describedby` is not in the list of the props allowed for `<input>` defined by [`getInputProps()`](https://github.com/SamHecquet/chakra-ui/blob/main/packages/radio/src/use-radio.ts#L200) so adding this prop when using `<Radio>` ends up …

fix(radio): add aria-describedby to improve accessibility

---

.changeset/empty-tools-smash.md
packages/system/src/system.types.tsx
tooling/cli/src/command/tokens/create-theme-typings-interface.ts
tooling/cli/src/command/tokens/extract-component-types.ts
tooling/cli/src/command/tokens/extract-property-paths.ts
tooling/cli/src/command/tokens/index.ts
tooling/cli/src/index.ts
tooling/cli/src/scripts/read-theme-file.worker.ts
tooling/cli/test/extract-property-paths.test.ts
tooling/cli/test/theme-typings.test.ts

Closes #5153
The type for variants and sizes are hardcoded as loose types:
```tsx
<Button variant="abc" /> // valid type but not available in the theme
```
```tsx
<Button variant="abc" /> // invalid
```  
```bash
chakra-cli tokens --strict-component-types
```
will generate following types:
```ts
export interface ThemeTypings {
// ...
components: {
Button: {
sizes: "sm" | "md" | "lg"
variants: "solid" | "outline" | "ghost"
}
}
}
```
No, because of opt in.
This PR could have a follow up to expand the strict mode to the theme tokens as well.

feat(cli): generate strict theme variant and size types

---

tooling/cli/src/utils/format-with-prettier.ts
tooling/cli/test/format-with-prettier.test.ts

Follow up PR to #5225
Closes #5219
Prettier is used to format the TS interface created by the `chakra-cli tokens` command.
Prettier was required during runtime, and if it was not available it should be skipped. 
This breaks the node worker script setup.
Added prettier as dependency (previous PR) and import prettier the "normal" way.
No

fix(cli): replace runtime require of prettier with import

---

.changeset/seven-berries-invent.md
packages/theme/src/components/form-error.ts

Closes #5294
There is a content shift due different `lineHeight` of FormError and FormHelper
`lineHeight` is not set for FormError
`lineHeight` is set to `"normal"`
No

fix(form-error): unify lineHeight for FormError and FormHelper

---

.changeset/olive-planes-think.md
packages/menu/src/menu.tsx
packages/menu/src/use-menu.ts

Closes #4935
Omit `disabled` and `aria-disabled` from type `MenuItemProps`. They will be overridden by `useClickable`.
```tsx
<MenuItemProps disabled /> 
// No error, but prop won't be proxied to DOM element
```
```tsx
<MenuItemProps disabled /> 
// TS error
```
No, it'll catch bugs.

fix(menu): omit is is-disabled props from MenuItemProps

---

.changeset/twelve-papayas-judge.md
packages/theme/src/components/modal.ts

Closes #4903
`<Modal size="full">` is currently not completely visible on iOS.
Footer is missing
Use `@supports(min-height: -webkit-fill-available)` query to apply the correct height.
No
Really looking forward to [Dynamic Viewport Units](https://css-tricks.com/the-large-small-and-dynamic-viewports/)

fix(modal): show footer with size=full

---

.changeset/unlucky-mugs-jump.md
packages/media-query/src/use-breakpoint.ts
packages/media-query/tests/use-breakpoint-value-ssr.test.tsx
packages/media-query/tests/use-breakpoint-value.test.tsx

If `env.window.matchMedia` is available when the hook mounts, use it to find the initial state. This prevents the value changing the next "tick" after the hook mounts, often causing layout changes that look like flashes on the screen.
I am having trouble with the tests, the SSR test suite doesn't mock matchMedia, but it seems to be "working" and matching the "sm" breakpoint. In SSR it should return the default breakpoint as I have tested for `env.window.matchMedia`.
Addresses #4251
Even though `defaultBreakpoint` was added, the essential problem of an incorrect first value is still present.
When useBreakpoint mounts, its first returned value is `defaultBreakpoint` or `undefined`, even when `window.matchMedia` is available.
When `window.matchMedia` is available, the first returned value is …

fix: #4251 layout flashing from useBreakpoint

---

.changeset/old-pigs-flow.md
packages/checkbox/src/use-checkbox.ts

Closes #4596
related issue is in the React library.see https://github.com/facebook/react/issues/9142
If it is disabled, then remove disabled.The focused style cannot be removed
Once disabled, focus styles are removed
no
Since the switch is not isLoading, I use isDisabled instead.It would be nice if you could add isLoading to the switch

fix(checkbox): remove focus styles when disabled

---

.changeset/green-news-boil.md
packages/avatar/src/avatar.tsx
packages/avatar/stories/avatar.stories.tsx

Closes #5256
Avatar Img didn't use the srcSet attribute when we passed.
srcSet prop passed in Avatar is not used.
Added srcSet prop passed in Avatar to use in AvatarImg.
No

fix(avatar): use srcSet attr

---

.changeset/itchy-singers-behave.md
packages/layout/src/grid.tsx
packages/layout/stories/grid.stories.tsx
packages/layout/stories/simple-grid.stories.tsx

Allows for usage of GridItem's that have named template areas to be used in conjunction with a Grid that has a defined template area.
This matches the usage pattern of a grid container and its children using grid template areas.
Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas
Currently `GridItem` doesn't have an `area` prop which means we cannot have a `Grid` that defines a grid template area to contain `GridItems` with a named grid area. The `area` prop is currently defined on `Grid` so the following works but is not semantically correct:
```
<Grid templateAreas='"one two three"'>
<Grid area='one'>one</Grid>
<Grid area='two'>two</Grid>
<Grid area='three'>three</Grid>
</Grid>
```
Have moved the `area` prop from `Grid` to `GridItem` so the following is now …

fix(grid): move `area` prop from Grid to GridItem

---

.changeset/cyan-drinks-jump.md
packages/modal/src/drawer.tsx

Closes #5334
Update `DrawerProps` type to include `ThemingProps` for the Drawer component
Type `DrawerProps` extends `ModalProps` and inherits the size and variant typings.
DrawerProps is now extending the `ThemingProps<'Drawer'>` explicitly.
No

fix(drawer): add ThemingProps type

---

.changeset/modern-wombats-march.md
packages/system/src/system.types.tsx

Closes #5324
This PR fixes a regression introduced with #5243
In some types and function definition TS throws an error like: 
```
Types of property 'variant' are incompatible.
Type 'string' is not assignable to type 'never'.
```
Updated the generic fallback type.
No

fix: loosen ThemingProps type

---

.changeset/red-lamps-clap.md
packages/styled-system/src/pseudos.ts

Fixes `_placeholderShown` selector. https://caniuse.com/css-placeholder-shown
`&::placeholder-shown`
`&:placeholder-shown`
No

fix: update placeholder shown selector

---

.changeset/moody-icons-shake.md
tooling/cli/README.md

The default placement of types is now a different spot than earlier.
Closes # 
> The suggested path in the readme did not work with the latest of Chakra UI. This PR just updates the text.

Change the placement of the default --out option

---

.changeset/spotty-pandas-hide.md
packages/system/src/system.types.tsx

Updated type `ThemingProps` to allow string values for the props `variant` and `size` even on components which are not in the default theme.
Components which are not in the default chakra theme are not allowed to have a variant or size prop.
```tsx
<Text variant="impressive" />
//                          ^- impressive is not assignable to `undefined`
```
`string` values are allowed
```tsx
<Text variant="impressive" />
//  works
```
No

feat: allow ThemingProps variant and size for non theme components

---

.changeset/popular-monkeys-matter.md
packages/slider/src/use-range-slider.ts

Closes #5346 
As per the discussion in #5081 , the index value needs to be updated for the range-slider.
No

fix: index issue with range slider

---

.changeset/real-socks-rest.md
packages/theme-tools/src/component.ts

I noticed that the types `StyleConfig` and `MultiStyleConfig` do currently not allow style functions for their properties even though they are supported as stated in the [docs](https://chakra-ui.com/docs/theming/advanced). So I just took the existing types for the style functions and added them as possible options to `StyleConfig` and `MultiStyleConfig`.
The types `StyleConfig` and `MultiStyleConfig` only allow style objects for their properties right now. These types are therefore too strict as style functions (`(options: StyleOptions) => StyleObject`) are also allowed here.
The new types for `StyleConfig` and `MultiStyleConfig` are including `SystemStyleFunction` and `PartsStyleFunction` as possible options for their properties, so that the types are reflecting the actual possibilities …

chore: include functions in style config types

---

.changeset/short-bananas-decide.md
packages/checkbox/src/use-checkbox.ts

Added a `CheckboxState` type as the return type of the state returned by the `useCheckbox` hook.
Old return type:
New return type:
Added type:
No
While working on the documentation of the `useCheckbox` hooks in [the docs repo](https://github.com/chakra-ui/chakra-ui-docs/issues/72) I figured out it would be easier to use the hook and to document it if the returned state had its own type. Thus I added a type for the state returned from the`useCheckbox` hook

feat: add type for state returned by useCheckbox

---

.changeset/popular-jars-know.md
packages/theme/src/components/index.ts
packages/theme/src/index.ts

Remove more than half the code by using more modern syntax.
> Came across a unnecessarily bloated way of re-exporting default exports. This change simplifies it a bit.
Nope.
Totally understand if this is a stylistic choice, so if you don't want it, just close my PR, no feelings will be hurt.

refactoring(theme): Simplify exports

---

packages/layout/stories/text.stories.tsx

The current CI workflow for type checking is failing after merging #5355 
Lint checks are failing in the PR workflow due to an unnecessary TypeScript comment in the `Text` component stories.
Removes the TypeScript comment that fails linting checks.
No

chore: fix typing comments in Text stories

---

.changeset/tender-forks-grow.md
packages/theme/components/package.json
packages/theme/foundations/blur/package.json
packages/theme/foundations/borders/package.json
packages/theme/foundations/breakpoints/package.json
packages/theme/foundations/colors/package.json
packages/theme/foundations/package.json
packages/theme/foundations/radius/package.json
packages/theme/foundations/shadows/package.json
packages/theme/foundations/sizes/package.json
packages/theme/foundations/spacing/package.json
packages/theme/foundations/transition/package.json
packages/theme/foundations/typography/package.json
packages/theme/foundations/z-index/package.json
packages/theme/package.json

This PR creates entry points for the theme object to help non-`@chakra-ui/react` users consume parts of the theme without the overhead of our large theme object.
When I say non-`@chakra-ui/react`, I mean users who use `@chakra-ui/system` or even `@chakra-ui/styled-system` directly to build their internal design systems.
No

feat: add entrypoints for theme parts

---

.changeset/little-melons-sell.md
packages/hooks/src/use-const.ts
packages/hooks/tests/use-const.test.tsx

Closes #5444
Fixes TypeScript definitions for the `useConst` hook when using the init function such as:
```ts
const a: string = useConst(() => 'bar');
```
```
// Type '() => "bar"' is not assignable to type 'string'.ts(2322)
const a: string = useConst(() => 'bar');
```
No

fix: useConst ts issue

---

.github/workflows/pr.yml

An improvement to our PR workflow. At the moment, we create an NPM snapshot each time a PR is made to make it easier to test features/fixes in a local project.
This workflow step fails if the PR author is not a member of the Chakra UI org since it needs access to the NPM_TOKEN. This PR updates the workflow step to skip the workflow if the author is not a member.

ci: skip pr publish step if actor is not org member

---

.changeset/great-days-yawn.md
packages/system/src/providers.tsx

Extract the hoisting of CSS variable to its own component to allow rehoisting.
Inline Code
Render `<CSSVars cssVarsRoot=".my-css-selector" />` to attach CSS variables.
No

feat: add CSSVars component

---

.changeset/wise-donuts-grow.md
packages/button/src/button-spinner.tsx
packages/button/src/button.tsx

Closes #5056 
> iconSpacing got removed from spinner as part of this [pull request](https://github.com/chakra-ui/chakra-ui/pull/3732)
> Spinner has hardcoded spacing of **0.5**
> passing iconSpace to spinner and using it for spacing
No

fix(button): use iconSpacing for ButtonSpinner

---

.changeset/tiny-knives-hang.md
packages/color-mode/src/color-mode-script.tsx

Closes #5453
The ColorModeScript tries to evaluate `root` but it is not present in the closure.
Remove access to out of scope variable.
Replaced with duplicate code
No

fix: respect the closure of the color mode script

---

.changeset/six-bags-bake.md
tooling/cli/src/command/tokens/extract-property-paths.ts

Closes #5457
I would be happy if the scan depth for non-color tokens in Chakras CLI script for generating typings could be increased from one.
Currently, the chakra CLI tool scans theme variables and generates typings for them, by scanning for a depth of up to 3 for color variables, but only up to one for everything else. This means that a color with the token name "general.brand.default" would be found, but "general.brand.default.subprop" not. However, in our project we also use nested font sizes and font weights, e.g. "body.small" is one of the font size values. If the CLI tool would scan that as well, it would help us by providing better typings.
Default scan depth increased to 3.
No

Increase scan depth for Chakra CLI on non-color tokens

---

packages/tooltip/README.md

Rephrases the documentation for the Tooltip component to explain why Chakra wraps the Tooltip in a `span` if no React element is passed to `children`.
The documentation sentence structure is slightly difficult to follow:
> [If the `children` of Tooltip is a string, we wrap with in a `span` with `tabIndex` set to 0, to ensure it meets the accessibility requirements.](https://chakra-ui.com/docs/overlay/tooltip#usage)
Rewords the documentation to abstract the implementation details for how Chakra makes a Tooltip accessible:
> If the `children` of Tooltip is a string, it will be wrapped with a focusable `span` element to ensure the Tooltip meets accessibility requirements.
No

docs(tooltip): rephrase usage when no React element is passed as children

---

packages/descendant/src/descendant.ts
packages/descendant/src/use-descendant.ts

Closes #5317 
> Enable property access via index
>  Strict type checking with "noPropertyAccessFromIndexSignature": true enables accessing a field via the “dot” (obj.key) syntax, and “indexed” (obj["key"]) .Property is accessed via the "dot"(obj.key) syntax
>Since the Property 'index' comes from an index signature, it is now accessed with ['index']
No

fix(descendant): enable property access via index

---

.changeset/twelve-dots-sip.md
packages/accordion/package.json
packages/anatomy/package.json
packages/skeleton/package.json
packages/switch/package.json

This PR fixes the [implicit transitive peer dependency](https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0) warnings that appear when installing `@chakra-ui/react` with Yarn 2+.
When installing `@chakra-ui/react` with Yarn 2+ these warnings are listed:
```
➤ YN0002: │ @chakra-ui/accordion@npm:1.4.3 [12ba7] doesn't provide framer-motion (p0709a), requested by @chakra-ui/transition
➤ YN0002: │ @chakra-ui/anatomy@npm:1.2.1 doesn't provide @chakra-ui/system (p2ef3e), requested by @chakra-ui/theme-tools
➤ YN0002: │ @chakra-ui/skeleton@npm:1.2.5 [12ba7] doesn't provide @chakra-ui/theme (pd5fa7), requested by @chakra-ui/media-query
➤ YN0002: │ @chakra-ui/skeleton@npm:1.2.5 [12ba7] doesn't provide @emotion/react (p4535b), requested by @chakra-ui/system
➤ YN0002: │ …
```

fix: add missing peer dependencies

---

.changeset/pretty-beans-reply.md
packages/accordion/package.json
packages/checkbox/package.json
packages/menu/package.json
packages/modal/package.json
packages/popover/package.json
packages/react/package.json
packages/switch/package.json
packages/toast/package.json
packages/tooltip/package.json
packages/transition/package.json

Closes #5483 
Updated the list of valid versions for framer motion as peerDependency to include v6
List of peerDependencies was including v3, v4 and v5
List of peerDependencies was including v3, v4, v5 and v6
No

chore: allow framer motion v6

---

.changeset/dirty-ravens-drum.md
.changeset/modern-parents-raise.md
tooling/cli/package.json

cli package has a dependency to /utils@^1.10.0 which is not a `latest` release. See [npmjs.org](https://www.npmjs.com/package/@chakra-ui/utils)
You can end up with multiple installed chakra versions.
Replaced with `^1.9.1`
No

fix(cli): use latest pkg version of /utils

---

.changeset/sweet-adults-refuse.md
packages/system/src/system.types.tsx
packages/system/tests/forward-ref.test.tsx

Closes #5194  
Disallow props from outside the prop interface
// This should throw a type error
<Chakra.Button test/>
// Now it does!
<Chakra.Button test/>
Possibly... but in a good way.  If people have been passing invalid props to their components, now there will be type-safety around it.

fix(TS): #5194 Disallow props from outside the prop interface

---

.changeset/thirty-swans-shave.md
packages/form-control/src/form-control.tsx

This is a very simple change that just drops a line of code that is basically a "noop" here.

Remove redundant `useMemo` from `FormControl`

---

.changeset/soft-countries-sin.md
packages/checkbox/src/use-checkbox-group.ts
packages/checkbox/stories/checkbox.stories.tsx
packages/checkbox/tests/checkbox.test.tsx
packages/utils/src/array.ts

Closes #5501
When using the `useCheckboxGroup` hook with numbers instead of strings the checkboxes aren't reflecting the changes. I noticed the issue in two places:
- `use-checkbox-group.ts` on line 89: the `values` array may contain both string and number values. The comparison doesn't take that into account. Instead of `includes`, which relies on the type as well, I replaced it with `value.some((val) => String(props.value) === String(val))`, so that both strings and numbers can be taken into an account.
- `use-checkbox-group.ts` on line 70: I replaced the `remove` method with a local `filter` that compares the string values for the same reason.
The checkboxes don't reflect the changes.
The checkboxes do reflect the changes.
No (hopefully)
I've also added an additional example in the …

fix(useCheckboxGroup): fixing the issue when using the useCheckboxGroup hook with numbers

---

.changeset/shy-cobras-wonder.md
tooling/cli/src/command/tokens/index.ts

Closes #5523
This PR adds a `process.exit(1)` call to the `try`/`catch` of `generateThemeTypings`.
Process exits with a success (`0`) status code in all cases.
Process exits with an "Uncaught Fatal Exception" (`1`) when `generateThemeTypings` fails.
No

fix(cli): add failure exit code

---

.changeset/chilled-pugs-wink.md
packages/input/src/input.tsx
packages/input/stories/input.stories.tsx
packages/input/tests/input.test.tsx

Closes #5489 
Add htmlSize prop to enable the usage of the native size prop and to resolve the conflict with the input theme prop size.
The native input size prop can't be used because it gets overriden by the input theme prop size.
There is a new htmlSize prop to pass the native size prop to an input.
No
Added Storybook story to test the behaviour with the native size prop

fix: resolve native input size prop conflict with input theme props

---

.changeset/chilly-boxes-kick.md
packages/media-query/src/use-media-query.ts

Closes # 
#5467 and #5197
Support useMediaQuery for older browsers. Conditionally check if the
MediaQueryList object supports the addEventListener() method, else fallback to
the legacy .addListener() method.
Website crashes on Safari browsers < v13
the method `addListener()` is used instead of `addEventListener()`
No

fix(use-media-query): conditional check if addEventListener is supported

---

packages/tooltip/src/tooltip.tsx

Closes #5283
Fix an issue where arrow tooltip background color only consider `bg` props.
Currently `Tooltip` only consider `bg` props.
While, in this PR, I try to add some additional bg props to be considered while customize the arrow background color.
No.

fix(tooltip): add some background props for options to style arrow bg

---

.changeset/five-tables-warn.md
packages/input/src/input-element.tsx

This commit makes it possible to style input elements from the theme files.
You can style both the input field and the input addon components from the theme config. However, that wasn't possible with the current solution. 
This pull request applies any styling scoped under the `element` part.
Previously, when you added styles to the theme config with the `element` part name, they were ignored. 
With this change, those styles will be applied in the same way done in the addon component.
Nope, this should not impact any existing code.

Apply theme styles for input element

---

.changeset/breezy-dogs-sniff.md
packages/media-query/src/media-query.tsx

Closes #5573 
The `Show` / `Hide` components don't have descriptions set for their props.
The `Show` / `Hide` components don't have descriptions set for their props.
The `Show` / `Hide` components now have descriptions set for their props, and the `props-docs` package is ready to be regenerated.
No

docs(show-hide): adding props descriptions to Show / Hide components

---

.changeset/yellow-baboons-hang.md
packages/tag/src/tag.tsx

Closes #5587 
Change order of aria-label prop on TagCloseButton to be overwritable
aria-label of TagCloseButton can not be overwritten
aria-label of TagCloseButton can be overwritten
No

fix: not overwritable aria label prop on TagCloseButton

---

.changeset/fair-clocks-thank.md
packages/checkbox/package.json
packages/checkbox/src/use-checkbox.ts
packages/checkbox/stories/checkbox.stories.tsx
packages/checkbox/tests/checkbox.test.tsx
packages/switch/stories/switch.stories.tsx
packages/switch/tests/switch.test.tsx

Closes #4629
This is an alternative to #4643. Instead of using `useFormControlProps` inside the checkbox component. I use it inside the `useCheckbox` hook. This way all implementations (Checkbox, Switch) benefit from it.
Checkbox and Switch now support FormControl
No

fix(use-checkbox): add form-control support to use-checkbox

---

.changeset/young-poems-serve.md
packages/accordion/src/accordion.tsx
packages/accordion/stories/accordion.stories.tsx
packages/anatomy/src/index.ts
packages/theme/src/components/accordion.ts

closes #5593 
Updated style config for `Accordion`
This change introduces `styles.root` for `Accordion`
No

fix(accordion):  introduce `styles.root` for `Accordion`

---

CONTRIBUTING.md

No issue; prompted by https://github.com/chakra-ui/chakra-ui/pull/5571
Recent changes to entry points have caused the storybook build to be
inadequate resulting in errors like
`Can't resolve '@chakra-ui/hooks/use-animation-state'`.
Following the instructions for running storybook results in a failed build.
The instructions reflect the current requirements for running storybook
No
Is this accurate? Or does `yarn build` only need to be run once when changing branches (and then you just need `yarn preconstruct` + `yarn storybook` to get SB running)?

chore: update storybook instructions

---

.changeset/wicked-turkeys-travel.md
packages/media-query/src/use-breakpoint-value.ts
packages/media-query/stories/media-query.stories.tsx
packages/skeleton/tests/skeleton.test.tsx
packages/skeleton/tests/test-data.ts

Closes #5555
Followup PR for the `useBreakpoint` fix in #5576.
```
extendTheme({ breakpoints: { preSm: "28em", postSm: "36em" } })
// ...
const isMobile = useBreakpointValue({ base: true, lg: false });
```
resulted in `isMobile` to be:
base (true) - preSm (false) - sm (true) - postSm (false) - md (false) ...
base (true) - preSm (true) - sm (true) - postSm (true) - md (false) ...
No
The chakra theme holds enhanced breakpoint details in `theme.__breakpoints` for **internal** use only!

fix: use sorted breakpoints in useBreakpointValue

---

.changeset/nervous-plums-own.md
packages/modal/src/use-modal.ts
packages/modal/tests/use-modal.test.tsx

Fix `useAriaHidden` deps.
Currently, the `useInert` of `Modal` is not working because `useAriaHidden` is not triggered correctly.
`useAriaHidden` will be triggered correctly and the target elements will be given the `aria-hidden` attribute.
No

fix: fix useAriaHidden deps

---

.changeset/grumpy-moons-look.md
packages/styled-system/src/index.ts
packages/styled-system/src/theme.types.ts
packages/styled-system/src/theming.types.ts
packages/styled-system/src/utils/types.ts

Here I'm following up on a previous idea I had mentioned [in this PR](https://github.com/chakra-ui/chakra-ui/pull/4067#pullrequestreview-666149028). The TypeScript experience when distributing a component library based on Chakra still isn't _great_ on account of the Chakra CLI step being required for consumers to the library to get the proper language server/editor experience. Not only is it an extra step, but there are multiple ways in which it can break preventing consumers of our library from getting accurate type definitions.
In this PR, I'm proposing a small change to the way that these custom types are defined that both allow the existing CLI functionality to continue working exactly as it had previously, but also providing an optional advanced feature that would allow custom type …

Support for custom theme types via TypeScript module augmentation

---

.changeset/thick-swans-attend.md
packages/media-query/src/use-breakpoint-value.ts
packages/media-query/src/use-breakpoint.ts
packages/media-query/tests/test-data.ts
packages/media-query/tests/use-breakpoint-value-ssr.test.tsx
packages/media-query/tests/use-breakpoint-value.test.tsx

Closes #5506
Based on PR #5638 💖  thanks to @ishowta
Ensure first render consistency in SSR+CSR environments.
The PR #5234 introduced the side effect of mismatching SSR+CSR renders.
This was not fixed by my previous PR #5576.
To ensure the render consistency on the server and client I reordered the priority of the parameter `defaultBreakpoint` for `useBreakpoint`.
If a `defaultValue` is set, it has priority over `window.matchMedia`. 
The hook `useBreakpointValue` uses now a default value for `defaultBreakpoint` (`base`) to make use of this priority change.
No

fix: first render consistency of useBreakpointValue in SSR+CSR envs

---

.changeset/nine-cars-sneeze.md
packages/layout/src/link-box.tsx

Closes #5630 
Fixed an issue regarding the zIndex of the LinkOverlay in LinkBox.
Content outside the LinkOverlay can not be clicked when having an opacity below 1.\
Codesandbox from the issue: https://codesandbox.io/s/laughing-sun-q1qjmw?file=/src/index.tsx
Content outside the LinkOverlay can be clicked when having an opacity below 1.
Codesandbox with an override of the changed zIndex of this PR: https://codesandbox.io/s/elegant-varahamihira-9zuwk6?file=/src/index.tsx
No

fix: conflicting zindex of linkoverlay with opacity

---

.changeset/poor-llamas-obey.md
packages/color-mode/src/color-mode-script.tsx

This PR adds a runtime safeguard to `ColorModeScript` since there's no need for the values to be dynamic and it's creating a `script` with `dangerouslySetInnerHTML`.
The `initialColorMode` passed to `ColorModeScript` is currently only guarded via TypeScript typing. Setting `initialColorMode` to evil values like `(() => { console.log('hello'); return 'light'; })()` is possible.
This security issue is obviously far fetched but it is nevertheless there, and made worst since `ColorModeScript` obscures the fact that it's using `dangerouslySetInnerHTML`. 
Adds hardening to `ColorModeScript` by runtime checking for three specific color mode values: `dark`, `light` and `system`.
No

fix: add color mode script runtime safeguard

---

.changeset/beige-poems-fold.md
.changeset/modern-dryers-kiss.md
.changeset/proud-camels-dream.md
packages/anatomy/src/index.ts
packages/editable/src/editable.tsx
packages/editable/src/use-editable.ts
packages/editable/stories/editable.stories.tsx
packages/editable/tests/editableTextarea.test.tsx
packages/theme/src/components/editable.ts

Editable textarea element to handle multi-line input within editable context. 
Closes #1622 
>  Add EditableTextare element to handle multiline input with editable context
> new line input is possible with editable context.
```typescript
// editable/src/use-editable.ts
...
const [value, setValue] = useControllableState({
defaultValue: defaultValue || "",
value: valueProp,
onChange: onChangeProp,
})
...
const inputRef = useRef<HTMLInputElement | HTMLTextAreaElement>(null)
```
Because the editable context has one controllable state as default, 
use union type for input to maintain compatibility with the above condition.
Despite of the similarity of `editable.test.tsx` and `editableTextarea.test.tsx`, which is the test file in `editable pakage`,
I choose to split test suite to minimize lines …

feat(editable): add editable textarea element

---

.changeset/lemon-jobs-impress.md
tooling/cli/src/command/tokens/create-theme-typings-interface.ts
tooling/cli/test/theme-typings.test.ts

Closes #5585
The CLI tokens command now includes semantic tokens in the generated ThemeTypings
ThemeTypings only included "normal" tokens.
CLI scans `theme.semanticTokens` too.
No

feat(cli): include semantic tokens in generated theme typings

---

.changeset/brave-emus-mate.md
packages/tabs/src/use-tabs.ts
packages/tabs/stories/tabs.stories.tsx

Closes (https://github.com/chakra-ui/chakra-ui/issues/5664)
Add "width" to the list of transitionProperties of the TabIndicator to prevent the background from overlapping adjacent tabs. This issue occurs when one tab's width is larger than the other tabs.
The transition behavior when the selected tab changes.
Including "width" as a transition property of the TabIndicator prevents any overlapping when the selected tab changes (assuming the tabs differ in width so the issue shows itself)
No
Example of the issue:
https://codesandbox.io/s/pedantic-dawn-ds3hfu?file=/src/index.tsx
I did not include a test since the nature of the issue is more visual/timing related -- it seemed hard to create a test to capture that.

fix(TabIndicator): avoid bg flash when long tab text 

---

.changeset/modern-snails-remember.md
packages/styled-system/src/config/text-decoration.ts

Closes #5592 
added the type number for textUnderlineOffset property of TextDecorationProps.
When using the Heading component and passing property textUnderlineOffset with a numerical value. typescript doesn't allow you to use a numerical value to it and shows error.
When using the Heading component and passing property textUnderlineOffset with a numerical value. Typescript doesn't allow you to use a numerical value to it.
it throws error : `Type error: Type '6' is not assignable to type 'ResponsiveValue<TextUnderlineOffset<0 | (string & {})>>'`.
with these changes, it is possible to pass numerical values to the textUnderlineOffset property for the Heading component, it won't throw any typescript error 
No

fix: Added type number for text underline offset

---

.changeset/nasty-lobsters-hope.md
packages/toast/src/use-toast.tsx

Closes #5692
spreading `defaultOptions`  aswell as `option` to `createStandaloneToast` when passing `options` to `useToast` 
No

fix(toast): #5692 provide default options when passing options to useToast

---

.changeset/happy-ads-confess.md
packages/layout/src/link-box.tsx

Closes #5673 
This fixes a problem that buttons are no longer clickable within a `LinkBox` with a `LinkOverlay`  because of the zIndex. This is a result of the changes of https://github.com/chakra-ui/chakra-ui/pull/5632.
Buttons are not clickable if they are within a `LinkBox` with a `LinkOverlay`, see e.g. the CSB from the issue: https://codesandbox.io/s/bold-leaf-rhjbxj?file=/src/index.tsx
Buttons are clickable again, this should represent the fix: https://codesandbox.io/s/stoic-glitter-9em593
No
It worked also with `zIndex: 1` on Firefox 97.0 and Chromium 99.0.4844.51 but it feels wrong so that I set it to 2 to avoid unexpected behavior on other browsers/versions.

fix: buttons zIndex in linkbox with usage of link overlay

---

.changeset/loud-crews-help.md
packages/layout/src/link.tsx

Closes #4243
Remove `noreferrer` attribute from `<Link isExternal />` as described in the linked issue

fix: remove no referrer

---

.changeset/chilly-files-argue.md
packages/checkbox/src/checkbox.tsx
packages/radio/src/radio.tsx

Closes #5454
Add support for forwarding props to the underlying `input` component in the `Radio` and `Checkbox` components.
I think these components should get major refactoring in v2. We're doing quite a number of implicit work and we can avoid if we used the compound component pattern.

fix: add support for input props in radio and checkbox

---

.changeset/twenty-plants-burn.md
packages/modal/src/modal.tsx

Closes # 
> add `onCloseComplete` prop to Modal, it  from support provided by AnimatePresence。
> I can't do something after the Modal close animation is over
> I can do something after the Modal close animation is over
NO

feat(modal): add onCloseComplete prop to Modal

---

.changeset/tall-candles-deny.md
packages/radio/src/use-radio.ts

No Issue
This PR adds a type for the state returned by the `use-radio` hook. The purpose of this is to improve documentation and readability. Also in this Pr 
This was the returned type:
The new type:
No
-

refactor: add type for `use-radio` returned state

---

.changeset/quiet-items-eat.md
packages/editable/src/use-editable.ts
packages/editable/stories/editable.stories.tsx
packages/editable/tests/editable.test.tsx
packages/editable/tests/editableTextarea.test.tsx

Closes #5758
Fix issue where editable preview remains interactive even when `isDisabled: true` is passed.
Switches to edit mode because `tabindex: 0` is still set on it

fix: disabled state in editable

---

.changeset/spicy-dolphins-tickle.md
packages/hooks/src/use-boolean.ts

This allows us to use it in hook deps:
```js
const [flag, setFlag] = useBoolean();
useEffect(() => {}, [setFlag]);
```

fix: memoize switch object in useBoolean

---

.changeset/plenty-mails-juggle.md
packages/menu/src/menu.tsx
packages/menu/src/use-menu.ts
packages/menu/tests/menu.test.tsx

Closes #5462
Fix issue where menu items cannot type `type=submit`

fix: allow use-menu to specify button type

---

.changeset/wet-rules-speak.md
packages/checkbox/src/checkbox.tsx
packages/theme/src/components/checkbox.ts
packages/theme/src/components/radio.ts

Previously, the cursor was **not** set to `not-allowed` when a `Radio` was disabled
This is now fixed by updating and reusing the `Checkbox` base style
No
By moving the cursor style to the `container` part, we are now sure that the whole component will inherit from it

fix: add cursor not-allowed for disabled checkbox and radio

---

.changeset/ten-turkeys-drop.md
packages/layout/README.md
packages/layout/src/wrap.tsx
packages/layout/stories/wrap.stories.tsx

* Adds the option to specify vertical and horizontal spacing options for the `<Wrap>` component, should the user choose. 
* Falls back to the `spacing` prop for defaults or to set both h and v at the same time.
* Also fixes the code example of Wrap in the layout package.
The Wrap component adds the `spacing` prop to both horizontal and vertical margins, with no opportunity for the user to specify anything else.
Users can optionally specify `hSpacing` and/or `vSpacing` to choose a specific margin for that axis.
Example:
```jsx
<Wrap vSpacing={0} hSpacing={['8px', '12px', '24px']}>
<Box/>
<Box/>
<Box/>
<Box/>
</Wrap>
```
No, intentionally made backwards compatible.
Happy to rename if this prop naming is not preferred.
I recognize that there could be room for improvements on `spacing`-only …

feat(wrap): separate x and y margins

---

.changeset/sharp-crews-wave.md
packages/form-control/src/form-label.tsx
packages/form-control/tests/form-control.test.tsx

Added `optionalIndicator` to `FormLabel` to provide a way to signalize if a field is optional
Currently, we only show `<RequiredIndicator/>` if a field is `required` to do the same for the inverse side the `Indicator has to be passed to the `children`
made `optionalIndicator` a prop which can be passed to `<FormLabel/>` with default value `null` which renders if the field is not required.

feat(form-control): add optional indicator for `FormLabel`

---

README.md

> Fixed the Browser Stack Logo in README, apparently, the previous logo was removed from marker.io, so I used imgur.
> ![image](https://user-images.githubusercontent.com/68690233/161872126-672f26c1-d54f-4e34-966f-2a9b218cf9e6.png)
> The image alt text is displayed.
> ![image](https://user-images.githubusercontent.com/68690233/161872174-cb324e15-5e79-4f96-9603-9ed8d2c24f13.png)
> Logo is displayed.
> ![image](https://user-images.githubusercontent.com/68690233/161872266-ccc040c4-f97a-4467-b8fe-0660727aa476.png)
No.

fix(README): add new browser stack icon

---

.changeset/young-items-return.md
packages/transition/src/collapse.tsx

Closes #5778
Fix intermittent Collapse component overflow initial/hidden issue.
Collapse component sometimes doesn't collapse.
Collapse component always collapses.
No
Read: https://github.com/chakra-ui/chakra-ui/issues/5778
This is my first PR here—please let me know if I'm doing anything wrong!

fix(collapse): #5778 remove explicit overflow hidden/initial on exit/enter animation

---

.changeset/forty-plums-attend.md
packages/toast/package.json
packages/toast/src/index.ts
packages/toast/src/toast.component.tsx
packages/toast/src/toast.provider.tsx
packages/toast/src/toast.types.ts
packages/toast/stories/toast.stories.tsx
yarn.lock

This PR removes the dependency to @reach-ui/alert, because it is not compatible with React 18. 
It uses `ReactDOM.render` to announce the toast message.
According to this reach-ui PR https://github.com/reach/reach-ui/pull/906 it may not be necessary to reattach the message for a11y reasons.
The toast package wraps the toast message in Reach UIs Alert component.
This leads to a ReactDOM error:
> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
Replaced the Reach Alert with a div element with following properties:
```ts
<chakra.div 
role="status"
aria-live="polite" // do not interrupt current announcements …
```

chore(toast): remove dependency to @reach-ui/alert

---

.github/workflows/pr.yml

When creating a PR targeting the next branch our PR workflow is not getting started
PR workflow only runs on target main
PR workflow runs on target main and next
No

ci: run PR workflow on next branch as target

---

.changeset/polite-planets-travel.md
packages/button/src/button-group.tsx
packages/button/stories/button.stories.tsx
packages/button/tests/button-group.test.tsx
packages/theme/src/components/button.ts

Closes #4531
Collapse borders in outlined buttons inside `ButtonGroup` with `isAttached`.
Reinstates the behavior of https://github.com/chakra-ui/chakra-ui/pull/230
Currently the `ButtonGroup` requires manually adding `mr="-px"` to each outlined button when using `isAttached` to get rid of the double border.
`ButtonGroup` applies the negative margin automatically when using `isAttached` with `variant="outline"`
Before:
After:

fix(ButtonGroup): collapse borders with isAttached enabled

---

.changeset/strong-years-behave.md
packages/toast/src/use-toast.tsx

Closes #5868
The toast method of useToast is recreated on every render. 
toast is not memoized.
`React.useMemo` is used.
No

feat: memoize toast fn

---

.changeset/three-dogs-breathe.md
packages/media-query/src/use-breakpoint.ts
packages/media-query/src/use-media-query.ts
packages/media-query/tests/use-breakpoint-value-ssr.test.tsx

- Refactored the `useMediaQuery` hook to be more resilient and cross-browser
friendly.
- Add support for fallback values to `useMediaQuery` to help users provide SSR
friendly fallback when using width queries.

refactor: use-media query

---

.changeset/hungry-owls-matter.md
packages/editable/tests/editable-textarea.test.tsx
packages/env/src/env.tsx
packages/system/tests/style-config.test.tsx

Closes #5842
Chakra UI + React 18 currently throws when you use `Suspense` at any level. This is due to the `EnvironmentProvider` we use and how it updates the state.
To solve this, I wrapped the update in `startTransition`

fix: suspense and react-18

---

.changeset/quick-worms-retire.md
packages/popover/src/popover.tsx

Add a `reference` to popover close button, as it is already done in other component.
Using Popover component, I wanted to bring the focus on the `PopoverCloseButton`, using `initialFocusRef`.
However, as opposed to the `CloseButton` component, I do not have access to the reference. 
This led me to add a reference directly in the PopoverCloseButton component.

fix: add reference to popover close button

---

.changeset/pink-hotels-carry.md
packages/hooks/src/use-disclosure.ts

Closes #5939
This PR improves the accessibility of components using the `useDisclosure()` hook in tandem with `getButtonProps()` and `useDisclosureProps()`.
At the moment, the `getButtonProps()` function returned by the `useDisclosure()` hook returns a static `"aria-expanded": true` prop.
It now returns a dynamic `"aria-expanded": isOpen` to match the `useDisclosure` state.
No
See [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#buttons)

[useDisclosure] Return a dynamic "aria-expanded" value from getButtonProps #5939

---

packages/css-reset/src/css-reset.tsx

Closes #5575
This will need to be documented, but ultimately this allows users to override the automatic focus style overrides applied when using focus-visible.
The focus-visible documentation suggests adding a get-out like this, so Chakra really needs to give us one!
When using the focus-visible package, it is impossible to apply certain styles to certain focussed elements. For example, adding a shadow to a link when focussed is currently not possible.
By adding a special `data-` attribute, we allow developers to opt-out of this override in certain cases.
No
The focus-visible docs are slightly confusing on this. It says first:
> We suggest that users selectively disable the default focus style by selecting for the case when the polyfill is loaded and .focus-visible is not applied to the …

Allow opt-in for outline/shadow on focused elements

---

packages/hooks/src/use-outside-click.ts
packages/hooks/tests/use-outside-click.test.tsx

Closes #5837
I expect `useOutsideClick()` to respond to clicks anywhere on the page,     
but it was ignoring clicks outside `<body>`. There can be space below the   
end of the body for `<body>` elements who's height is less than the         
browsers height.                                                          
Now, we respond to events on document too. the test added in the prior    
commit now passes.                                                        
`useOutsideClick()` ignores clicks on `document`
`useOutsideClick()` responds to clicks on `document`
Not a breaking change.

fix: use-outside-click register clicks on document

---

.changeset/chatty-hornets-shake.md
packages/image/src/image.tsx
packages/image/src/use-image.ts
packages/image/stories/image.stories.tsx
packages/image/tests/use-image.test.tsx

Closes #5581 #5288
added fallback strategies to the image component
Currently unsure in a few points how to write a useful test for this since I'm not sure how to verify resource loads in jest
Also, not sure how to handle this specific case:
`fallbackStrategy==="onError" && Boolean(fallbackSrc) && status==="loading"`
In this case, I currently render `null` as `fallbackImage` which could lead to unexpected behaviour in the layout.
**The main problem is:** when `fallbackStrategy==='onError'` I want to load the `fallbackSrc` only if `status==='error'` therefor we don't have a resource to display when `status==='loading'`  
Possible Alternatives:
- render an `img` without the `src`-Attribute, but this doesn't comply to html5 standards since `src` is a required attribute`
- remove unnecessary …

feat(image): add imageFallbackStrategies

---

.changeset/empty-cats-sin.md
.changeset/rotten-zoos-train.md
packages/alert/src/alert.tsx
packages/toast/src/toast.tsx
packages/toast/src/use-toast.tsx
packages/toast/stories/toast.stories.tsx

Closes #5930
> Adds support for passing in custom icons into toasts. 
> we do not have a possibility to render custom icons on the toast element.
> The toasts elements will now render custom icons, if they are passed into their props. If there are no icons passed in, we will render the Default `<AlertIcon />` component. The icon is a React Node that will be passed into the component using the prop `icon`, which is `optional`.
No, this does not break anything instead adds a new feature.
This would be a great feature for devs who want to customise their toast's UI. So, I just need to know that if this feature will fit match UI perfectly.

feature: support for adding custom icons

---

.changeset/tender-pugs-sniff.md
package.json
packages/styled-system/package.json
yarn.lock

Closes #5714 
`Property.ColorAdjust` is replaced with `Property.PrintColorAdjust` in csstype 3.0.11 and type errors occur.
Update csstype to 3.0.11 or higher to fix this.
```ts
// menu/dist/declarations/src/use-menu.d.ts:480
colorAdjust?: import("csstype").Property.ColorAdjust | undefined;
// menu/dist/declarations/src/use-menu.d.ts:986
WebkitPrintColorAdjust?: import("csstype").Property.ColorAdjust | undefined;
```
```ts
// menu/dist/declarations/src/use-menu.d.ts:481
colorAdjust?: import("csstype").Property.PrintColorAdjust | undefined;
// menu/dist/declarations/src/use-menu.d.ts:993
WebkitPrintColorAdjust?: import("csstype").Property.PrintColorAdjust | undefined;
```
No
12212162f267ed34720e6482e5ffa8a7a21d4a7f cause errors because both 3.0.9 and 3.0.11 are present.
You need to install …

fix: update csstype and typings

---

packages/theme-tools/src/component.ts

Closes https://github.com/chakra-ui/chakra-ui/issues/5960
This PR increases the accuracy & safety of `mode()` arg/return types
Currently, using `mode()` returns `any`, which causes TypeScript ESLint to throw an unsafe assignment error:
```
Unsafe assignment of an `any` value. (@typescript-eslint/no-unsafe-assignment)
FILE  /Users/mc/Sites/saber/client/src/theme/global.ts:9:7
7 |   global: (props) => ({
8 |     '*, *::before, &::after': {
>  9 |       borderColor: mode('gray.300', 'whiteAlpha.300')(props),
|       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10 |     },
11 |   }),
12 | }
```
Looking at the value of `SystemStyleObject`, I believe the return value needs to be a string:
```ts
type CSSDefinition<D> = D | string | RecursiveCSSSelector<D | string>
export interface …
```

refactor: Fix unsafe any in theme tools mode()

---

.changeset/nervous-keys-look.md
packages/modal/src/alert-dialog.tsx

There was likely an oversight when creating the type definition for `AlertDialog`. `AlertDialogProps` requires the `leastDestructiveRef` property to be present, even though the property can be trivially set to `undefined`. This makes the property effectively optional, but the types don't (currently) allow this.
When creating a `AlertDialog` in a TS project, the elements requires the `leastDestructiveRef` property. However, the property can trivially be set to `undefined`.
```tsx
<AlertDialog
isOpen
onClose={() => { ... }}
leastDestructiveRef={undefined}
>
```
When creating a `AlertDialog` in a TS project, the `leastDestructiveRef` property is now optional and can be omitted.
```tsx
<AlertDialog
isOpen
onClose={() => { ... }}
>
```
The behavior is identical to setting `leastDestructiveRef` …

Make `leastDestructiveRef` property non-nullable

---

.changeset/modern-dogs-ring.md
packages/popover/src/use-popover.ts

Closes #5658
In certain browsers and OS, the popover component was closing unexpectedly due to [this known issue with the select element](https://stackoverflow.com/questions/46831247/select-triggers-mouseleave-event-on-parent-element-in-mozilla-firefox).
For more details on the research behind this PR, please see my [comment](https://github.com/chakra-ui/chakra-ui/issues/5658#issuecomment-1080024524) within the original issue.
The `onMouseLeave` handler does not check for the native `relatedTarget` before mutating the hovering status and calling the `onClose` handler.
Checks the `relatedTarget` on the native event inside of the `onMouseLeave` synthetic event handler before invoking any close handlers.
No

fix(popover): check related target onMouseLeave to prevent unexpected closing

---

.changeset/small-hats-raise.md
packages/layout/src/wrap.tsx
packages/layout/stories/wrap.stories.tsx

Closes #5907
Fix issue where setting zero value for either x or y causes all spacing to be collapse (and not work)
See attached issue
No

fix: wrap spacing collapse with zero value

---

.changeset/thirty-ghosts-lick.md
examples/nextjs-typescript/components/PropertySummary.tsx
packages/popover/stories/popover.stories.tsx
packages/popper/src/use-popper.ts
packages/popper/stories/popper.stories.tsx
packages/system/src/should-forward-prop.ts
packages/system/src/system.types.tsx
packages/tag/src/tag.tsx

Closes #5865
ix issue where` matchWidth` doesn't work as expected due to the fixed `min-width: max-content` style attached to the element
- If the content length is shorter than the trigger, the matchWidth property works as expected
- If the content length is longer than the trigger, due to the `min-width: max-content`, the min-width becomes the length of the content and gets longer than the trigger.
We don't apply `min-width: max-content` when `matchWidth` is set to `true`
No

fix(popper): match-width behavior

---

package.json
tooling/cli/bin/tsconfig.json
tooling/cli/package.json
tsconfig.json
yarn.lock

I have updated the ts-node dependency in order to use a version which supports the [swc: true option](https://typestrong.org/ts-node/docs/swc/).
This improvement will speed up the ts-node, in particular it affects the `@chakra-ui/cli` package: in a personal project I was able to reduce the `chakra-cli tokens <path/to/your/theme.(js|ts)>` script execution time from~15s to ~3s.
In my PR I have also run a `yarn-deduplicate` script (see [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate)) in order to clean up the lockfile.
slow `chakra-cli tokens <path/to/your/theme.(js|ts)>`
faster `chakra-cli tokens <path/to/your/theme.(js|ts)>` ⚡ 
No
-

tooling: use `swc` for `ts-node`

---

.changeset/five-dots-own.md
examples/storybook-addon/.storybook/main.js
examples/storybook-addon/package.json
tooling/storybook-addon/src/feature/decorator/ChakraProviderDecorator.tsx

Closes #5977
This PR fixes the usage of our storybook addon with no custom theme.
The storybook-addon expected a custom theme to be set via `parameters`.
The storybook-addon uses the default theme as fallback
No

fix(storybook-addon): use default theme as fallback

---

packages/theme-tools/src/color.ts

Relates to #5949
This PR deprecates all `@ctrl/tinycolor` utility functions as discussed in #5949.
All `@ctrl/tinycolor` utility functions in the `@chakra-ui/theme-tools` package are marked as deprecated
No

chore: deprecate tinycolor helper functions

---

.changeset/rare-pans-tickle.md
packages/modal/package.json
yarn.lock

Bump react-remove-scroll to ^2.5.3 which is compatible with React 18
No

chore: bump react-remove-scroll

---

.changeset/cuddly-countries-sip.md
packages/color-mode/src/color-mode-provider.tsx

Closes # 
Add `StorageManager.get` call in `colorMode`'s default state for better SSR behavior.
`StorageManager` isn't able to read cookies on the server side.
Allows for a custom `StorageManager` to be created that'll read cookies on the server side.

fix: add manager call to colorMode default state

---

.changeset/bright-news-retire.md
packages/toast/src/toast.tsx

Closes #6017
Provide a default variant to the `Alert` component rendered in [toast.tsx](https://github.com/chakra-ui/chakra-ui/blob/fed228c088bcecc9b367198f79231c98e0a1d29d/packages/toast/src/toast.tsx#L30)
No default value is set, so without the user defining the `variant` pop passed into `toast` the default variant from `Alert` of `subtle` will be rendered instead. This can cause accessibility issues with contrast, as the `subtle` variant renders an opaque background.
Give the `variant` prop passed into `toast` a default value of `solid` to render solid background colors.
No

fix(toast): set a default variant of `solid`

---

.changeset/dull-books-repeat.md
packages/color-mode/src/color-mode.utils.ts
packages/theme/src/index.ts
packages/theme/src/semantic-tokens.ts
packages/theme/src/styles.ts

This PR fixes the flash of white in most Chakra UI apps by using semantic tokens to manage the global color styles we set.
Flash of incorrect color styles
No more flash. The UI remains consistent
No

fix: update theme to use semantic tokens

---

.changeset/serious-mirrors-breathe.md
packages/focus-lock/package.json
yarn.lock

Closes https://github.com/chakra-ui/chakra-ui/issues/5855#issuecomment-1128011334. Similar to https://github.com/chakra-ui/chakra-ui/pull/5998.
Bump react-focus-lock to ^2.9.1 which is compatible with React 18
No.

chore: bump react-focus-lock

---

.changeset/cuddly-houses-worry.md
.changeset/lucky-eels-hunt.md
packages/descendant/src/index.ts
packages/react/src/chakra-provider.tsx
packages/theme/src/components/index.ts
packages/theme/src/index.ts

Closes #6021
- type `UseDescendantsReturn` wasn't exported from `@chakra-ui/descendants`
- bundle import was used `@chakra-ui/theme` for `Components`
- type `ToastProviderProps` was imported from `src` in `@chakra-ui/react`
This resulted in `src` directory being referenced in type declarations of consumers of those packages, which resulted in a failed typecheck in typescript projects not configuring `"skipLibCheck": true` in their `tsconfig.json`
- exports `UseDescendantsReturn` type from `@chakra-ui/descendants`
- switches to use default import over bundled import for `Components` in `@chakra-ui/theme`
- `ToastProviderProps` is imported from `@chakra-ui/toast`
This makes sure that `src` directories are no longer referenced in the emitted tye declarations.

fix(types): missing type exports

---

.changeset/nasty-cows-begin.md
packages/theme/src/components/tag.ts

Closes [6054](https://github.com/chakra-ui/chakra-ui/issues/6054)
Tag component variants borderRadius was overwriting baseStyle eventhough
borderRadius was same for all variants. borderRadius is now part of the
baseStyle, so it can be overwritten by a custom theme on the baseStyle instead of variants. 
No

fix: baseStyle borderRadius on Tag component

---

.changeset/pink-goats-give.md
packages/toast/src/create-standalone-toast.tsx
packages/toast/src/toast.placement.ts
packages/toast/src/use-toast.tsx

I fixed two toast issues.
1. Fix toast default position to bottom
2. Fix to be able to use the position passed by the `useToast` argument
1. According to the [official docs](https://chakra-ui.com/docs/components/feedback/toast#props) and [types](https://github.com/chakra-ui/chakra-ui/blob/32db866119e831dbc38d92c706a67f87d8a3a946/packages/toast/src/use-toast.tsx#L15), the default position is bottom, but for now it is top
2. The position passed by the `useToast` argument does nothing
1. Fix toast default position to bottom
2. Fix to be able to use the position passed by the `useToast` argument

fix: toast position

---

CHANGELOG.md
CONTRIBUTING.md

_Addresses ChakraUI Docs Issue [#632](https://github.com/chakra-ui/chakra-ui-docs/issues/632)_
Update `CHANGELOG.md` to add `live=false` to any jsx snippets that were missing it.
Also, this PR fixes some formatting as well as adding a note in `CONTRIBUTING.md` about always adding `live=false` when including jsx snippets in a changeset.

fix(CHANGELOG.md): fix jsx snippets

---

.changeset/six-eyes-sniff.md
packages/system/src/use-style-config.ts

Due to past PR for responsive variant and size support, there was a regression in the types.
Throws a TS error
Works

revert: use-style-config types

---

.changeset/seven-swans-joke.md
packages/theme/src/components/tabs.ts

Closes #6062 
1. Adds disabled state to variants [`enclosed`, `enclosed-colored`, `soft-rounded`, `solid-rounded`] of the Tabs component. 
2. Also added a fix that prevents visual feedback of a successful click on the `_disabled` tabs of variant `line`.
1. Previously there was no visual feedback if a tab was disabled to the end user.
2. Previously, when clicking the tab would show a background color that gave indication of a successful click, other components in the library such as Button, Checkbox, and Input do not display this.
1. When a tab is `_disabled` the `cursor: 'not-allowed'` will be shown, also the `opacity: 0.4` will be displayed.
2. When clicking the `_disabled` tab, the background will be `background: none`.
No, this is not a breaking change.
(1) Added the disabled state to …

fix(tabs): Adding disabled state for all variants.

---

packages/modal/README.md

> The `AlertDialog` component currently has an example that Typescript throws an error for. This PR provides a reference point for people hitting the same issue.

docs: Add typescript details to `AlertDialog`

---

.changeset/sixty-dragons-smell.md
packages/toast/src/toast.provider.tsx

Closes #6096
`useSyncExternalStore` requires the `getServerSnapshot` argument for ssr, but I forgot to pass it in #6091 .
Add `getServerSnapshot` to fix the toast.
Toast doesn't work with ssr
Toast work with ssr
No

fix(toast): add getServerSnapshot function for ssr

---

examples/next-js/README.md

- Updated ZEIT references to Vercel (new name of the organisation)
- Added direct links instead of redirecting links referencing ZEIT
> Vercel incorrectly referenced as ZEIT.
> Vercel incorrectly referenced as ZEIT.
> Updated the docs and links to correctly reference Vercel.
No.
None.

docs: update ZEIT references to Vercel

---

.changeset/serious-otters-tell.md
.changeset/slow-kangaroos-accept.md
tooling/cli/bin/tsconfig.json
tooling/cli/package.json
tooling/cli/src/command/tokens/index.ts
tooling/cli/src/index.ts
tooling/cli/src/scripts/read-theme-file.worker.ts
tooling/cli/src/utils/format-with-prettier.ts
yarn.lock

New watch flag for the tokens command. 
You can specify a directory path to watch for changes. 
It defaults to the parent dir of `<source>`, e.g.`src/theme/theme.ts` => `src/theme`.
```shell
> chakra-cli tokens src/theme/theme.ts --watch
> chakra-cli tokens --help
Usage: chakra-cli tokens [options] <source>
Options:
--out <path>              output file e.g. node_modules/@chakra-ui/styled-system/dist/declarations/src/theming.types.d.ts
--strict-component-types  Generate strict types for props variant and size
--watch [path]            Watch directory for changes and rebuild
-h, --help                display help for command
```
No watch flag
- The tokens command with `--watch` watches the parent dir of the theme file for changes and rebuilds the typings
- fixed an error where prettier …

feat: chakra-cli tokens --watch

---

.changeset/quick-fans-act.md
packages/radio/src/radio.tsx

Closes #5926
Fix a bug in chromium browsers where the modal position would change when focusing on the radio button in the modal.
When a radio button is focused inside a modal which has some long content, the modal position is affected in chromium browsers.
This is caused by `position: absolute` of the [`visuallyHiddenStyle`](https://github.com/chakra-ui/chakra-ui/blob/d26c7d7aa2ca8951794cdfdc5c340bf8ff0866ec/packages/visually-hidden/src/visually-hidden.tsx#L18) used by [`<input type="radio">`](https://github.com/chakra-ui/chakra-ui/blob/d26c7d7aa2ca8951794cdfdc5c340bf8ff0866ec/packages/radio/src/radio.tsx#L117).
Wrap the `<input type="radio">` with `position: relative` and fix it so that the modal doesn't move when focusing on the radio button.
No
- Checkbox also uses …

fix(modal): fix modal not to change position when the radio button is focused

---

.changeset/nervous-bulldogs-cheer.md
packages/accordion/src/accordion.tsx
packages/alert/src/alert.tsx
packages/avatar/src/avatar.tsx
packages/breadcrumb/src/breadcrumb.tsx
packages/editable/src/editable.tsx
packages/form-control/src/form-control.tsx
packages/form-control/src/form-error.tsx
packages/form-control/src/form-label.tsx
packages/form-control/tests/form-control.test.tsx
packages/input/src/input-addon.tsx
packages/input/src/input-element.tsx
packages/input/src/input-group.tsx
packages/layout/src/list.tsx
packages/menu/src/menu.tsx
packages/modal/src/drawer.tsx
packages/modal/src/modal.tsx
packages/number-input/src/number-input.tsx
packages/popover/src/popover.tsx
packages/progress/src/progress.tsx
packages/slider/src/range-slider.tsx
packages/slider/src/slider.tsx
packages/stat/src/stat.tsx
packages/system/src/providers.tsx
packages/table/src/table.tsx
packages/tabs/src/tabs.tsx
packages/tag/src/tag.tsx

Closes #5119
As outlined in the issue, because all components share a pre created StyleContext, the error message was not very descriptive. This PR replaces the current implementation with a helper to create a consistent StyleProvider in every component. This will ensure that the error message is:
1. Consistent
2. Helpful
Currently the error message when missing wrapping a component in the correct parent component with the correct StyleProvider reads:
```
useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />` 
```
```useStyles: "styles" is undefined. Seems you forgot to wrap the components in "<__COMPONENT_NAME__" />"```
The context name now also includes the component name.
>> <StyleProvider to <__COMPONENT_NAME__StyleProvider>
No

feat(StyleProvider): style provider factory w/ helpful error message

---

.changeset/hip-wombats-lie.md
packages/media-query/src/media-query.hook.tsx
packages/media-query/src/media-query.tsx
packages/media-query/src/use-breakpoint-value.ts
packages/media-query/src/use-breakpoint.ts
packages/media-query/src/use-media-query.ts

Closes #6130
Add support for client-side rendered (CSR) apps to get the correct value on the first render.
> Affected hooks: `useMediaQuery`, `useBreakpoint`, `useBreakpointValue`.
These hooks are built to work in server-side rendering (SSR) applications by default. You might notice a quick flash of incorrect media query values when you use them.
If you're creating a CSR-only app, you can now leverage the `ssr` argument to get the correct value on the first render.
```jsx live=false
const [isMobile] = useMediaQuery("(max-width: 768px)", {
// you can now pass `ssr: false`
ssr: false,
})
const buttonSize = useBreakpointValue(
{ base: "sm", lg: "md" },
// you can now pass `ssr: false`
{ ssr: false },
)
// you can now pass `ssr: false`
const breakpoint = useBreakpoint({ ssr: false })
```
CSR …

fix(media-query): get correct first render value for csr apps

---

.changeset/strong-bottles-compare.md
packages/system/src/providers.tsx

Fixed a regression where useStyles and StylesProvider were removed from `@chakra-ui/system`
The last release introduced this breaking change from [this PR](https://github.com/chakra-ui/chakra-ui/commit/391f51221fd1fca1ec40bed1f41d163b66731ce3#diff-895ce969e1d1346a8856aa25b2e2bc87efd71a2c14a5734b850e6b7ef45553d5L63-L68). Thanks for the heads-up @TimKolberger 
We've now reverted this regression and marked it as deprecated
No

revert: use-styles regression

---

.changeset/clever-shrimps-whisper.md
packages/color-mode/src/color-mode.utils.ts

Closes #5197
Support color mode for older browsers. Conditionally check if the
MediaQueryList object supports the addEventListener() method, else fallback to
the legacy .addListener() method.
crashes on Safari browsers < v13 with error `mediaQueryList.addEventListener is not a function` 
the method `addListener()` is used instead of `addEventListener()` for older browsers
No

fix(color-mode): check if mediaQueryList.addEventListener is supported

---

.changeset/pretty-pandas-cover.md
packages/descendant/src/use-descendant.ts

Mitigates an upcoming correctness improvement in TypeScript 4.8
TypeScript 4.8 has improved checking around unconstrained type parameters and now correctly identifies potentially-unsafe instantiations of generic types with `null` and `undefined`
See https://github.com/microsoft/TypeScript/issues/49489
This code will not build in TypeScript 4.8
Now it will
Sort of? Code that invoked this with `null` or `undefined` will now correctly see an error, but this code presumably already crashed

Apply the same constraint to this type parameter as the place it's used

---

.changeset/rude-suns-type.md
tooling/cli/package.json
tooling/cli/src/index.ts
yarn.lock

Closes https://github.com/chakra-ui/chakra-ui/issues/6161
`lodash.throttle` was missing in the most recent Chakra CLI change
The CLI is breaking when running the `tokens` command (https://github.com/chakra-ui/chakra-ui/issues/6161)
No

fix(CLI): fix CLI lodash throttle dependency

---

.changeset/forty-dodos-play.md
packages/toast/package.json

`@chakra-ui/toast` imports `@chakra-ui/system` but doesn't satisfy its peer dependencies (`@emotion/react` and `@emotion/styled`). It only works by using those requirements by chance. Though this could cause issues down the line and with P-n-P. By hoisting `@chakra-ui/system` to being a peer dependency, we can leave that to the package consumer (as it should be).
Undeclared import in `@chakra-ui/toast`
There is now no undeclared import
Maybe? Users will now have to install @chakra-ui/system themselves. But as with the issue in the first place, most users will never notice this because its already installed in their `node_modules`. Anyone using P-n-P will two fewer warnings in their install command.

Import @chakra-ui/system as a peer dependency for toast

---

.changeset/friendly-terms-cover.md
.changeset/perfect-icons-exist.md
packages/layout/src/simple-grid.tsx
packages/layout/stories/simple-grid.stories.tsx
packages/system/src/hooks.ts
packages/system/stories/system.stories.tsx
packages/system/tests/style-config.test.tsx

Closes #6199
This PR fix issue where SimpleGrid's `minChildWidth` doesn't allow size tokens but the types hints so. I've also removed a couple of unused functions in the `system` package
Doesn't support tokens
Now supports tokens
No

fix: simple grid

---

.changeset/wet-cobras-call.md
packages/radio/package.json
packages/radio/src/use-radio.ts

Closes #6166
Fix issue where radio component doesn't show focus visible outlines.
No

fix: focus visible in radio

---

.changeset/many-seas-chew.md
packages/media-query/tests/test-data.ts
packages/react/tests/extend-theme.test.tsx
packages/skeleton/tests/test-data.ts
packages/styled-system/tests/css.test.ts
packages/styled-system/tests/interpolation.test.ts
packages/system/tests/hooks.test.ts
packages/theme-tools/src/create-breakpoints.ts
packages/theme/src/foundations/breakpoints.ts
packages/theme/src/theme.types.ts

Closes -> no current issue
The `createBreakpoints` function has a warning regarding deprecation, see [create-breakpoints.ts](https://github.com/chakra-ui/chakra-ui/blob/8e201b9f84a914e58cdc9ee90b3e03269fabf4d7/packages/theme-tools/src/create-breakpoints.ts#L20). According to that this PR removes all occurences in the repo (except in [responsive.test.ts](https://github.com/chakra-ui/chakra-ui/blob/8e201b9f84a914e58cdc9ee90b3e03269fabf4d7/packages/utils/tests/responsive.test.ts#L130) as long as the function is in the repo).
Internal usage of deprecated `createBreakpoints` function
- Internal usage of objects with the breakpoints
- JSDoc deprecation warning for the function
No
- Occurances of the function in the docs repo are already removed: …

refactor: remove internal usage of deprecated createBreakpoints function

---

.changeset/cuddly-cars-sin.md
tooling/cli/package.json
tooling/cli/src/command/tokens/create-theme-typings-interface.ts
tooling/cli/src/command/tokens/index.ts
tooling/cli/src/command/tokens/resolve-output-path.ts
tooling/cli/src/index.ts
tooling/cli/src/scripts/read-theme-file.worker.ts
tooling/cli/test/theme-typings.test.ts
yarn.lock

`chakra-cli tokens` formats the output file if prettier is available.
However, there are environments like CI that do not require formatting.
I add `--no-format` option to finish type generation faster in such environments.
`chakra-cli tokens` always formats the output file if prettier is available
`--no-format` disables formatting
No
Benchmarks in my local project
| format | no format |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2343568/174332357-989f03d9-34bc-4dae-abbc-adf6cc714ef1.png) | ![image](https://user-images.githubusercontent.com/2343568/174332532-ab7211a0-da25-4a29-b50a-f928d1f5a616.png) |

feat(cli): add --no-format option

---

.changeset/yellow-ligers-trade.md
packages/modal/src/drawer.tsx

This PR exports the useDrawerContext hook. This is useful for when you want to implement a swipe to close functionality further down the stack, like on the DrawerContent.
Not a breaking change, but an extension of the API

feat: export use-drawer-context

---

.changeset/twelve-years-lie.md
packages/tooltip/src/use-tooltip.ts

Closes #2503
Avoid rendering multiple tooltips so that they are not appeared after opening a modal
If the user clicks the modal trigger button before opening the tooltip, `openWithDelay` will be called twice by `onMouseEnter` and `onFocus`. `openWithDelay` using `setTimeout` to open a tooltip.
#2503 is caused by this double `setTimeout` .
When the user click the trigger button, `onClick` or `onMouseDown` is called, and they call `closeWithDelay` to close a tooltip and clear an enter timer.
However, `enterTimeout` ref stores only the latest timer id, so `closeWithDelay` clears only the latest timer and the previous timer displays a tooltip after opening the modal.
Don't show tooltips after opening a modal
No
Testable sandbox https://codesandbox.io/s/serene-worker-i9mpqg

fix(tooltip): don't show tooltips after opening a modal

---

.changeset/soft-ducks-reply.md
packages/theme/src/components/modal.ts

Closes #6066 
Add `borderRadius` of `none` to the default style of `full` size modal.
Current full size modal has a border radius by default.
Now the full size modal has no border radius by default.
No.

feat(modal): add border radius of zero on full size

---

.changeset/smooth-garlics-collect.md
packages/transition/src/transition-utils.ts

`withDelay` lacks type annotations for return types. That causes `tsc` to infer return types while emitting type declarations. Sadly, inferred return types have a deep import into `framer-motion`  (`import("framer-motion/types/types")` as you can see [here](https://unpkg.com/@chakra-ui/transition@2.0.2/dist/declarations/src/transition-utils.d.ts)). That deep import is valid for some framer-motion versions (e.g. `6.2.9`) but not for the latest framer-motion version (`6.3.16`). 
By explicitly annotating return types, we fix the problem and also avoid future problems. 
1. `@chakra-ui/transition` has type declarations that are prone to failure because inferred types have deep imports into `framer-motion`. Proof: https://unpkg.com/@chakra-ui/transition@2.0.2/dist/declarations/src/transition-uti …

build(transition): fix ts types for withDelay

---

.changeset/test-malant.md
packages/utils/src/dom-query.ts

Closes #6249
Fix issue where `getAllFocusables` causes excessive repaint due to `getComputedStyle` calls. This affects the drawer, alert dialog, and dialog components

perf: improve responsiveness of modal dialogs

---

.changeset/proud-planes-poke.md
packages/utils/src/object.ts

Closes #6270 for version 2.x
See PR #6274
This is exactly the same change, but as a PR onto the main branch as a convenience for you folks so you don't have to cherry-pick it.

fix(utils): avoid TypeError in getCSSVar when theme is an empty object

---

.changeset/selfish-bees-kneel.md
packages/styled-system/tests/style-config.test.ts
packages/utils/src/breakpoint.ts
packages/utils/tests/responsive.test.ts

Closes #6269
Fixes breakpoint calculation which was causing certain viewport widths to be excluded from media query coverage.
Media queries which are generated from theme breakpoints do not cover all possible pixel widths.
Media queries cover all possible viewport widths.
No

fix(utils): breakpoint calculation

---

.changeset/slow-insects-sing.md
packages/layout/src/highlight.tsx
packages/layout/tests/layout.test.tsx

Closes #6344 
Added edge case handling for `useHighlight` if the user provides an empty `string` / `array`
No

fix(layout): highlight works with empty query

---

.changeset/slow-turkeys-laugh.md
CONTRIBUTING.md

📝 Description
whole project is migrated to pnpm
but contributing.md documentation is not changed
from yarn to pnpm
Add a brief description
Changed yarn to pnpm in CONTRIBUTING.md
⛳️ Current behavior (updates)
Please describe the current behavior that you are modifying
only CONTRIBUTING.md
🚀 New behavior
Please describe the behavior or changes this PR adds
only changing contributing docs
💣 Is this a breaking change (Yes/No):
No

docs(CONTRIBUTING): update yarn to pnpm

---

.changeset/beige-geckos-hide.md
.changeset/sour-birds-remember.md
examples/create-react-app/package.json
packages/theme/package.json
pnpm-lock.yaml

I've fixed two issues to run create-react-app-ts
https://nodejs.org/api/packages.html#packages_conditional_exports
> "default" - the generic fallback that always matches. Can be a CommonJS or ES module file. This condition should always come last.
If `default` does not come last, you get `Module not found: Error: Default condition should be last one` error.
Fix `Plugin "react" was conflicted between "package.json » ...` error
- Cannot import `@chakra-ui/theme`
- Cannot start `create-react-app-ts`
- Can import `@chakra-ui/theme`
- `pnpm --filter create-react-app-ts start` works as expected
No

fix theme's exports settings and create-react-app's eslint error

---

CHANGELOG.md

Closes: N/A
This updates the CHANGELOG entries where the proposed migration from `isFullWidth` to `width='100%'` is currently `width=100%` which is an invalid syntax.
Invalid syntax
Happy copy and paste 🎉 
No

chore: fix invalid syntax in CHANGELOG migration

---

.changeset/lemon-moose-rescue.md
packages/color-mode/src/index.ts

`@chakra-ui/color-mode` does not export `localStorageManager` since [this change](https://github.com/chakra-ui/chakra-ui/pull/6421/files#diff-fff2dc680fc166b88870023a6365f992dc1a05a5b7907cfc2d71f4777dda49cb).
This PR fixes to export `localStorageManager` .
Cannot import `localStorageManager`
Can import `localStorageManager`
No

fix: export `localStorageManager`

---

.changeset/tame-cobras-scream.md
packages/styled-system/src/create-theme-vars/css-var.ts
packages/styled-system/tests/css-var.test.ts

Closes #5424
Tokens that include symbols in the name are broken. This PR makes it works by escaping symbols.
https://codesandbox.io/s/confident-kalam-27b3m
With the following code, the background color is still transparent in spite of `bg` property being `$red`. The CSS variable will be `--chakra-colors-$red` that invalid.
```tsx
function App() {
return <Heading bg="$red">Welcome to Chakra + TS</Heading>;
}
const rootElement = document.getElementById("root");
render(
<ChakraProvider theme={extendTheme({ colors: { $red: "#880000" } })}>
<App />
</ChakraProvider>,
rootElement
);
```
https://codesandbox.io/s/competent-bush-hm9pmu
The background color …

fix(css-vars): escape symbols in css var

---

.changeset/curly-trees-serve.md
packages/theme/src/components/form.ts

- Changed the font colour for the FormHelperText as the previous colour (gray.500) failed the WebAIM Contrast check (can check here https://webaim.org/resources/contrastchecker/) - check #718096 against #FFFFFF.
Closes # 
- Changed the font colour for the FormHelperText as the previous colour (gray.500) failed the WebAIM Contrast check (can check here https://webaim.org/resources/contrastchecker/) - check #718096 against #FFFFFF.
- 
The colour of the FormHelperText from gray.500 to gray.600, i.e. darker shade of gray to meet accessibility contrast requirements
No.

Improve FormHelperText contrast

---

.storybook/main.js

This PR is a workaround.
Storybook build is very slow after build system migration in #6356.
I think this is a storybook's issue but I haven't been able to find the root cause.
I fixed this issue by not using glob patterns for directories in the `stories` setting.
No
I tested with the following settings
- original => slow
- `stories: ["../packages/**/stories/*.stories.tsx"]`
- single directory => slow
- `stories: ["../packages/*/stories/*.stories.tsx"]`
- without `packages` => slow
- `stories: ["../**/stories/*.stories.tsx"]`
- single package => fast 
- `stories: ["../packages/button/stories/*.stories.tsx"]`
- two packages => slow
- `stories: ["../packages/{button,alert}/stories/*.stories.tsx"]`

chore: speed up storybook builds

---

.changeset/three-jokes-swim.md
packages/react/src/chakra-provider.tsx

Closes #6463
This PR adds an explicit declaration to `chakra-provider.tsx` that will forcefully change the declaration output from this:
```
declare function ChakraProvider({ children, toastOptions, ...restProps }: ChakraProviderProps): JSX.Element;
declare namespace ChakraProvider {
var defaultProps;
}
```
to this:
```
declare function ChakraProvider({ children, toastOptions, ...restProps }: ChakraProviderProps): JSX.Element;
declare namespace ChakraProvider {
let defaultProps: {
theme: Theme;
};
}
```
I was
The current implementation leaves TypeScript to infer the type that must be emitted for `ChakraProvider.defaultProps`, which it fails to do. This causes TypeScript builds to fail in strict mode for consumers of `@chakra-ui/react`.
The new implementation explicitly declares the type …

Add explicit type declaration to `ChakraProvider.defaultProps`

---

.changeset/pink-elephants-divide.md
packages/counter/src/use-counter.ts

Closes https://github.com/chakra-ui/chakra-ui-docs/issues/914
Corrects defaults for min and max prop of `NumberInput` Component in docs.
Default value is `Infinity` in docs but in the implementation it differs.
Default value is corrected to `Number.MIN_SAFE_INTEGER` / `Number.MAX_SAFE_INTEGER`, see https://github.com/chakra-ui/chakra-ui/blob/main/packages/counter/src/use-counter.ts#L64-L65
No
Interface `UseCounterProps` with the wrong default values is only used for `UseNumberInputProps` of `NumberInput`.

docs: fix default values for min and max prop of NumberInput

---

.changeset/small-bugs-prove.md
packages/tabs/src/use-tabs.ts
packages/tabs/stories/tabs.stories.tsx

Closes #6443
This PR allows wrapping tab panels with arbitrary elements. To ensure backward compatibility, we're using react context to propagate the details we currently pass via props.
Can't wrap tab panel
No

feat: allow wrapping tab panel

---

.changeset/loud-ears-happen.md
packages/components/descendant/src/use-descendant.ts

Closes https://github.com/chakra-ui/chakra-ui/issues/6572
> Add correct constraint for useDescendants K generic
> Using strict=true on tsconfig with typescript v4.8.2 will fail on build.
> Old constraint: `K = {}`
> New constraint `K extends Record<string, any> = {}`

fix: add correct constraint for useDescendants K generic

---

.changeset/twelve-wombats-trade.md
pnpm-lock.yaml
tooling/gatsby-plugin/src/provider.js

Closes #6493 
The Gatsby plugin adds a default `portalZIndex` of `40` in the `WrapRootElement` which causes issues when working with modals and/or alerts.
When attempting to show a toast/alert while having a modal opened, the toast will be shown behind the modal because it gets rendered within the Chakra portal that has a `zIndex` of `40`.
The toast/alert will be rendered on top of the modal, since its `zIndex` property is not limited to `40`.
No

fix(gatsby): removed default portalZIndex value from WrapRootElement

---

.changeset/eighty-trains-arrive.md
packages/components/theme/src/components/tooltip.ts

Fix tooltip theme

---

.changeset/moody-ladybugs-glow.md
packages/components/theme/src/components/select.ts

When using `Select` with `xs` size it uses `sm` instead. This fixes the typo.
No

Fix incorrect Select xs sizing

---

CONTRIBUTING.md

There are currently duplicate command descriptions for running storybook in https://github.com/chakra-ui/chakra-ui/blob/main/CONTRIBUTING.md#commands.
There are two descriptions for the command `pnpm storybook`.
Removed the duplicate entry, leaving one description for the command `pnpm storybook`.
No.
The duplicate description was added in https://github.com/chakra-ui/chakra-ui/pull/6650.

Remove duplicate command in docs

---

.changeset/neat-flies-smile.md
packages/hooks/use-focus-on-pointer-down/src/index.ts

Closes #6658
Fix regression where the popover doesn't close for Safari. A recent refactoring caused this
No

Fix: Popover pointerdown regression

---

.changeset/strange-buses-exercise.md
packages/hooks/use-controllable-state/src/index.ts

fix(slider): default value cannot be set after update
Fixes #6619

fix(slider): default value cannot be set after update

---

.changeset/funny-lies-switch.md
packages/components/layout/src/stack/stack.tsx
packages/components/layout/src/wrap.tsx

Fixes #6660
This PR prevents the app from crashing when Stack is overloaded with children
**NB:** This does not help improve loading and refresh performance otherwise, libraries like `react-virtualized` should be used to handle large lists.

fix(stack): prevent crashing when there's a lot of children

---

.changeset/new-dolls-trade.md
packages/components/styled-system/src/pseudos.ts
packages/legacy/utils/src/dom-query.ts
packages/utilities/dom-utils/src/index.ts

The following HTML did not apply the `_disabled` style. because the selector used in `_disabled` was `[disabled]` instead of `:disabled`.
```
<fieldset disabled>
<chakra.button _disabled={{color="#999"}}>click!!</button>
</fieldset>
```
So replaced `[disabled]` with `:disabled` to reflect the disabled state correctly.
`_disabled` in `<fieldset disabled>` doesn't work 
`_disabled` in `<fieldset disabled>` will work 
No

Update `_disabled` to use state selector

---

.changeset/lazy-ants-attack.md
.changeset/ninety-pugs-suffer.md
.changeset/perfect-cycles-argue.md
.changeset/strange-guests-deliver.md
packages/components/accordion/src/accordion-panel.tsx
packages/components/checkbox/src/checkbox-icon.tsx
packages/components/menu/src/menu-list.tsx
packages/components/modal/src/drawer-content.tsx
packages/components/modal/src/modal-content.tsx
packages/components/modal/src/modal-overlay.tsx
packages/components/modal/src/modal-transition.tsx
packages/components/modal/stories/drawer.stories.tsx
packages/components/modal/stories/modal.stories.tsx
packages/components/popover/src/popover-content.tsx
packages/components/popover/src/popover-transition.tsx
packages/components/tooltip/src/tooltip.tsx
packages/components/transition/src/collapse.tsx
packages/components/transition/src/fade.tsx
packages/components/transition/src/index.ts
packages/components/transition/src/scale-fade.tsx
packages/components/transition/src/slide-fade.tsx
packages/components/transition/src/slide.tsx
packages/components/transition/src/transition-utils.ts

Closes #6449
Closes #5843
Closes #6189
Closes #5883
This PR adds support for overriding framer motion props across components.
It's almost impossible to override the framer motion config for menu, popover, tooltip, etc.
Motion-related elements now have `motionProps` prop that allows users to have full control over the styling.
No

Support motion overrides

---

.changeset/lemon-tools-lick.md
tooling/storybook-addon/src/feature/arg-types.ts

adjust getThemingArgTypes so it also return arg types when component doesn't support colorSchemes
getThemingArgTypes will not return any arg types when component doesn't support colorSchemes
getThemingArgTypes now also returns arg types when component only supports variants and/or sizes

fix(storybook-addon): getThemingArgTypes works without colorScheme

---

.changeset/giant-owls-invent.md
tooling/storybook-addon/src/feature/decorator/ChakraProviderDecorator.tsx

This will allow setting the theme used in storybook via a callback function, that gives acces to the current context.
The usecase triggering this PR, is to allow selecting a theme via the toolbar.
Themes can only be set as objects in storybook
Themes can still be set as objects, but can also be set by returning a theme in a callback function

feat(storybook-addon): allow setting the theme via a callback

---

.changeset/seven-ducks-rest.md
README.md
packages/components/button/stories/button.stories.tsx
packages/components/button/tests/button.test.tsx
packages/components/styled-system/src/pseudos.ts
packages/legacy/utils/src/dom-query.ts
packages/utilities/dom-utils/src/index.ts

Closes #6736 
Changes in #6700 caused components not to be disabled when `isDisabled` prop was used together with the `as` prop. This PR reverts the removed `[disabled]` CSS selector but keeps the `:disabled` selector on top.
`<Button as="div" isDisabled />` is not disabled properly 
`<Button as="div" isDisabled />` now is disabled properly
No

fix: add `[disabled]` on top of `:disabled` selector to fix regression

---

.changeset/cold-cheetahs-drop.md
packages/components/modal/src/drawer-content.tsx

This adds the missing containerProps to Drawer in order to make the API consistent with Modal.

feat: add containerProps to drawer component

---

.changeset/strange-bugs-chew.md
packages/components/checkbox/src/checkbox.tsx

Closes #6749
This PR refactors the checkbox component to be slightly less strict in its default styles. Using the chakra factory with `baseStyles` has more specificity over the `__css` prop, making it hard to override from the theme.
Can't override certain properties in the checkbox theme
No

fix: checkbox style overrides

---

.changeset/nasty-pots-mix.md
packages/components/modal/src/drawer-content.tsx
packages/components/modal/tests/drawer.test.tsx

Closes #6604 
Add `aria-hidden` to siblings of modal/drawer element, so the screen readers only need to care about the modal.
Adding or removing `useInert` does not alter the state of drawer when opened due to its ref not being defined.
We use the drawer container ref to trigger the modifications in the DOM attributes.
No

fix: drawer inert siblings' elements when opened

---

.changeset/seven-kiwis-argue.md
packages/components/editable/src/use-editable.ts
packages/components/editable/stories/editable.stories.tsx

Closes #6819 
Fixed input retaining focus when programmaticaly leaving input mode

fix(editable):  input retaining focus when programmaticaly leaving input mode

---

.changeset/small-colts-fry.md
packages/hooks/use-focus-effect/package.json
packages/hooks/use-focus-effect/src/index.ts
packages/legacy/hooks/src/use-focus-on-show.ts
pnpm-lock.yaml

This is an attempt to fix focus theft when the focus is intentionally moved away from the open element and even when it is moved outside of the current window.
Notice that I have a focus on the popover on the right. We manage the open state of that popover ourselves and we don't use focus trapping in it.
I've noticed that sometimes when I move the focus to the source code on the left then I quickly lose my cursor in the code. I've investigated the issue and it turned out that the popover element was being programmatically focused by Chakra after I manually moved it outside of that window.
After further investigation, I've managed to narrow it down to this `focus` call:
https://github.com/Andarist/chakra-ui/blob/5af9b7dddd0e1c7788ee9459246909758da3adc1/packages/legacy/hooks/src/use-focus-on …

fix(focus): fixed accidental focus thefts from overly eager transitionend handler

---

.github/ISSUE_TEMPLATE/bug_report.yml

update Description type to textarea in `.github/ISSUE_TEMPLATE/bug_report.yml`
use `textarea` instead of `input`
When I try to open a bug report issue, the description form just has one line. Some tip wad hidden. In my opinion a textarea would be more appropriate here. Once the PR is accepted, the description will behave the same as Steps to reproduce

chore: update Description type to textarea

---

.changeset/wet-yaks-guess.md
packages/components/css-reset/src/css-reset.tsx

Closes #6798
- There is an issue with the visibility of important elements of Modals
- Currently parts of the modal can be hidden because of visible UI of the operating system (e.g. address bar in iOS)
- This provides a bad UX as e.g. the close icon or the footer of a modal isn't visible / accessible to the user
- By using the `dvh` unit the browser correctly adapts the actual visible height automatically
- Like the previously used `lvh` unit this is only supported in certain browsers, see https://developer.mozilla.org/en-US/docs/Web/CSS/length#browser_compatibility
- By using `@supports` we ensure progressive enhancement (like before)
- This is **not** a breaking change as the browser support for `lvh` and `dvh` units is equal
- Good reference blog post discussing the difference in units …

fix(css-reset): Use dvh unit if supported

---

.changeset/slow-geese-tan.md
packages/components/progress/src/progress.tsx
packages/components/progress/src/progress.utils.tsx
packages/components/progress/tests/Progress.test.tsx

Closes https://github.com/chakra-ui/chakra-ui/issues/6913
Allows overriding the role on `Progress`, for example to use it as a `Meter`
Setting `role` prop sets the role for the containing div, rather than overriding the progressbar role
Setting `role` prop now overrides `progressbar`
No

feat(progress): allow overriding role for Progress

---

.codesandbox/ci.json
package.json

The pnpm version in CodeSandbox CI is v6 and we can't change it in config. This causes an error on the build.
As a workaround, install pnpm v7 at the beginning of the build.
CodeSandbox builds fail.
CodeSandbox builds succeed.
No

ci(codesandbox): use pnpm v7 in CodeSandbox CI

---

.changeset/rich-singers-build.md
packages/components/radio/src/use-radio-group.ts
packages/components/radio/src/use-radio.ts

Closes #6966
Radio bugs when accepting number in value prop.
##🚀 New behavior
> I change the types of "value" on Radio, and the types of "value" and "defaultValue" on RadioGroup. All to only accepts string instead of "string | number"
For more details, please check the discussion on the issue.

fix: [Radio] adjust value prop type

---

.changeset/slow-pens-rule.md
packages/components/modal/tests/alert-dialog.test.tsx
packages/components/modal/tests/drawer.test.tsx
packages/components/modal/tests/modal.test.tsx

Related to https://github.com/chakra-ui/chakra-ui/issues/7006 and https://github.com/chakra-ui/chakra-ui/pull/7007
The current modal unit tests do not actually cover the modal because it's in a portal, so outside `container`.
Unit tests run aXe over `container`, whereas the modal is in a portal so is appended to the `baseElement`
Unit tests run aXe over `baseElement`
No - unit tests
Had to disable one rule due to https://github.com/chakra-ui/chakra-ui/issues/7006 (for drawer, which doesn't use a `section` element) and https://github.com/dequelabs/axe-core/issues/3752 (for modal/alert dialog)

test(Modal): make Modal a11y tests cover the modals

---

.changeset/wet-ears-warn.md
packages/components/progress/src/progress.tsx
packages/components/progress/tests/Progress.test.tsx

Updating properties for the `Progress` component, so that we can accommodate all the cases for addressing a11 issues. This PR is for adding `aria-valuetext` on the proper level (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuetext)
Currently, if we pass the `aria-valuetext` prop to the Progress component it gets applied to the wrapper div
this is invalid behavior and the screen readers cannot read it properly
With the change that I've included, the `aria-valuetext` prop is passed properly to the desired div, and the screen reader is reading the value correctly (tested with VoiceOver on iOS device, as well with VoiceOver in web browser/s).
> Please describe the …

fix(progress): Adding aria-valuetext property to the Progress component

---

.changeset/beige-emus-judge.md
pnpm-lock.yaml
tooling/cli/package.json
tooling/cli/src/scripts/read-theme-file.worker.ts

This started out because I was getting errors with the `paths` option in `tsconfig.json`.
We have the following in our config:
```json
"paths": {
"*": ["first/*", "second/*"]
}
```
The current system doesn't support the solo `*` _at all_. As an aside, it also don't support multiple paths for a single alias. I spent some time trying to make the existing system support the paths, but then found there was already an included package, that does this automatically. A nice added bonus is the removal of a dependency.
- There's a crash when trying to use the CLI
```
> chakra-cli tokens --strict-component-types --strict-token-types path/to/theme.ts
Chakra UI CLI  v2.2.0 by Chakra UI
Generate theme typings for autocomplete
✖ An error occurred
Error: Theme file or package not found
Error: Cannot …
```

fix(cli): fully support ts config paths

---

.codesandbox/ci.json
package.json

It seems that now codesandbox CI pre-installs pnpm v7.18.2 and current workaround causes an error.
https://ci.codesandbox.io/status/chakra-ui/chakra-ui/pr/7128/builds/328172
So this PR reverts #7015.

ci(codesandbox): remove workaround that install pnpm v7 on csb CI

---

.changeset/serious-numbers-know.md
tooling/cli/README.md
tooling/cli/src/command/tokens/create-theme-typings-interface.ts
tooling/cli/src/command/tokens/index.ts
tooling/cli/src/index.ts
tooling/cli/src/scripts/read-theme-file.worker.ts
tooling/cli/test/theme-typings.test.ts

Closes https://github.com/chakra-ui/chakra-ui/issues/6901
https://github.com/chakra-ui/chakra-ui/pull/5579 added the ability to override the theme typings by module augmentation rather than by writing to node_modules (which would better support e.g. Yarn PnP, for example).
This allows generating theme typings in a structure which can be used in this way.
The CLI generates theme typings in a structure which is designed for use in overwriting node_modules.
When the CLI is run with `--template augmentation`, theme typings are generated which are appropriate for use with module augmentation.
No - default behaviour is still to generate theme typings in the old format.

feat(cli): allow generating theme typings to use via module augmentation

---

.changeset/green-ligers-knock.md
packages/components/input/src/input-group.tsx

Closes https://github.com/chakra-ui/chakra-ui/issues/5742
z-index on InputElement is set to 2, which leads to issues with overlapping menus/popovers etc
Input elements are overlayed on top of overlapping menus/popovers - see https://codesandbox.io/s/nostalgic-newton-pwjm0z?file=/src/index.tsx
The input group creates a stacking context, so all the z-indexes being set within it are isolated
No

fix(InputGroup): make input component z-indexes isolated to the input

---

.changeset/kind-penguins-play.md
packages/core/system/src/should-forward-prop.ts
packages/core/system/src/system.types.tsx

Closes #7221
Fix TS issue with the native `translate` props.
Throws a TS error when spreading the style props unto an element
No

fix: translate errors

---

.changeset/poor-items-refuse.md
.changeset/shaggy-foxes-burn.md
packages/components/focus-lock/package.json
packages/components/modal/package.json
packages/components/modal/src/modal-focus.tsx
packages/components/modal/src/modal-manager.ts
packages/components/modal/src/use-modal.ts
pnpm-lock.yaml

Closes #6213
Fixed issue where the console throws a warning from `react-remove-scroll` when multiple modal dialogs are open.
Throws a console error
Doesn't throw an error anymore
No

fix: multiple modal dialog console error

---

CONTRIBUTING.md

Fixed typo from "dependecnies" to "dependencies".

docs(CONTRIBUTING): fix "dependecnies" typo

---

.changeset/thick-islands-admire.md
packages/components/avatar/src/avatar-group.tsx

When passing prop max as 0 (zero) excess shows correct value but the all avatars are also rendered that because 0 is a falsey. 
Current behavior is that excess and children are rendered if prop `max` is 0 (zero).
This will make that only excess will be rendered when passing prop `max` as 0 (zero)
No
Because slice can work with negative numbers didn't add validation for this case, just because excess don't validate for negative numbers also.

Change childrenWithinMax check to same as excess

---

.changeset/invalid-regexp-group.md
packages/core/styled-system/src/utils/parse-gradient.ts

Closes #7317
Update the regex of parseGradient in @chakra-ui/styled-system to make it works on legacy Firefox browser.
The regex of parseGradient in styled-system doesn't work on Firefox 69.
New regex works well on firefox 69 and other modern browsers.
No
Seems firefox 69 doesn't support named capture groups in regex.
more details: https://stackoverflow.com/questions/55774080/firefox-gives-syntaxerror-invalid-regexp-group

fix: invalid regexp group on firefox 69

---

.changeset/slimy-paws-add.md
packages/components/menu/src/use-menu.ts
packages/components/menu/stories/menu.stories.tsx

Closes #7139 
Closes #7100 
Mousing over multiple menu items quickly causes infinite rerenders. This breaks the focusing behaviour for the default `Menu` as per #7100, as the focus no longer changes when hovering over a `MenuItem`. The problem is even worse for a `Menu` with scrollable `MenuItem`s as it causes the jittering issue from #7139. This behaviour was introduced via #7032 in [@chakra-ui/react@2.4.2](https://github.com/chakra-ui/chakra-ui/releases/tag/%40chakra-ui%2Freact%402.4.2).
Infinite rerenders are caused when an animation frame is requested to focus a `MenuItem`, and before this animation frame can execute, another animation frame is requested to focus a different `MenuItem`. This can be replicated by mousing over multiple menu items quickly.
Consider a `Menu` with 2 …

fix(Menu): prevent infinite rerendering

---

packages/components/checkbox/src/checkbox.tsx

> `iconStyles`  variable, after refactoring commit, started to have an empty item in the `useMemo` dependency.
As far as I can understand, it's not an expected behavior, so I deleted this empty item from the dependency list.

fix(Checkbox): empty item in useMemo dependencies

---

.changeset/two-ligers-join.md
packages/components/input/src/input-group.tsx

Add `data-group` attribute to `InputGroup` component.
This will allow uniform styling changes for `Input`, `InputElement`, and
`InputAddon` to occur when detecting state changes such as `:hover` and
`:focus-within`.
Example gif below with a left and right `InputElement`

refactor(input-group): add data-group attribute

---

.changeset/blue-fireants-perform.md
packages/components/menu/src/index.ts

Closes #7368
`MenuProvider` not exported
Exports `MenuProvider`

fix(menu): export menu provider

---

.changeset/cold-pans-sort.md
packages/components/avatar/src/avatar-image.tsx
packages/components/avatar/src/avatar.tsx

Closes #7416 
Adds support for setting `crossOrigin` attribute on avatar image.
No support for cross origin which is required when serving in ["cross origin isolation" mode](https://web.dev/coop-coep/).
Adds optional prop for crossOrigin
No

fix(avatar): add crossOrigin prop to avatar and avatar image

---

.changeset/loud-socks-sing.md
packages/components/css-reset/src/css-reset.tsx

Closes # 
When working inside a Shadow DOM, the `--chakra-vh` variable is not set properly because it attaches to :root
Modals with `closeOnOverlayClick` do not trigger because the `content_container` has a height of 0px.
Modals with `closeOnOverlayClick` do not trigger because the `content_container` has a height of 0px.
Setting the css variable to the `:host` selector as well will fix issue abovve. 
No

fix(css-reset): attach variable to :host as well

---

.changeset/breezy-deers-judge.md
packages/components/css-reset/src/css-reset.tsx
packages/components/provider/src/chakra-provider.tsx
packages/components/theme/src/styles.ts

Closes #6946
Add support for scoping the css reset to a specific selector.
To use this feature, pass the `resetScope` prop to the `ChakraProvider` or
`ChakraBaseProvider` component.
```jsx live=false
import { ChakraProvider } from "@chakra-ui/react"
function App() {
return (
<ChakraProvider resetScope=".ck-reset">
<App />
</ChakraProvider>
)
}
```
No

feat: add css reset scope

---

.changeset/clean-tips-fry.md
packages/hooks/context/src/index.ts

Closes #7469 
Added passing defaultValue property to the createContext function
createContext defaulValue property doesn't work.
defaultValue is passing and works as expected.
No

fix: defaultValue is not passsed

---

.changeset/fast-cherries-flash.md
.changeset/modern-ads-glow.md
packages/components/checkbox/src/use-checkbox.ts
packages/components/radio/src/use-radio.ts

Closes #7143
Closes #6924
This PR fixes an issue in which the browser shows a console warning due to the `event.preventDefault` call on touch start. This also surfaces as a critical bug when trying to scroll on mobile.
It works as expected.
No

fix: passive event warning on mobile

---

.changeset/late-trees-smile.md
packages/components/toast/src/toast.tsx
packages/components/toast/stories/toast.stories.tsx

Closes # [7472](https://github.com/chakra-ui/chakra-ui/issues/7472)
Add colorScheme prop support for the toast component
The colorScheme prop is passed now for the toast component in order to change the color
of the Alert component.
The colorScheme prop is not defined in the toast stories.
The Toast component is not supported the colorScheme prop
Implement the  Toast component and called with useToast
pass the colorScheme prop in the useToast hook
The color for the Alert is not updated
Implement the  Toast component and called with useToast
pass the colorScheme prop in the useToast hook
The color for the Alert is updated based on the prop
No

fix: colorScheme is not passed in the toast component

---

.changeset/late-pandas-own.md
packages/components/tag/stories/tag.stories.tsx
packages/components/theme/src/components/tag.ts

Closes #7485 
Add support for the colorScheme values for the tag component
Tag component not reading `var(--badge-color)` and `var(--badge-bg)` CSS variables
Tag component reading colorScheme prop and setting the value for `color` and `bg` with the `--badge-bg` and `badge-color`CSS variables just like in the Chakra example in the official docs
No

fix: tag component not reading badge color and badge bg css variables

---

.changeset/tall-lies-tap.md
examples/create-react-app/package.json
examples/next-app/package.json
examples/next-pages/package.json
examples/vite-ts/package.json
package.json
packages/components/avatar/src/avatar-group.tsx
packages/components/button/src/button-icon.tsx
packages/components/checkbox/src/checkbox-icon.tsx
packages/components/icons/package.json
packages/components/layout/stories/container.stories.tsx
packages/components/menu/src/menu-icon.tsx
packages/components/transition/src/collapse.tsx
packages/core/styled-system/src/create-theme-vars/create-theme-vars.ts
packages/core/system/src/factory.ts
packages/core/system/src/system.ts
packages/core/system/src/system.types.tsx
packages/integrations/next-js/src/link.tsx
pnpm-lock.yaml
tooling/test-utils/src/accessibility.tsx
tooling/test-utils/src/utils.ts

Closes #7459
This PR attempts to fix the TypeScript issues with 5.0 and Chakra UI. I managed to get the errors down to 2 from about 50 😅. The last 2 are proving to be quite cumbersome, but we'll see
With 5.0, you get a weird TS error along the lines of "too deep to resolve types."
Should work (or at least for the majority of cases)
The alternative is to introduce the `asChild` prop to circumvent the problem. I really hope we don't have to use this, but we'll see.

fix: type issues with TS 5.0

---

.changeset/pretty-pumpkins-sin.md
tooling/gatsby-plugin/README.md
tooling/gatsby-plugin/src/provider.js
tooling/gatsby-plugin/src/theme.js

Closes #7179 
This PR reverts the Gatsby plugin back to the version prior to adding the `ChakraBaseProvider` as an option with the `baseTheme`. 
This is a two-fold change
Console warning `Attempted import error: 'baseTheme' is not exported from './theme' (imported as 'baseTheme')` when attempting to use `extendBaseTheme` in the project 
Warning is gone because the `baseTheme` import is removed from the plugin.
No. Use of the `extendBaseTheme` is still valid, and only the added option `isBaseProvider` is removed.
In using the added features of `extendBaseTheme` and `ChakraBaseProvider` and from the discussion in the related issue, the provider seems unnecessary. 
With the component default theming stripped away initially from `ChakraBaseProvider`, the user might already be inclined to …

revert(gatsby-plugin): revert implementation of `baseTheme`

---

.changeset/friendly-books-sin.md
packages/integrations/next-js/src/image.tsx

> Added loading props to the `@chakra-ui/next-js` package, currently the use of `loading="eager"` does not change the `loading="lazy"` included by default in `next/image`
> The use of props loading does not produce any effect 
> It is now possible to modify the props loading and thus put the images in "eager" mode
No

Add loading props to the @chakra-ui/next-js.

---

.changeset/strong-pianos-report.md
packages/components/editable/src/use-editable.ts
packages/components/editable/stories/editable.stories.tsx
packages/components/editable/tests/editable.test.tsx

> Adds two new props to editable component -- finalFocusRef and onBlur.
> Editable always focuses edit buttons on blur. 
> Editable requires you to add onSubmit and onCancel hooks if you want to always make a change onBlur. 
> Focusing on the edit button is sometimes not desirable, and the workaround is very hacky (involving setTimeouts). This change also makes Editable more inline with other chakra ui components.
> We can now add a simple onBlur callback to always take an action onSubmit or onCancel
No

feat: add props to editable

---

.changeset/wicked-parrots-relax.md
packages/integrations/next-js/src/image.tsx

Closes # 
This pull request adds missing props (`loader`, `quality`, `unoptimized`, etc...) to `shouldForwardProp` for the `NextImage` component Previously, these props were being discarded due to `shouldForwardProp` not including them. 
https://github.com/vercel/next.js/blob/1c007cee2f100a7a15a3fdb02ca7e86e60208cc8/packages/next/src/client/image.tsx#L99
The `loader`, `quality`, etc props were not being forwarded to the `NextImage` component.
The `loader`, `quality`, etc props are now being forwarded to the `NextImage` component.
No.

fix(next-js): forward some props

---

packages/components/theme/src/components/tabs.ts

I just read the source chakra found an extra expression there. 
You can see that we have isVertical constant on 93 line.
After that we also write the same expression on 94 line but we can use isVertical constant

refactor: superfluous expression removed

---

.changeset/breezy-crabs-swim.md
packages/components/avatar/src/avatar-name.tsx
packages/components/avatar/tests/avatar.test.tsx

Closes #7602
This fixes the issue that the 'initials' are rendered twice when a single name is passed to the Avatar component
```tsx
<Avatar name="Name" /> // => "NN"
```
```tsx
<Avatar name="Name" /> // => "N"
```
This is how it worked before Chakra 2.6.0
No

fix(avatar): render a single initial when only one name is passed

---

.changeset/tough-kings-double.md
packages/components/slider/src/slider.tsx

Updated how the Slider's default value for `orientation' is set.
Currently, when passing `undefined` to `orientation`, it makes the Slider track dissappear. This is happening because the "horizontal" default value is being rewritten by the provided props.
Reproduction sandbox: https://codesandbox.io/s/gifted-lucy-b35ll5?file=/src/index.js
`<Slider orientation={undefined} />` will use the "horizontal" default value
No

Fix Slider track from dissapearing when providing `undefined` as prop for `orientation`

---

packages/popover/src/popover.tsx

Closes #5844 for v1 branch.
This is exactly same change that @pomSense did, but for v1 branch
The `PopoverTrigger` component breaks with React 18.
The child for PopoverTrigger isn't typed, which leads to the following error with react 18:
```
Type '{ children: any; }' has no properties in common with type 'IntrinsicAttributes'.
```
Added type to the PopoverTrigger type and specified it accordingly to the PopoverTrigger component:
```typescript
interface PopoverTriggerProps {
/**
* The React child to use as the
* trigger for the popover
*/
children: React.ReactChild
}
export const PopoverTrigger: React.FC<React.PropsWithChildren<PopoverTriggerProps>> = (props) => {
// enforce a single child
const child: any = React.Children.only(props.children)
const { getTriggerProps } = …
```

Adds child types for popover in v1 branch

---

packages/components/avatar/src/avatar-name.tsx

Closes #7623
Using array indices has better compatibility over the Array method `at`
No

Use array indices over array at method

---

packages/integrations/next-js/src/link.tsx

Closes #7676 
Add `isExternal` prop to @chakra-ui/next-js `Link`
`Link` is missing the `isExternal` prop the core `Link` has.
This makes both core and next-js `Link` component more consistent by adding the missing `isExternal` prop and behavior to next-js `Link`.
No

fix(next-js): add isExternal to link

---

packages/components/number-input/src/use-number-input.ts

Improve type safety for event handlers in useNumberInput 
Currently, the `getStepFactor` function is limited to handling `React.KeyboardEvent` and `React.WheelEvent` instances, and the `spinUp` and `spinDown` functions use a type of `any` for their event parameter. Furthermore, the event listener for "wheel" events uses an unnecessary type assertion when calling `getStepFactor`.
With the changes in this PR:
- The `getStepFactor` function is now able to handle standard `WheelEvent`s along with `React.KeyboardEvent` and `React.WheelEvent`.
- The `spinUp` and `spinDown` functions have had their event parameter type specified as `React.PointerEvent`, providing more accurate typing.
- The "wheel" event listener now has a specified type of `WheelEvent` for its event parameter, and the …

refactor: improve type safety for event handlers in useNumberInput

---

.changeset/fast-pans-happen.md
packages/components/avatar/stories/avatar.stories.tsx
packages/components/theme/src/components/avatar.ts

Closes #7666
> Added a `fontSize` adjustment in the theme for `Avatar` excess label. Applicable for sizes `xs` and `2xs` only, as we don't want the label to grow beyond its default value for larger sizes, but need it to shrink for these small ones.
> The excess label can tend to overflow from the background, as mentioned in the original issue.
> Excess label no longer overflows, and shrinks for `xs` and `2xs` sizes, due to introduced changes in `Avatar` theme.

fix: avatar excess label

---

.changeset/silent-snails-rhyme.md
packages/components/checkbox/src/use-checkbox.ts
packages/components/checkbox/tests/checkbox.test.tsx

> If there are multiple checkboxes on a form and you call `form.reset`, only the last one gets reset. This is because we override the onreset instead of adding multiple listeners.
> `form.reset` only resets the last checkbox in a form.
> `form.reset` will reset all checkboxes to the original state because we are using listeners now.
No

fix(checkbox): fixing form reset on checkboxes when there are more than one

---

.changeset/late-kangaroos-hope.md
packages/components/avatar/src/avatar.tsx

Closes #7825
> Adding referrerPolicy to Avatar puts the referrerPolicy attribute on the surrounding `span`, not the `img` tag, this prevents it from working.
> referrerPolicy is passed down to the `AvatarImage` component in `Avatar`.

fix(avatar): pass referrerPolicy from Avatar to AvatarImage instead of span

---

.changeset/swift-yaks-shop.md
packages/components/anatomy/src/components.ts
packages/components/menu/src/menu-icon.tsx
packages/components/theme/src/components/menu.ts

Closes # 
This PR extends the menu theme to accept `icon` as part of the theme.
Currently, the base style of `MenuIcon` is hardcoded in the component so there is no clean way to customize menu icon styles.
You can style the menu icon the same way as other parts of the menu theme.
No. The base styles are still here but are moved to the theme.

feat(menu): extend menu theme with icon part

---

.changeset/stale-clouds-applaud.md
packages/components/theme/src/components/input.ts
packages/components/theme/src/components/progress.ts

Reverts the usage of `getColorVar` to `getColor`.

revert(theme): revert `getColorVar` to `getColor`

---

.changeset/polite-chicken-pump.md
packages/components/popover/src/use-popover.ts

Clarify the usage of `openDelay` and `closeDelay` properties of `Popover` component.
Only default values are specified.
Provide simple descriptions about the functionality of the properties and inform the users they only work if trigger mode is `hover`.
No, its primary goal is to prevent future users from misusing the props.
N/A

docs(Popover): add description for `openDelay` and `closeDelay` properties

---

.changeset/angry-dryers-laugh.md
packages/components/media-query/src/use-breakpoint-value.ts

Support null type in useBreakpointValue
Closes # 
Add null type in useBreakpointValue
just add type
just add type
No
The null value in Chakra's responsive value indicates a wildcard with a small value. This rule is applied when using useBreakpointValue(). However, useBreakpointValue() does not support null values. Therefore, I added the null type to useBreakpointValue.

Support null in useBreakpointValue

---

.changeset/clever-pandas-move.md
packages/components/tabs/docs.json
packages/components/tabs/src/use-tabs.ts

Closes # 
NA
API documentation is not up to date. Technically, the solution is not just a documentation update, but a refactor, since it's concerned with APIs and not just internals.
`useTab()`, `<Tab />`, and their common `UseTabOptions` interface.
- Props are documented but unused: Documentation shows that `useTab()` and `<Tab />` may receive props `id`, `panelId`, and `isSelected`. I expected to get some use from these props, but they are unused.
- Used prop `isFocusable` is not documented.
- Prop `isDisabled` is documented as defaulting to `false` in `useTab()`, but it actually defaults to `undefined`.
- Unused props `id`, `panelId`, and `isSelected` are no longer documented.
- Prop `isDisabled` defaults to `false`, and this is consistent with the current documentation.
- Prop …

refactor: use-tabs prop interface

---

.changeset/clean-shrimps-flow.md
.changeset/old-worms-punch.md
.changeset/unlucky-ways-rescue.md
packages/components/anatomy/src/components.ts
packages/components/input/src/input-group.tsx
packages/components/input/stories/input.stories.tsx
packages/components/theme/src/components/input.ts

The support for responsive `size` values added in #6050 breaks down when a responsive `size` is supplied to an `InputGroup` that includes `InputElement` and/or `InputAddon` children. This is due to the way the dimensions for the input, element and addons are calculated: https://github.com/chakra-ui/chakra-ui/blob/fa62897ca65d2af82bbe07e50fb323415bfe974e/packages/components/input/src/input-group.tsx#L41-L74
I was hoping to be able to resolve this in our design system with a pure theme-driven solution, but because there's no root element "part" to target in the case of `InputGroup`, it was impossible. This change adds a new `group` part to the input theme allowing the responsive case to be handled via CSS variables. This was the least invasive change I could come up with, but am happy to …

fix(input): handle responsive sizing in input addons/elements

---

packages/components/select/README.md

> When you use the Select Component, if you type your event param like the readme, an error occurs : 
> Typescript error in doc
> No more error 😄 
> No

fix: type error in readme

---

.changeset/famous-forks-bathe.md
packages/components/anatomy/package.json
packages/components/theme-tools/package.json
packages/components/theme/package.json

Closes # 
This PR removes `"use client"` directive from non-component packages to allow them to be imported from server components.
The dist of `theme`, `theme-tools` and `anatomy` have `"use client"` directive. This will cause an error when importing them from files other than client components.
For example, think the code below.
```ts
import { tagAnatomy } from '@chakra-ui/anatomy';
import { createMultiStyleConfigHelpers } from '~/components/elements/chakra';
const { definePartsStyle, defineMultiStyleConfig } = createMultiStyleConfigHelpers(tagAnatomy.keys);
// ...
```
Then the error below is occurred.
```
Error: Cannot access .key on the server. You cannot dot into a client module from a server …
```

fix: remove "use client" directive from non-component packages

---

.changeset/soft-phones-fail.md
packages/components/tabs/src/tabs.tsx

Closes #7846
TabIndicator does not align with Tab when window is resized with center-aligned tabs
Distored UI when device orientation or width is changed - On changing the device
width and change of device orientation, the tab indicator element which is
position absolute aligns realtive to the outer container element. 
The position of immediate parent(tabs) is set to relative in this fix. This makes
sure, if the orientation changes the tab indicator is aligned relative to its
parent.
No

fix(tabs): https://github.com/chakra-ui/chakra-ui/issues/7846

---

.changeset/nervous-moles-sit.md
packages/components/modal/src/modal-transition.tsx
packages/components/modal/src/modal.tsx

> Added `slideInTop` and `slideInLeft` options in motionPreset prop in modal component
> motionPreset on modal component has only `slideInBottom` and `slideInRight` options
> motionPreset on modal component has `slideInBottom`, `slideInRight`,  `slideInTop` and `slideInLeft` options
No

feat:(modal): Added "slideInTop" and "slideInLeft" motion preset

---

.changeset/twenty-crabs-jump.md
packages/components/toast/src/toast.provider.tsx

Closes https://github.com/chakra-ui/chakra-ui/issues/8006
Chakra toast notification manager divs all have the same aria-label of "Notifications" but they need to have a unique label. The proposed fix appends "-{position}" to the aria-label name.
This PR addresses Issue 8006 [https://github.com/chakra-ui/chakra-ui/issues/8006](https://github.com/chakra-ui/chakra-ui/issues/8006)
Reference:
`If a page includes more than one region landmark, each should have a unique label.` [https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/region.html](https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/region.html)
> Our accessibility testing tool axe raises an error for the presence of duplicate aria-labels for the toast manager divs
> Assign unique names to the toast id managers so that …

fix(toast-landmark-issue): Add toast manager position to aria-label for a11y compliance

---

.changeset/short-taxis-boil.md
packages/components/theme/src/components/alert.ts

Closes #8002 
This PR changes the standard colors used for the alert and toast components. Making the background color slightly darker to make it WCAG AA compatible (a contrast ratio of 4.5:1).
Currently for example the "success" status had a contrast ratio of 3.24:1.
Now it has contrast ratio of 4.54:1 making it WCAG AA compatible.
No.
This affects both the alert and toast component.

fix(alert): status colors wcag compliant

---

.gitignore

After running `pnpm build:fast` there are 90 generated empty turbo logs named `turbo-build` which are not ignored.
`pnpm build` runs with no problems because files like `turbo-build.log` are ignored (strange behaviour with these names, by the way). 
Fixed gitignore
No

fix: add turbo in gitignore

---

examples/next-app/package.json
examples/next-pages/package.json
packages/components/card/package.json
packages/components/provider/package.json
packages/components/stepper/package.json
packages/core/styled-system/package.json
packages/core/system/package.json
packages/hooks/context/package.json
packages/hooks/use-animation-state/package.json
packages/hooks/use-callback-ref/package.json
packages/hooks/use-controllable-state/package.json
packages/hooks/use-disclosure/package.json
packages/hooks/use-event-listener/package.json
packages/hooks/use-focus-effect/package.json
packages/hooks/use-focus-on-pointer-down/package.json
packages/hooks/use-interval/package.json
packages/hooks/use-latest-ref/package.json
packages/hooks/use-merge-refs/package.json
packages/hooks/use-outside-click/package.json
packages/hooks/use-pan-event/package.json
packages/hooks/use-previous/package.json
packages/hooks/use-safe-layout-effect/package.json
packages/hooks/use-size/package.json
packages/hooks/use-timeout/package.json
packages/hooks/use-update-effect/package.json
packages/integrations/next-js/package.json
packages/utilities/event-utils/package.json
plop/component/package.json.hbs

Plop package generator was not updated correctly for the new folder structure for the `directory` property in `repository`.
Many typos after structure change, incorrectly generated `directory` property.
Typos corrected (also some keywords). Generates package.json with appropriate `directory` property.
No
Maybe this is unnecessary

fix: plop and metadata

---

.changeset/soft-doors-sell.md
packages/integrations/next-js/src/link.tsx

Closes #8027 
In #7677 I added isExternal to NextLink, but I missed adding it to types.
TypeScript throws an error when using `isExternal` in `<Link isExternal [...]>`
This adds the missing types.
No
@trevorblades in https://github.com/chakra-ui/chakra-ui/pull/7677#issuecomment-1599672262 and @fzn0x in https://github.com/chakra-ui/chakra-ui/pull/7677#issuecomment-1680705252 correctly commented this in the original PR https://github.com/chakra-ui/chakra-ui/pull/7677 but it had been already merged.
Also, please be extra kind - this is my first TypeScript types contribution 😱

fix(next-js): add isExternal to types

---

packages/components/form-control/src/form-label.tsx

Align requiredIndicator type with optionalIndicator type. Allows for overriding requiredIndicator with `null`.
FormLabel is not able to overwrite `requiredIndicator` to not be rendered.
Aligns the type of requiredIndicator with optionalIndicator. Now requiredIndicator is also a ReactNode and can be overwritten with `null`.
No

fix(form-control): form-label requiredIndicator type

---

packages/components/anatomy/src/components.ts

Closes [Issue](https://github.com/chakra-ui/chakra-ui/issues/8032)
Switch component is using [link](https://github.com/chakra-ui/chakra-ui/blob/6d12ea81f4791f4df2953533b570178f59551b74/packages/components/switch/src/switch.tsx#L103) in codebase, meanwhile, it is not defined in anatomy.
Adding new part inside switch anatomy
current workaround to use label key, is this:
```ts
const { definePartsStyle, defineMultiStyleConfig } = createMultiStyleConfigHelpers([
...switchAnatomy.keys,
'label',
]);
```

fix: missing label key in switch anatomy

---

.changeset/shaggy-donkeys-sip.md
packages/components/tooltip/src/use-tooltip.ts

Caused by https://github.com/chakra-ui/chakra-ui/commit/0bec820bd1ece0c4ba9538394fe2897ff1043c87
`getScrollParent` recursively works its way up the DOM calling `window.getComputedStyle` This isn't too bad in a real browser, but is horrible for performance in JSDOM (particularly versions before https://github.com/jsdom/jsdom/pull/3482)
This doubled the execution time of some of our tests, and is generally unnecessary unless we're actually using `closeOnScroll`
Tooltips slow performance by recursive search for the scroll parent, even if that is unnecessary
Tooltips only slow performance by scroll parent search when required
No

fix(Tooltip): don't track scroll parent when `closeOnScroll` not set

---

.changeset/honest-tigers-study.md
packages/components/form-control/src/form-control.tsx
packages/components/form-control/tests/form-control.test.tsx

Closes #8049, #7922
Allow theming and styling of FormControl and it's child components using `_group*` type [style props](https://chakra-ui.com/docs/styled-system/style-props).
Only some of the child components, e.g. `FormInput`, can be styled based on the state of the FormControl, while e.g. `FormHelperText` cannot be.
Allow theming and styling of `FormControl` using `_disabled`, `_focus`, `_invalid`, `_readOnly`, and it's child components using `_groupDisabled`, `_groupFocus`, `_groupInvalid`.
No.
The only case I can foresee where some styling would break, is if a project has custom group components using these properties, AND nests them with the …

feat: add state style prop support for FormControl

---

.changeset/fair-boats-smile.md
pnpm-lock.yaml
tooling/storybook-addon/package.json
tooling/storybook-addon/src/ChakraProviderDecorator.tsx
tooling/storybook-addon/src/color-mode/ColorModeTool.tsx
tooling/storybook-addon/src/direction/DirectionTool.tsx

Based on a bug found in the color mode toggle, this PR addresses the bug and updates how the decorator is created.
- Bumps Storybook deps to latest (7.5.3)
- Toggling state for color mode originally used Storybook's `useAddonState` api hook. However, this hook is not reliable to persistent allow toggling of boolean state. Replaces this hook with React's `useState` as this state is a primitive.
- Makes use of the `makeDecorator` function to make this addon more like an official Storybook addon.
- Removes unneeded props from the button components that were originally part of a Type error bug.
> Additional context: regarding the issue with `useAddonState`: this was found in the Ethereum.org repo when working on their migration to NextJS. The toggle was breaking after initial change.

refactor(storybook-addon): update deps and tooling

---

.changeset/flat-chicken-scream.md
packages/components/menu/src/menu-list.tsx

In the `MenuList` component, changed the order of props to keep `chakra-menu__menu-list` as className.
In the `MenuList` component, `chakra-menu__menu-list` and `listProps.className` are combined and then overwritten with listProps.className. As a result, `chakra-menu__menu-list` may be lost.
```ts
<MenuTransition
...
className={cx("chakra-menu__menu-list", listProps.className)}
{...listProps} // overwrite className
...
/>
```
Changing the order of props prevented `chakra-menu__menu-list` from being lost from the className.
```ts
<MenuTransition
...
className={cx("chakra-menu__menu-list", listProps.className)}
{...listProps}
...
/>
```
No
Nothing

fix(MenuList): fix props order not to overwrite className

---

.changeset/blue-masks-tell.md
packages/components/theme/src/components/menu.ts

Closes # 
Modifies the `Menu` theme properties to use the variable `dropdown` for z-indices, which is defined in the theme here: https://chakra-ui.com/docs/styled-system/theme#z-index-values.
The Menu's z-index property is currently hardcoded to "1", which would sometimes cause open menu elements to appear behind other z-indexed elements.
Menu's elements inherit the proper z-index value, making it more difficult to accidentally appear behind other UI elements.
No
Tested / verified this update locally in Storybook.
I didn't see an issue filed for this specifically, but it was close enough to [this issue](https://github.com/chakra-ui/chakra-ui/issues/7408). If dedicated issues are preferred, let me know and I can create one.
https://github.com/chakra-ui/chakra-ui/pull/7778

fix(menu): update menu z-index for defined dropdown theme variable

---

.changeset/lucky-donuts-burn.md
packages/integrations/next-js/src/use-emotion-cache.ts

Closes #8131
> Adds missing nonce that is passed to `CacheProvider` from package `@chakra-ui/next-js` to the emotion cache style that is created
> Sandbox demoing current behavior [codesandbox](https://codesandbox.io/p/devbox/mystifying-shadow-x2qgvs?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp9xpakk00093b5wt3n8wv6v%2522%252C%2522sizes%2522%253A%255B70%252C30%255D% …

fix: #8131 adds nonce to created emotion style element

---

.changeset/old-kids-smile.md
packages/components/toast/src/index.ts

Currently there is no way to get `toastStore` singleton instance which may be useful to track toast changes.
Not changing any current behaviour.
Export `toastStore` from `toast` package index.
NO

refactor(toast): export toastStore from toast package

---

.changeset/happy-falcons-guess.md
packages/components/src/avatar/avatar-name.tsx
packages/components/src/avatar/avatar.test.tsx

fix(components) Avatar component doesn't get initials properly when string has leading and trailing spaces

---

.changeset/great-windows-warn.md
packages/styled-system/src/config/color.ts

Adds the CSS [accent-color](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color) to styled-system props to be used in controls and buttons.
No

feat(styled-system): add accent-color prop

---

.changeset/spotty-buckets-know.md
packages/components/src/modal/modal.tsx

Although the documentation (https://chakra-ui.com/docs/components/modal/props) says that the default value of  `preserveScrollBarGap` in `<Modal/>` is `true`, the default value is not set in the code. This pull request sets `true` as the default value of `preserveScrollBarGap`. Another option is to modify the documentation.
The default value of `preserveScrollBarGap` in `<Modal/>` is not set and it is not consistent with the documentation.
A `padding-right` will be applied to the body element that's equal to the width of the scrollbar as the documentation says.
No

fix: add default preserveScrollBarGap

---

website/content/getting-started/nextjs-pages-guide.mdx

There's a small typo on the `_app.js` snippet for adding custom fonts with NextJS. This just fixes that to `return` the fragment instead of prefixing the fragment with a semicolon.
typo 😭 
fixed the typo 🥳 
No

Fix custom font code snippet typo on nextjs-pages-guide

---

.changeset/pretty-cougars-cough.md
.changeset/tasty-scissors-watch.md
packages/cli/src/config.ts
packages/cli/src/create-theme-typings-interface.ts
packages/cli/src/extract-property-paths.ts
packages/cli/src/generate-theme-typings.test.ts
packages/components/src/system/should-forward-prop.test.ts
packages/components/src/system/should-forward-prop.ts
packages/components/src/system/system.ts
packages/styled-system/src/create-theme-vars/create-theme-vars.ts
packages/styled-system/src/create-theme-vars/flatten-tokens.ts
packages/styled-system/src/create-theme-vars/to-css-var.ts
packages/styled-system/src/css.ts
packages/styled-system/src/pseudos.ts
packages/styled-system/src/shared.types.ts
packages/styled-system/src/system.ts
packages/styled-system/src/system.types.ts
packages/theme/src/theme.types.ts

Add support for custom theme conditions or pseudo props via `theme.conditions`
```ts
// theme.ts
const theme = extendTheme({
conditions: {
closed: "&[data-state='closed']", // pseudo prop
}
})
```
No way to add custom pseudo props or conditions
Now possible
No

feat: support custom conditions / psuedo props

---

.changeset/young-lizards-double.md
website/configs/site-config.json

This PR update `editUrl` in the official documentation.
The "Edit this page on GitHub" button does not navigate to the correct repository; instead, it is linked to the old repository.
The button will navigate to correct repository.
No.

docs: update edit url

---

.changeset/metal-mangos-judge.md
packages/components/src/checkbox/use-checkbox.ts
packages/components/src/radio-group/use-radio.ts

Fixes #7702
This PR improves runtime performance of Checkbox and Radio component by reducing re-renders caused by state changes for calculating `data-focus-visible` attribute.
Although the original issue was closed as it is regarded an expected behavior, this causes a significant performance hit in my project where I use checkboxes to select rows in tables with many rows.
All checkboxes/radio buttons from Chakra UI on the screen re-renders whenever input modality changes
Re-renders via the modality change do not happen when the component isn't focused
No

fix(components): suppress unnecessary re-renders of Checkbox and Radio component

---

MIGRATION.md

Closes # 
Just adds a link to https://lucide.dev/guide/packages/lucide-react
It's just text: `lucide-react`
Now it's a link: [`lucide-react`](https://lucide.dev/guide/packages/lucide-react)
No

docs: added link to guide in MIGRATION.md

---

MIGRATION.md

- change `isDisabled` to `disabled`
- change `colorScheme` to `colorPalette`
Closes # 

fix(v3): update Button migration guide

---

.changeset/nine-bags-rest.md
packages/components/src/button/button.tsx

Closes #7269
Closes #7816
Closes #7905
Also re-enables the only currently known workaround for the accessibility problem described in  #7965. 
Removing the ability to use the disabled-prop posed a breaking change, which is hereby fixed.
Despite the `disabled` prop being exposed in the type system, any value given will be discarded and overwritten by `isDisabled || isLoading`.
Values given to `disabled`-prop are now respected again. 
One use case (which was possible in 1.x up until 2.0.15) is the combination of `isLoading disabled={false}` to ensure that a button does not lose focus while in loading-state. 
This reverts a breaking change.
This closes #7907, effectively replacing it.

fix: Undo Breaking Change by re-allowing disabled prop on button

---

.changeset/funny-foxes-tease.md
packages/components/src/alert/index.ts

Closes #8104 
This PR exports the `useAlertContext` hook. This increases the flexibility users have for customizing the Alert and the Toast component that depends on it. A specific example is that this allows users to customize which icons are used for different Alert statuses by implementing a custom AlertIcon component without also implementing custom Alert and Toast components. There are more details in the linked issue. 
`useAlertContext` is not exported.
`useAlertContext` is exported.
Not a breaking change, but an addition to the API surface.
Hopefully I'm targeting the correct branch. I copied the format of this other PR that made a similar change: https://github.com/chakra-ui/chakra-ui/pull/6142.

feat: export useAlertContext

---

website/src/components/omni-search.tsx

Closes #8490 
In the `omni-search` component of the docsite, the `useEventListener` hook for the keyboard shortcut to open the search modal has incorrect arguments applied to the first two parameters, resulting in the entire hook failing.
Move the two arguments to the second and third param. The first param is looking for a target object which is not needed and can be defined `null`. The second param needs the string `keydown` because that is the mapped event name. And the third param needs the actual event handling.
The current broken behavior will still impact the site when it shifts over to Chakra v3

fix(website/omni-search): correct the usage of `useEventListener`

---

packages/react/__tests__/checkbox.test.tsx

Closes #8511
In testing with the `checkbox` component, there is a `user` wrapped in an `act`.
`act` are used
remove `act`
No

fix: remove `act` when testing with `checkbox` components

---

packages/cli/src/io.ts

The v3 `npx chakra-cli tokens </path/to/theme.ts>` command is currently writing token typing files into the wrong directory.
This is because `import.meta.resolve("@chakra-ui/react")` returns a file URL, with `file://` at beginning, not a path.
The CLI is writing the files to: `/path/to/my-chakra-project/file:/path/to/my-chakra-project/node_modules/@chakra-ui/react/dist/types/styled-system/generated`
The CLI should write files to: `/path/to/my-chakra-project/node_modules/@chakra-ui/react/dist/types/styled-system/generated`
No

[v3] fix(cli/theme-output-dir): fix theme typing output dir by converting file URL into path

---

website/src/components/algolia-search.tsx
website/src/components/omni-search.tsx

Fixes keyboard interaction to open and close the search dialog. Also positively impact click outside to close dialog.
Other current bugs in the search dialog are handled separately.

[v3] fix(website/omni-search): update styling and apply correct disclosure to open and close dialog

---

.changeset/yellow-kings-exercise.md
packages/react/src/components/steps/step-context.tsx
packages/react/src/components/steps/step-item.tsx

Closes # 
Added the `aria-current` attribute to the Stepper.
The current step does not have the `aria-current` attribute.
The current step now has `aria-current="step"` assigned.
No.
References:
- [aria-current - Accessibility | MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current#values)
- [Using the aria-current attribute - Tink - Léonie Watson](https://tink.uk/using-the-aria-current-attribute/)
- [aria-current AT and Browser support](https://codepen.io/Deafinitive/pen/wvqJQxd)

chore(stepper): add aria-current attribute

---

packages/react/__tests__/editable.test.tsx

Closes #8538 
In testing with the `editable` component, there is a `user` wrapped in an `act`.
`act` are used
remove `act`
No

Remove `act` when testing with `editable` components

---

packages/react/__tests__/focus-lock.test.tsx

Closes #8540 
Currently,` fireEvent` is used to test the `focus-look` component.
We think this should be changed to `user`.
`fireEvent` is used.
Change `fireEvent` to `user`
No

fix: change fireEvent to user

---

packages/react/__tests__/number-input.test.tsx

Closes #8578 
Currently, `act` and `fireEvent` are used in the number-input test. We consider it necessary to remove `act` or replace `fireEvent` with `user`.
- delete act
- change fireEvent to user
No

fix: deleted `act` and changed `fireEvent` to `user`

---

website/content/getting-started/vite-guide.mdx

In the Chakra UI setup guide for Vite projects, included the missing import statement `import App from './App';` to ensure clarity and completeness of the example provided. This addition ensures that readers can correctly implement Chakra UI with Vite without encountering import errors.
Closes # 
Added the missing import statement `import App from './App';` to the Chakra UI setup example in the documentation.
The current Chakra UI setup example in the documentation does not include the import statement for the App component.
This PR adds the necessary import statement `import App from './App';` to the example code. This ensures that the App component is properly included when setting up ChakraProvider in Vite projects.
No.
No additional information.

Add missing import for App component in Chakra UI setup guide

---

apps/compositions/src/ui/scrubber-input.tsx

ScrubberInput snippet has the same type name as StepperInput, which can lead to conflicts when both snippets are exported from the same file.
No

fix: update scrubber input type

---

.changeset/wet-wombats-dream.md
packages/react/src/components/link/link-box.tsx

Passing the `target` prop to `LinkOverlay` does not work.
The `target` prop is ignored.
`target` passed along to `chakra.a` element.
No

fix: link overlay target

---

.changeset/sweet-owls-eat.md
packages/components/src/checkbox/checkbox.test.tsx
packages/components/src/checkbox/use-checkbox.ts
packages/components/src/radio/radio.test.tsx
packages/components/src/radio/use-radio.ts

Add for attribute to Radio and Checkbox label if ID is available
Radio and Checkbox nest within the label but are not linked by `for` attribute on the label. Our screenreader (userway) does not read the associated text as a result of that (and the fact that the label text is nested in a span).
Label now contains the `for`
No, I have also attempted not to overwrite any provided `htmlFor` (even though it's not valid TS to have provided `for` or `htmlFor` to Radio or Checkbox)

Add for attribute to Radio and Checkbox label if ID is available (v2.x)

---

.changeset/little-experts-do.md
packages/components/src/color-mode/color-mode-provider.test.tsx
packages/components/src/color-mode/color-mode-provider.tsx
packages/components/src/color-mode/color-mode.utils.test.tsx
packages/components/src/color-mode/color-mode.utils.ts

Closes https://github.com/chakra-ui/chakra-ui/issues/8043
This PR adds the functionality to pass the `nonce` from `EmotionCache` inside the style tag injected by `color-mode.utils.ts` 
Previously, when Chakra Ui was used in a project with a Content Security Policy in place, the following error would be thrown:
```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src http://my-domain.test/ 'nonce-LBVC3WAK89jF6Nh0lWF7IQ=='". Either the 'unsafe-inline' keyword, a hash ('sha256-GNF74DLkXb0fH3ILHgILFjk1ozCF3SNXQ5mQb7WLu/Y='), or a nonce ('nonce-...') is required to enable inline execution.
preventTransition @ color-mode.utils.ts:55
setDataset @ color-mode.utils.ts:17
(anonymous) @ color-mode-provider.tsx:68
(anonymous) @ …
```

fix(components/color-mode): Include `nonce` from `EmotionCache` inside injected style tag

---

.changeset/late-seas-eat.md
packages/next-js/tsconfig.json

Since the `chakra-ui/next-js` package lacks a `tsconfig.json` file, I created one by copying it from the `chakra-ui/react` package.
Due to a likely mistake, the `tsconfig.json` file is missing from the `chakra-ui/next-js` package, leading to an incorrect build being provided since `@chakra-ui/next-js@2.2.1`. This build does not properly import React functions.
```javascript
// dist/esm/link.mjs
import { useStyleConfig, omitThemingProps, chakra } from '@chakra-ui/react';
import NextLink from 'next/link';
import { forwardRef } from 'react';
import { interopDefault } from './interop.mjs';
const LinkEl = interopDefault(NextLink);
const cx = (...classNames) => classNames.filter(Boolean).join(" ");
const Link = forwardRef(function Link2(props, ref) {
const styles = useStyleConfig("Link", …
```

fix: add tsconfig.json to next-js package (v2)

---

.changeset/short-lions-jog.md
apps/compositions/src/examples/heading-with-gradient.tsx
packages/react/__stories__/heading.stories.tsx
packages/react/src/preset-base.ts

Closes #8904 
Added transform function to `backgroundClip` property to appropriately handle `text` value by setting `color` to `transparent`
`bgGradient` property did not work on typography components since color was not set to transparent when `bgClip` was set to `text`
Transform function added to `backgroundClip` property to appropriately set color to transparent when backgroundClip is set to `text`
No. All tests still pass. This just resolves a bug related to setting gradient on typography components and preserves backwards compatibility.
New `Heading` story created showcasing gradient on heading.

fix: backgroundClip text transform

---

.changeset/hip-clocks-exercise.md
packages/components/src/system/system.ts
packages/styled-system/src/create-theme-vars/to-css-var.ts
packages/styled-system/src/system.ts
packages/styled-system/src/utils/types.ts

Closes #8933.
The latest changes to enable custom theme conditions added a lot of overhead in the rendering of styled components.
The rendering of styled components is 5 times slower.
The rendering of styled components is as fast as it was before the implementation of custom theme condition.
I don't think so.
I don't know how to author changeset, hopefully it's correct, otherwise let me know what to change.

fix: pre-compute the isStyleProp function

---

.changeset/honest-mugs-tease.md
packages/components/src/system/use-style-config.ts

Closes #8911.
With the latest versions of Next.js canary and/or React canary, the dev server goes in an infinite loop while rendering pages in which a React element is passed as a prop to any chakra-ui styled components. There is a reproduction repo in the linked issue.
Dev server goes in a infinite loop.
Everything works as expected.
No.
The issue seem to be in some internals of React only when server side rendering. In the browser it works fine.

fix: next.js dev server inifinite loop

---

apps/www/content/docs/get-started/migration.mdx

I just noticed that the `Wrap` component is removed, but in the migration guide it's mentioned like a changed component.
Confusing Wrap mention because that removed.
I just removed Wrap from Component Changes section.
No.

docs: Remove Wrap from Component Changes in migration guide

---

apps/compositions/src/lib/cursor-token-doc.tsx
apps/www/content/docs/theming/cursors.mdx

The docs for the `cursor` token are pointing at the wrong path. Currently they say to use `theme.cursor`, but in reality it should be `theme.tokens.cursor`. At least that's the only way I've made it work locally, but with proper typing, and functionally.
Current incorrect docs page: https://www.chakra-ui.com/docs/theming/cursors

docs: Fix the theme path for `cursor` in the docs

---

apps/www/content/docs/get-started/migration.mdx

✏️ Fix typo in migration.mdx —  `typigns` -> `typings`

---

apps/www/content/docs/get-started/installation.mdx

Corrected a typo in the documentation, changing "when" to "with" for improved clarity.
The documentation currently contains a typo where "when" is used instead of "with," which could lead to minor confusion when reading.
The typo has been corrected to "with," improving the readability and accuracy of the documentation.
> No
> This is a small, non-functional update to the documentation with no impact on code or user functionality.

docs: fix typo 'when' to 'with'

---

.changeset/poor-sheep-study.md
apps/www/content/docs/components/box.mdx

I was reading the documentation and I came across a small typography mistake [on this page](https://www.chakra-ui.com/docs/components/box#psuedo-props).
I'm removing the mistake in "Psuedo"
This PR modifies the title "Psuedo" to "Pseudo" basically.
No
I'm not sure about how I created the changeset... It would be nice to have it in the next version but I'm not sure if all packages should be affected. 
Thank you in advance for your insights !

docs: fix a small typo mistake in title for pseudo

---

apps/www/content/docs/get-started/migration.mdx

Fixes a grammatical error in the v3 migration docs page
No

docs: fix typo in migration docs

---

apps/www/content/docs/get-started/migration.mdx

Was a little confused on how I could replace `LightMode` and `DarkMode` component behavior before reading the docs that states that we can add `dark` and `light` class.
This PR add this to the migration instructions

docs: add LightMode and DarkMode migration instructions

---

apps/www/content/docs/styling/dark-mode.mdx

Updates semantic tokens link to point to `/docs/theming/semantic-tokens`

Update dark-mode.mdx to fix semantic tokens link

---

.changeset/unlucky-seas-turn.md
packages/cli/src/utils/generate-system-types.ts

When trying to typegen with strict tokens, all properties are inferred as any due to a missing imported type. This PR fixes this issue by conditionally importing this type when `strictTokens` are set.
Given the following config:
```ts
import { createSystem, mergeConfigs } from "@chakra-ui/react";
import { defaultConfig } from "@chakra-ui/react/preset";
const config = mergeConfigs(defaultConfig, {
strictTokens: true,
});
export default createSystem(config);
```
When running `pnpm chakra typegen theme.ts`, all properties are inferred as `any`.
When running the above-mentioned command, the properties will be inferred as expected and strict.
No

fix: import WithEscapeHatch type when strictTokens is enabled

---

apps/www/content/docs/theming/slot-recipes.mdx

Related https://github.com/chakra-ui/chakra-ui/issues/9023
Updated the usage of slot recipes.
Currently the docs does not mention the need for manually typing `withProvider` and `withContext`, resulting in many typescript errors (see in original issue) 
The docs are now showing the manual typing with a small note.
No
While I understand the trade-off, I think that manually typing the generics adds too much clutter and impacts development velocity.

docs: add TypeScript typing information for slot recipes

---

apps/www/components/docs/header.tsx

Closes # 
The docs page still contained 2.8.x as version option in the version menu. As there was currently a release for v2 with minor version 10, this is updated.
Displaying 2.8.x as version option in version menu.
Displaying 2.10.x as version option in version menu.
No

docs: update minor version of v2 in version menu

---

.changeset/many-moose-fix.md
packages/react/src/theme/recipes/checkmark.ts

Closes https://github.com/chakra-ui/chakra-ui/issues/9097
Fixes an issue where the `svg` inside the checkmark control was not visible in Safari.
No
N/A

fix: checkmark indicator svg is not visible on safari

---

apps/www/content/docs/get-started/cli.mdx

Closes #  none
When I tried to migrate Chakra UI from v2 to v3, I initially used `pnpx @chakra-ui/cli snippet add`, but it only displayed an error saying "Can't find package."
Later, I switched to npx and discovered that it was due to the `import.meta.resolve` feature, which requires Node.js version to be `>= v20.6.0`.
I spent about 1 hours debugging this, so I think it would be helpful to include this in the documentation as a reminder.
- none
- none
- No
- Screenshots

docs: Update cli.mdx (node.js version reminder)

---

.changeset/eight-pots-judge.md
packages/react/src/hooks/use-media-query.ts

Closes https://github.com/chakra-ui/chakra-ui/issues/9127
call useBreakpointValue() with ssr: false throws "Cannot call an event handler while rendering" error.
calling `getWin()` immediately inner useMediaQuery:
change it to `getWindow?.() ?? window`
no

fix: useBreakpointValue throws error if ssr is false

---

apps/www/content/docs/components/toast.mdx

I found out that the docs for the Toaster are a bit outdated. A few propertynames have been renamed.
Currently, under https://www.chakra-ui.com/docs/components/toast it says:
But as you can see here, **postition** does not exist anymore, it has been renamed to **placement**.
Also, parameters like **bottom-right** do not exist anymore, you renamed it to **bottom-end**.
This is probably not a big problem because you should come across **placement** when searching for properties starting with **p** but the docs should still be correct 😃

docs: correct toast position -> placement

---

apps/www/content/guides/theming-add-custom-font-to-nextjs.mdx
apps/www/content/guides/theming-add-custom-font-to-vite.mdx

This PR adds guides for custom fonts in a nextjs and vite app.
No

docs: add custom font guides

---

apps/www/content/docs/components/portal.mdx

The docs for the `Portal` component refer to a `containerRef` prop, but the actual prop name is `container`.

docs: correct Portal container prop

---

apps/compositions/src/examples/toaster-pause-and-play.tsx
apps/www/content/docs/components/toast.mdx

I noticed that the [Pause and Play](https://www.chakra-ui.com/docs/components/toast#pause-and-play) example for the Toast component didn't seem to work. 
It turns out that the `disabled` properties were inverted causing the buttons to be disabled when they should have been enabled, and vice versa.
Also: 
- Updates the example to disable the _Show Toast_ button while the toast is visible, and re-enable it once the toast is dismissed.
- Adds clarification to the documentation on what pause/resume actually does, because I found that a little unclear when I was reading this.

docs: fix disabled button state in Toast Pause and Play example

---

packages/react/src/styled-system/index.ts

These types are used by styled system utilities, but they are not expored causing inferred type cannot be named type errors when used.
```
@saas-ui/react:build: src/theme/animation-styles.ts(3,14): error TS2742: The inferred type of 'animationStyles' cannot be named without a reference to '../../../../node_modules/@chakra-ui/react/dist/types/styled-system/composition'. This is likely not portable. A type annotation is necessary.
@saas-ui/react:build: src/theme/layer-styles.ts(3,14): error TS2742: The inferred type of 'layerStyles' cannot be named without a reference to '../../../../node_modules/@chakra-ui/react/dist/types/styled-system/composition'. This is likely not portable. A type annotation is necessary.
@saas-ui/react:build: src/theme/text-styles.ts(3,14): error TS2742: The inferred …
```

fix: export missing types

---

.changeset/large-queens-cover.md
packages/react/src/styled-system/create-slot-recipe-context.tsx
packages/react/src/styled-system/index.ts

When exporting withProvider / withContext from a module it results in type cannot be named error because the used types are not exported from the package.
Code:
```
import { createSlotRecipeContext } from '@chakra-ui/react'
export const {
withProvider,
withContext,
useStyles: useNavbarStyles,
} = createSlotRecipeContext({
key: 'navbar',
})
```
Error:
```
src/components/navbar/navbar.context.ts(4,3): error TS4023: Exported variable 'withProvider' has or is using name 'WithProviderOptions' from external module "/Users/eelco/Development/appulse/saas-ui-v3/node_modules/@chakra-ui/react/dist/types/styled-system/create-slot-recipe-context" but cannot be named.
src/components/navbar/navbar.context.ts(5,3): error TS4023: Exported variable 'withContext' has or is using name 'WithContextOptions' …
```

fix: export missing slot recipe context types

---

.changeset/hip-apes-learn.md
packages/react/src/components/timeline/index.ts

Without this change unable to import TimelineTitle component in react.

fix: include missing `TimelineTitle` in exports

---

.changeset/nervous-points-attend.md
packages/cli/src/utils/context.ts

Add support for React Router 7 in the CLI's framework detection logic. Both React Router 7 and Remix projects follow similar project structures with code organized in the `app` directory, so we now detect projects using `@react-router/dev/vite` and treat them the same way as Remix projects.
Currently, the CLI only detects Remix projects by checking for `@remix-run/dev` in the vite config file. However, React Router 7 projects also follow a similar project structure with code organized in the `app` directory, so they should follow the same directory structure conventions.
The CLI now also checks for `@react-router/dev/vite` in the vite config file. If either `@remix-run/dev` or `@react-router/dev/vite` is found, the project will be treated as a Remix project, ensuring consistent component …

feat(cli): support React Router 7 framework detection

---

.changeset/calm-days-yawn.md
packages/cli/src/index.ts

Closes # N/A
Update CLI to display the actual package version instead of a hardcoded version number.
Currently, the CLI version is hardcoded as "3.0.0", which may not reflect the actual package version.
- CLI now reads the actual version from package.json file
- Running `npx @chakra-ui/cli--version` will display the real package version
No
This change improves version accuracy by ensuring the CLI displays the version that matches the installed package version.

fix(cli): output the real version

---

.changeset/friendly-ligers-arrive.md
packages/react/src/theme/recipes/menu.ts

The menu recipe didn't utilize --available-height.
Same applies to select, @segunadebayo do you want to implement this?

fix: add max available height to menu content

---

apps/www/content/docs/components/close-button.mdx
apps/www/content/docs/components/environment-provider.mdx
apps/www/content/docs/components/format-byte.mdx
apps/www/content/docs/components/format-number.mdx
apps/www/content/docs/components/icon-button.mdx
apps/www/content/docs/components/radio.mdx
apps/www/content/docs/components/rating.mdx
apps/www/content/docs/components/segmented-control.mdx
apps/www/content/docs/components/text.mdx

> Updates broken links in docs.
> Accidentally came across the link to the `Text` component not working properly. I wanted to fix it, and I realized I might as well just go through all of the components and fix which have broken links & update them. `Text` and `Icon-Button` had broken links that I could update, for the others, their source was not under the components directory, and at first thought I removed the source links, but I can update this PR if need be. The `environment-provider.mdx` mentions that it's using Zag.js internally, and I couldn't find any source files for this so I also removed this link, but again, I can update the PR if need be.
> The broken source links now either work and lead you to the correct source information, or they the source links are removed.
No.
None.

docs: updated source links

---

apps/www/content/docs/get-started/cli.mdx

Closes #
Since the way to add all snippets was changed to need a flag in the cli i thought the docs should showcase this, because its a bit misleading right now how to add all the snippets
No

Added --all flag to cli docs

---

apps/www/content/docs/components/skeleton.mdx

The snippet installation instructions for the Skeleton page does not align with the rest of the docs. I've updated it to use the new chakra cli tool, to be consistent with the rest. 
No
Thanks for a great design system! It's a joy to use :)

Docs: Update skeleton snippet installation guide

---

.changeset/little-readers-retire.md
apps/www/content/docs/get-started/migration.mdx

Closes # 
> Updates the migration doc to make it obvious you must add `semanticTokens` when you update `colorScheme` to `colorPalette` for it to work.`
> Nil
> Docs update
No

docs: update migration doc about changing `colorScheme` to `colorPalette`

---

apps/www/content/docs/components/hover-card.mdx

> The purpose of this PR is to fix typo on `hover-card`. The `import` statement should be from `hover-card` (`@/components/ui/hover-card`) instead of `popover` (`@/components/ui/popover`)
```jsx
import {
HoverCardArrow,
HoverCardContent,
HoverCardRoot,
HoverCardTrigger,
} from "@/components/ui/hover-card"
```
> When you import some parts of Hover Card (example: `HoverCardArrow`) from `@/components/ui/popover` , you will get warning because `Module '"@/components/ui/popover"' has no exported member 'HoverCardArrow'.` and you can't run the app.
> The changes should fix the docs so that you can follow it and import `hover-card` properly.

docs(hover-card): fix typo import from popover

---

README.md

It's expected that when an NPM badge is clicked on a README, we should go to its NPM page. Doesn't hurt if the GitHub badge has a link as well.
Both link to their images
Both link to their corresponding pages (NPM and GitHub repo pages). We can now click them to navigate!
No

[README] Add proper links to npm and github badges

---

apps/www/content/guides/theming-custom-breakpoints.mdx

the breakpoint guide before the change didn't work and caused errors and when checking the style page it was using this format to declare the custom breakpoints
Closes # 
the breakpoint guide caused errors and was different from the official documentation
no behaviour just the guide
no behaviour just documentation
Yes the code wasn't running as expected and error were showing

docs: update theming-custom-breakpoints.mdx

---

apps/www/components/site/accessibility.section.tsx
apps/www/next.config.mjs

Closes #9365 
This change updates the `/docs` route to lead to its intended destination.
The current `/docs` route leads to a 404 at https://www.chakra-ui.com/docs/get-started/overview/installation
The new `/docs` route will lead to its intended destination at https://www.chakra-ui.com/docs/get-started/installation
No

docs: fix /docs endpoint

---

packages/react/src/components/image/image.tsx

Closes # 
> replace broken link in JSDoc comment
The JSDoc comment  in file `chakra-ui\packages\react\src\components\image\image.tsx` at **line 32** contained a broken link, leading to a 404 error page on the Chakra UI docs.
The broken link `https://chakra-ui.com/image` was replaced by `https://www.chakra-ui.com/docs/components/image` which now leads to the correct documentation for the Image component.
> No

update broken documentation link

---

apps/www/components/pagination.tsx
apps/www/components/sidenav.tsx
apps/www/lib/use-route.ts

The problem is a 404 error when going to the URL: `https://www.chakra-ui.com/docs/get-started//showcase` because the URL itself is incorrectly formed. The picture below shows where to click to reproduce the problem.
This happens when you click on the pagination button, but also clicking on Showcase in the sidebar does not cause the error, but it also does not redirect the user to a new page, which contradicts the external parameter.
After the changes made, the behavior is as expected: when clicking on a link (in the sidebar or in the pagination) if there is an external parameter - it redirects the user to another page
No

fix: the logic for external routes

---

apps/www/content/docs/styling/text-styles.mdx

📝 Description
Fixed an incorrect description in the Chakra UI documentation for the textStyles configuration.
⛳️ Current behavior (updates)
In the file `chakra-ui/apps/www/content/docs/styling/text-styles.mdx` in line 57 there is an inconsistency in the description of textStyles. That field should be next to the extend field, not inside it
🚀 New behavior
An edit was made with the correct description
💣 Is this a breaking change (Yes/No):
No
📝 Additional Information

fix doc: moved textStyles from extend

---

website/content/getting-started/index.mdx

This updates the v2 docs. I just ran the command to check what version of framer motion would be resolved and ended up with chakra ui 3 being installed.
Running the install command at https://v2.chakra-ui.com/getting-started will actually install chakra ui v3.
Arguably that is what everybody should migrate to asap and it's definitely the cooler kid in town now – however if someone specifically looks at the v2 docs, they would propably expect to get v2 from the install instructions :smile: 
Running the install command at https://v2.chakra-ui.com/getting-started will now install chakra ui v2.
No

Amend install command so that v2 docs don't install v3

---

apps/compositions/src/ui/input-group.tsx

Closes #9420
Adds the correct typing for the `children` prop in the `InputGroup` component to resolve compatibility issues with TypeScript and prevent build errors in projects using Chakra UI.
Currently, the `children` prop in `InputGroup` is typed generically (`React.ReactElement<unknown>`), which may cause build errors in TypeScript projects when using incorrectly typed child elements.
The updated typing expects a child of type `React.ReactElement<InputElementProps>`. This ensures TypeScript can correctly validate the children of `InputGroup` and prevents compilation errors.
No
Without the correct typing, build errors can occur in TypeScript projects that utilize the `InputGroup` component. This is because TypeScript cannot properly infer the expected types when using custom child …

fix(input-group): add proper typing for children prop

---

packages/react/src/anatomy.ts
packages/react/src/theme/recipes/color-picker.ts
packages/react/src/theme/recipes/fieldset.ts

- The color picker anatomy is not exported as other anatomies
- The fieldset anatomy doesn't contain all the keys
- You can not import the anatomy like `import { colorPickerAnatomy } from "@chakra-ui/react/anatomy";`
- If you import the fieldset anatomy the content key is missing
- Exporting the color picker anatomy like other components
- Extending the fieldset anatomy with the content key
No

fix: wrong anatomy exportation

---

packages/react/src/theme/recipes/number-input.ts

The input is using the semantic token radii of l2. But the number input triggers are using the token radii.xs
If I decide to increase/decrease the radii semantic tokens, the input triggers will not be adjusted as they are not using the semantic token
Using the semantic token on the number input triggers 
No

fix: align input radius

---

apps/www/content/docs/get-started/migration.mdx

The migration guide refers to `<NumberInput.Field />` which is not exported, which I believe should be `<NumberInput.Input />`
> Fix example of NumberInput usage, replacing NumberInput.Field with NumberInput.Input to match what's exported from package
> Corrects mistake in documentation
> None
No

fix docs: NumberInput example in Migration guide

---

.changeset/orange-shrimps-exercise.md
packages/react/src/theme/recipes/select.ts

Visually, the background of the highlighted Select option is much more emphasized in dark mode than in light mode:
To my understanding, the same semantic token should be used for light mode and dark mode in this case, as the highlighted option should have the same emphasis in light and dark mode.
But if we feel that using the semantic token in both light and dark mode leads to a bad contrast, then it means the colors of the semantic tokens are not optimal, and should be changed.

refactor(recipe): use the same semantic token for Select _highlighted regardless of theme

---

packages/components/src/highlight/highlight.tsx
packages/components/src/system/providers.tsx
packages/components/src/system/system.types.tsx
packages/components/src/system/system.utils.ts
packages/components/src/toast/create-standalone-toast.tsx
packages/components/src/toast/toast.tsx
packages/theme-tools/src/component.ts

Fix issue where `chakra.x` factory component props throws TS error in React 19. The same as https://github.com/chakra-ui/chakra-ui/commit/be8f80ad9e1a2c987ebb477944377ed72138e33c, but for v2.
No

fix: JSX namespace

---

apps/www/content/docs/get-started/migration.mdx

Closes #9503 
Fixed wrong code in migration guide that leads to errors with next-themes when "attribute" is set to "class" in next-themes ThemeProvider
Migration guide change. The proposed code in it causes errors in specific scenario. 
The migration guide provides correct code for how Chakra is working now when using the snippets.
No

fix(docs): Fixed error in migration guide when using snippet Provider

---

packages/react/src/theme/recipes/select.ts

I noticed a slight difference in normal and select inputs' placeholders.
Select input's span uses flat color styling without opacity, differing from the normal input's placeholder, which uses a color-mixing technique with 80% opacity.
Implemented consistent color-mixing styling for the select input's placeholder, matching the styling of the normal input placeholders for consistency.
https://github.com/user-attachments/assets/06de736a-2661-4ab8-8ef9-d8ecb619b2ad
No
N/A

fix(select): improve select placeholder styling

---

apps/www/content/docs/styling/dark-mode.mdx

The attribute "theme" does not exist, the correct property is "value".
This [demo](https://github.com/chakra-ui/chakra-ui/blob/main/sandbox/vite-ts/src/main.tsx) also use "value" instead of "theme"
theme -> value
No

docs: update dark-mode

---

packages/cli/src/commands/snippet.ts
packages/cli/src/utils/get-file-dependencies.ts

Fix `chakra snippet add` overwriting existing files even without `--force` specified.
`chakra snippet add` overwrites existing files even without specifying `--force`.
`chakra snippet add` checks if the file for the snippet already exists and only overwrites with `--force`.
No, but users might have relied on the automatic overwriting.
The `chakra snippet add` command erroneously relied on the snippet `id` to detect whether it was already existing. This does not work, because the `id` comes without the file extensions and therefore `existsSync(id)` will always fail.
This is fixed by extracting the filename from the registry instead and falling back on the id, if no entry was found. The latter might be better handled by proper error messages and early returns but no such facility exists at …

fix(cli): properly check for existing files when not run with --force

---

apps/www/content/docs/get-started/environments/shadow-dom.mdx
apps/www/content/docs/get-started/frameworks/next-app.mdx
apps/www/content/docs/get-started/frameworks/next-pages.mdx
apps/www/content/docs/get-started/frameworks/remix.mdx
apps/www/content/docs/get-started/frameworks/vite.mdx
apps/www/content/docs/get-started/installation.mdx

Closes #
When I used the sample code listed in the documentation, an error occurs in the import statement.
In the following section of source code, an error message is displayed indicating that the module does not exist and the button is not displayed.
```
import { Button } from "@/components/ui/button"
```
The button is displayed.
No

fix docs: update docs of get started

---

.changeset/warm-spiders-do.md
packages/react/src/theme/recipes/breadcrumb.ts

Closes #9615
Hides list marker and Rotates separator in rtl parent/page.
currently the chevron is in the wrong direction (facing right instead of left) and list marker from user set list-style property can be visible inside breadcrumb's UI.
Now, chevron is rotated to face the correct direction for RTL breadcrumb and using `listStyle:none` property no marker is visilble for Items.
No

fix: improve rtl support for breadcrumb

---

apps/www/content/docs/get-started/cli.mdx

Closes # 
This PR fixes a documentation error where the `--outdir` option was mistakenly shown with `chakra snippet` command instead of the correct `chakra snippet add` command. 
This update ensures users follow the proper usage (snippet add --outdir xxx) and helps prevent any potential confusion.
```
chakra snippet --outdir ./components/custom
```
The documentation example incorrectly shows the `--outdir` option with the `snippet` command, which may mislead users into running `snippet --outdir xxx` and encountering errors.
Updated the documentation to correctly demonstrate the usage of the `--outdir` option with the `snippet add` command. Users should now use `snippet add --outdir xxx` for the expected behavior.
No
related discussion is here: …

Fixed CLI docs example that was incorrect and misleading.

---

package.json
pnpm-workspace.yaml

Closes # 
Remove references to the legacy website folder and its related scripts, as it is no longer used in Chakra UI version 3.
The` pnpm-workspace.yaml `file and` package.json` scripts currently include references to the website folder. However, the website folder is no longer in the repository, and running `pnpm --filter=./website build` returns: 'No projects matched the filters ~'.
- Removed `website` from `pnpm-workspace.yaml`.
- Deleted the `website` script from `package.json`.
- These changes ensure that references to non-existent packages are cleaned up, reducing confusion and potential errors in the workspace.
No
- The website folder seems to have been deprecated and removed in Chakra UI version 3.
- If the website folder is still required or referenced externally, this PR can …

chore(package): remove legacy `website` package and scripts

---

apps/www/content/docs/styling/chakra-factory.mdx

> The current link is not valid
> Goes to a 404 page
> Goes to the composition page
No

docs: fix composition link

---

packages/components/src/checkbox/use-checkbox.ts

Closes #9647
This updates the v2 Checkbox component to handle `isIndeterminate` accessibility according to the W3C specifications:
https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox-mixed/
Currently, there is no ARIA support for indeterminate checkboxes.
This changes `aria-checked` based on the value of `isIndeterminate`
No

[v2] fix checkbox indeterminate state accessiblity

---

.changeset/weak-turtles-check.md
packages/react/src/components/aspect-ratio/aspect-ratio.tsx

Closes #9711
CSS prop value now is merging config.
Before fix, CSS prop on AspectRatio component is overriding the default CSS value.
After fix, provided CSS prop value will merge (as it was intended).
No

fix: avoid to overrride aspect ratio css prop when css prop is provided

---

README.md

Closes # 
The link to Ryan Florence’s tweet in the "Testimonials" section no longer works because the tweet was removed. This PR updates the link to Ryan Florence’s main Twitter profile.
A broken link points to a removed tweet, resulting in unavailable page.
The link now directs to Ryan Florence’s profile, preserving proper attribution without leading users to a non-existent resource.
No.
This is a minor documentation fix. If there’s a preferred link or format, I’m happy to adjust.

docs(readme): replace expired tweet link with Ryan Florence's profile

---

apps/www/content/docs/theming/radii.mdx

📝 Description
This PR adds a reference table for converting between px and rem, making it easier for developers to switch seamlessly between units.
⛳️ Current behavior (updates)
Currently, there is no clear reference for px to rem conversions in the documentation, which may require developers to calculate values manually.
🚀 New behavior
Adds a table listing common rem values and their px equivalents, improving accessibility and consistency in UI design.
💣 Is this a breaking change (Yes/No):
No
📝 Additional Information
Using rem ensures better scalability, accessibility, and maintainability. This update helps developers quickly find the correct unit conversions without extra effort. 🚀

docs: [v3.8] Update radii.mdx

---

.changeset/rare-bugs-clap.md
packages/components/src/checkbox/use-checkbox.ts
packages/components/src/radio/use-radio.ts

Avoid re-rendering when focus visible tracker emits a value. Greatly improves performance on pages with lots of checkboxes and/or radios.
Fixes #9771

fix: checkbox / radio perf

---

apps/www/components/mdx/prop-table.tsx

The path of Composition within the `asChild` row of `Item` section leads to a "404 Page Not Found". It needed a minor fix by updating the path in `apps/www/components/mdx/prop-table.tsx` file.
The link for Composition in the `asChild` row of `Item` section leads to a "404 Page Not Found". The older link led to [composition](https://www.chakra-ui.com/docs/guides/composition).
https://github.com/user-attachments/assets/1d1b5042-feef-4629-8671-e9ad445ba304
I have fixed the path. Updated it to the actual one i.e. [Composition](https://www.chakra-ui.com/docs/components/concepts/composition)
https://github.com/user-attachments/assets/821a1533-3b95-4e52-9b79-df38eddf4716
No

docs: update the link to composition page

---

apps/www/public/types/ark/menu.json

Closes #9884  
This PR updates the documentation for the `Menu` component, correcting the default values for `lazyMount` and `unmountOnExit`. 
The previous values in the documentation were outdated and incorrect based on the latest changes in Chakra UI.
- `lazyMount` was documented as `false`, but the correct default is `true`.
- `unmountOnExit` was documented as `false`, but the correct default is `true`.
- Updated `lazyMount` to correctly reflect `true` as the default value.
- Updated `unmountOnExit` to correctly reflect `true` as the default value.
No

fix(docs): update default values for lazyMount and unmountOnExit in Menu

---

apps/www/public/types/ark/tooltip.json

Like #9888, but for the `Tooltip` component.
`lazyMount` and `unmountOnExit` are true by default since [3.6.0](https://github.com/chakra-ui/chakra-ui/blob/main/.changelog/v3.mdx#360---2025-02-02).
- `lazyMount` was documented as `false`, but the correct default is `true`.
- `unmountOnExit` was documented as `false`, but the correct default is `true`.
- Updated `lazyMount` to correctly reflect `true` as the default value.
- Updated `unmountOnExit` to correctly reflect `true` as the default value.
No

fix(docs): update default values for lazyMount and unmountOnExit in Tooltip

---

.changeset/polite-boxes-thank.md
packages/react/src/components/breadcrumb/breadcrumb.tsx

Closes # 
- Added `aria-hidden="true"` attribute to the separator component of the breadcrumb.
- The separator in a breadcrumb should not be read by screen readers. ([Refer to W3C documentation](https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/examples/breadcrumb/#accessibilityfeatures))
No

refactoring(breadcrumb.tsx): prevent screen reader from reading the separator

---

apps/compositions/src/examples/highlight-multiple.tsx

`Accentuate` in the array passed to query was capitalized, however `accentuate` in the content was lowercase.
This caused the accentuate in the content to not be highlighted.

docs: fix capitalization error in highlight multiple docs

---

packages/components/src/modal/modal.tsx
packages/props-docs/generated/modal.json

We observed we're unable to set the `<Modal lockFocusAcrossFrames={false} />`. Further checking the [v2](https://github.com/chakra-ui/chakra-ui/blob/v2/packages/components/src/modal/modal.tsx#L158) [code](https://github.com/chakra-ui/chakra-ui/blob/0511f22/packages/components/src/modal/modal.tsx#L158) stated that it was unable to override due to the logical OR operator
The `lockFocusAcrossFrames` prop of `<Modal />` is always `true` and is unable to override. This is also inconsistent with the v2 doc. https://v2.chakra-ui.com/docs/components/modal/props
1. Allow overriding the `lockFocusAcrossFrames` prop of `<Modal />`
2. Update the document of it to show the matching default value
No.

fix(v2 / modal): Allow overriding lockFocusAcrossFrames prop

---

apps/www/content/docs/components/radio.mdx

Remove unused import of `Radio` component from the radio documentation page to keep the docs accurate.
The radio component documentation currently shows an import statement that includes the `Radio` component which causes a TypeScript error:
```
Module "@chakra-ui/react" has no exported member Radio.
```
This indicates that the import statement is incorrect and needs to be updated.
- Remove the non-existent `Radio` import from the documentation.
- Keep only the necessary `RadioGroup` import.
- Fix the TypeScript error for developers who copy the code.
- Ensure documentation accuracy.
No.

docs: remove unused import of Radio component

---

.changeset/popular-queens-try.md
packages/components/src/slider/slider-utils.ts

Closes #9151
The following pull request addresses an issue in V2 of Chakra UI, where the custom size `SliderThumb` component has an incorrect offset relative to the `SliderTrack`. 
At the moment, the `SliderThumb` component gets rendered with a slight offset compared to the actual value. This appears to be the case for both keyboard and mouse interactions and appears to be caused by reliance on the hardcoded `--slider-thumb-size` variable, meaning that a custom-size slider thumb was incorrectly offset. As a side effect, this also meant that the `SliderThumb` component could be moved beyond the `SliderTrack`.
<video src="https://github.com/user-attachments/assets/f33fb3fa-5b11-4ffe-97d7-6da54223f8a1"></video>
You can find more details about this issue, along with steps to reproduce it, in …

fix(slider-v2): Correctly offset custom size slider thumb

---

packages/react/src/theme/recipes/checkmark.ts

Semantic token `cursor.checkbox` is not being used by the `<Checkbox />` component. This PR fixes this by mimicking the same implementation as in the `< RadioGroup />` component. 
Semantic token `cursor.checkbox` not taken into account.
Semantic token `cursor.checkbox` consumed by the `<Checkbox />` component.
No
N/A

fix(checkbox): cursor token

---

packages/components/src/system/style-config.test.tsx
packages/components/src/system/use-style-config.ts

Closes #9984 
Omit react elements from `mergedProps` in `useStyleConfigImpl`
SSR rendered components freeze in dev mode when non-memoized react components are passed to `useStyleConfigImpl`
This PR omits those props from being uses as they are not needed anyway.

fix(styleconfig): omit react elements from props used in useStyleConfig

---

.changeset/sweet-impalas-return.md
packages/react/src/theme/recipes/drawer.ts

Fix drawer close animation for RTL pages when placement is end
Currently, on RTL pages, when the placement is set to `end` (the default), the close animation is incorrect. The drawer appears from the left side but doesn’t move to the left side when closed.
This PR fixes the animation name for said conditions.
No

Fix drawer close animation

---

apps/compositions/src/examples/input-with-focus-error-color.tsx
packages/react/src/theme/recipes/input.ts

Fix the focus state of the flushed variant when the input is in an error state.
https://github.com/user-attachments/assets/648d69ca-a980-4659-a21a-52f221206d07
https://github.com/user-attachments/assets/02108cc7-9f59-4afe-bb57-d52c60678501
No

fix(input): flushed input variant error focus style 

---

.changeset/gorgeous-fans-argue.md
packages/react/src/styled-system/css.types.ts
packages/react/src/styled-system/recipe.types.ts

Additional fixes to support TS exactOptionalPropertyTypes

fix(system): allow undefined for optional properties in CSS and recipe types

---

apps/compositions/src/ui/native-select.tsx

rename interface NativeSelectField to NativeSelectFieldProps consistency

fix: rename interface NativeSelectField to NativeSelectFieldProps

---

packages/react/src/theme/recipes/dialog.ts

Closes #10170
Use `dvh` and `dvw` units instead of `vh` and `vw` to dynamically adjust to viewport size changes.
Dialogs with size set to `"full"` might overflow on certain mobile devices.
Dialogs with size set to `"full"` adjust dynamically to viewport size changes.

fix(dialog): use dvh and dvw units

---

apps/compositions/src/ui/toggle-tip.tsx

The ToggleTip composition was missing contentProps, resulting in lack of customizability
Added contentProps to ToggleTip
Matches Tooltip's implementation: https://github.com/chakra-ui/chakra-ui/blob/a8ae90cb02044b54a2bb221d619b997793697244/apps/compositions/src/ui/tooltip.tsx#L9-L33

feat(compositions): add contentProps to ToggleTip

---

apps/compositions/src/examples/checkbox-with-form.tsx

Fix to the composition example of the checkbox documentation: https://www.chakra-ui.com/docs/components/checkbox#composition
`<form>` has `onSubmit` event defined but the submit button was missing the `type="submit"`.
Submit button did nothing when clicked (onSubmit was dead code)
Submit button now shows the form elements in the console.

fix(docs): submit button in checkbox-with-form example

---

apps/compositions/src/ui/color-mode.tsx

Closes #10292 
> Fixes the Cumulative Layout Shift (CLS) on the color mode button by ensuring the Skeleton fallback matches the IconButton's boxSize. This resolves a minor UI jump during hydration.
> Currently, the color mode button, when initially rendered, has a Skeleton fallback with `boxSize="8"`, while the `IconButton` itself uses `boxSize="9"`. This mismatch causes a slight layout shift (CLS) as the component hydrates.
> The `Skeleton` fallback for the color mode button now uses `boxSize="9"`, matching the `IconButton`. This eliminates the layout shift, providing a smoother user experience during the initial render.
No
> N/A

fix: resolve CLS in color mode button (#10292)

---

apps/www/content/docs/components/checkbox-card.mdx

Closes #10307 
For grouping CheckboxCard components documentation mentions a non-existent component called CheckboxCardGroup. 
The example correctly shows <CheckboxGroup /> instead
Documentation description is:
Use the CheckboxCardGroup component to group multiple checkbox cards.
Documentation description is:
Use the CheckboxGroup component to group multiple checkbox cards.
No

fix(docs): typo CheckboxCardGroup component on Checkbox Card/Group section

---

.changeset/thirty-eels-battle.md
packages/react/src/theme/recipes/table.ts

This PR fixes an issue where the `stickyHeader` prop does not work on the `Table` component when `variant="outline"` is set.
When using the `stickyHeader` prop along with `variant="outline"`, the table header does not remain sticky at the top of the viewport upon scrolling.
Example: https://stackblitz.com/edit/fmajukce?file=src%2FApp.tsx
The table header correctly sticks to the top of the viewport when scrolling, even when the `outline` variant is set.
No
I don't know why `overflow: hidden` is set.

fix(table): ensure stickyHeader works with outline variant

---

apps/www/docs.config.ts

> Fixes navigation to Showcase page from /docs
> When in /docs, navigating to the Showcase page was broken
> User can now navigate to the Showcase page from /docs

fix(www): update showcase navigation

---

.changeset/eight-plums-warn.md
packages/cli/src/commands/blocks.ts

Removed the filtering logic that excluded "documentation" blocks from the CLI blocks command, allowing users to access and download all blocks, including documentation blocks.
Previously, the CLI filtered out blocks in the "documentation" group, preventing users from accessing documentation-related blocks via the `blocks` command.
All blocks from the Chakra Pro API are now available through the CLI, including documentation blocks. Users can discover and download any block without arbitrary filtering.
No - This is purely additive functionality. It removes a restriction rather than changing existing behavior.
**Files changed:**
- `packages/cli/src/commands/blocks.ts` - Removed the filter that excluded documentation blocks

fix(cli): remove documentation blocks filtering

---

packages/react/src/components/skip-nav/skip-nav-link.tsx

SkipNavContent and SkipNavLink were broken because both of them were elements having the same `id` and the browser would always focus on SkipNavLink since it appears earlier in the DOM. This fix removes the `id` attribute from SkipNavLink so that it always focuses on SkipNavContent.
This Issue can be reproduced from the [docs page](https://chakra-ui.com/docs/components/skip-nav)
- Press <kbd>tab</kbd> to focus on SkipNavLink
- Press <kbd>enter</kbd> to trigger skip navigation
- URL now includes `#chakra-skip-nav` at the end but focus does not change
- Press <kbd>tab</kbd> to focus on SkipNavLink
- Press <kbd>enter</kbd> to trigger skip navigation
- URL now includes `#chakra-skip-nav` at the end and **the focus is on SkipNavContent**
No

bugfix: remove id attribute from SkipNavLink
