packages/chakra-ui/src/Spinner/index.js
=> Add borderStyle prop to Spinner

packages/chakra-ui-docs/pages/button.mdx
This PR fixes a broken link in the documentation.
=> Fixes external URL

packages/chakra-ui/src/CircularProgress/index.js
=> [CircularProgress] Force using same size numbers

packages/chakra-ui/src/IconButton/index.d.ts, packages/chakra-ui/src/Toast/index.d.ts, packages/chakra-ui/src/index.d.ts
Just a few TypeScript definition updates. Thanks for the amazing work on Chakra UI!
Fixes #63
=> Fix TypeScript definitions

packages/chakra-ui-docs/pages/index.js
Hi there, thanks for this project, looks interesting :)
Just a quick PR to fix the casing of GitHub.
=> Fix casing of GitHub

packages/chakra-ui/src/Slider/index.d.ts
=> Add typings for Slider.onChange

packages/chakra-ui-docs/pages/getting-started.mdx
=> Fixed little typo.

packages/chakra-ui-docs/pages/textarea.mdx
What does this pull request do?
=> Add resize prop to Textarea docs, closes #93

packages/chakra-ui/src/Button/index.d.ts
add types to allow leftIcon and rightIcon to be icons from libraries like react-icons and not only strings
=> fix(button): fix the types for leftIcon and rightIcon

packages/chakra-ui/src/index.d.ts
=> fix(types): include named exports from theme in main type definitions

packages/chakra-ui/src/CSSReset/preflight.js
This works around an old jsdom bug present in jest v24 dependencies.
Closes #161.
=> fix(cssreset): remove comments from CSSReset preflight.js

CONTRIBUTING.md
add branch naming convention section
add more information regarding PR submission
=> Update the Contributing.md file

packages/chakra-ui-docs/pages/stack.mdx, packages/chakra-ui/src/Stack/examples.js, packages/chakra-ui/src/Stack/index.d.ts, packages/chakra-ui/src/Stack/index.js
=> [Stack] Add `isReversed` prop

packages/chakra-ui-docs/pages/stack.mdx, packages/chakra-ui/src/Stack/examples.js, packages/chakra-ui/src/Stack/index.d.ts, packages/chakra-ui/src/Stack/index.js
=> [Stack] Fix spacing of items when flex-direction is reverse

packages/chakra-ui-docs/pages/numberinput.mdx
=> chore: numberInput docs to show how to implement numeric keyboard

packages/chakra-ui/src/NumberInput/index.js, packages/chakra-ui/src/useNumberInput/index.d.ts, packages/chakra-ui/src/useNumberInput/index.js
Fixes #181.
It will fix the behavior for the future `NumberInput` as we can re-use the logic
=> fix: numberInput stepping twice on mobile

packages/chakra-ui-docs/components/CodeBlock.js, yarn.lock
=> chore(docs): enabled button to copy to clipboard on readonly code blocks

packages/chakra-ui/src/Checkbox/index.js, packages/chakra-ui/src/ControlBox/index.js
Follows the [WAI-ARIA Checkbox Pattern](https://www.w3.org/TR/wai-aria-practices/#checkbox).
Fixes #222.
=> fix: set aria-checked to mixed when partially checked

packages/chakra-ui/package.json
Using react hooks requires version 16.8 or later
=> chore: pin react peerDependency

packages/chakra-ui/src/ButtonGroup/index.js
=> Collapse borders in ButtonGroup with isAttached enabled

packages/chakra-ui/src/Stack/index.js
=> fix(stack): convert React children to array before processing

packages/chakra-ui-docs/pages/iconbutton.mdx
Fixes broken react-icons link in https://chakra-ui.com/iconbutton#with-custom-icon.
=> fix(docs): broken link in iconbutton.mdx

packages/chakra-ui/src/Checkbox/examples.js, packages/chakra-ui/src/Checkbox/index.d.ts, packages/chakra-ui/src/Checkbox/index.js
I've added the isReadOnly prop to Checkbox component.
#52
=> [Checkbox] Add 'isReadOnly' attribute

packages/chakra-ui-docs/components/components.js, packages/chakra-ui-docs/pages/divider.mdx
Add the `Divider` component to the documentation
=> docs: add "Divider" component to the documentation

packages/chakra-ui/src/NumberInput/index.d.ts
=> fix: use `UseNumberInputProps` instead of `useNumberInputProps`

packages/chakra-ui/src/Modal/index.js
Fixes issues with Drawer (and potentially AlertDialog) pointed by @caiorios in #268
=> chore: generate portal id inside Modal component

.codesandbox/ci.json
1. codesandbox template based on https://codesandbox.io/s/epic-zhukovsky-27i2n
2. you can have a quick preview on https://github.com/sinchang-bot/chakra-ui/pull/1
3. project admin needs to install codesandbox GitHub app first.
closes #246
=> ci: add codesandbox config

packages/chakra-ui/package.json, packages/chakra-ui/src/useNumberInput/utils.js
Remove pretty-num and replace with pure Javascript
=> refactor: pretty-num

packages/chakra-ui-docs/pages/select.mdx
new icon -> new background color
=> (docs): update select.mdx

packages/chakra-ui/src/RadioButtonGroup/index.js
=> fix: ignore Tab key press for keyboard navigation

packages/chakra-ui-docs/pages/collapse.mdx
Just modified the document to fix a typo.
=> Fixed typos

packages/chakra-ui/src/Popover/index.d.ts
=> Fix Popover usePortal type definition

packages/chakra-ui-docs/pages/badge.mdx
Fixed link to theming page on https://chakra-ui.com/badge
Closes #395
=> [docs] fix link to theme page

packages/chakra-ui-docs/pages/cssreset.mdx
A new page for the CSSReset component in chakra-ui-docs.
Closes #381
=> Documentation for the CSSReset component

packages/chakra-ui/src/Tag/index.d.ts, packages/chakra-ui/src/Tag/index.js
Hey Charka people!
This is my very first PR to OS, so please bear with me. 
I added the ability to disable the TagCloseButton component, and I also added the disabled styles to it.
I tried my best matching your code style, but if anything is not 100%, I'm very happy to change it.
Thanks for this awesome lib!
=> feature(tagclosebutton): added isdisabled style and types to tagclosebutton

packages/chakra-ui/src/Tooltip/index.js
=> fix(tooltip): Don't show tooltip after mouse leaves the target component

packages/chakra-ui/src/Input/styles.js
=> Remove line-height properties from Input styles

packages/chakra-ui/src/Editable/index.js
Closes #424 
This MR adds the functionality to call `onCancel()` when the field is blurred.
=> feat(editable): cancel on blur

packages/chakra-ui/src/Checkbox/index.js
Added `aria-labelledby` prop to chekcbox input
=> feat(checkbox): add aria-labelledby attribute to input

packages/chakra-ui-docs/components/components.js, packages/chakra-ui-docs/pages/skeleton.mdx, packages/chakra-ui/src/Skeleton/examples.js, packages/chakra-ui/src/Skeleton/index.d.ts, packages/chakra-ui/src/Skeleton/index.js, packages/chakra-ui/src/index.d.ts, packages/chakra-ui/src/index.js
=> Add Skeleton component

package.json, packages/Menu/src/Menu.tsx, packages/NumberInput/package.json, packages/PinInput/src/Pin-Input.tsx, packages/Popover/src/Popover.tsx, packages/Progress/package.json, packages/Progress/src/Progress.line.tsx, packages/Progress/src/Progress.utils.tsx, packages/Tabs/src/Tabs.tsx, packages/Toast/package.json, packages/Toast/src/Toast.hook.tsx, packages/Toast/src/Toast.tsx, packages/preset-base/package.json, packages/styled/package.json
=> fix(build): Initial Setup

packages/chakra-ui-docs/pages/theme.mdx
Correct the typo error in the Breakpoints section.
=> fix(docs): Update for typo

packages/chakra-ui-docs/components/GitHubButton.js, packages/chakra-ui-docs/components/Header.js, packages/chakra-ui-docs/pages/index.js
=> fix: move github button out of header on mobile

package.json, packages/chakra-ui/src/Stack/examples.js, packages/chakra-ui/src/Stack/index.js
=> build: added forwardRef to Stack

packages/css-reset/src/CSSReset.tsx, packages/parser/src/configs/pseudo.selector.ts, website/components/MDXComponents.js, website/pages/pseudobox.mdx
=> fix: use pseudo element instead of pseudo class

.team/CODE_REVIEW_GUIDELINE.md, .team/COMPONENT_TEST_CHECKLIST.md
This PR creates a component test checklist document, which outlines some basic items that should be verified for each component module to ensure that it meets our testing standards:
appropriately, updates state correctly, etc.)
Since accessibility is the core of The Chakra Way™️, we have multiple related checklist items to help us guarantee that our components remain as accessible as possible.
=> chore: create component test checklist document

.storybook/main.js, packages/checkbox/migration.md, packages/preset-base/src/components/Input.ts, packages/preset-base/src/components/PinInput.ts, packages/radio/README.md, packages/radio/migration.md, packages/radio/src/Radio.stories.tsx, packages/radio/src/Radio.tsx, packages/radio/src/RadioGroup.hook.tsx, packages/radio/src/RadioGroup.tsx, packages/radio/src/index.ts, packages/radio/src/tests/__snapshots__/Radio.test.tsx.snap
This PR includes updates made to the radio component package in preparation for release. The following activities were carried out:
- Tests review
- Types review
- Storybook examples
- Addition of the migration
- Comments review
- Readme review
- Dependency list review
- Addition of the RadioGroup component
=> Chore: review radio component

.storybook/main.js, packages/spinner/README.md, packages/spinner/src/Spinner.stories.tsx, packages/spinner/src/Spinner.tsx
This PR includes updates made to the spinner component package in preparation for release. The following activities were carried out:
- Tests review
- Types review
- Storybook examples
- Comments review
- Readme review
- Dependency list review
=> Review spinner component

packages/chakra-ui/src/PseudoBox/index.d.ts
Related issue : https://github.com/chakra-ui/chakra-ui/issues/561
There is obviously a code duplication going on here, but I just couldn't find a good interface name for this one. 😅Open to suggestions!
=> Fix: add content prop to PseudoBox typings

.storybook/main.js, packages/close-button/README.md, packages/close-button/package.json, packages/close-button/src/CloseButton.stories.tsx, packages/close-button/src/CloseButton.tsx, packages/input/src/Input.tsx, packages/preset-base/src/components/CloseButton.ts
This PR includes updates made to the close button component package in preparation for release. The following activities were carried out:
- Minor bug fix
- Tests review
- Types review
- Storybook examples
- Comments review
- Readme review
- Dependency list review
=> fix: close button component review

.storybook/main.js, packages/stat/README.md, packages/stat/package.json, packages/stat/src/Stat.stories.tsx, packages/stat/src/Stat.tsx
This PR includes updates made to the stat component package in preparation for release. The following activities were carried out:
- Tests review
- Types review
- Storybook examples
- Comments review
- Readme review
- Dependency list review
=> chore: Review stats component

packages/chakra-ui-docs/pages/recipes.mdx
Addresses this issue: https://github.com/chakra-ui/chakra-ui/issues/669
=> docs: adds chakra with framer to recipes page

.github/stale.yml
resolves #704 
The labels in this list are related to these types of items:
- bugs
- new feature or documentation discussion
- showcase/reviews
- contribution requests
- high priority items
=> chore(stalebot): add labels to exempt list

examples/create-react-app/package.json, package.json, packages/editable/src/Editable.tsx, packages/menu/src/Menu.transition.tsx, packages/modal/src/Modal.tsx, packages/pin-input/src/Pin-Input.tsx, yarn.lock
[Typescript 3.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html) is out with some [nice speed improvements](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#speed-improvements). This might make it faster to compile and test our code.
=> chore: typescript 3.9

examples/create-react-app/package.json, package.json, packages/editable/src/Editable.tsx, packages/menu/src/Menu.transition.tsx, packages/modal/src/Modal.tsx, packages/pin-input/src/Pin-Input.tsx, yarn.lock
Reverts chakra-ui/chakra-ui#715
=> Revert "chore: typescript 3.9"

examples/create-react-app/package.json, package.json, packages/editable/src/Editable.tsx, packages/menu/src/Menu.transition.tsx, packages/modal/src/Modal.tsx, packages/pin-input/src/Pin-Input.tsx, packages/toast/src/Toast.manager.tsx, packages/toast/src/Toast.types.ts, yarn.lock
=> chore: typescript 3.9 (second try)

examples/create-react-app/package.json, examples/next-js/package.json, package.json, yarn.lock
Added examples to yarn workspaces and clean up dependencies
=> fix(examples): ensure that nestjs and cra example works just fine

tooling/gatsby-plugin-chakra-ui/gatsby-ssr.js
=> fix(gatsby-plugin): add react import to gatsby-ssr

packages/chakra-ui/src/IconButton/index.d.ts
when using custom icons with the `IconButton` component, this is what I have to do:
```ts
<IconButton icon={() => <Icon name="myAwesomeCustomIcon"/>}/>
```
instead of just
```ts
<IconButton icon="myAwesomeCustomIcon"/>
```
this functionality is already support by the `Icon` component, so it should also be support by the `IconButton` component
=> fix: update `IconButton` types

packages/chakra-ui/src/Toast/index.js
Fixed #666 - [useToast hook] onClose callback doesn't work
=> fix: add on close callback in useToast

packages/chakra-ui/src/theme/icons.d.ts
=> fix: add support for custom icon set

packages/chakra-ui/src/Menu/index.js
=> fix: #714 MenuList closes incorrectly on IE 11

packages/chakra-ui/src/Button/index.d.ts
Doesn't specifically need to be a string
=> update Button loadingText type

packages/hooks/src/useBoolean.ts
Found a baby typo while checking out the TS branch. Great work with the conversion!
=> fix: update useBoolean hook

docs/pages/contributing.mdx
This PR adds a brief note on our documentation goals to `contributing.mdx`:
- Friendly & Human
- Cover FAQs & Common Issues
- Copy-able
=> docs(contributing): add documentation goals

.dependabot/config.yml
This PR fixes the `dependabot` configs so it can function correctly and stop complaining in each of its PRs :D
=> chore(dependabot): fix configs

docs/src/pages/index.jsx
I noticed the index page isn't rendering the `SEO` component. This PR fixes that.
=> chore(site): add seo to index page

.storybook/main.js, packages/editable/stories/editable.stories.tsx
➕ Configure Storybook to use the stories in all the packages
🐛 Fix Editable import
=> 🐛➕ Fix Storybook Compilation errors

CONTRIBUTING.md
🖊 Fix branch name for new contributions
=> 📃 docs: Update CONTRIBUTING.md

.storybook/main.js, packages/tag/src/tag.tsx
This PR attempts to fix issue #958.
=> chore: add button type attribute to tag close button

website/docs/components/toast.mdx
Updated description of properties for component toast in `website/docs/components/toast.mdx`
=> docs(toast): updated documentation for toast component

website/docs/components/icon.mdx, website/docs/migration.mdx, website/docs/theming/theme.mdx
@with-heart Thanks for pointing me to the correct locations to update in #922. I made a fork this time so I can keep this branch up-to-date with `master` so the PR doesn't go stale. Please note this PR leaves off the one place I did change in #922 as it occurred to me migration notes might not be needed in that package (assuming it's new).
I also spotted some more icons feedback in the #906 today. If you'd like me to tackle some of those with this PR to make it more meaningful please don't hestitate to ask.
=> docs: add icon migration notes

website/docs/components/editable.mdx, website/docs/migration.mdx
=> docs(editable): fix the custom controls example

packages/layout/src/stack.tsx
=> fix(stack): default align-items css value

website/docs/hooks/use-breakpoint-value.mdx
Added useBreakpointValue docs
Closes #1053
=> docs: added useBreakpointValue hook documentation to the website

packages/button/src/button.tsx
Fixes #1024 
As I mentioned in the issue, it should be developer role to handle this. But I may be missing some things :)
=> fix(button): remove negative margin on icons

website/docs/components/icon.mdx
Updated documentation for the Icon component.
=> docs(icon): update documentation for icon component

website/src/components/header.js
This PR fixes the GitHub link on the site.
=> chore(site): fix github link

packages/tooltip/src/use-tooltip.ts, packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap, packages/tooltip/tests/tooltip.test.tsx, website/docs/components/tooltip.mdx
Adds isDisabled prop to Tooltip Components. Closes #703
=> feat(tooltip):Provide a prop for disabling a tooltip.

website/docs/layout/stack.mdx
=> docs: added not about Stack's primary use case and using Flex for more control

packages/control-box/README.md, packages/control-box/package.json
This PR makes a few changes to resolve some build failure issues, and also updates the package name for `control-box` in its `README` and `package.json`
=> chore: fix new packages

website/src/pages/index.js
fix typo `fontsize` to `fontSize`
=> docs(index): fix typo fontsize to fontSize

packages/slider/src/use-slider.ts, packages/slider/stories/slider.stories.tsx, packages/utils/src/number.ts, packages/utils/tests/number.test.ts
=> fix: #1180 slider moving incorrectly when min is odd and step is even

CONTRIBUTING.md
Update the documentation site notes from Next JS to Gatsby
=> chore(contributing): update docs commands and finish storybook section

examples/next-js/package.json, examples/next-js/pages/_app.js, examples/next-js/pages/_document.js, examples/next-js/pages/index.js, examples/nextjs-typescript/package.json, examples/nextjs-typescript/pages/_app.tsx, examples/nextjs-typescript/pages/index.tsx
This PR centralizes imports for both examples to `@chakra-ui/core`.
=> chore(nextjs): update next js and ts package imports

.changeset/angry-buses-camp.md, packages/color-mode/src/index.ts, packages/color-mode/src/use-color-mode-state.ts, packages/theme/src/index.ts
Fixes #1223 
This PR adds the `ColorModeOptions` type to the theme config.
=> fix: added ColorModeOptions type to theme config

packages/select/src/select.tsx
=> fix(select): add fit-content prevent element overflow

tooling/cra-template-typescript/README.md
This PR updates the `README` for `cra-template-typescript` to match the same format as its js counterpart.
=> docs(tooling): update cra ts template readme with correct usage

website/docs/components/link.mdx
Due to: https://github.com/chakra-ui/chakra-ui/commit/d0fcc4a07ee2f1b8b4026d88017c8d739455d271
=> docs(link): remove disabled prop

packages/toast/src/use-toast.tsx
=> refactor(toast): memoize object returned by useToast

packages/input/src/input-addon.tsx, packages/layout/src/code.tsx, packages/layout/src/kbd.tsx
Fixes some function name errors, probably coming from copy-pasting.
Has no repercusion other than calming down my ocd 🤪
=> fix: fix function name typos

examples/next-js/pages/_app.js, examples/next-js/pages/_document.js, packages/color-mode/src/color-mode.tsx, packages/color-mode/src/color-mode.utils.ts, packages/color-mode/src/index.ts, packages/color-mode/src/storage-manager.ts, packages/color-mode/src/use-color-mode-state.ts, packages/system/src/providers.tsx, website/docs/color-mode.mdx, yarn.lock
@segunadebayo I wanted to get the conversation started around injecting the color mode storage mechanism into `ColorModeProvider`.
=> feat: added storageManager prop to ColorModeProvider

website/docs/form/button.mdx
=> docs(button): remove mention of scale for colorScheme prop

packages/radio/src/radio.tsx, packages/radio/stories/radio.stories.tsx
=> fix(radio): set default isChecked prop value

packages/system/package.json, packages/system/src/providers.tsx
=> feat(system): extend props

packages/avatar/src/avatar.tsx
=> refactor: extract AvatarImage

website/pages/docs/theming/theme.mdx
Small grammar fixes
Wonderful library, thanks for your amazing work.
=> docs: theme grammar 

packages/switch/src/switch.tsx, packages/switch/tests/__snapshots__/switch.test.tsx.snap
=> fix(switch): replace div with span

packages/checkbox/src/checkbox.icon.tsx
=> fix(checkbox): omit checkbox props from Icon spread

website/pages/docs/overlay/modal.mdx
=> docs: Update modal.mdx

CONTRIBUTING.md
=> chore(contributing): add github access token link and instructions

website/next.config.js
=> fix(website): update "edit this page" url

packages/menu/src/use-menu.ts
* Description here: https://github.com/chakra-ui/chakra-ui/issues/1807
Fixes #1807
=> fix(menu): give MenuList props style precedence

packages/avatar/src/avatar-group.tsx
=> feat(avatar): added border radius prop to avatar group

packages/slider/src/use-slider.ts
=> refactor: useSlider return `isDragging` object

website/pages/docs/overlay/drawer.mdx
When full drawer is opened Instead of refresh the page you can press escape to exist
=> docs: Update drawer.mdx

.github/pull_request_template.md
Currently, the PR template has duplicate content which was removed here.
see https://github.com/chakra-ui/chakra-ui/blob/develop/.github/pull_request_template.md
=> fix(pr-template): remove duplicate content

packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap, packages/tooltip/tests/tooltip.test.tsx
fixed all tooltip tests
- no longer use general fake timers for jest
- updated snapshots
Accessibility tooltip test was failing. Also, the first snapshot did not take a hovered state into account and thus only tested the dummy button.
=> test(tooltip): fix

packages/alert/tests/__snapshots__/alert.test.tsx.snap, packages/button/tests/button.test.tsx, packages/checkbox/tests/__snapshots__/checkbox.test.tsx.snap, packages/editable/tests/editable.test.tsx, packages/input/tests/__snapshots__/input.test.tsx.snap, packages/number-input/tests/__snapshots__/number-input.test.tsx.snap, packages/progress/tests/Progress.test.tsx, packages/progress/tests/__snapshots__/Progress.test.tsx.snap, packages/radio/tests/__snapshots__/radio.test.tsx.snap, packages/radio/tests/radio.test.tsx, packages/select/tests/__snapshots__/select.test.tsx.snap, packages/switch/tests/__snapshots__/switch.test.tsx.snap, packages/textarea/tests/__snapshots__/text-area.test.tsx.snap, packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap
Some tests fail
- Tests using `rerender` correctly update their `testing-library` query targets
- Snapshots have been updated
Needed in order for #1699 to pass and be merged.
=> chore: fix failing tests

.gitignore, CHANGELOG.md, package.json
`CHANGELOG.md` has been generated and the `lerna-changelog` config has been updated to work correctly.
-
-
-
=> chore: generate changelog for 1.0.0-rc.3

website/pages/docs/theming/theme.mdx
- New color generator site which is easier to get started 
-
-
=> docs: add smart-watch color generator

website/configs/docs-sidebar.ts
Icon Button is currently not listed in the docs sidebar, but is an existing page https://next.chakra-ui.com/docs/form/icon-button
Icon Button is listed in the sidebar as a form element
=> docs: add Icon Button to sidebar

CONTRIBUTING.md
- Simple text updates to README to fix various minor spelling/grammar issues.
=> docs: fix minor spelling/grammar issues

website/configs/docs-sidebar.ts, website/next.config.js, website/pages/index.tsx
- added redirects for all links in the old navigation
- ~~a few are missing and annotated as such~~ edit: nothings missing, although technically controlbox now redirects to box since its gone
=> chore(docs): add redirects

website/pages/docs/feedback/circular-progress.mdx, website/pages/docs/migration.mdx
Documentation for next version (https://next.chakra-ui.com/docs/components/circular-progress) contains ```isIndeterminate```.
which was removed from CircularProgress
CircularProgress will show indeterminate progress if ```value``` is ```undefined```.
=> docs: Remove isIndeterminate from Circular Progress docs

website/pages/docs/form/radio.mdx
=> docs: fix typo

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
CodeSandbox template links are included in the final bug report.
- CodeSandbox template links are hidden by an html comment.
- All block descriptions are hidden by an html comment.
=> chore(issue-templates): add html comments to hide non-essential text blocks

tooling/cra-template-typescript/template/src/App.tsx, tooling/cra-template-typescript/template/src/Logo.tsx, tooling/cra-template/template/src/App.js
`Grid` component in `App` uses incorrect props, causing type error.
Fixes #1908 
- `Grid` no longer uses these props.
=> fix(cra-templates): remove unused props from App Grid

website/pages/docs/form/button.mdx, website/src/components/codeblock/react-live-scope.tsx
Fixes #1870 
- Missing icons added to `react-live-scope`.
- BONUS: Added a note about `react-icons` to the social buttons section of `Button` docs
=> docs: fix icon imports

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
The "new issues" page allows users to file a bug report or feature request, or open an issue with no template.
The "new issues" page allows users to choose from the following:
- "Report a bug" which leads to the bug report issue template
- "Request a feature" which leads to the feature request template
- "Ask a question" which leads to the GitHub Discussions page
- "Chat with other community members" which leads to the Discord link
This PR also updates the formatting on the bug report and feature request to make them a little more clear in formatting, and to force the user to create their own issue title.
=> chore: update new issue config and templates

website/pages/docs/theming/customize-theme.mdx
`button` should be `border`
The theme documentation shows the wrong comment.
The theme documentation shows the right comment.
=> docs(Customize): Fix typo (button -> border) 

website/pages/docs/features/color-mode.mdx
Docs have a typo
- Fixing docs
-
-
=> docs(ColorMode): Fix typo (defaultValue -> initialValue)

packages/progress/src/progress.tsx
No change in behaviour
No change in behaviour
N/A
=> refactor(progress): declare isIndeterminate once

website/pages/docs/form/form-control.mdx
When using the current example, the following console warnings appear:
Exactly the same, without the warnings 🎸 
Updated to reflect the latest Formik API: https://formik.org/docs/api/field
=>  Update Form Control Formik example

website/pages/docs/components/accordion.mdx
Documentation left out something that caused an hour of confusion.
Documentation includes a blurb to avoid confusion.
=> docs(accordion): specify defaultIndex and allowMultiple quirk

website/pages/docs/components/breadcrumb.mdx, website/pages/docs/components/close-button.mdx, website/pages/docs/data-display/badge.mdx, website/pages/docs/data-display/code.mdx, website/pages/docs/data-display/stat.mdx, website/pages/docs/form/icon-button.mdx, website/pages/docs/form/number-input.mdx, website/pages/docs/form/slider.mdx, website/pages/docs/form/switch.mdx, website/pages/docs/form/textarea.mdx, website/pages/docs/getting-started.mdx, website/pages/docs/hooks/use-disclosure.mdx, website/pages/docs/theming/customize-theme.mdx, website/pages/docs/theming/theme.mdx, website/pages/guides/z-index.mdx
There are broken links throughout the docs.
Fixed the broken links.
=> docs: fixed broken links

packages/alert/tests/__snapshots__/alert.test.tsx.snap, packages/button/tests/__snapshots__/button.test.tsx.snap, packages/checkbox/tests/__snapshots__/checkbox.test.tsx.snap, packages/close-button/tests/__snapshots__/close-button.test.tsx.snap, packages/icon/tests/__snapshots__/create-icon.test.tsx.snap, packages/icon/tests/__snapshots__/icon.test.tsx.snap, packages/stat/tests/__snapshots__/stat.test.tsx.snap, packages/tag/tests/__snapshots__/tag.test.tsx.snap
=> test: update snapshots

packages/form-control/README.md
=> docs: minor spelling/grammar fixes

website/pages/guides/with-nextjs-font-files.mdx
This PR adds a short guide for adding font files to Chakra's default theme for apps running on Next.js.
=> docs: guide for nextjs with custom font files

website/pages/docs/feedback/circular-progress.mdx
=> docs(feeback): update circular progress

packages/alert/src/alert.tsx, packages/alert/stories/alert.stories.tsx, packages/alert/tests/__snapshots__/alert.test.tsx.snap, packages/avatar/src/avatar-group.tsx, packages/avatar/src/avatar.tsx, packages/button/tests/__snapshots__/button.test.tsx.snap, packages/close-button/tests/__snapshots__/close-button.test.tsx.snap, packages/input/tests/__snapshots__/input.test.tsx.snap, packages/portal/tests/__snapshots__/portal.test.tsx.snap, packages/portal/tests/portal.test.tsx, packages/select/tests/__snapshots__/select.test.tsx.snap, packages/styled-system/src/css.types.ts, packages/system/src/hooks.ts, packages/system/src/system.ts, packages/system/src/system.utils.ts, packages/system/tests/should-forward-prop.test.ts, packages/system/tests/style-resolver.test.ts, packages/toast/src/use-toast.tsx, packages/utils/package.json, packages/utils/src/object.ts, yarn.lock
Updated the systems package to use a style resolver function that manages how style props are merged in combination with other possible ways of defining styles (__css, sx, apply, etc). For example, take a component defined this way:
```jsx
<Box fontSize="24px" sx={{ fontSize: "40px" }}></Box>
```
We want to manage the priority of the styles properly to prevent unwanted behaviors. Right now, the `sx` prop has the highest priority so the resolved font-size will be `40px`
=> feat: improve system style merging

packages/utils/src/number.ts
Chakra UI utils can be used in other libraries
-
-
-
I am using Chakra Utils in projects where I don't use Chakra UI.
It would be nice to be more generic in utils & hooks.
Let me know if this is agreable else I can close the PR
=> refactor: clamp warning message

tooling/gatsby-plugin-chakra-ui/README.md
---
The previous link was a 404
=> chore(gatsby-plugin-chakra-ui): Fix link in README to theme

website/pages/docs/migration.mdx
From v0 to v1 migration guide had missing `useDisclosure` so I have added that
No
=> :memo: added useDisclosure to migration guide

packages/modal/stories/modal.stories.tsx, website/pages/docs/overlay/modal.mdx
The Modal docs contain some example use of modals. Some of these have close buttons that does not actually close the modals when clicked. 
The modals are now closed when the close buttons are clicked.
=> docs(modal): make close buttons close the modals

website/pages/docs/hooks/use-controllable.mdx
- [x ] Tests for the changes have been added (for bug fixes / features) `N/A`
- [x ] Docs have been reviewed and added / updated if needed (for bug fixes
There were a couple of typos in `use-controllable.mdx`
There are a couple less typos in `use-controllable.mdx`
- [x ] No
Should the `mdx` file be named `use-controllable-state.mdx` too?
=> typo corrections on use-controllable

website/pages/docs/theming/component-style.mdx
Incorrect spelling of `Parameters`
Correct spelling of `Parameters`
=> docs: fix Parameters typo

TRIAGE.md
I've been working on this for awhile and I need to stop and take a break. But I think it covers a lot of my thinking on triage and hopefully covers the topic pretty well so far.
Wanted to open this as a draft to hopefully get some feedback before I start working on it again.
=> docs: create TRIAGE overview document

packages/theme/src/components/progress.ts
Adding the hasStripe attribute does not have any stripe effect
Stripe effect takes effect
=> fix(progress): replace bg with bgColor

packages/color-mode/src/color-mode-script.tsx
Looks like it should also accept `'system'`
=> fix: defaultColorMode type in ColorModeScript

packages/checkbox/src/checkbox.icon.tsx, packages/checkbox/src/checkbox.tsx, packages/checkbox/stories/checkbox.stories.tsx, packages/checkbox/tests/__snapshots__/checkbox.test.tsx.snap, packages/checkbox/tests/checkbox.test.tsx, website/pages/docs/form/checkbox.mdx
Fixes: #2039
- a custom icon can be passed to `Checkbox`
=> feat(checkbox): add icon prop

website/pages/docs/getting-started.mdx
The following code in the getting started is not working
```jsx
// 1. Import the extendTheme util - it will merge with the default theme
import { extendTheme } from "@chakra-ui/core"
// 2. Extend the theme to include custom colors, fonts, etc.
const colors = {
colors: {
brand: {
900: "#1a365d",
800: "#153e75",
700: "#2a69ac",
},
},
}
const customTheme = extendTheme({ colors })
// 3. Pass the `theme` prop to the `ChakraProvider`
function App() {
return (
<ChakraProvider theme={customTheme}>
<App />
</ChakraProvider>
)
}
```
Remove the nested colors object that is not working ;)
```jsx
// 1. Import the extendTheme util - it will merge with the default theme …
```
=> docs(getting-started) Fix "Add Custom theme" section

website/src/components/footer.tsx
The links on the footer don't work.
Fix `url` to `href`
=> docs: fix links on footer (documentation)

website/pages/docs/components/breadcrumb.mdx
=> docs(breadcrumb): Small correction

packages/avatar/src/avatar.tsx
- Suport avatar image loading strategy
see #2150
=> fix(avatar): add loading prop for avatar

website/pages/docs/form/form-control.mdx
=> Remove duplicate RequiredIndicator

packages/toast/src/toast-manager.tsx, packages/toast/src/toast.class.tsx, packages/toast/src/toast.tsx, packages/toast/src/toast.types.ts, packages/toast/src/toast.utils.ts, packages/toast/src/use-toast.tsx, packages/toast/stories/toast.stories.tsx
Fixes:  #2121
- `closeAll` actually closes all toasts
- better performance for a few functions as well as normalization
=> fix(toast): closeAll method actually closes all

website/pages/docs/theming/customize-theme.mdx
The described behaviour was fixed in #1967. 
I removed the warning, because function results are now merged as well.
=> docs(customize-theme): remove obsolete warning

BACKERS.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, TRIAGE.md
Grammar and spellcheck fixes for markdown files. Some of the grammar changes might be debatable, let me know if you disagree. There's also one area with missing content (email?) that needs to be updated.
=> docs: grammar and spellcheck on markdown files

packages/media-query/src/use-breakpoint-value.ts, packages/media-query/tests/use-breakpoint-value.test.tsx
The useBreakpointValue hook does not work when provided with an array.
Fixes: #2184 
- The hook now works again when provided with an array.
- The storybook example as described in the issue works.
- The hook also works when given a custom breakpoint.
=> fix(use-breakpoint-value): fix hook when given array of values

website/pages/docs/layout/wrap.mdx
just some minor spelling updates to the documentation
=> fix: minor spelling tweaks

packages/breadcrumb/tests/breadcrumb.test.tsx, packages/checkbox/CHANGELOG.md, packages/collapse/stories/collapse.stories.tsx, packages/modal/src/modal.tsx
=> docs: fixed few spellings

website/pages/docs/data-display/list.mdx
Hi :wave:, thanks for amazing work, it's real pleasure to use Chakra :)
Found a little typo in docs 
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/layout/src/list.tsx#L14
-
-
-
=> docs(list): fix stylePos to stylePosition

website/pages/docs/features/color-mode.mdx
fix typo
Fixes: spelling from "customtheme" to "customTheme"
-
-
-
=> docs(Color Mode): fix typo in Color Mode docs

website/pages/docs/components/icon.mdx
=> docs(icons): fix typo

website/pages/docs/data-display/image.mdx
Added a section to the Image docs that explicitly states the Img Component for SSR usage. (#2232)
=> docs(image): add usage information for Img

website/pages/docs/theming/customize-theme.mdx
Customize Theme page has some code demonstrating, the below importation method, but it shows errors that "module cannot be found", other parts of the docs import them from the core
```
import { extendTheme } from "@chakra-ui/theme"
import { mode } from "@chakra-ui/theme-tools"
```
changed the docs to import from the core, as other parts of the Theme docs
```
import { extendTheme } from "@chakra-ui/core"
import { mode } from "@chakra-ui/core"
```
=> docs(customize theme): fix update Import {extendTheme, mode} to point to @chakra-ui/core

packages/number-input/tests/number-input.test.tsx
=> test(number-input): added more test cases for number-input

website/pages/docs/getting-started.mdx, website/pages/docs/migration.mdx, website/pages/index.tsx
=> docs: fixed some typos

website/pages/docs/hooks/use-breakpoint-value.mdx
Update useBreakPointValue to be imported from "@chakra-ui/core"
import { useBreakpointValue } from "@chakra-ui/media-query"
import { useBreakpointValue } from "@chakra-ui/core"
=> docs(useBreakPointValue): import from "@chakra-ui/core"

website/pages/docs/comparison.mdx, website/pages/docs/migration.mdx, website/pages/docs/theming/advanced.mdx, website/pages/docs/theming/component-style.mdx, website/pages/docs/theming/customize-theme.mdx, website/pages/docs/theming/theme.mdx
=> docs: fixed typos in theming

website/pages/docs/features/text-and-layer-styles.mdx
Needless curly brackets {`h1`}
- Typo fix
=> docs: Fix typo in Text Styles example

website/pages/docs/layout/box.mdx, website/pages/docs/layout/center.mdx, website/pages/docs/layout/container.mdx, website/pages/docs/layout/flex.mdx, website/pages/docs/layout/grid.mdx, website/pages/docs/layout/simple-grid.mdx, website/pages/docs/layout/stack.mdx, website/pages/docs/layout/wrap.mdx
=> docs: fixed typos

packages/checkbox/src/checkbox.tsx, packages/checkbox/stories/checkbox.stories.tsx
Fixes:  #2339 
if set `isDisabled={false} `, not-allowed cursor should hidden.
=> fix(checkbox): fix data-disabled type

website/pages/docs/theming/customize-theme.mdx
Fix borders import naming and remove styles file extension.
=> Fix imports in customize-theme documentation

packages/editable/src/editable.tsx
The `editable` component's theme does not have a `container` style but it is added to the `Editable` component as undefined.
- Removed the `container` style from the `Editable` component.
=> fix: removed editable container style

website/pages/docs/features/color-mode.mdx
=> docs: Add ColorModeScript import to be explicit

packages/skip-nav/README.md
`skip-nav` references `@reach/skip-nav`
`skip-nav` now references `@chakra-ui/skip-nav`
=> docs(skip-nav): fixed typo

packages/popper/src/use-popper.ts
Found a baby typo while reviewing. Great work on the project!
=> fix(popper): correct variable name typo in usePopper

website/pages/docs/features/style-props.mdx
=> docs(style-props): add background shorthand

website/pages/docs/theming/customize-theme.mdx
Documentation update. The `mode` method is in `/theme-tools`, not `/core`.
This is for the next docs: https://next.chakra-ui.com/docs/theming/customize-theme
=> [Docs]: fix incorrect module for mode method

packages/media-query/src/media-query.utils.ts, packages/media-query/src/use-breakpoint-value.ts, packages/media-query/tests/utils.test.ts
Currently, `useBreakpointValue` is not working with custom breakpoint
- support custom breakpoints
=> fix(use-breakpoint-value): should work with custom breakpoints

packages/layout/src/link-box.tsx
Fixes: Error in `import { LinkBox } from "@chakra-ui/core"`
- `LinkBox` can be exported.
=> Fix link box export

packages/theme-tools/src/color.ts
- N/A
- this is only update to jsdoc comments (does storybook/etc require an update for helper functions like this?)
Fixes: N/A (undocumented)
- fixes jsdoc about the `blacken` function
- fixes jsdoc about the `darken` function
- adds jsdoc about the `lighten` function
1st PR for chakra :tada: don't be shy -- lemme know what i did wrong
=> docs: correct and add jsdocs

website/pages/docs/form/slider.mdx
small vertical slider example 
Fixes: #2465
=> docs(vertical-slider): add vertical slider example

website/pages/docs/form/number-input.mdx
This fixes a type where "minimum" is repeated where it should be "maximum".
- Currently "minimum and minimum" is typed.
Fixes: [#2482]
- Fixes typo to "minimum and maximum"
=> fix: type in number-input.mdx

website/pages/docs/layout/container.mdx
=> docs: typo fix

website/pages/docs/theming/theme.mdx
Currently export default object doens't contain a borderRadius key
Add borderRadius key in export default object
Fix issues: #2485
=> docs(default-theme): Add borderRadius key in object

tooling/cra-template/template.json
*(They are not required for this fix)*
When starting a new CRA project using the `@chakra-ui` template, runtime errors are raised due to the following missing dependencies:
- `@emotion/react`
- `@emotion/styled`
Fixes: #2493
The missing dependencies have been added to the manifest file of the CRA template.
N/A.
=> fix(cra-template): added missing dependencies

website/pages/docs/migration.mdx, website/pages/guides/integrations/with-gatsby.mdx
The documentation regarding the gatsby plugin doesn't mention the rename of the plugin
The documentation now mentions the rename of the gatsby plugin first so users don't get confused. ive updated the with-gatsby.mdx file. if there are more files that need to be updated then please let me know :)
=> Update Docs to mention Gatsby plugin rename

website/pages/docs/migration.mdx
There is a renamed prop for `List` component but it doesn't appear on migration guide.
Fixes: (no open issue)
`List` component has been added to migration guide to mention renamed `stylePos` prop.
N/A
=> docs(migration): include List component

.github/workflows/pr.yml
Fixes: #2547
Build success without error
related: https://github.com/actions/setup-node/issues/212
=> fix(workflow): update PR workflow

README.md
The link of guide 'create-react-app' is not linking to the correct location.
The link of guide 'create-react-app' is linking to the correct location
=> docs(cra-template): update cra-template link

.changeset/empty-spoons-decide.md, packages/styled-system/src/config/others.ts
Fixes: #2454 
- filter field not missing from type of _groupHover.
=> fix: filter style props

package.json, yarn.lock
- Build fails due duplicate popper dependency
```bash
> yarn why @popperjs/core
yarn why v1.22.5
[1/4] 🤔  Why do we have the module "@popperjs/core"...?
=> Found "@popperjs/core@2.5.4"
info Has been hoisted to "@popperjs/core"
info Reasons this module exists
- "workspace-aggregator-f29cf9a9-db9a-4a36-8ba4-bb07122f0e23" depends on it
- Hoisted from "_project_#@storybook#components#@popperjs#core"
- Hoisted from "_project_#@storybook#components#react-popper-tooltip#@popperjs#core"
=> Found "@chakra-ui/popper#@popperjs/core@2.4.4"
info This module exists because "_project_#@chakra-ui#popper" depends on it.
```
- Build succeeds :tada:
=> chore(popper): pin yarn resolution for @popperjs/core

tooling/cra-template-typescript/package.json, yarn.lock
=> chore: add web-vitals as devDep to fix lint

.changeset/tame-forks-sell.md, packages/hooks/src/use-controllable.ts
Doesn't provide the correct previousValue when used as `updateValue(prev => prev + 1)`
Because the `value` is not provided in the deps list for `useCallback`
Previous Value is properly updated after setting [onChange, value] in the deps list of `updateValue`
=> fix: updateValue's next as function same prevValue

CONTRIBUTING.md
The current documentation states:
---
**Shortcut:** To make this shorter and more convenient, we've added an alias for
each component in the root `package.json`. Now you can simply do:
```bash
yarn pkg button build
yarn pkg button test
yarn pkg button test --watch
yarn pkg button lint
```
---
But these commands are in conflicts because pkg return results for `@chakra-ui/button` and `@chakra-ui/close-button`:
```
yarn pkg button build
yarn run v1.22.10
$ manypkg run button build
☔️ error an identifier must only match a single package but "button" matches the following packages:
☔️ error @chakra-ui/button
☔️ error @chakra-ui/close-button
error Command failed with …
```
=> docs: improve pkg example with non duplicate alias

website/pages/docs/migration.mdx
The migration guide does not include any relevant information about a deprecated component.
Fixes: #1890 
The migration guide include some relevant information for the user when migrating to v1 and was using a Callout component.
For me it was useful to read the comments in the related issue in order to be able to upgrade and I thought probably it would be useful to other people. Feel free to edit the example and I hope it helps!
=> fix: add Callout to migration

website/pages/docs/overlay/drawer.mdx
Remove redundant `borderRadius="0"` on `<Input>` inside `<InputGroup>`
=> docs: update drawer example

.changeset/rotten-rats-accept.md, packages/layout/src/container.tsx, packages/layout/stories/container.stories.tsx, packages/layout/tests/__snapshots__/layout.test.tsx.snap, packages/layout/tests/layout.test.tsx, packages/theme/src/components/container.ts, packages/theme/src/components/index.ts
Fixes: [2593](https://github.com/chakra-ui/chakra-ui/issues/2593)
- Container becomes themeable
=> feat(Container): add theme support to container

tooling/gatsby-plugin/README.md, website/pages/guides/integrations/with-gatsby.mdx
Docs dont list everything needed for gatsby-plugin
Fixes: #2605 
Docs now list all deps needed.
=> docs: updated packages needed for gatsby-plugin

website/pages/docs/hooks/use-disclosure.mdx
Fixes: #2530
- Document `useDisclosure` parameter
=> docs(use-disclosure): add parameter docs

packages/transition/src/collapse.tsx, packages/transition/src/fade.tsx, packages/transition/src/scale-fade.tsx, packages/transition/src/slide-fade.tsx, packages/transition/src/slide.tsx, website/pages/docs/components/transitions.mdx
Incomplete documentation for the transition components
- Improved props documentation
- uses <PropsTable /> Component to document props
=> docs(transition): update transition props documentation

website/pages/docs/feedback/toast.mdx
Wrong type is documented for toast's `title` prop.
- Changed the documented type to `string` from `boolean` type
=> docs: update toast title prop type to string

website/pages/docs/theming/advanced.mdx
Docs show use of mergeWith to update theme.
Updated docs to use extendTheme.
=> docs: replace mergeWith with extendTheme in example

.changeset/dirty-news-look.md, packages/layout/src/list.tsx, packages/theme/src/components/index.ts, packages/theme/src/components/list.ts
`List`, `ListItem`, and `ListIcon` are currently not themable.
Fixes: #2630
Now able to style `List`, `ListItem`, and `ListIcon` in the theme.
=> feat: added theming to List, ListItem, and ListIcon

.changeset/curly-games-repeat.md, packages/modal/src/modal.tsx, packages/theme/src/components/modal.ts
=> feat: added theming to ModalCloseButton

.changeset/soft-grapes-smile.md, packages/radio/package.json, packages/radio/src/use-radio.ts, packages/radio/tests/radio.test.tsx
Fixes: #2631
`FormControl` propagates props down to `Radio` children.
=> feat: radio uses props of wrapping form control

packages/radio/src/use-radio.ts
PR pipeline is failing due to lint issues.
- Lint checks succeed
=> chore(lint): resolve use-radio failures

.changeset/unlucky-games-happen.md, packages/react/src/extend-theme.ts, packages/theme/src/index.ts
The typings of the theme override is not specific enough to help while working on a theme extension.
- Autocomplete for existing components
- existing colors
- new colors
=> chore(extend-theme): improve theme override typings

CONTRIBUTING.md
I added some details to the "Steps to PR" section that tripped me up on my previous (first) PR.
=> docs(contributing): add details to "Steps to PR"

packages/theme/src/components/alert.ts
=> fix(theme): add "description" to parts array for alert

.changeset/lemon-toys-count.md, packages/theme/src/components/alert.ts
Fixes: #2672
`AlertIcon` will not shrink when using `Alert` with long text.
=> fix(alert): prevent shrinking icon

.changeset/hot-beers-rule.md, website/pages/docs/feedback/spinner.mdx
Spinner page has no import section.
- added import section to Spinner page
=> docs: add "import" section to Spinner page

.changeset/forty-goats-pull.md, .changeset/wicked-humans-judge.md, packages/close-button/src/close-button.tsx, packages/theme/src/components/drawer.ts
Postition of Close Button in a Drawer has incorrect position.
- Postion is fixed
- Additional styles are applied correctly
@dodas is the original author, I just created a PR for those changes
=> fix(drawer): close button styles

.changeset/strong-nails-end.md, packages/styled-system/src/css.ts, packages/styled-system/tests/css.test.ts
Fixes: #2700
expand the shortcut definition by setting `property` and `scale` to the `key` name
=> fix: style prop configured as boolean in styled-system is not working

website/pages/docs/components/breadcrumb.mdx
Documentation content changes
No
=> docs(breadcrumb): fix docs of isCurrentPage prop

packages/table/src/table.tsx
Closes # 
Updated table component to fix lint errors
No
=> fix: updated table component to fix lint errors

.github/workflows/release.yml
Closes # 
Default commit message created by changesets is not semantic.
=> chore(release-config): set changesets commit message

website/src/components/header.tsx, website/src/components/sidebar/sidebar.tsx
Closes #2746
Fixes  #2746 (for me at least ;) )
*  #2746
*  #2746
* No
=> fix: firefox css quirks, resolves #2746

website/pages/guides/with-nextjs-font-files.mdx
=> docs: fix a grammar mistake

.changeset/short-fans-chew.md, packages/layout/src/list.tsx
Closes #1518 
This PR wraps `ListItem` in `forwardRef`.
No
=> fix(list): enable ref forwarding for ListItem

website/pages/docs/form/select.mdx
Select comes in 4 variants (outline, unstyled , flushed , and filled), not 3.
Adjusting docs
Adjusting docs
=> docs: 4 variants in select component

website/pages/docs/components/tabs.mdx
Closes # 
Add orientation and more props in the docs that are omitted because them are included in ThemingProps type
Orientatios and more props are omitted in the docs.
Props are showing correctly in the docs.
=> docs(tabs): fix omitted props

website/configs/guides-sidebar.json, website/pages/guides/custom-fonts.mdx
This PR adds a guide for adding custom fonts to a Chakra project using `@font-face` rules and the `Global` component from `@emotion/react`.
=> docs(guides): add Custom Fonts guide

website/configs/docs-sidebar.json, website/pages/docs/features/gradient.mdx, website/pages/docs/features/style-props.mdx
- Wrote the documentation for gradient support
=> docs: updated gradient doc

.changeset/FormControl-fix.md, website/pages/docs/form/form-control.mdx
Closes # 
> in formControl page in the validation example it works with "Naruto" string but not with "naruto" so I changed this behavior 
> Currently it works only for "Naruto" string
> Now it validates for both "Naruto" and "naruto"
No
=> refactor: Update form-control.mdx

website/pages/docs/features/responsive-styles.mdx
Closes # 
Let's say you have a Box that looks like this:
but the example is use Text Component.
This is Typo or on purpose?
> Let's say you have a Box that looks like this:
> Let's say you have a Text that looks like this:
No
=> docs: fix typo on Responsive Styles page

website/pages/docs/theming/theme.mdx
This PR is for pixel correction in Doc
| 96   | 24rem   | 344px  | <Box bg="pink.200" h="4" w="96"/> |
| 96   | 24rem   | 384px  | <Box bg="pink.200" h="4" w="96"/> |
No
N/A
=> Doc: Fix correct pixel

website/pages/docs/layout/container.mdx
Add import code for Container.
=> docs: add Container import

.changeset/four-hornets-joke.md, website/configs/guides-sidebar.json, website/pages/guides/integrations/with-react-table.mdx, website/src/components/codeblock/react-live-scope.tsx
Add integration guide with react-table
=> docs(guide): add react-table integration guide

.changeset/khaki-falcons-rule.md, website/pages/docs/components/visually-hidden.mdx, website/pages/docs/form/radio.mdx, website/pages/docs/overlay/drawer.mdx
A few little changes related to the `Import` section of various component docs.
No
=> docs: make the Import section consistent across components

packages/modal/stories/index.stories.tsx, packages/modal/stories/modal.stories.tsx
Closes # 
Removed multiple reexports of modal.stories & fixed the import order of `react-lorem-component`
=> chore(modal): remove storybook multiple exports

website/pages/guides/integrations/with-framer.mdx
Closes # 
Previous implementation passed all framer motion props to the DOM element.
Filter all framer motion props with function `isValidMotionProp` from framer-motion.
No framer props are passed to the DOM element.
No
here is the [referenced codesandbox](https://codesandbox.io/s/chakra-ui-motion-box-sbk9e?file=/src/App.tsx)
=> docs(motion-box): update motion box guide

.changeset/spicy-goats-rule.md, examples/gatsby/src/pages/index.js, examples/next-js/pages/index.js, packages/input/README.md, packages/input/stories/input.stories.tsx, website/pages/docs/form/input.mdx
`<input type="phone">` is not exist on specification. and `<input type="tel">` should be corrrect.
SEE https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
Code example is not good
Code example is valid.
No
=> fix document using <input type="phone">

website/pages/docs/features/color-mode.mdx
Fixed a grammar mistake
Closes # 
> There was grmmar mistake in the docs
=> docs: update color-mode.mdx

packages/avatar/tests/avatar.test.tsx, yarn.lock
Closes # 
Added skipped tests for Avatar image load/fail cases.
=> test(avatar): added mocked image tests

packages/theme/src/components/input.ts
=> style(box-shadow): fix input flushed variant

.changeset/tall-ducks-laugh.md, packages/media-query/src/create-media-query.ts, packages/media-query/tests/create-media-query.test.ts, yarn.lock
fixes useBreakpoinValue infinite loop due to bug in createMediaQueries 
Closes #2990
see issue for more info
=> fix(media-query): update impl

.changeset/dirty-mirrors-design.md, packages/form-control/src/form-label.tsx, packages/theme/src/components/form-error.ts, packages/theme/src/components/form-label.ts, yarn.lock
Closes # 
Fixed FormLabel margin and textAlign to support rtl; fixed form error icon margin to support rtl
FormLabel and form error icon has wrong padding and text align on rtl
FormLabel and form error icon has correct padding
no
=> fix: fixed form label for rtl support

website/pages/guides/with-nextjs-font-files.mdx
=> docs: change the Global import

website/pages/docs/comparison.mdx, website/pages/docs/features/color-mode.mdx
* `styled system`  → `styled-system` for consistency in `chakra-ui`
* Correction / clarification for `ColorModeScript`
=> Small improvements in docs

.changeset/lovely-beans-knock.md, website/pages/index.tsx
The numbers are going up fast!
Also, how do we count the "Core contributors"?
=> docs: update homepage stat numbers

.eslintrc, packages/hooks/src/use-id.ts
Closes #3020
Fixed SSR issue with `useId` hook. Copied over some of the source from `@reach/auto-id`
=> fix: ssr issue with auto-id

website/pages/docs/data-display/table.mdx
Closes #3097 
Added `Tfoot` to the `Table` docs import section and added `Tfoot` to each example on the page.
=> docs(table): add Tfoot import and uses

.all-contributorsrc, .changeset/famous-foxes-move.md, .changeset/fast-masks-learn.md, .changeset/four-ways-visit.md, .changeset/lazy-poets-cheat.md, .changeset/odd-cobras-fix.md, .changeset/smooth-tomatoes-hope.md, README.md, packages/accordion/src/use-accordion.ts, packages/hooks/src/use-controllable.ts, packages/layout/src/center.tsx, packages/menu/src/use-menu.ts, packages/pin-input/src/use-pin-input.ts, packages/pin-input/tests/pin-input.test.tsx, packages/popover/src/use-popover.ts, packages/portal/src/portal.tsx, packages/portal/stories/portal.stories.tsx, packages/radio/src/use-radio-group.ts, packages/select/src/select.tsx, packages/tabs/src/use-tabs.ts, website/pages/docs/data-display/table.mdx, website/pages/docs/form/pin-input.mdx, website/pages/docs/migration.mdx, website/pages/docs/overlay/menu.mdx, website/pages/docs/theming/theme.mdx
=> chore: prepare release

.github/workflows/pr.yml, .github/workflows/release.yml
This PR upgrades `actions/cache` to `v2` which should improve caching performance.
=> chore(ci): upgrade actions/cache to v2

website/pages/docs/data-display/list.mdx
If missing UnorderedList (or OrderedList), an unhandled runtime error is thrown:
ReferenceError: UnorderedList is not defined
Closes # 
=> docs: update '@chakra-ui/react' import

.changeset/cuddly-numbers-bake.md
This PR adds a changeset for #3179. Oops!
=> chore: add changeset

packages/checkbox/stories/checkbox.stories.tsx, packages/input/stories/input.stories.tsx, packages/menu/stories/menu.stories.tsx, website/src/components/omni-search.tsx
Closes #3163
I did a quick Search in all `.tsx` files and added `key` prop to loop items where missing.
No
=> chore: add missing `key` props

.changeset/bright-dingos-carry.md, packages/tabs/src/use-tabs.ts
Closes https://discord.com/channels/660863154703695893/776516215337386054/801222407267811348
No
=> chore(tabs): export useTabsContext

.changeset/cuddly-mice-repeat.md, packages/breadcrumb/src/breadcrumb.tsx, packages/breadcrumb/stories/breadcrumb.stories.tsx, packages/theme/src/components/breadcrumb.ts
=> feat(breadcrumb): make container and link themable

website/pages/docs/features/color-mode.mdx
Simplifies Color Mode doc code example by removing unnecessary function.
=> docs: remove function not utilized in doc example code

.changeset/calm-lamps-kneel.md, packages/styled-system/src/utils/index.ts, packages/styled-system/tests/css.test.ts
=> fix(css-colors): pass css color names

.changeset/perfect-goats-drop.md, website/pages/docs/theming/advanced.mdx
This PR makes a few minor edits to the changeset file and docs from #3092.
=> docs(theming): clean up theme typings JetBrains support note

README.md
updated logo image url
Current logo image url is broken.
I changed to logo url from
`https://github.com/chakra-ui/chakra-ui/blob/master/logo/logo-colored@2x.png`
to
`https://raw.githubusercontent.com/chakra-ui/chakra-ui/main/logo/logomark-colored@2x.png`
Before
After
No
=> docs: update logo url on README.md

CONTRIBUTING.md, tooling/gatsby-plugin/README.md, website/configs/site-config.ts, website/next.config.js, website/pages/docs/features/chakra-factory.mdx, website/pages/docs/theming/customize-theme.mdx, website/pages/docs/theming/theme.mdx, website/src/components/component-links.tsx
Updated all occurances of `develop` branch to `main`.
=> chore: point to `main` branch instead of `develop`

website/configs/docs-sidebar.json, website/pages/docs/features/the-sx-prop.mdx, website/src/components/page-container.tsx, website/src/components/sidebar/sidebar.tsx, website/src/utils/convert-backticks-to-inline-code.tsx
Added the documentation for the `sx` prop.
=> docs: add documentation for the `sx` prop

website/src/components/logo.tsx
> Removed an unused `fill` variable in `website/components/logo.tsx`. Found the alert in lgtm.com.
> No
=> fix: removed unused fill variable in components/logo.tsx

website/pages/docs/media-and-icons/avatar.mdx
Added props table for `Avatar` that I accidentally removed in https://github.com/chakra-ui/chakra-ui/commit/ea5cb20558bb621968752d5ebc2fa8e937b5e54c 🤦‍♂️
No
=> docs: add avatar props table

website/pages/docs/navigation/link.mdx
This doc was missing an important import to help identify where the icon was being sourced from.
Closes # 
=> docs: Add missing icon import to docs.

website/pages/docs/navigation/link-overlay.mdx
Closes # 
> Spelling error
Fixing a spelling error in link-overlay docs
Fixes a spelling error
No
=> Fixed spelling error - Bugfix

website/pages/docs/comparison.mdx
Fixes minor typos in comparison doc.
=> docs: Fix minor typos in comparison.mdx

website/src/components/algolia-search.tsx
Closes # 
The current search bar does not have an accessible text
Adds `aria-label` attribute to the search button
No
=> docs: add aria-label to SearchButton

website/configs/resources.json
Closes # 
Added link to my blog on building Image Gallery with Next and Chakra UI.
No
=> docs: add blog on FCC using Chakra UI in resources.json

website/pages/docs/theming/theme.mdx
Links to a tool specifically designed to preview and export Chakra
color scales.
I made Themera so it's a shameless plug, but I believe
@with-heart suggested this to be a good idea on Discord.
=> docs: Link to Themera for generating custom themes

website/pages/docs/layout/container.mdx
Added link to the default theme source for `Container` component.
No
=> docs(container): add theme link

.all-contributorsrc, README.md
Updates id from @psujit14 to @psujit
=> docs: add psujit as a contributor

website/pages/docs/migration.mdx
Closes # 
Fixing small grammar issues
No
=> Fix grammar of migration guide

website/pages/docs/getting-started.mdx
Closes # https://github.com/chakra-ui/chakra-ui/issues/3391
Include working nextjs example
Current installation starter guide does not work with NextJS
Seperate NextJS code example that works
No
=> docs(installation): adding nextjs starting example

website/src/components/footer.tsx
Closes #3520
SVG flag has no label or discernible text
Add a title to the svg so it can more perceivable to screen readers
=> docs: add title to footer svg flag

website/pages/docs/comparison.mdx
Closes # 
Updated information regarding TailwindCSS dark mode in comparison docs
Currently docs mention dark mode for tailwindCSS as experimental
Added update description for tailwind dark mode
No
=> docs: updated exisiting dark mode comparison for tailwindCSS

.changeset/cyan-worms-change.md, .changeset/funny-radios-teach.md, .changeset/yellow-readers-know.md, README.md, examples/create-react-app/package.json, examples/gatsby/package.json, examples/next-js/package.json, examples/nextjs-typescript/package.json, package.json, packages/checkbox/package.json, packages/checkbox/src/checkbox-icon.tsx, packages/menu/package.json, packages/menu/src/menu.tsx, packages/modal/package.json, packages/popover/package.json, packages/react/package.json, packages/toast/package.json, packages/tooltip/package.json, packages/transition/package.json, packages/transition/src/collapse.tsx, tooling/cra-template-typescript/template.json, tooling/cra-template/template.json, website/pages/docs/getting-started.mdx, website/pages/docs/migration.mdx, yarn.lock
Closes #3618
This PR makes a number of changes in order to add support for `framer-motion` v4 (released yesterday) while continuing to support the v3 range. This conditional support for both enables to merge this as a `minor` change rather than a `major` (which would be required if we were to _force_ users to upgrade to v4).
See my comment over here for a more detailed description of what's in this PR: https://github.com/chakra-ui/chakra-ui/issues/3618#issuecomment-802817719
`framer-motion` v4 breaks Chakra projects.
`framer-motion` v4 no longer breaks Chakra projects. Users can use v3 or v4 without issue.
No
=> feat: add support for framer-motion v4

website/pages/docs/theming/theme.mdx
=> docs: Update theme.mdx

website/pages/guides/integrations/with-framer.mdx
While updating my project from framer-motion v3 to v4 I looked at the new docs for this and found that the imports were slightly incorrect. Fixed it now :)
=> chore(docs): Update Framer Motion TS Guide

packages/progress/README.md
Fixed typo "the" -> "they" in the Progress component docs
=> docs(Progress): fixed typo "the" -> "they"

website/pages/docs/migration.mdx
The code diverts from the usual format of single spaces before the opening bracket
Double space typo
Cleans up some code formatting
No
=> fix: docs migration typo cleanup

.changeset/shaggy-glasses-cough.md, website/configs/docs-sidebar.json, website/pages/docs/hooks/use-outside-click.mdx
Add a page for the `useOutsideClick` hook in the doc site.
=> docs(hooks): add use-outside-click page

.changeset/breezy-fireants-bow.md, website/configs/docs-sidebar.json, website/pages/docs/hooks/use-merge-refs.mdx
Add a page for the `useMergeRefs` hook in the doc site.
=> docs(hooks): add use-merge-refs page

.changeset/perfect-maps-hug.md, website/configs/docs-sidebar.json, website/pages/docs/hooks/use-boolean.mdx
Add a page for the `useBoolean` hook in the doc site.
=> docs(hooks): add use-boolean page

website/pages/docs/hooks/use-outside-click.mdx
Fix useOutsideClick docs example
The example logs an error to the console
No
=> fix: useOutsideClick example broken

website/src/components/header.tsx
Bugfix for the inconsistent navbar background-color transition when switching between color modes.
The main block and the navbar are not switching to the same color at the same time as the main have 0.2 second transition duration.
Navbar have 0.2 seconds transition duration
No
=> fix: background color transition for navbar

CHANGELOG.md
=> docs: updated changelog

.changeset/lovely-tomatoes-dream.md, .changeset/many-masks-listen.md, .changeset/moody-flies-provide.md, .changeset/quiet-cobras-whisper.md, .changeset/shy-dancers-beam.md, .changeset/six-sheep-laugh.md, .changeset/tidy-dots-refuse.md, packages/button/src/button-group.tsx, packages/button/stories/button.stories.tsx, packages/input/src/input-addon.tsx, packages/input/src/input-element.tsx, packages/input/src/input-group.tsx, packages/input/stories/input.stories.tsx, packages/layout/src/list.tsx, packages/popover/src/popover.tsx, packages/theme/src/components/alert.ts, packages/theme/src/components/input.ts, packages/theme/src/components/spinner.ts, packages/theme/src/components/tabs.ts, packages/theme/src/components/tag.ts, packages/toast/src/use-toast.tsx
Update component styles to use RTL
=> fix: update theme and rtl styles

.changeset/great-grapes-flow.md, packages/transition/src/collapse.tsx
Closes # 
> Support custom variants for transition components
> Not allowed custom transition variants
> You can now rewrite chakra default transition variant
No, nice to have only
=> fix(transition): rest param

.changeset/real-chicken-fetch.md, packages/popper/README.md, packages/popper/src/use-popper.ts
Update README for the `popper.js` wrapper.
Fix a typo in jsodcs for the `UsePopperProps` interface.
=> docs(popper): update and improve README

website/pages/docs/feedback/toast.mdx
Closes #3535
Add small note where to use the useToast hook.
=> docs(toast): add note to call useToast below ChakraProvider

website/configs/site-config.ts, website/src/components/footer.tsx, website/src/components/header.tsx
Added links to our new YouTube channel in the navigation bar and footer.
=> feat: adding youtube links in footer and navigation

website/package.json, website/pages/docs/getting-started.mdx, website/src/components/mdx-components.tsx, yarn.lock
Embedding the YouTube video "Getting Started with Chakra UI" in the docs
=> feat: embedded getting started video in docs

website/pages/docs/theming/component-style.mdx
Added a little Pro tip on how to see a list of the parts for a certain multipart component.
=> docs: added a tip on checking the list of parts of a multipart component

website/pages/docs/theming/theme.mdx
Append lacked value on spacing table  
Not exist 0.5, 1.5, 2.5, 3.5.
Append 0.5, 1.5, 2.5, 3.5
No
=> docs(theme): Add spacing table (0.5, 1.5, 2.5, 3.5)

website/pages/docs/theming/customize-theme.mdx
=> Fix wrong prop in the docs

packages/theme/src/components/tabs.ts
Closes # 
> Update tabs sizes use theme vars
> current tabs size use hardcode vars
> change tabs size use theme vars
=> Update tabs sizes use theme vars

packages/system/README.md
=> chore: code style

CHANGELOG.md
Adding a simple CodeSandbox link that demonstrates the new Ring props in the Changelog page
No
=> docs: Added a CodeSandbox link for Ring update in Changelog

.changeset/quiet-toys-yell.md, packages/styled-system/src/utils/parse-gradient.ts, packages/styled-system/src/utils/transform-functions.ts, packages/styled-system/tests/transform-functions.test.ts
Closes #4043 🤞
Please check issue description & comments
<Progress /> with isIndeterminate not working 
Fix 🤞
I hope not.
=> fix(transform-functions): bgImage url bool condition

packages/modal/README.md
Closes #4033
Fixed the `DrawerOverlay` tag closing in the README for the `Modal` package.
No
=> docs: fixed DrawerOverlay tag closing

website/pages/guides/integrations/with-framer.mdx
Fixes the small typo of "verion" in the with-framer doc.
N/A
N/A
No
=> docs(with-framer): fix typo

website/pages/guides/integrations/with-hook-form.mdx
Closes # 
> Updated the link for the usage of React-hook-forms. Updated to latest version 7.6.4
=> doc(website): doc links Update to react-form-hooks  v7.6.4

website/configs/resources.json
Adding the new Design vs Dev Challenge video link in the Resources page
=> docs: added design vs dev challenge video link in resources

website/pages/docs/comparison.mdx
"How is Chakra different from Ant Design?" docs > comparison
The section was empty
The section now has a comparison between the two libraries
No
=> docs: chakra and ant design comparison

.changeset/eight-numbers-lick.md, packages/tabs/package.json, packages/tabs/src/use-tabs.ts, packages/tabs/stories/tabs.stories.tsx
=> fix(tabs): render tab indicator at the correct pos

.changeset/fuzzy-cobras-stare.md, packages/button/jest.config.js, packages/button/src/button.tsx, packages/button/tests/button-group.test.tsx, packages/button/tests/button.test.tsx
Implement new test cases to button package
Only tests to a few button behaviors, with 72% of branch coverage
Increment 12 new test statements extending branches converge to 82%,
- button-group -> 83%
- button -> 90%
- ...
=> Tests 🧪: Add new test cases to button package

packages/toast/stories/toast.stories.tsx
Add Story for Standalone Toast
=> chore(storybook): Add Standalone toast story

website/pages/guides/component-guide.mdx
Closes # 
Typo on line 84: "enable teams leverage the library" should be "enable teams _to_ leverage the library"
N/A
N/A
No
=> docs: fix typo in component-guide.mdx

website/pages/docs/feedback/toast.mdx
Add update toasts example to docs. Closes #4136
=> docs(toast): add update toasts example

website/pages/docs/feedback/toast.mdx
Closes #4112
Added a note to the `createStandaloneToast` docs that a custom theme **must** be passed as an argument or the text size of the page will shift. 
No
=> docs(toast): add required theme arg note for createStandaloneToast

.changeset/honest-onions-look.md, website/src/components/icons-list.tsx
Closes #3889 
The pull request contains code that is part of the website docs, more specifically from the icons list, at the [icons page](https://chakra-ui.com/docs/media-and-icons/icon#all-icons)
Nothing happens when the user clicks some icon
When clicking on any icon at [icons page](https://chakra-ui.com/docs/media-and-icons/icon#all-icons), the icon name is copied to the clipboard
No
=> docs(icons): copy icon to clipboard feature

.changeset/fast-walls-wash.md, packages/popover/src/use-popover.ts, packages/popover/stories/popover.stories.tsx
=> fix(popover): arrowshadowcolor not working

website/pages/docs/features/style-props.mdx
Change wording to be more clear.
Wording is hard to understand
No new behavior
No
=> Update wording in style-props.mdx

packages/theme-tools/src/color.ts
Closes # 
The `amount` parameter should be `opacity` and have the appropriate description
No
=> docs(transparentize): parameter typo

website/src/components/omni-search.tsx
=> fix(docs): unescaped search query

website/pages/docs/features/global-styles.mdx
> added a dependency for an example: /docs/features/global-styles
=> docs: added dependency to example

README.md, website/configs/site-config.ts, website/next-redirect.js, website/src/components/discord-strip.tsx
Closes #4207
This PR updates Discord links in `README` and in various places on the site with our custom Discord url (https://discord.gg/chakra-ui).
=> fix(website): update Chakra discord links

.changeset/lemon-deers-carry.md, tooling/cli/bin/tsconfig.json
Closes #4200
This PR enables `esModuleInterop` for the `chakra-cli tokens` command to fix its usage in projects using this configuration.
No
[TSConfig Reference ES Module Interop](https://www.typescriptlang.org/tsconfig#esModuleInterop)
=> feat(cli): enable esModuleInterop for cli tokens command

website/pages/docs/data-display/divider.mdx
Fixed a broken Divider Source link
Link points to https://github.com/chakra-ui/chakra-ui/tree/main/packages/divider
Link points to https://github.com/chakra-ui/chakra-ui/blob/main/packages/layout/src/divider.tsx
Nope
=> docs: fixed broken divider source link

packages/button/stories/button.stories.tsx
Add Unstyled Button to the Storybook.
=> chore(storybook): add unstyled button

website/pages/guides/with-nextjs.mdx
The guide at https://chakra-ui.com/guides/with-nextjs does not include all the libraries needed for chakra; this PR adds those back. This guide comes up in google search, which is where I found it, so fixing this would make it easier for people like me :)
=> docs: update to add other required libraries

.github/workflows/daily.yml
Fixes failing daily.yml action due to nothing to commit:
https://github.com/chakra-ui/chakra-ui/actions/runs/1106766811
https://stackoverflow.com/a/40255467
=> chore: fix failing daily cron action

CHANGELOG.md
=> docs: add changelog for next release

website/pages/docs/contributing.mdx
=> fix(docs): update branch name in `contributing.md`

website/pages/docs/features/css-variables.mdx
Fix a typo in the website documentation
=> Fix typo in docs

website/pages/guides/integrations/with-framer.mdx
=> docs(example): remove unused import in example with-framer

.changeset/angry-weeks-explain.md, packages/theme-tools/package.json, packages/theme-tools/src/color.ts
Closes https://github.com/chakra-ui/chakra-ui/issues/4705
Get rid of tinycolor2 to reduce bundle size on user land.
N/A
the new behavior is the same as the current 
No
=> feat(theme-tools): use @ctrl/tinycolor instead of tinycolor2

website/pages/docs/features/gradient.mdx, website/pages/docs/features/style-props.mdx
Unified the spaces for Style Props Docs and Gradient Docs.
There are parts with space and parts without space.
Spaces are unified.
No
=> Align spaces in features docs

website/pages/docs/layout/box.mdx
from typing i found usage of d is deprecated, so should the docs
=> fix: @deprecated — - Please use display instead

.changeset/polite-pants-arrive.md, website/pages/docs/theming/component-style.mdx, website/pages/docs/theming/customize-theme.mdx
Closes #4871
Since a few issues aroused regarding multipart component styling I tried to give a better hint on how this works.
No
=> chore(docs): add more detailed explanation about multipart component styling

.changeset/twenty-pots-lie.md, website/configs/resources.json
Adding https://www.lekoarts.de/react/how-to-build-an-advanced-multipart-component-with-chakra-ui to the resources overview
Hope you like it! :)
=> chore(website): Add article about multipart component

README.md
Adjust framer version in the readme to current version
=> chore: adjust readme to use framer in v5

.changeset/quiet-carpets-exercise.md, packages/media-query/src/media-query.hook.tsx, packages/popper/src/use-popper.ts
=> fix: use-colormode preference hook

CHANGELOG.md
=> chore: Fix typo

.changeset/twelve-trainers-eat.md, packages/popover/src/popover.tsx, packages/popover/src/use-popover.ts, packages/popover/stories/popover.stories.tsx
Follow up on https://github.com/chakra-ui/chakra-ui/pull/4734
Closes #4733
Demo: an Input with a popover
https://user-images.githubusercontent.com/14360171/141017574-e91c3e52-88ff-4229-a2d1-a42731c9a50d.mov
=> feat(popover): PopoverAnchor

.changeset/sweet-rabbits-turn.md, packages/accordion/stories/accordion.stories.tsx
Closes # 
accordion.story.tsx has type errors shown in code editor.
@chakra-ui/accordion stories show typescript error on input Changes and refs.
add type declarations for current issue.
No
=> fix: accordion story

.changeset/little-dodos-happen.md, packages/hooks/src/use-const.ts
Closes # 
Add a comment about `useState` alternative, to make clear why `useRef` is the best choice.
Fix a typo in jsdoc.
No
N/A
=> docs(hooks): add a notice about useState alternative

CONTRIBUTING.md
=> docs: remove docsite dev instructions

.changeset/kind-phones-lick.md, tooling/storybook-addon/package.json
Closes #5336
Missing dependency for `@chakra-ui/icons` forces users to install this package explicitly.
Added `@chakra-ui/icons` as dependency.
No
=> fix(sb-addon): add missing dependency of @chakra-ui/icons

.changeset/tasty-pears-sell.md, packages/toast/src/use-toast.tsx
Based on #4240
- added a changeset
=> fix(toast): update use-toast to not return new object each render

.changeset/unlucky-crabs-repeat.md, packages/icon/src/create-icon.tsx
Closes -> no current issue
Add missing word in comment for a prop.
missing word in comment
no missing word in comment
No
=> fix: typo in CreateIconOptions comment

packages/layout/src/simple-grid.tsx
> The JSDocs for the `SimpleGrid` had grammatical errors. Along with making the correction, tried to provide a clearer idea on the component's purpose compared to using `Grid`.
> Should I include param details for IDE intellisense to let you know what the unique props are?
=> docs(simple-grid): Fix grammar in the component description and provide more explicit detail on the component's purpose.

packages/menu/src/menu.tsx
Closes # 
adding comment  to rootProps
No
=> add comments to rootprops menu list

.changeset/stupid-boats-punch.md, packages/checkbox/src/checkbox-icon.tsx, packages/menu/src/menu.tsx
Closes #3618
fix: #3618 CRA template fails with newer versions of framer-motion
Uncaught TypeError: framer_motion__WEBPACK_IMPORTED_MODULE_5__.motion.custom is not a function
When using the CRA template
Added type check to prevent this error
No
=> fix: newer framer motion

.github/workflows/release.yml
Closes # /
Sibling PR to review: 
https://github.com/chakra-ui/chakra-ui-docs/pull/510
To fix the bug where the github action was failing. Why did this happen? After some investigation it turned out because the CURL request was in multiple lines, it should stay in one line.
The github action fails.
The github action won't fail.
No.
=> fix: Putting CURL request in one line to fix bug where requested wasn't being sent

.github/workflows/next.yml, examples/create-react-app/package.json, examples/gatsby/package.json, examples/next-js/package.json, examples/nextjs-typescript/package.json, tooling/gatsby-plugin/package.json
This PR fixes mismatching npm version ranges to allow the next branch to build
=> fix(next): branch setup

packages/checkbox/tests/checkbox.test.tsx, packages/color-mode/test/color-mode-script.test.tsx, packages/radio/tests/behavior.test.tsx
Fixup #5828
Update tests affected by #5828
Tests are failing due usage of deprecated APIs
Use updated APIs to fix the test run
No
=> test: remove deprecations

examples/nextjs-typescript/package.json, packages/alert/package.json, packages/alert/src/alert.tsx, packages/alert/stories/alert.stories.tsx, packages/anatomy/src/index.ts, packages/color-mode/test/color-mode-provider.test.tsx, packages/color-mode/test/color-mode-provider__browser.test.tsx, packages/media-query/package.json, packages/skeleton/package.json, packages/theme/src/components/alert.ts, packages/toast/src/toast.types.ts, packages/toast/src/use-toast.tsx, packages/toast/stories/toast.stories.tsx, packages/toast/test/use-toast.test.tsx, packages/utils/src/function.ts, yarn.lock
Closes #3911 
> There is no support for async/loading toasts
> No support for displaying loading status in toasts
> Added toast.promise  as suggested in this discussion https://github.com/chakra-ui/chakra-ui/pull/4322#issuecomment-894024858
this is a follow up of stale/closed PR https://github.com/chakra-ui/chakra-ui/pull/4322
=> feat: add support for async toast

examples/nextjs-typescript/package.json
=> fix: replace asterix version

.changeset/green-moose-care.md
=> chore: trigger CI

.changeset/pretty-terms-attend.md, packages/theme/src/styles.ts
Closes #5886
Improve color contrast of default input elements
=> fix: placeholder color contrast

.changeset/quiet-ligers-tease.md, packages/editable/src/use-editable.ts
Related #424 #3198
Call onCancel when submitOnBlur is false
=> fix(editable): cancel on blur

.eslintrc, examples/create-react-app/package.json, examples/nextjs-typescript/package.json, examples/vite-ts/package.json, package.json, packages/form-control/src/use-form-control.ts, packages/hooks/src/use-why-update.ts, packages/layout/src/stack.utils.tsx, packages/modal/src/drawer.tsx, packages/popper/src/popper.placement.ts, packages/popper/src/utils.ts, packages/react/tests/extend-theme.test.tsx, packages/select/tests/select.test.tsx, packages/styled-system/src/config/others.ts, packages/styled-system/src/create-theme-vars/create-theme-vars.ts, packages/styled-system/src/utils/parse-gradient.ts, packages/styled-system/src/utils/transform-functions.ts, packages/table/stories/react-table.stories.tsx, packages/utils/src/object.ts, packages/utils/src/pointer-event.ts, tooling/cli/src/scripts/read-theme-file.worker.ts, tooling/cra-template-typescript/template.json, tooling/storybook-addon/src/preset/emotion-fallback.ts, tooling/test-utils/src/mock-image.ts, yarn.lock
Update TypeScript and fix type errors
=> chore: upgrade typescript and fix types

.changeset/new-rivers-fail.md
This PR updates the changeset text for the toast package to be more clear what to do with the `ToastManager` returned from `createStandaloneToast`.
=> chore(toast): update changeset

.changeset/plenty-eggs-type.md
Fixup #5619
Add missing changeset for the package css-reset
=> chore(css-reset): add changeset

.changeset/olive-crews-mix.md, packages/layout/src/link-box.tsx
Closes #5918
After some consequential problems of https://github.com/chakra-ui/chakra-ui/pull/5632 the changes will be reverted with this PR. 
https://github.com/chakra-ui/chakra-ui/pull/5679 will also be reverted because it was also a consequential problem of https://github.com/chakra-ui/chakra-ui/pull/5632.
Yes (hopefully only for a small group of people)
=> fix: restore zindex of LinkOverlay from LinkBox

README.md
Updated links to documentation for v2 and also updated installation instructions to match docs
Backlinks to older Chakra UI versions were missing and installation instructions did'nt match docs anymore.
New backlink for v1 docs and updated installation instructions with a reference to the docs.
No
=> chore: update readme for v2

.changeset/grumpy-hats-jog.md
Relates to #5855
A missing changeset prevented the release of all packages without the `src` directory.
Packages with no explicit changeset were not published
All packages will be published
No
=> chore: add changeset for all packages

.changeset/honest-dolls-fetch.md, packages/media-query/src/use-media-query.ts, packages/media-query/tests/use-media-query.test.ts
Fix hydration mismatch issue when using `useBreakpoint` or `useBreakpointValue` in an SSR environment.
Throws a mismatch error
Works
No
=> fix: use-media-query ssr

.changeset/cuddly-carrots-pay.md, .changeset/witty-cheetahs-kick.md, packages/styled-system/src/style-config.ts, packages/styled-system/src/utils/create-transform.ts, packages/styled-system/tests/css.test.ts, packages/styled-system/tests/style-config.test.ts, packages/utils/src/breakpoint.ts, packages/utils/tests/responsive.test.ts
Closes #6083
- Fix media query calculations for responsive variants and sizes
- Fix issue where values with `!important` can resolve to a double `!important`
being added
No
=> fix: styled system and responsive variant

.changeset/tall-owls-lie.md, .storybook/main.js, tooling/storybook-addon/package.json, yarn.lock
Enable `lazyCompilation` and `fsCache` to speed up storybook builds
|  |  |
| --- | --- |
| Before | `24 s for manager and 26 s for preview` |
| After (w/o cache) | `23 s for manager and 24 s for preview` |
| After (w/ cache) | `11 s for manager and 9.37 s for preview` |
No
=> chore: make storybook builds fast

.changeset/eight-zebras-invent.md, packages/modal/package.json, yarn.lock
Closes #6084
Update react-remove-scroll to fix shifting screen when opening modal
When opening modal, it shifts the html body.
Works as expected (not shift body)
No
- Related PR: https://github.com/theKashey/react-remove-scroll-bar/pull/32
- Test sandbox: https://codesandbox.io/s/fix-shifting-screen-91vorj
=> fix(modal): fix shifting screen when opening modal

README.md
Closes # 
updating link for create-react-app template in README
=> fix(docs): updating link for cra-template

packages/media-query/README.md, packages/select/README.md
Closes # 
> I check the Select component folder and I found a missing name on the README.md file.
> None.
> None.
No.
None.
=> fix(doc): add select and media-query names to README.md file

.changeset/dull-worms-happen.md, .changeset/hip-timers-jump.md, .changeset/pink-rocks-marry.md, examples/next-js/next.config.js, examples/next-js/package.json, examples/next-js/pages/portal.js, examples/nextjs-typescript/next.config.js, examples/nextjs-typescript/package.json, packages/portal/src/portal.tsx, yarn.lock
Closes #6297
Closes #6304
Portal and portal-related components are broken in development + strict mode because the portal does not render its children.
This PR fixes to render children correctly.
- Portal does not render children
- Modal does not work
No
=> fix(portal): fix portal to render children

.changeset/quiet-spiders-lay.md, .changeset/tiny-rabbits-admire.md, examples/nextjs-typescript/Chakra.tsx, examples/nextjs-typescript/pages/_document.tsx, examples/nextjs-typescript/pages/index.tsx, examples/nextjs-typescript/theme.ts, packages/color-mode/src/color-mode-provider.tsx, packages/env/src/env.tsx
Closes #6129
Closes #5842
Additional implementation of #6171.
Fix hydration issues of  `EnvironmentProvider` and `ColorModeProvider`
In SSR with Suspense, `EnvironmentProvider` and `ColorModeProvider` do not work because of hydration issue.
No
=> Fix hydration issues

.changeset/silent-schools-fetch.md, tooling/cli/README.md
Closes # 
Update a sample command in cli's README
No
=> docs(cli): update a sample command in cli's README

.changeset/healthy-tables-burn.md, packages/layout/src/highlight.tsx, packages/layout/stories/highlight.stories.tsx
Closes https://github.com/chakra-ui/chakra-ui/issues/6321
Add prop key in `Highlight` component to avoid warnings.
No
=> fix(layout): add prop key in `Highlight` component to avoid warnings

.changeset/kind-kiwis-notice.md, .eslintrc
Specify react version for eslint-plugin-react to avoid warning.
ref: https://github.com/jsx-eslint/eslint-plugin-react#configuration
Got warning on `pnpm lint`
```
$ pnpm lint
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration
```
No warning
=> chore(lint): specify react ver for eslint-plugin-react

.changeset/shaggy-camels-dance.md, .changeset/sharp-llamas-rush.md, hooks/use-size/README.md, hooks/use-size/index.ts, hooks/use-size/package.json, hooks/use-size/src/index.ts, hooks/use-size/stories/use-size.stories.tsx, packages/hooks/src/use-dimensions.ts, pnpm-lock.yaml
This hook will replace the `useDimensions` hook we currently have.
=> feat: add use-size hook

.gitignore
Add `hooks/**/dist` to `.gitignore`
No
=> chore: gitignore `hooks/**/dist`

packages/transition/README.md
Update prop name
Closes # 
update prop name for Collapse component
no change in behavior
no change
no
=> docs: Update prop name

.changeset/lovely-waves-matter.md, utilities/shared-utils/README.md, utilities/shared-utils/index.ts, utilities/shared-utils/package.json, utilities/shared-utils/src/index.ts
chore: add shared-utils package
=> chore: add shared-utils package

.changeset/cuddly-suns-eat.md, .changeset/lucky-toys-give.md, packages/accordion/package.json, packages/accordion/src/accordion-button.tsx, packages/accordion/src/accordion-icon.tsx, packages/accordion/src/accordion-item.tsx, packages/accordion/src/accordion-panel.tsx, packages/accordion/src/accordion.tsx, packages/accordion/src/use-accordion.ts, pnpm-lock.yaml, utilities/shared-utils/src/index.ts, utilities/shared-utils/src/types.ts
=> chore(accordion): refactor

.changeset/fifty-days-shout.md, packages/descendant/package.json, packages/descendant/src/use-descendant.ts, pnpm-lock.yaml
=> chore(descendant): refactor

.changeset/wise-fireants-collect.md, packages/control-box/package.json, packages/control-box/src/control-box.tsx, pnpm-lock.yaml
=> chore(control-box): refactor

.changeset/clean-ways-poke.md, packages/close-button/package.json, packages/close-button/src/close-button.tsx, pnpm-lock.yaml
=> chore(close-button): refactor

.changeset/lovely-lamps-cough.md, packages/alert/package.json, packages/alert/src/alert-description.tsx, packages/alert/src/alert-icon.tsx, packages/alert/src/alert-title.tsx, packages/alert/src/alert.tsx, pnpm-lock.yaml
=> chore(alert): refactor

.changeset/hungry-crews-return.md, .changeset/loud-meals-itch.md, hooks/use-safe-layout-effect/README.md, hooks/use-safe-layout-effect/index.ts, hooks/use-safe-layout-effect/package.json, hooks/use-safe-layout-effect/src/index.ts, packages/checkbox/package.json, packages/checkbox/src/checkbox-context.ts, packages/checkbox/src/checkbox-group.tsx, packages/checkbox/src/checkbox.tsx, packages/checkbox/src/use-checkbox-group.ts, packages/checkbox/src/use-checkbox.ts, pnpm-lock.yaml, utilities/react-types/src/index.d.ts, utilities/shared-utils/src/index.ts
=> chore(checkbox): refactor

.changeset/fair-cameras-cry.md, packages/avatar/package.json, packages/avatar/src/avatar-badge.tsx, packages/avatar/src/avatar-group.tsx, packages/avatar/src/avatar.tsx, pnpm-lock.yaml
=> chore(avatar): refactor

.changeset/gentle-walls-compete.md, hooks/use-focus-on-pointer-down/README.md, hooks/use-focus-on-pointer-down/index.ts, hooks/use-focus-on-pointer-down/package.json, hooks/use-focus-on-pointer-down/src/index.ts, packages/editable/package.json, packages/editable/src/editable-context.ts, packages/editable/src/editable-input.tsx, packages/editable/src/editable-preview.tsx, packages/editable/src/editable-textarea.tsx, packages/editable/src/editable.tsx, packages/editable/src/use-editable.ts, pnpm-lock.yaml
=> chore(editable): refactor

.changeset/hip-seals-repeat.md, packages/color-mode/package.json, packages/color-mode/src/color-mode-context.ts, packages/color-mode/src/color-mode-provider.tsx, packages/color-mode/src/color-mode.utils.ts, packages/color-mode/src/storage-manager.ts, pnpm-lock.yaml
=> chore(color-mode): refactor

.changeset/pink-badgers-dream.md, packages/form-control/package.json, packages/form-control/src/form-control.tsx, packages/form-control/src/form-error.tsx, packages/form-control/src/form-label.tsx, packages/form-control/src/use-form-control.ts, pnpm-lock.yaml
=> Refactor form control

.changeset/lazy-kiwis-camp.md, packages/icon/package.json, packages/icon/src/create-icon.tsx, packages/icon/src/icon.tsx, pnpm-lock.yaml
=> Refactor icon

.changeset/strong-vans-itch.md, packages/layout/package.json, packages/layout/src/aspect-ratio.tsx, packages/layout/src/badge.tsx, packages/layout/src/box.tsx, packages/layout/src/center.tsx, packages/layout/src/code.tsx, packages/layout/src/container.tsx, packages/layout/src/divider.tsx, packages/layout/src/flex.tsx, packages/layout/src/grid.tsx, packages/layout/src/heading.tsx, packages/layout/src/kbd.tsx, packages/layout/src/link-box.tsx, packages/layout/src/link.tsx, packages/layout/src/list.tsx, packages/layout/src/simple-grid.tsx, packages/layout/src/spacer.tsx, packages/layout/src/stack.tsx, packages/layout/src/stack.utils.tsx, packages/layout/src/text.tsx, packages/layout/src/wrap.tsx, pnpm-lock.yaml, utilities/breakpoint-utils/CHANGELOG.md, utilities/breakpoint-utils/README.md, utilities/breakpoint-utils/index.ts, utilities/breakpoint-utils/package.json, utilities/breakpoint-utils/src/breakpoint.ts, utilities/breakpoint-utils/src/index.ts, utilities/breakpoint-utils/src/responsive.ts
=> Refactor layout

.changeset/sour-readers-wink.md, packages/live-region/package.json, packages/live-region/src/live-region.ts, pnpm-lock.yaml
=> Refactor Live region

.changeset/itchy-needles-juggle.md, packages/input/package.json, packages/input/src/input-addon.tsx, packages/input/src/input-element.tsx, packages/input/src/input-group.tsx, packages/input/src/input.tsx, pnpm-lock.yaml, utilities/shared-utils/src/index.ts
=> Refactor Input

packages/spinner/package.json, pnpm-lock.yaml, utilities/object-utils/src/index.ts
Fix type errors
ref: https://github.com/chakra-ui/chakra-ui/runs/7931755225
No
=> Fix type errors

.changeset/chilly-adults-warn.md, pnpm-lock.yaml, tooling/cli/package.json, tooling/storybook-addon/package.json
=> chore: remove unused npm packages

packages/components/form-control/tests/form-control.test.tsx, packages/components/icon/src/create-icon.tsx, packages/components/popper/src/use-popper.ts
This PR fixes a few minor typos in the docs.
=> docs: fix some typos

.changeset/perfect-cycles-argue.md, packages/components/layout/src/highlight.tsx, packages/components/tooltip/package.json, packages/components/tooltip/src/tooltip.tsx, packages/components/tooltip/src/use-tooltip.ts, packages/components/tooltip/stories/tooltip.stories.tsx, packages/components/tooltip/tests/tooltip.test.tsx, pnpm-lock.yaml
Closes #5528 
Tooltip on disabled buttons wasn't showing up because disabled buttons don't trigger mouse events. There was also an issue when `shouldWrapChildren` prop is set to `true`, the `span` wrapper needs a `display="inline-block"` to fix the tooltip positioning.
Disabled buttons don't trigger the tooltip.
Disabled buttons do trigger the tooltip.
No
=> fix(tooltip): fixed tooltip wrapping and changed mouse events to pointer events

.changeset/ninety-pugs-suffer.md, packages/components/popover/package.json, packages/components/popover/src/use-popover.ts, pnpm-lock.yaml
=> chore(popover): refactor

.changeset/afraid-gorillas-give.md, packages/components/pin-input/src/use-pin-input.ts
=> fix(pin-input): focus issue

.changeset/tasty-poems-boil.md, packages/components/avatar/src/avatar-image.tsx, packages/components/avatar/src/avatar.tsx, packages/components/theme/src/components/avatar.ts
Fixes #4304
Fix issue where background remained after image is loaded
=> fix(avatar): wrong avatar styling

.changeset/stupid-papayas-think.md, packages/components/breadcrumb/src/breadcrumb.tsx, packages/components/theme/src/components/breadcrumb.ts
Fixes #6230
Fixes breadcrumb item alignment styles
=> fix(breadcrumb): breadcrumb items alignment

.changeset/odd-shirts-cough.md, packages/components/theme/src/components/number-input.ts
Closes #6627 
Fixes number input disabled style.
=> fix(number-input): disabled style

.changeset/young-chicken-remember.md, packages/components/accordion/src/use-accordion.ts
Fixes #6734
Fixed `allowMultiple` warning condition logic
=> fix(accordion): allowMultiple warning condition

.changeset/angry-adults-cough.md, .changeset/pink-guests-suffer.md, .eslintrc, packages/components/slider/package.json, packages/components/slider/src/use-slider.ts, packages/components/slider/stories/slider.stories.tsx, packages/hooks/use-latest-ref/README.md, packages/hooks/use-latest-ref/clean-package.config.json, packages/hooks/use-latest-ref/package.json, packages/hooks/use-latest-ref/src/index.ts, packages/hooks/use-latest-ref/tsconfig.json, packages/hooks/use-latest-ref/tsup.config.ts, pnpm-lock.yaml
Closes #6606, #6750
Fixed issue with slider props updates
=> fix(slider): stale data issues

.changeset/warm-spiders-deny.md, packages/components/react/package.json, packages/components/toast/package.json, pnpm-lock.yaml
Fixed unmet `@chakra-ui/styled-system` dependency issue
Closes #6756
=> Fixed unmet dependency issues

.changeset/calm-apples-prove.md, packages/components/toast/src/use-toast.tsx
Closes #6775
Fixes toast `containerStyles` types
=> fix(toast): containerStyle types

.changeset/metal-candles-peel.md, packages/legacy/hooks/src/use-clipboard.ts, packages/legacy/hooks/tests/use-clipboard.test.tsx, pnpm-lock.yaml
Closes #6759 
Exposing a new function from `useClipboard` to enable the control over the value even after first initialization
With the current behaviour `useClipboard` doesn't offer the any way to set the value copied after the first initialization of the hook.
The `useClipboard` hook now exposes a `setValue` function that enables the control over the copied value even after the first initialisation
```
const {setValue} = useClipboard('initial value')
onCopy() // copies 'initial value'
setValue('new value')
onCopy() // copies 'new value'
```
No
=> feat: expose `setValue` from `useClipboard`

.changeset/.changeset/pink-rockets-pull.md, packages/components/toast/src/toast.tsx, packages/components/toast/src/toast.types.ts, packages/components/toast/stories/toast.stories.tsx
Closes #6613
Expose options to toast `render`
=> Expose toast options in `render`

packages/components/theme/src/components/alert.ts
=> refactor: alert theme

.changeset/nine-years-pretend.md, .codesandbox/ci.json, packages/components/theme/src/components/tooltip.ts
=> chore: update tooltip theme

packages/components/theme/src/components/skip-link.ts
chore: refactor theme - Skiplink
=> chore: refactor theme - Skiplink

packages/components/theme/src/components/close-button.ts
chore: refactor theme - CloseButton
=> chore: refactor theme - CloseButton

packages/components/theme/src/components/slider.ts, packages/components/theme/src/components/switch.ts
=> chore: refactor switch theme

packages/components/theme/src/components/drawer.ts
chore: refactor theme - Drawer
=> chore: refactor theme - Drawer

.changeset/eighty-dogs-dream.md, packages/components/progress/src/progress.tsx
Closes #6899
Add title to progress inner element for better accessibility
=> fix(progress): add title for accessbility

packages/components/theme/src/components/form-control.ts
chore: refactor theme - FormControl
=> chore: refactor theme - FormControl

packages/components/theme/src/components/popover.ts
chore: refactor theme - Popover
=> chore: refactor theme - Popover

packages/components/theme/src/components/form-error.ts
chore: refactor theme - FormError
=> chore: refactor theme - FormError

.changeset/light-jobs-nail.md, .changeset/plenty-steaks-stare.md, package.json, packages/components/anatomy/src/components.ts, packages/components/card/README.md, packages/components/card/clean-package.config.json, packages/components/card/package.json, packages/components/card/src/card-context.tsx, packages/components/card/src/card.tsx, packages/components/card/src/index.ts, packages/components/card/stories/card.stories.tsx, packages/components/system/src/providers.tsx, packages/components/theme/src/components/card.ts, packages/components/theme/src/components/index.ts, packages/components/theme/src/semantic-tokens.ts, pnpm-lock.yaml
This PR introduces the new `Card` component to Chakra UI
No
=> feat: add card component

.changeset/dull-hotels-kick.md, packages/components/theme/src/components/tabs.ts
=> chore: update tabs theme

packages/components/theme/src/components/select.ts
chore: refactor theme - Select
=> chore: refactor theme - Select

packages/components/theme/src/components/menu.ts
=> chore: refactor menu theme

plopfile.js
Closes # 
Fix template generation output directory
=> chore: fix plop outDir

.changeset/gorgeous-bags-repeat.md, packages/components/theme/src/components/modal.ts
FIx safari full size glitch
Closes #5889
=> fix(modal): safari full size glitch

.changeset/fifty-socks-arrive.md, .changeset/forty-laws-sing.md, packages/components/menu/src/use-menu.ts, packages/components/menu/stories/menu.stories.tsx
=> fix(menu): update active item on focus

.changeset/chilly-dragons-sin.md, packages/components/card/src/card-footer.tsx
fix theme being overidden
Fixes #7109
=> fix (card): fix theme being overidden

packages/components/skeleton/README.md
To match other component READMEs.
PR Type: **docs**
No breaking changes
=> docs(skeleton): add import and usage

examples/vite-ts/package.json, pnpm-lock.yaml
Update vite in `exmaples/vite-ts` to fix build error.
`pnpm build` on `examples/vite-ts` fails with the error below
```
[vite:react-babel] [masked]/chakra-ui/packages/core/system/src/system.ts: Missing semicolon. (18:4)
16 | import { DOMElements } from "./system.utils"
17 |
> 18 | type StyleResolverProps = SystemStyleObject & {
|     ^
19 |   __css?: SystemStyleObject
20 |   sx?: SystemStyleObject
21 |   theme: any
file: [masked]/chakra-ui/packages/core/system/src/system.ts:18:4
error during build:
SyntaxError: [masked]/chakra-ui/packages/core/system/src/system.ts: Missing semicolon. (18:4)
16 | import { DOMElements } from "./system.utils"
17 |
> 18 | type StyleResolverProps = SystemStyleObject & {
|     ^
19 |   __css?: SystemStyleObject
20 |   sx?: SystemStyleObject
21 |   theme: any …
```
=> build(examples): update vite in examples/vite-ts to avoid build error

.changeset/wet-islands-look.md, packages/components/theme/package.json
Closes #7130
See #7130
Can import from `@chakra-ui/theme/components` or `@chakra-ui/theme/foundations`
https://codesandbox.io/s/unruffled-bouman-vzwkx6
No
=> build(theme): Export components and foundations from theme package

.codesandbox/ci.json
The artifacts of Codesandbox CI doesn't includes new Card component.
It causes an error on PR preview.
https://codesandbox.io/s/twilight-rgb-qmlw8y
=> chore(csb): add `packages/components/card` to csb packages

examples/next-js/next.config.js, examples/next-js/package.json, examples/nextjs-typescript/components/NextChakraLink.tsx, examples/nextjs-typescript/next.config.js, examples/nextjs-typescript/package.json, pnpm-lock.yaml
update next-js examples to next 13
=> chore: update next-js examples to next 13

.changeset/chatty-games-refuse.md, packages/components/theme-tools/src/color.ts
Closes #7155 
Resolve theme tools to values between 0 and 1
=> fix: theme-tools methods color mix amounts

.changeset/fifty-games-swim.md, packages/core/styled-system/tests/style-config.test.ts, packages/utilities/breakpoint-utils/src/breakpoint.ts
Resolves https://github.com/chakra-ui/chakra-ui/issues/7202
=> fix(styled-system): fix issue with useBreakpointvalue in Firefox

tsconfig.json
=> chore: remove react-shim.js that is no longer in use

.changeset/late-starfishes-rhyme.md, packages/components/skeleton/src/skeleton.tsx
Closes #7230 
> Fixed `fadeDuration` and `speed` animation problems with the solution proposed in the mentioned issue.
=> fix(SkeletonText): fade and speed animation

packages/components/skeleton/src/skeleton-text.tsx
Closes #7237
> Fixed theming problems with the solution proposed in the mentioned issue.
=> fix(SkeletonText): theming

packages/components/checkbox/package.json, packages/components/checkbox/tests/checkbox.test.tsx, packages/components/live-region/package.json, packages/components/menu/docs.json, packages/components/menu/src/use-menu.ts, packages/components/menu/stories/menu.stories.tsx, packages/components/pin-input/README.md, packages/components/select/tests/select.test.tsx, packages/components/skip-nav/package.json, packages/components/theme-tools/src/color.ts, packages/legacy/react-utils/package.json
This PR fixes a few typos.
I don't think so.
=> docs: fix typos

.github/composite-actions/install/action.yml
It looks like your project doesn't do any testing or anything related to playwright.
Closes # 
=> chore(playwright): remove playwright env

.changeset/few-apes-yawn.md, packages/components/editable/src/index.ts
Closes # 
Export "useEditableContext" to enable extension of Editable component
Cannot access the Editable context therefore customising the behavior of editable is very challenging.
Can import "useEditableContext" hook therefore can create custom Editable components more easily. For example, the editable component can be extended to support a wide range of datatypes, not just text or textarea.
No
=> Export "useEditableContext" hook

.changeset/flat-bags-protect.md, packages/core/styled-system/src/pseudos.ts
Closes #7431 
Add ``::first-letter` pseudo element to the styled-system props.
No
[MDN Reference](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter)
=> feat(styled-system): add first-letter pseudo

.changeset/gorgeous-deers-rest.md, packages/components/theme/src/components/modal.ts
=> chore: refactor theme - Modal

.changeset/slow-dolls-bake.md, packages/hooks/use-outside-click/src/index.ts, packages/legacy/hooks/src/use-outside-click.ts, packages/legacy/hooks/tests/use-outside-click.test.tsx
Added:
- listenContextMenu option in useOutsideClick
- tests for listenContextMenu and enabled in useOutsideClick
=> feat: added option to listen context menu click in useOutsideClick

packages/components/control-box/src/control-box.tsx
=> chore: add deprecation message to control box

packages/integrations/next-js/package.json
This seems a lot more standard https://www.npmjs.com/search?q=keywords%3Anext-js vs. https://www.npmjs.com/search?q=keywords%3Anextjs.
=> fix(next): correct npm tag

README.md
Adding `pnpm` and `bun` to Readme
=> docs: add Bun and pnpm to readme

packages/components/pin-input/src/use-pin-input.ts
Just fixing a little typo
N/A
N/A
NO
=> Fix error message in use-pin-input.ts

README.md
Closes #8063 
> When I tried to preview the Readme.md file in VSCode, I couldn't because some `img` tags were not self-closing.
> I couldn't preview the Readme.md file in my Vscode 
> I can now preview the Readme.md file in my Vscode 
No
Before fix:
After fix:
=> fix: Can now preview ReadMe file in VSCode

packages/hooks/use-controllable-state/README.md
Closes # N/A
README correction for the use-controllable-state hook
README.md from use-controllable-state contains use-callback-ref info.
README.md from now use-controllable-state now contains correct info.
No
=> docs(react-use-controllable-state): update README.md

packages/react/src/anatomy/create-anatomy.ts
Just fix method name in error message
-
-
No
-
=> chore(create-anatomy): fix method name in error message

MIGRATION.md
=> docs: add Collapsible migration guide

.changeset/clean-monkeys-travel.md, MIGRATION.md, packages/react/src/theme/recipes/collapsible.ts, packages/react/src/theme/slot-recipes.ts
Add Collapsible recipe.
Storybook preview: https://chakra-ui-storybook-git-fork-isbatak-feat-coll-f45805-chakra-ui.vercel.app/?path=/story/components-collapsible--basic
=> [v3] feat: Collapsible recipe

.changeset/lazy-beans-visit.md, packages/hooks/src/use-callback-ref.ts
Update use callback ref to use useInsertionEffect
=> [v3] feat(hooks): Update use callback ref to use useInsertionEffect

website/content/docs/components/link/usage.mdx
=> docs: update usage.mdx

.changeset/two-hats-provide.md, packages/react/src/preset-base.ts
`blur` property can accept `blurs` tokens
=> [v3] fix(preset): blur prop conversion to CSS var

MIGRATION.md
mention a color palette size change in migration file
=> [v3] docs(migration): mention a color palette size change in migration file

MIGRATION.md
=> [v3] docs(migration): update custom tooltip example

apps/compositions/src/examples/badge-with-group.tsx, apps/compositions/src/examples/badge-with-icon.tsx, apps/www/app/playground/page.tsx
=> [v3] add more badge examples

apps/compositions/src/examples/button-icons.tsx, apps/compositions/src/examples/button-with-icons.tsx, apps/compositions/src/examples/button-with-loading.tsx, apps/www/app/playground/page.tsx
=> [v3] add more button examples

apps/compositions/src/examples/checkbox-with-custom-icon.tsx, apps/compositions/src/examples/checkbox-with-indeterminate.tsx, apps/compositions/src/examples/checkbox-with-states.tsx, apps/www/app/playground/page.tsx, packages/react/__stories__/checkbox.stories.tsx
=> [v3] add more checkbox examples

apps/compositions/package.json, apps/compositions/src/examples/dialog-nested.tsx, apps/compositions/src/examples/dialog-with-datalist.tsx, apps/compositions/src/examples/dialog-with-focus.tsx, apps/compositions/src/examples/dialog-with-scroll.tsx, apps/compositions/src/ui/dialog.tsx, apps/www/app/playground/page.tsx, packages/react/__stories__/dialog.stories.tsx, pnpm-lock.yaml
> Added `Lorem` component for generating text for dialog
> Fixed storybook's usage of `Lorem` component's input property (`size` -> `count`)
=> [v3] added more dialog examples

apps/www/content/docs/components/breadcrumb.mdx, apps/www/content/docs/components/select.mdx
This PR adds documentation for the breadcrumb and select components.
=> docs: add docs for select and breadcrumb

apps/www/content/docs/components/checkbox-card.mdx, apps/www/content/docs/components/file-upload.mdx, apps/www/docs.config.ts
Add docs for checkbox card and file upload
=> Add docs for checkbox card and file upload

apps/www/app/page.tsx, apps/www/app/page/accessibility.tsx
=> docs(v3): Accessbility section

apps/www/app/page/accessibility.tsx, apps/www/app/page/design-system.tsx, apps/www/app/page/header.tsx, apps/www/app/page/hero-showcase.tsx, apps/www/app/page/hero.tsx, apps/www/app/page/partners.tsx, apps/www/app/page/stats.tsx, apps/www/app/page/testimonials.tsx
=> docs(v3): refactor components

apps/www/app/page.tsx, apps/www/app/page/accessibility.tsx, apps/www/app/page/design-system.tsx, apps/www/app/page/frameworks.tsx, apps/www/app/page/hero-showcase.tsx, apps/www/app/page/hero.tsx, apps/www/app/page/partners.tsx, apps/www/app/page/sponsors.tsx, apps/www/app/page/stats.tsx, apps/www/app/page/templates.tsx, apps/www/app/page/testimonials.tsx
=> docs(v3): add responsiveness

apps/compositions/src/examples/mark-basic.tsx, apps/www/content/docs/components/blockquote.mdx, apps/www/content/docs/components/link.mdx
This PR modifies and updates the documentation of typography components.
=> docs: review typography components

apps/www/app/page/demo-code.tsx, apps/www/app/page/hero-showcase.tsx
- Change codeblock background
- FIx demo tooltip
=> docs(v3): codeblock background change

packages/react/package.json
=> fix: styled system export

apps/compositions/src/examples/radio-disabled.tsx, apps/www/content/docs/components/radio.mdx, apps/www/content/docs/components/rating.mdx, apps/www/content/docs/components/select.mdx, apps/www/content/docs/components/slider.mdx, apps/www/content/docs/components/status.mdx, apps/www/content/docs/components/tabs.mdx, apps/www/content/docs/components/tag.mdx, apps/www/content/docs/components/toast.mdx, apps/www/content/docs/components/tooltip.mdx
This PR updates and improves the documentation for more components.
=> docs: review component documentation

apps/www/app/page.tsx, apps/www/app/page/accessibility.tsx, apps/www/app/page/blob.tsx, apps/www/app/page/design-system.tsx, apps/www/app/page/frameworks.tsx, apps/www/app/page/hero-showcase.tsx, apps/www/app/page/partners.tsx, apps/www/app/page/sponsors.tsx, apps/www/app/page/stats.tsx
- Enforce dark mode
- Refactor blobs
- Retint blobs
=> docs(v3): enforce dark mode

.changeset/silly-pumas-begin.md, packages/react/package.json
=> fix: export anatomy

apps/www/content/docs/components/locale-provider.mdx, apps/www/content/docs/components/show.mdx
This PR updates and modifies the utilities documentation
=> docs: review of utilities

apps/www/content/docs/styling/chakra-factory.mdx, apps/www/content/docs/styling/overview.mdx
This PR updates the styling documentation.
=> docs: review styling docs

apps/www/content/docs/styling/animation-styles.mdx, apps/www/content/docs/styling/conditional-styles.mdx, apps/www/content/docs/styling/dark-mode.mdx, apps/www/content/docs/styling/focus-ring.mdx, apps/www/content/docs/styling/layer-styles.mdx, apps/www/content/docs/styling/responsive-design.mdx, apps/www/content/docs/styling/text-styles.mdx
This PR adds updates and improvements to the styling documentation.
=> docs: review styling documentation

apps/compositions/src/lib/color-token-doc.tsx, apps/www/content/docs/theming/customization/breakpoints.mdx, apps/www/content/docs/theming/customization/colors.mdx, apps/www/content/docs/theming/customization/sizes.mdx, apps/www/content/docs/theming/overview.mdx, apps/www/content/docs/theming/radii.mdx, apps/www/content/docs/theming/semantic-tokens.mdx
This PR adds updates and improvements to the theming documentation.
=> docs: review theming documentation

apps/www/content/docs/get-started/frameworks/vite.mdx
This PR updates and improves instructions for getting started with Vite and Chakra UI.
=> docs: update vite get started documenations

.github/workflows/pkg-pr.yml
=> chore: add pkg-pr-new workflow

apps/www/content/docs/get-started/installation.mdx, apps/www/content/docs/get-started/migration.mdx
This PR improves and updates the migration documentation.
=> docs: update migration documentation

packages/cli/package.json, packages/hooks/package.json, packages/react/package.json, packages/utils/package.json, scripts/conditions.ts
Remove `source` condition from exports to prevent issues with consuming the package in other bundlers.
=> chore: remove source before packing

apps/www/app/enterprise/page.tsx
Closes # 
Fixed malformed description text for Enterprise Page on Website
In apps/www/app/enterprise/page.tsx, the description text was "optimize your ship your site faster"
In apps/www/app/enterprise/page.tsx, the description text is now "optimize and ship your site faster"
No
N/A
=> chore(www/enterprise): fix heading typo

.changeset/mighty-dolls-repeat.md, packages/react/src/utils/walk-object.ts
Closes #8856 
Fixed improper handling of nullish values in `mapObject`
`templateAreas` prop on `Grid`/`GridItem` doesn't work as intended. Not backwards compatible with v2.
This is due to an edge case in the `mapObject` util.
How the solution was inferred:
- New Grid Item uses [mapObject](https://github.com/chakra-ui/chakra-ui/blob/dae58e48453cbc35df88e2518a95366fe8d93bc5/packages/react/src/components/grid/grid-item.tsx#L23)
- Old GridItem uses [mapResponsive](https://github.com/chakra-ui/chakra-ui/blob/4e2df65d03d3ac236371e9dc6430902b5b7a3465/packages/components/layout/src/grid-item.tsx#L47)
- mapObject calls provided `fn` with null or undefined: https://github.com/chakra-ui/chakra-ui/blob/4e2df65d03d3ac236371e9dc6430902b5b7a34 …
=> fix: map-object util

apps/www/content/blog/01-whats-new-in-v3.mdx
Add new blog post titled, "What's new in v3"
=> docs: add new blog post

.changelog/v3.mdx
=> docs: add changelog for v3

apps/www/content/docs/get-started/cli.mdx, apps/www/content/docs/get-started/frameworks/next-app.mdx, apps/www/content/docs/get-started/frameworks/next-pages.mdx, apps/www/content/docs/get-started/frameworks/remix.mdx, apps/www/content/docs/get-started/frameworks/storybook.mdx, apps/www/content/docs/get-started/frameworks/vite.mdx, apps/www/content/docs/get-started/installation.mdx, apps/www/content/docs/get-started/migration.mdx, apps/www/content/docs/styling/animation-styles.mdx, apps/www/content/docs/styling/dark-mode.mdx, apps/www/content/docs/styling/layer-styles.mdx, apps/www/content/docs/styling/text-styles.mdx, apps/www/content/docs/theming/customization/overview.mdx, apps/www/content/docs/theming/overview.mdx, apps/www/content/docs/theming/recipes.mdx, apps/www/content/docs/theming/semantic-tokens.mdx, apps/www/content/docs/theming/slot-recipes.mdx, apps/www/content/docs/theming/tokens.mdx
This PR removes the @next flag that was present in the installation and CLI docs.
=> docs: remove @next flag

apps/www/content/docs/components/container.mdx
Fixes the Storybook link to the Container component.
=> fix: Update container.mdx for container storybook link

apps/www/content/docs/styling/conditional-styles.mdx
Fixes typo in documentation
No behavior change
No
=> fix: typo in docs

apps/www/content/docs/get-started/migration.mdx
=> docs: update migration.mdx

apps/www/content/blog/01-chakra-v2-vs-v3-a-detailed-comparison.mdx
This PR adds updates the new blog article titled - Chakra v2 vs v3 - a detailed comparison.
=> docs: updates to blog article

apps/www/content/docs/components/concepts/server-components.mdx
There was a mistake in the docs description of how the Server Components work in React. 
They are not hydrated on the client.
Update to be correct, still keep it minimalistic.
No
=> docs: update description of server components feature

README.md
Closes # 
> Update the link address for style props.
> I notice that style props link address navigate to a 404 page.
> The correct page.
=> docs: update the link address for style props

apps/www/content/docs/theming/spacing.mdx
Closes # 
Typo on the spacing docs references "color tokens" -> "spacing tokens"
=> Update spacing.mdx typo

apps/www/app/docs/[...slug]/page.tsx, apps/www/components/event-badge.tsx
This PR adds a link to the docs for publicity of the London Meetup
=> docs: add event link

apps/www/content/docs/components/password-input.mdx
Replaced `PasswordStrengthIndicator` with `PasswordStrengthMeter`
=> docs:fix password docs import

apps/www/content/docs/get-started/frameworks/vite.mdx
Changes the json snippet of section 4 to be titled 'tsconfig.app.json' to match the section description.
=> docs: correct filename

apps/www/components/site/header.section.tsx, apps/www/docs.config.ts
This PR adds the playground to the navigation.
=> docs: add playground to nav

apps/www/content/docs/theming/tokens.mdx
Add token reference syntax section
=> feat(docs): document token reference syntax

apps/www/content/docs/get-started/frameworks/next-app.mdx, apps/www/content/docs/get-started/frameworks/next-pages.mdx, apps/www/content/docs/get-started/frameworks/remix.mdx, apps/www/content/docs/get-started/frameworks/vite.mdx, apps/www/content/docs/get-started/installation.mdx
This PR updates the get started guides with a note for jsx applications.
=> docs: update get started guides

README.md, packages/gatsby-plugin/README.md, website/content/getting-started/cra-guide.mdx, website/content/getting-started/gatsby-guide.mdx, website/content/getting-started/index.mdx, website/content/getting-started/nextjs-app-guide.mdx, website/content/getting-started/nextjs-pages-guide.mdx, website/content/getting-started/redwoodjs-guide.mdx, website/content/getting-started/remix-guide.mdx, website/content/getting-started/vite-guide.mdx
Users believe they are installing v2 by using provided scripts but they are annoyed by "not working examples" later
=> docs(v2): fix chakra version in usage

.github/composite-actions/install/action.yml, .github/workflows/issue-stale.yml
Closes # 
* Updated the versions of actions in the workflow files, including `actions/setup-node` to `v4` and `actions/stale` to `v9`, to ensure compatibility and leverage the latest features and fixes provided by these releases.
* The workflow currently uses an older version of `actions/setup-node` (e.g., v2 or v3), which may lack the latest updates or features available in the `v4` release.
* The workflow also uses an older version of `actions/stale`, which may not include the improvements or fixes available in `v9`.
* The workflow now uses `actions/setup-node@v4`, providing improved performance, new features, and the latest fixes introduced in …
=> chore(.github): update action version in workflow files

apps/www/content/docs/components/concepts/color-mode.mdx
=> (docs) color-mode CLI command fix

apps/www/content/docs/theming/overview.mdx
the import was missing in the documentation which could be confusing for new developers
Closes # 
Just minor change for documentation
nothing related to behaviour its just a missing import in the explaination
none
no
=> docs: update theming customization overview

apps/www/content/docs/components/toast.mdx
correct the createToaster offset prop
=> docs: update toast.mdx

apps/www/components/mdx/steps.tsx
This PR Fixes the overflow currently encountered on mobile devices
https://github.com/user-attachments/assets/e02d710e-50df-4b19-93f5-cebbd57fc3da
https://github.com/user-attachments/assets/ca0cad9f-5162-4605-9929-446489c5d809
=> fix(docs): fix overflow  in documentation

CONTRIBUTING.md, apps/www/content/docs/get-started/contributing.mdx
Added command to run the chakra-ui project locally
=> docs: add command to start dev server 

apps/www/content/docs/components/radio.mdx
Closes # 
Looks like the link on Ark is to radio-group, rather than radio.
Leads to 404
Shows the right page
No, Docs change
=> docs: update radio.mdx

apps/www/content/docs/components/accordion.mdx
Wrong variants
Closes # 
> The Accordion component variants are not the right ones.
=> docs: update accordion.mdx

packages/cli/src/commands/typegen.ts, packages/cli/src/utils/io.ts
Adds a workaround for #9440
Adds the ability to specify an optional `outdir` when running the `typegen` cli command.
Currently the output directory is hard-coded. 
The default value is still the same, but an optional `--outdir` value can be specified to override it and generate the  type files in a different location.
No, the default remains the same when no `outdir` is specified.
As mentioned in [#9440](https://github.com/chakra-ui/chakra-ui/issues/9440#issuecomment-2590764193), this will provide a usable workaround for anyone using Yarn PnP to be able to run the `typegen` command and take advantage of the generated types. May also be useful for debugging or other purposes.
@segunadebayo I mentioned putting up a PR for this as a workaround in #9440, but since that issue is closed I …
=> feat(cli): allow specifying outdir when running typegen command

apps/compositions/src/examples/tag-basic.tsx, apps/compositions/src/examples/tag-closed-component.tsx, apps/compositions/src/examples/tag-with-avatar.tsx, apps/compositions/src/examples/tag-with-close.tsx, apps/compositions/src/examples/tag-with-colors.tsx, apps/compositions/src/examples/tag-with-icon.tsx, apps/compositions/src/examples/tag-with-overflow.tsx, apps/compositions/src/examples/tag-with-sizes.tsx, apps/compositions/src/examples/tag-with-variants.tsx, apps/www/content/docs/components/tag.mdx
This PR removes the snippets and updates docs for Tag
=> docs: refactor snippets

apps/compositions/src/examples/pin-input-count.tsx, apps/www/content/docs/components/pin-input.mdx
=> docs: count example added in pin-input

apps/www/content/docs/components/drawer.mdx
Reverts chakra-ui/chakra-ui#9659
=> Revert "Update drawer.mdx"

apps/www/content/docs/components/segmented-control.mdx
This PR fixes the incorrect recipe link of SegmentedControl component.
> Goes to a 404 page
> Goes to the correct recipe file
No
=> docs: fix SegmentedControl recipe link

apps/compositions/src/examples/rating-basic.tsx, apps/compositions/src/examples/rating-closed-component.tsx, apps/compositions/src/examples/rating-controlled.tsx, apps/compositions/src/examples/rating-emoji.tsx, apps/compositions/src/examples/rating-in-testimonial.tsx, apps/compositions/src/examples/rating-with-colors.tsx, apps/compositions/src/examples/rating-with-custom-icon.tsx, apps/compositions/src/examples/rating-with-half.tsx, apps/compositions/src/examples/rating-with-hook-form.tsx, apps/compositions/src/examples/rating-with-readonly.tsx, apps/compositions/src/examples/rating-with-sizes.tsx, apps/compositions/src/examples/rating-with-store.tsx, apps/www/content/docs/components/rating.mdx, packages/react/__stories__/rating.stories.tsx
This PR removes the snippets and updates docs for Rating
=> docs: refactor rating snippets

apps/www/content/docs/styling/animation-styles.mdx
Updates configuration syntax to align with Chakra UI v3 standards and fixes CLI typegen command documentation.
1. Current configuration example uses the _extend_ property in the _theme_ object to add animationStyles, a remnant from v2.
2. The CLI typegen command example is missing the source file path.
1. Updated configuration to use v3 syntax by removing unnecessary _extend_ property.
2. Added source file path to CLI typegen command based on other examples, such as recipes.mdx, slot-recipes.mdx etc.
No
This update improves the developer experience by ensuring the documentation is accurate and complete.
=> docs: [v3.8] Update animation-styles.mdx

apps/compositions/src/examples/number-input-basic.tsx, apps/compositions/src/examples/number-input-closed-component.tsx, apps/compositions/src/examples/number-input-controlled.tsx, apps/compositions/src/examples/number-input-with-disabled.tsx, apps/compositions/src/examples/number-input-with-element.tsx, apps/compositions/src/examples/number-input-with-field.tsx, apps/compositions/src/examples/number-input-with-format-options.tsx, apps/compositions/src/examples/number-input-with-hook-form.tsx, apps/compositions/src/examples/number-input-with-invalid.tsx, apps/compositions/src/examples/number-input-with-min-max.tsx, apps/compositions/src/examples/number-input-with-mouse-wheel.tsx, apps/compositions/src/examples/number-input-with-scrubber.tsx, apps/compositions/src/examples/number-input-with-sizes.tsx, apps/compositions/src/examples/number-input-with-step.tsx, apps/compositions/src/examples/number-input-with-stepper.tsx, apps/www/content/docs/components/number-input.mdx, packages/react/__stories__/number-input.stories.tsx
This PR removes the snippets and updates docs for Number Input component.
=> docs: refactor number input snippets

apps/compositions/src/examples/radio-basic.tsx, apps/compositions/src/examples/radio-card-basic.tsx, apps/compositions/src/examples/radio-card-centered.tsx, apps/compositions/src/examples/radio-card-closed-component.tsx, apps/compositions/src/examples/radio-card-composition.tsx, apps/compositions/src/examples/radio-card-with-addon.tsx, apps/compositions/src/examples/radio-card-with-colors.tsx, apps/compositions/src/examples/radio-card-with-description.tsx, apps/compositions/src/examples/radio-card-with-icon.tsx, apps/compositions/src/examples/radio-card-with-sizes.tsx, apps/compositions/src/examples/radio-card-with-variants.tsx, apps/compositions/src/examples/radio-card-without-indicator-vertical.tsx, apps/compositions/src/examples/radio-card-without-indicator.tsx, apps/compositions/src/examples/radio-closed-component.tsx, apps/compositions/src/examples/radio-controlled.tsx, apps/compositions/src/examples/radio-disabled.tsx, apps/compositions/src/examples/radio-with-colors.tsx, apps/compositions/src/examples/radio-with-hook-form.tsx, apps/compositions/src/examples/radio-with-sizes.tsx, apps/compositions/src/examples/radio-with-variants.tsx, apps/www/content/docs/components/radio-card.mdx, apps/www/content/docs/components/radio.mdx, packages/react/__stories__/radio-card.stories.tsx
This PR removes the snippets and updates docs for Radio and Radio card.
=> docs: refactor radio snippets

apps/www/content/blog/05-refactoring-snippets.mdx
=> docs: update blog post

apps/compositions/src/examples/select-basic.tsx, apps/compositions/src/examples/select-with-icon-button.tsx, apps/compositions/src/examples/select-with-item-description.tsx, apps/compositions/src/examples/select-with-option-group.tsx
Related to https://github.com/chakra-ui/chakra-ui/pull/9795
This PR improves the consistency of `Select` component examples by updating variable names to better match their contexts.
Variable names (e.g., "movie") in mapping functions don’t align with the actual data being used (e.g., frameworks).
Variable names in mapping functions now reflect the actual data (e.g., "movie" → "framework").
No.
=> docs: update variable names in select examples for consistency

apps/www/content/guides/styling-a-headless-component-with-chakra-ui.mdx
This PR adds a guide on how to styles a headless Ark UI component using Chakra UI
=> docs: new guide on styling headless components

apps/www/components/mdx-content.tsx, apps/www/components/mdx/iframe.tsx, apps/www/content/docs/charts/installation.mdx
This PR adds the charts video to the installation guide.
=> docs: add charts video

apps/www/content/blog/08-chakra-3.17-combobox-is-here.mdx, apps/www/content/blog/08-chakra-3.19-combobox-is-here.mdx
This PR adds a new blog post titled, "Chakra 3.17 - Combobox Is Here".
=> docs: add new blog post 

.changeset/lemon-windows-study.md, packages/cli/src/utils/generate-recipe.ts, packages/cli/src/utils/generate-system-types.ts, packages/react/src/styled-system/breakpoints.ts, packages/react/src/styled-system/composition.ts, packages/react/src/styled-system/create-slot-recipe-context.tsx, packages/react/src/styled-system/css-var.ts, packages/react/src/styled-system/factory.types.ts, packages/react/src/styled-system/generated/prop-types.gen.ts, packages/react/src/styled-system/generated/recipes.gen.ts, packages/react/src/styled-system/generated/system.gen.ts, packages/react/src/styled-system/token-dictionary.ts, packages/react/src/styled-system/types.ts, packages/react/src/styled-system/use-recipe.ts, packages/react/src/styled-system/use-slot-recipe.ts
Additional fixes to support TS `exactOptionalPropertyTypes`
=> fix(system): add undefined to support TS exactOptionalPropertyTypes

.changeset/tame-dingos-happen.md, packages/react/src/components/typography/index.ts
export Quote component and its types.
=> fix(typography): export Quote component and its types

.changeset/shy-cheetahs-call.md, packages/react/src/components/select/index.ts
=> fix(select): add missing SelectRootComponent type export

.changeset/dark-spoons-melt.md, apps/compositions/src/examples/drawer-with-conditional-variants.tsx, apps/www/content/docs/components/drawer.mdx, packages/react/__stories__/drawer.stories.tsx, packages/react/src/theme/recipes/drawer.ts
- improve `Drawer` recipe to better support conditional variants.
- add `Drawer` conditional variants example to the docs and storybook.
https://github.com/user-attachments/assets/2578583a-67f4-4ab3-a5a1-8b4e176ca617
https://github.com/user-attachments/assets/5f5bdb92-2ab5-471b-bdd8-adac8c370bde
Maybe
=> fix(drawer): conditional placement variants

.changeset/new-moose-know.md, packages/react/src/anatomy.ts
export clipboardAnatomy to allow clipboard component recipe creation in the user land.
=> feat(system): export clipboardAnatomy

apps/compositions/src/examples/collapsible-basic.tsx
This PR adds a short motivational explanation to the `CollapsibleBasic` example, highlighting the Sanskrit origin of the word **"Chakra"** and connecting it to Chakra UI’s design philosophy — balance, clarity, and flow in UI development.
This is not tied to any specific issue, but intended as a small enhancement to make the documentation/demo more meaningful and inspiring for new users exploring Chakra UI.
- Updated the content inside the `CollapsibleBasic` component
- The added message reflects Chakra's deeper meaning in a way that resonates with Chakra UI's goals
- No logic changes, purely documentation/example content
Thank you for the awesome library 🙌 Happy to contribute and open to feedback.
=> docs: add inspirational note on Chakra UI's name and purpose

apps/www/content/docs/components/radio.mdx, apps/www/content/docs/components/slider.mdx
Closes # 
fix some minor issues in comments
=> docs: fix some minor issues in comments

apps/www/content/docs/charts/area-chart.mdx, apps/www/content/docs/components/radio.mdx, apps/www/content/docs/get-started/frameworks/next-pages.mdx, apps/www/content/docs/get-started/installation.mdx, apps/www/content/docs/styling/layer-styles.mdx
This pull request fixes typos and improves grammar across multiple `.mdx` documentation files for clarity and consistency.
Some of the documentation contained minor typos and grammatical errors that could affect readability.
All reviewed `.mdx` files now have corrected typos and improved grammar. No functional or code changes were made.
No.
=> docs: correct typos and improve clarity in documentation

packages/react/src/hooks/use-controllable-state.ts
related to `exactOptionalPropertyTypes` TS prop
=> fix(TS): update type definitions for onChange and shouldUpdate in useControllableProp hook

apps/www/app/launch-week/data.ts
=> docs: add day 3

apps/www/content/blog/00-announcing-v3.mdx
This PR includes a few typos and grammatical corrections in the V3 release blog post.
No
=> fix(docs): fix typos and grammar corrections

apps/www/content/docs/components/drawer.mdx
Update the drawer offset documentation to match its examples
=> fix(docs): Update drawer offset docs to match examples

packages/react/src/components/pagination/index.ts
=> fix(pagination): export pagination types

.changeset/add-missing-layer-properties.md, .changeset/purple-cats-march.md, apps/www/content/docs/get-started/cli.mdx, packages/cli/README.md, packages/cli/package.json, packages/cli/src/commands/blocks.ts, packages/cli/src/index.ts, packages/cli/src/utils/fetch.ts, pnpm-lock.yaml
Implement the new blocks command for fetching pro blocks via CLI
=> feat(cli): implement blocks command
